### DISCUSSION TITLE
Callouts not mentioned in documentation

### DISCUSSION THREAD

**Discussion by petterhol** [twbs/bootstrap#31760] [General] [answered]
Hey everyone! I'm new to this game. My friend has installed me with a Bootstrap website via Hugo. I'm able to make most features work based on the Bootstrap and Hugo documentation, excessive Googleing and stealing ideas from my own project.

However, I seem to be out of ideas when it comes to using callouts. Before I can explain my problem, I just wanted to know if there's any reason there's no component documentation in v.4.5 about callouts, all the time the documentation have an excessive use of callouts themself. Am I looking at the wrong place?

**Comment by patrickhlauke** [comment, marked as answer]
Hi, callouts are not a core component of Bootstrap, but something that was added just for the documentation.

**Reply by petterhol** [reply]
Ah, alright. I was finally able to implement them in my own side. What would be the correct way to suggest this to be added to the code (without me being able to code it myself)?

**Reply by mdo** [reply]
There have been issues opened in the past for that. We're not doing it though because we need and want these callouts to be unique to our docs.

**Comment by vanillajonathan** [comment]
There is some mention of the custom callout components at:
https://getbootstrap.com/docs/5.0/customize/components/#creating-your-own

The SASS source code is at:
https://github.com/twbs/bootstrap/blob/main/site/assets/scss/_callouts.scss

Here it is in CSS:
```css
.bd-callout {
  padding: 1.25rem;
  margin-top: 1.25rem;
  margin-bottom: 1.25rem;
  border: 1px solid #e9ecef;
  border-left-width: .25rem;
  border-radius: .25rem;
}

.bd-callout h4 {
  margin-bottom: .25rem;
}

.bd-callout p:last-child {
  margin-bottom: 0;
}

.bd-callout code {
  border-radius: .25rem;
}

.bd-callout + .bd-callout {
  margin-top: -.25rem;
}

.bd-callout-info {
  border-left-color: #5bc0de;
}

.bd-callout-warning {
  border-left-color: #f0ad4e;
}

.bd-callout-danger {
  border-left-color: #d9534f;
}
```
