### DISCUSSION TITLE
How do I pull in scss variables using @use from Bootstrap 5?

### DISCUSSION THREAD

**Discussion by jgeurts** [twbs/bootstrap#32458] [Q&A] [answered]
Hi,

I have a simple stylesheet for a component in my site and I'm trying to pull in the `$zindex-fixed` variable, but my approach seems to have issues. Any help would be appreciated!

My stylesheet looks like:

```scss
@use "~bootstrap/scss/variables";

.playerBar {
  position: fixed;
  left: 0px;
  bottom: 0px;
  height: 90px;
  min-width: 620px;
  width: 100%;
  z-index: variables.$zindex-fixed;
  background: #1e1e1e;
}
```

I'm getting the following error:
```
SassError: Undefined mixin.
    ╷
307 │ @include _assert-ascending($grid-breakpoints, "$grid-breakpoints");
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/bootstrap/scss/_variables.scss 307:1  @use
```

This is using Bootstrap 5.0.0-beta1 with sass 1.30.0. Please let me know if I can provide more info to help diagnose!
