### DISCUSSION TITLE
How to add an arrow to a Bootstrap 5 Dropdown

### DISCUSSION THREAD

**Discussion by peheje** [twbs/bootstrap#32910] [Q&A]
Hi!
How do I enable the Popper arrow for [Bootstrap 5 Dropdowns?](https://getbootstrap.com/docs/5.0/components/dropdowns/)

The arrow being the little arrow from the menu to the button, marked here as red:
![Skærmbillede 2021-01-27 kl  11 28 26](https://user-images.githubusercontent.com/7273366/105979407-ed24c100-6093-11eb-84e6-f53a3ce0517c.png)

**Comment by ExtravagantBoost** [comment]
you can use Boostrap Utilities Api and try to create your own by creating an svg arrow or smt and try to statically positioning it via 
```position-absolute top-0 start-50 translate-middle```(taken from [position](https://getbootstrap.com/docs/5.2/utilities/position/) in bs docs)

**Comment by coliff** [comment]
I'd like to see this added as an option to Bootstrap's dropdown menus. I requested it a while ago, please feel free to add thumbs up reaction to it. 👍 
https://github.com/twbs/bootstrap/issues/37205

**Reply by ExtravagantBoost** [reply]
bootstrap does recommend that you create your own components as the pre-made components are quite limiting, but sure there should be a seperate class that will add the arrow to the ```.dropdown-menu``` class such as ```.menu-arrow``` with some of bootstrap properties

**Comment by giuliano-marinelli** [comment]
I leave you an **example** of how I implemented it in my application. It's just a copy of the github code. You have to add the `:before` and `:after` selectors to the `dropdown-menu` class to create the arrow border and front color respectively. Just replace the variables by the color you want:

```scss
.dropdown-menu:before {
  right: 15px;
  top: -16px;
  border: 8px solid #0000;
  border-bottom: 8px solid $border-color-translucent;
}

.dropdown-menu:after {
  right: 16px;
  top: -14px;
  border: 7px solid #0000;
  border-bottom: 7px solid $body-bg;
}

.dropdown-menu:before,
.dropdown-menu:after {
  content: "";
  left: auto;
  display: inline-block;
  position: absolute;
}
```

Also, i leave here another styles for make it work with darkmode too:
```scss
html[data-bs-theme="dark"] .dropdown-menu:before {
  border-bottom: 8px solid $border-color-translucent-dark;
}

html[data-bs-theme="dark"] .dropdown-menu:after {
  border-bottom: 7px solid $body-bg-dark;
}
```

You can create your own custom class for apply to specific dropdowns. 
_**Note: a problem is that the arrow position is static, so it's not very flexible.**_

Hope it helps you at least as a workaround.
Cheers.
