### DISCUSSION TITLE
is there a way for this utility?

### DISCUSSION THREAD

**Discussion by dkern** [twbs/bootstrap#32923] [Q&A]
Hello!

I'm asking myself if there a good way to build an utility like the example below. So basically is there a way to _wrap_ the values into `rotate()`, or do i have to put everything into the values list?

```scss
'rotate': (
    property: transform,
    class: 'rotate',
    values: (0, 1, 2, 3)
),
```

Expected output:
```css
.rotate-0 { transform: rotate(0deg); }
.rotate-1 { transform: rotate(1deg); }
.rotate-2 { transform: rotate(2deg); }
.rotate-3 { transform: rotate(3deg); }
```

Thanks!

**Comment by chuckrincon** [comment]
Try with this:
```scss
$utilities: map-merge(
  $utilities,
  (
    'rotate': (
      property: transform,
      class: rotate,
      values: (
        0: rotate(0deg),
        1: rotate(1deg),
        2: rotate(2deg),
        3: rotate(3deg),
      ),
    ),
  )
);
```
The `value` must be a list of values, or a map if you don’t want the class name to be the same as the value.

e.g. Map of values
```scss
$utilities: (
  'opacity': (
    property: opacity,
    values: (
      0: 0,
      25: 0.25,
      50: 0.5,
      75: 0.75,
      100: 1,
    ),
  ),
);
```
Produces
```scss
.opacity-0 { opacity: 0; }
.opacity-25 { opacity: .25; }
.opacity-50 { opacity: .5; }
.opacity-75 { opacity: .75; }
.opacity-100 { opacity: 1; }
```
e.g. List of values
```scss
$utilities: map-merge(
  $utilities,
  (
    'cursor': (
      property: cursor,
      class: cursor,
      values: auto pointer grab,
    ),
  )
);
```
Produces
```scss
.cursor-auto { cursor: auto; }
.cursor-pointer { cursor: pointer; }
.cursor-grab { cursor: grab; }
```
