### DISCUSSION TITLE
Offcanvas-top (placement)

### DISCUSSION THREAD

**Discussion by Hintzmann** [twbs/bootstrap#33476] [Ideas]
Can we have a modifier for the offcanvas, so it can be placed top of the viewport?

**Comment by Hiws** [comment]
Yeah, seems a bit odd that there's one for `bottom`, `start` and `end`, but not `top`.

The following snippet seems to do the trick though, if you want to add it yourself.
```css
.offcanvas-top {
    right: 0;
    left: 0;
    height: 30vh;
    max-height: 100%;
    border-bottom: 1px solid rgba(0,0,0,.2);
    transform: translateY(-100%);
    top: 0;
}
```
https://codepen.io/Hiws/pen/LYxGPaw?editors=1100
