### DISCUSSION TITLE
CSS only dropdown

### DISCUSSION THREAD

**Discussion by caub** [twbs/bootstrap#34217] [Show & Tell]
https://jsfiddle.net/caub/8xrps0zf/

```html
<details class="dropdown">
    <summary class="dropdown-toggle nav-link">Qux</summary>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="#">Action</a></li>
        <li><a class="dropdown-item" href="#">Another action</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Something else here</a></li>
    </ul>
</details>
```

```css
details.dropdown > summary {
  list-style: none;
}

details.dropdown > .dropdown-menu {
  position: absolute;
  list-style: none;
  z-index: 50;
  background-color: #fffe;
  display: block;
  min-width: 0;
}

details.dropdown[open] summary::before {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  content: "";
}
```
