### DISCUSSION TITLE
is it possible to disable the responsive font scaling feature ?

### DISCUSSION THREAD

**Discussion by adrianmak** [twbs/bootstrap#34365] [Q&A]
Im new on bootstrap 5.0 and use the bootstrap cdn in my html.
I found that the h1-h6 font size is responsive. 
is it possible disable the responsive font scaling ?

**Comment by coliff** [comment]
You could disable the responsive font scaling by copying the rules from Bootstrap 4.x
https://cdn.jsdelivr.net/npm/bootstrap@4/dist/css/bootstrap.css

```css
h1, .h1 {
  font-size: 2.5rem !important;
}

h2, .h2 {
  font-size: 2rem !important;
}

h3, .h3 {
  font-size: 1.75rem !important;
}

h4, .h4 {
  font-size: 1.5rem !important;
}

h5, .h5 {
  font-size: 1.25rem !important;
}

h6, .h6 {
  font-size: 1rem !important;
}
```

I recommend you keep the responsive font sizing as it is though... otherwise h1 etc may appear too large on small mobile screens.
