### DISCUSSION TITLE
Table border

### DISCUSSION THREAD

**Discussion by KatyPurry** [twbs/bootstrap#36993] [Q&A]
Hello,
I'm triying to add different borders colors on a table. The problem is `border-bottom` is over `border-right`. How can we make it the opposite?

```CSS
.table {
border-left: 1px solid #201f1f;
border-right: 1px solid #201f1f;
border-bottom: 1px solid #393939;
}
```

![image](https://user-images.githubusercontent.com/89610869/185743408-5c02801c-b6a4-4a95-ab3f-e7734c520750.png)
