### DISCUSSION TITLE
CSS Variables - setting --bs-primary won't affect button components

### DISCUSSION THREAD

**Discussion by devo-wm** [twbs/bootstrap#37057] [Q&A] [answered]
I had hoped that by setting the --bs-primary color in one place that would update the .btn-primary colors but it looks like I have to re-scope the btn-primary like so

```css
.btn-primary {
     --bs-btn-bg: var(--bs-primary);
... /* and so on */
}
```

Wondering if that's the best way to go about it, or should I be going another route?
