### DISCUSSION TITLE
How to change the accordion's color?

### DISCUSSION THREAD

**Discussion by michelami** [twbs/bootstrap#37229] [Q&A] [answered]
I would like to change the background, to another color as seen in the picture (the pink part) , using a new css file and override the bootstrap's one. I tried everything but it doesn't change the background behind the title, but the one behind the body. What code do i need to write?
![Screenshot (131)](https://user-images.githubusercontent.com/114733344/193233245-df1a1d3c-0ba0-4870-a96c-bffcd93666cf.png)

**Comment by Edditoria** [comment, marked as answer]
You can use the CSS variables provided by Bootstrap, and apply to `.accordion`:

```css
.accordion {
	--bs-accordion-btn-color: ghostwhite;
	--bs-accordion-btn-bg: pink;
	--bs-accordion-active-color: maroon;
	--bs-accordion-active-bg: lightpink;
}
```

Hope it helps. Happy Coding :)

**Reply by Mahamadou-Nouridine** [reply]
Thank you it worked for me

**Reply by uvistix** [reply]
> You can use the CSS variables provided by Bootstrap, and apply to `.accordion`:
> 
> ```css
> .accordion {
> 	--bs-accordion-btn-color: ghostwhite;
> 	--bs-accordion-btn-bg: pink;
> 	--bs-accordion-active-color: maroon;
> 	--bs-accordion-active-bg: lightpink;
> }
> ```
> 
> Hope it helps. Happy Coding :)

Thanks. worked for me

**Comment by michealpeerodada** [comment]
To change the background behind a title, create a custom.css file and add:

```css
.header-title {
  background-color: #desiredColor; /* Replace with your color */
}
```

Include it in your HTML after Bootstrap's CSS:

```html
<link rel="stylesheet" href="path/to/bootstrap.css">
<link rel="stylesheet" href="path/to/custom.css">
```
very recently, i have changes the accrodian background of inasaldiningprices.com, a great filipino site that covers [[local fast food menu]
