### DISCUSSION TITLE
When using 'table-responsive', how can I still use 2 fingers to shrink the table so that my mobile can show the whole table ? scroll bar not so good

### DISCUSSION THREAD

**Discussion by dodouwang** [twbs/bootstrap#37278] [Q&A]
I have a table which td is "white-space:nowrap;", so my table is very wide. In the mobile view, I am using 'table-responsive'.

I know there is a scroll bar in the bottom of the table, but sometimes I need to see the head column and tail column in the same time.

So I want to shrink the table using 2 fingers, but it doesn't work. How can I still use 2 fingers to shrink the table so that my mobile can show the whole table ?

Or, I can accept the solution that I don't need the scroll bar, instead, directly show the shrinked whole table in my mobile. I know the words will be small, but I can bear it. but how to realize it?

**Comment by Edditoria** [comment]
Bootstrap is usually used for responsive design across devices and has "standard" size and spacing. In my knowledge, it does not have settings to fit your need.

For your case, if showing first and last column is acceptable. You can make they sticky. Something like:

```css
.table-sticky-header thead {
  position: sticky;
  top: 0;
  z-index: 1;
  background: white;
}

.table-sticky-footer tfoot {
  position: sticky;
  bottom: 0;
  z-index: 1;
  background: white;
}

.table-sticky-first-col thead th:first-child {
  position: sticky;
  left: 0;
  z-index: 1;
  background: white;
}

.table-sticky-first-col tbody th {
  position: sticky;
  left: 0;
  background: white;
}

.table-sticky-last-col thead th:last-child {
  position: sticky;
  right: 0;
  z-index: 1;
  background: white;
}

.table-sticky-last-col tbody td:last-child {
  position: sticky;
  right: 0;
  background: white;
}
```

NOTE: The first column is `<th>` rather than `<td>`.

It is a starter code, btw. You may change more styles for your need.

Hope can help.
