### DISCUSSION TITLE
split dropdown glitch?

### DISCUSSION THREAD

**Discussion by ExtravagantBoost** [twbs/bootstrap#37387] [Q&A] [answered]
recently i pulled the Bootstrap CSS part of the repo and linked it to my HTML file (edit) As a seperate file and i got this result after; 
![index html - fileEditor2 - Replit](https://user-images.githubusercontent.com/116477764/198427018-b28383c5-dcf8-4f25-810b-2f56bf250ee2.png)
Note : this style is a custom css class, no other classes or child selectors affect this type of button
```css

.btn-file {
  --bs-btn-font-weight: 600;
  --bs-btn-color: var(--bs-black);
  --bs-btn-bg: #FD9A18;
  --bs-btn-border-color: #C36F02;
  --bs-btn-border-radius: .5rem;
  --bs-btn-hover-color: var(--bs-black);
  --bs-btn-hover-bg: #EA8502;
  --bs-btn-hover-border-color: #9C5902;
  --bs-btn-focus-shadow-rgb: var(--bs-warning-rgb);
  --bs-btn-active-color: var(--bs-btn-hover-color);
  --bs-btn-active-bg: #FDAF49;
  --bs-btn-active-border-color: #FDB659;
}
.btn-outline-file {
  --bs-btn-font-weight: 600;
  --bs-btn-color: #FD9A18;
  --bs-btn-bg:transparent;
  --bs-btn-border-color: #C36F02;
  --bs-btn-border-radius: .5rem;
  --bs-btn-hover-color: var(--bs-black);
  --bs-btn-hover-bg: #EA8502;
  --bs-btn-hover-border-color: #9C5902;
  --bs-btn-focus-shadow-rgb: var(--bs-warning-rgb);
  --bs-btn-active-color: var(--bs-btn-hover-color);
  --bs-btn-active-bg: #FDAF49;
  --bs-btn-active-border-color: #FDB659;
}

```
can anybody tell me what i did wrong? and what can i do to remedy this issue in the future?

**Comment by ExtravagantBoost** [comment, marked as answer]
fixed. had to place
```css

.dropdown-toggle.dropdown-toggle-split::after {

            content: "‎";/*there is an empty character the size of ‘|’ but has no whitespace in the quotes*/
        }

```
to respect sizing of text with the button
