### DISCUSSION TITLE
Bootstrap 5.1/5.2 Introduce CSS variables, but they don't work in emails.

### DISCUSSION THREAD

**Discussion by ychaker** [twbs/bootstrap#37511] [Q&A] [answered]
I recently upgraded to the latest Bootstrap (5.2), using the ruby gem (v5.2.2), which uses CSS variables (I think that's a cool idea for the future), however, I do not believe that this is supported in email clients (at least not in Gmail), and so my email templates are semi broken.

Anything that references the global or root CSS variables doesn't work.

For example, while testing locally using the Rails preview feature, I see the CSS variables assigned and present:
<img width="249" alt="Screen Shot 2022-11-17 at 12 10 05 PM" src="https://user-images.githubusercontent.com/29512/202513689-44cd07ef-daaa-4f12-8b16-394ca2983495.png">

However, in a deployed environment, when I send the email to an actual inbox, those same variables are missing, even though they're being used:

<img width="355" alt="Screen Shot 2022-11-17 at 12 08 46 PM" src="https://user-images.githubusercontent.com/29512/202515286-4869cc37-efaf-41d3-9333-9630443512f6.png">

I believe that Gmail is stripping them out because I can see in the code of the original message the following:

```
----==_mimepart_637663751e9e1_2ef2501b88846e
Content-Type: text/html; charset=iso-8859-1
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html>

<html style=3D'--bs-blue: #1B489D; --bs-indigo: #6610f2; --bs-purple: #6f42=
c1; --bs-pink: #d63384; --bs-red: #dc3545; --bs-orange: #fd7e14; --bs-yello=
w: #ffc107; --bs-green: #198754; --bs-teal: #20c997; --bs-cyan: #0dcaf0; --=
bs-black: #000; --bs-white: #fff; --bs-gray: #6c757d; --bs-gray-dark: #343a=
40; --bs-gray-100: #f8f9fa; --bs-gray-200: #e9ecef; --bs-gray-300: #dee2e6;=
 --bs-gray-400: #ced4da; --bs-gray-500: #adb5bd; --bs-gray-600: #6c757d; --=
bs-gray-700: #495057; --bs-gray-800: #343a40; --bs-gray-900: #212529; --bs-=
primary: #1B489D; --bs-secondary: #225cc9; --bs-success: #198754; --bs-info=
: #0dcaf0; --bs-warning: #ffc107; --bs-danger: #dc3545; --bs-light: #f8f9fa=
; --bs-dark: #212529; --bs-primary-rgb: 27, 72, 157; --bs-secondary-rgb: 34=
.4836956522, 91.9565217391, 200.5163043478; --bs-success-rgb: 25, 135, 84; =
--bs-info-rgb: 13, 202, 240; --bs-warning-rgb: 255, 193, 7; --bs-danger-rgb=
: 220, 53, 69; --bs-light-rgb: 248, 249, 250; --bs-dark-rgb: 33, 37, 41; --=
bs-white-rgb: 255, 255, 255; --bs-black-rgb: 0, 0, 0; --bs-body-color-rgb: =
33, 37, 41; --bs-body-bg-rgb: 255, 255, 255; --bs-font-sans-serif: system-u=
i, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liber=
ation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Seg=
oe UI Symbol", "Noto Color Emoji"; --bs-font-monospace: SFMono-Regular, Men=
lo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace; --bs-gra=
dient: linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 25=
5, 0)); --bs-body-font-family: var(--bs-font-sans-serif); --bs-body-font-si=
ze: 1rem; --bs-body-font-weight: 400; --bs-body-line-height: 1.5; --bs-body=
-color: #212529; --bs-body-bg: #fff; --bs-border-width: 1px; --bs-border-st=
yle: solid; --bs-border-color: #dee2e6; --bs-border-color-translucent: rgba=
(0, 0, 0, 0.175); --bs-border-radius: 0.375rem; --bs-border-radius-sm: 0.25=
rem; --bs-border-radius-lg: 0.5rem; --bs-border-radius-xl: 1rem; --bs-borde=
r-radius-2xl: 2rem; --bs-border-radius-pill: 50rem; --bs-link-color: #1B489=
D; --bs-link-hover-color: #163a7e; --bs-code-color: #d63384; --bs-highlight=
-bg: #fff3cd; box-sizing: border-box;'>
```

so Gmail is receiving these values in the email content the app is sending, but because Gmail strips the `html` tag altogether, they are lost. but even if I tried to move the CSS variables to an element other than the `html` tag, Gmail strips them.

I was able to hack a solution by spending a long time manually re-creating the main mixins and classes that I needed for the email using the SASS variables instead of CSS variables, so for example, I had to manually override this mixin:

```scss
@mixin button-variant(
  $background,
  $border,
  $color: color-contrast($background),
  $hover-background: if($color == $color-contrast-light, shade-color($background, $btn-hover-bg-shade-amount), tint-color($background, $btn-hover-bg-tint-amount)),
  $hover-border: if($color == $color-contrast-light, shade-color($border, $btn-hover-border-shade-amount), tint-color($border, $btn-hover-border-tint-amount)),
  $hover-color: color-contrast($hover-background),
  $active-background: if($color == $color-contrast-light, shade-color($background, $btn-active-bg-shade-amount), tint-color($background, $btn-active-bg-tint-amount)),
  $active-border: if($color == $color-contrast-light, shade-color($border, $btn-active-border-shade-amount), tint-color($border, $btn-active-border-tint-amount)),
  $active-color: color-contrast($active-background),
  $disabled-background: $background,
  $disabled-border: $border,
  $disabled-color: color-contrast($disabled-background)
) {
  color: #{$color};
  background-color: #{$background};
  border-color: #{$border};

  &:hover {
    color: #{$hover-color};
    background-color: #{$hover-background};
    border-color: #{$hover-border};
  }

  &:active {
    color: #{$active-color};
    background-color: #{$active-background};
    border-color: #{$active-border};
  }

  &:disabled {
    color: #{$disabled-color};
    background-color: #{$disabled-background};
    border-color: #{$disabled-border};
  }
}
```

and others like it.

This is obviously not maintainable for the future and I might have to do more customization in the future if I end up using a component I didn't already fix.

So my question is: is there a way to use Bootstrap 5.2 without CSS variables? 
Or does anyone know of an easy way to compile Bootstrap and replace all of the `var(--bs-foo)` or `var(--#{$prefix}foo)` with the actual values?

Or has anyone gotten the new version of bootstrap to work in email templates?

**Comment by julien-deramond** [comment, marked as answer]
Thanks for opening this discussion @ychaker, I wasn't aware of this limitation that seems to be confirmed in https://www.caniemail.com/features/css-variables/. It's very interesting!

I'd say you could use some PostCSS plugin to transform `bootstrap.css` (or directly `bootstrap.min.css` or the CSS you create yourself if it uses some customizations) like [postcss-css-variables](https://www.npmjs.com/package/postcss-css-variables).

If I copy/paste the content of [the CDN version of `bootstrap.css`](https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.css) in [their playground](https://madlittlemods.github.io/postcss-css-variables/playground/), the result seems to correspond to what you're trying to achieve. But I haven't tested it in depth, you'll tell me if it works :)

For example:

```css
body {
  margin: 0;
  font-family: var(--bs-body-font-family);
  font-size: var(--bs-body-font-size);
  font-weight: var(--bs-body-font-weight);
  line-height: var(--bs-body-line-height);
  color: var(--bs-body-color);
  text-align: var(--bs-body-text-align);
  background-color: var(--bs-body-bg);
  -webkit-text-size-adjust: 100%;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}
```

is transformed to:

```css
body {
  margin: 0;
  font-family: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5;
  color: #212529;
  text-align: undefined;
  background-color: #fff;
  -webkit-text-size-adjust: 100%;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}
```

**Reply by ychaker** [reply]
thanks @julien-deramond for the quick response.
I somehow didn't find the "playground" site when I was searching for solutions, although I did find the PostCSS plugin.
So the playground let me test it out before committing to implementing something with that plugin. Thanks for that suggestion.

What I did is the following:

```rb
# frozen_string_literal: true

namespace :assets do
  desc "compile the mailer css because it is special"
  task compile_mailer_css: :environment do
    puts "Compiling mailer CSS..."
    dest = Rails.root.join("app/assets/stylesheets/mailer.compiled.css")
    File.write(dest, Rails.application.assets.find_asset("mailer.css").to_s)

    cmd = "yarn run remove_css_variables"
    puts "Running command: #{cmd}"
    system(cmd)
  end
end

```

and this is the node script:

```js
var postcss = require("postcss");
var cssvariables = require("postcss-css-variables");
var nested = require("postcss-nested");

var fs = require("fs");
var filePath = "app/assets/stylesheets/mailer.compiled.css";

var mycss = fs.readFileSync(filePath, "utf8");

var output = postcss([
  // Flatten/unnest rules
  nested,
  // Then process any CSS variables
  cssvariables(/*options*/)
]).process(mycss).css;

// Write output back to the same file
fs.writeFile(filePath, output, err => {
  if (err) {
    console.error(err);
  }
});

```

This combo works, partially.

There were some styles that were missing after going through the PostCSS plugin, for example (and ironically since that's the example I used in my original post), the button styles were missing (eg: `btn-primary, btn-secondary, ...`).

so I did have to override the following mixins:

```scss
@mixin button-variant(
  $background,
  $border,
  $color: color-contrast($background),
  $hover-background: if($color == $color-contrast-light, shade-color($background, $btn-hover-bg-shade-amount), tint-color($background, $btn-hover-bg-tint-amount)),
  $hover-border: if($color == $color-contrast-light, shade-color($border, $btn-hover-border-shade-amount), tint-color($border, $btn-hover-border-tint-amount)),
  $hover-color: color-contrast($hover-background),
  $active-background: if($color == $color-contrast-light, shade-color($background, $btn-active-bg-shade-amount), tint-color($background, $btn-active-bg-tint-amount)),
  $active-border: if($color == $color-contrast-light, shade-color($border, $btn-active-border-shade-amount), tint-color($border, $btn-active-border-tint-amount)),
  $active-color: color-contrast($active-background),
  $disabled-background: $background,
  $disabled-border: $border,
  $disabled-color: color-contrast($disabled-background)
) {
  color: #{$color};
  background-color: #{$background};
  border-color: #{$border};

  &:hover {
    color: #{$hover-color};
    background-color: #{$hover-background};
    border-color: #{$hover-border};
  }

  &:active {
    color: #{$active-color};
    background-color: #{$active-background};
    border-color: #{$active-border};
  }

  &:disabled {
    color: #{$disabled-color};
    background-color: #{$disabled-background};
    border-color: #{$disabled-border};
  }
}

@mixin button-outline-variant(
  $color,
  $color-hover: color-contrast($color),
  $active-background: $color,
  $active-border: $color,
  $active-color: color-contrast($active-background)
) {
  color: #{$color};
  border-color: #{$color};

  &:hover {
    color: #{$color-hover};
    background-color: #{$active-background};
    border-color: #{$active-border};
  }

  &:active {
    color: #{$active-color};
    background-color: #{$active-background};
    border-color: #{$active-border};
  }

  &:disabled {
    color: #{$color};
    background-color: transparent;
    border-color: #{$color};
  }
}

@mixin button-size($padding-y, $padding-x, $font-size, $border-radius) {
  @include rfs($font-size, --#{$prefix}btn-font-size);
  font-size: $font-size;
  border-radius: #{$border-radius};
  padding: #{$padding-y} #{$padding-x};
}

@mixin make-container($gutter: $container-padding-x) {
  width: 100%;
  padding-right: calc(#{$gutter} * .5); // stylelint-disable-line function-disallowed-list
  padding-left: calc(#{$gutter} * .5); // stylelint-disable-line function-disallowed-list
  margin-right: auto;
  margin-left: auto;
}

@mixin make-row($gutter: $grid-gutter-width) {
  display: flex;
  flex-wrap: wrap;
  margin-top: calc(-1 * 0); // stylelint-disable-line function-disallowed-list
  margin-right: calc(-.5 * #{$gutter}); // stylelint-disable-line function-disallowed-list
  margin-left: calc(-.5 * #{$gutter}); // stylelint-disable-line function-disallowed-list
}

@mixin make-col-ready() {
  // Add box sizing if only the grid is loaded
  box-sizing: if(variable-exists(include-column-box-sizing) and $include-column-box-sizing, border-box, null);
  // Prevent columns from becoming too narrow when at smaller grid tiers by
  // always setting `width: 100%;`. This works because we set the width
  // later on to override this initial width.
  flex-shrink: 0;
  width: 100%;
  max-width: 100%; // Prevent `.col-auto`, `.col` (& responsive variants) from breaking out the grid
  padding-right: calc($grid-gutter-width * .5); // stylelint-disable-line function-disallowed-list
  padding-left: calc($grid-gutter-width * .5); // stylelint-disable-line function-disallowed-list
  margin-top: 0;
}

@each $color, $value in $theme-colors {
  $color-rgb: to-rgb($value);
  .text-bg-#{$color} {
    color: color-contrast($value) if($enable-important-utilities, !important, null);
    background-color: RGBA($color-rgb, 1) if($enable-important-utilities, !important, null);
  }
}
```

not sure if I needed the container/row stuff, but definitely the btn variants and the text-bg variants.
(PS: my version of the mixins isn't 100% the same as what the existing code provides, it's missing the shadow stuff for example, but it works well enough within the confines of email)

I also ran into an issue where I get lines like this:

```css
font-family:  ;
```

which would result in an error:

```
     ActionView::Template::Error:
       Error: style declaration must contain a value
               on line 1977:14 of stdin
       >>   font-family:  ;
```

so I had to manually find those lines and remove them.

And since I haven't tested every single component in the emails, I'm pretty sure there will be others that are missing.

So using the PostCSS plugin didn't completely solve the issue, but it did reduce the amount of manual work I have to do.

I hope this helps someone else who runs into a similar issue.
