### DISCUSSION TITLE
How to use @include font-size inside mixin

### DISCUSSION THREAD

**Discussion by yanalshoubaki** [twbs/bootstrap#37582] [General]
## Describe the issue

I create mixin that give me an font-size and line-height with rtl convert, but i need to add font-size function to make it responsive.

The mixin i created : 
```scss
@mixin fontSize($fontSize, $calc: false) {
  $getFont: map.get($font, $fontSize, "font-size");
  $getLineHeight: map.get($font, $fontSize, "line-height");
  @if $calc {
    font-size: calc(#{$getFont} + var(--font-size-adder));
    line-height: calc(#{$getLineHeight}+ var(--font-size-adder));
  } @else {
    @include font-size($getFont);
    line-height: $getLineHeight;
  }
}
```
the include not working

bootstrap version : 5.1.3
