### DISCUSSION TITLE
How do I deal with sticky :hover on iOS?

### DISCUSSION THREAD

**Discussion by gormster** [twbs/bootstrap#37700] [Q&A]
There used to be a section about sticky `:hover` and `:focus` on iOS in the docs, but it seems to have disappeared as of Bootstrap 5. However, it's still a huge problem: buttons hold the `:hover` state until you tap on something else. What's more, they don't actually enter that state until you either let go or hold the button for about a second. Seems like the thing we want is for buttons to go into the hover state as soon as the user touches the button, and remove that state as soon as touches end or are cancelled.

Am I stuck implementing this in JavaScript? It seems like a huge problem and I can't imagine no-one on the Bootstrap project has noticed it. It happens with all of the buttons on the [example pages](https://getbootstrap.com/docs/5.2/examples/heroes/). It just seems weird that there used to be information about it and now that info is gone, but the problem still exists. Everything I can find about it seems to heavily imply (but not outright state) that it's not an issue anymore… can anyone help me out here?

**Comment by gormster** [comment]
Ok, so literally minutes after posting this, I found the answer, sort of: add some code to reset the hover state to normal on devices that don't match `(hover: hover)`.

```scss
@media not all and (hover: hover) {
  .btn {
    &:hover {
      color: var(--#{$prefix}btn-color);
      text-decoration: if($link-decoration == none, null, none);
      background-color: var(--#{$prefix}btn-bg);
      border-color: var(--#{$prefix}btn-border-color);
    }
  }
}
```

This keeps the highlighting when the button is pressed and but gets rid of the sticky hover issue. However, it seems like this only works for my project, as I tried the same thing on the example page and it just made highlighting not happen at all. No idea what's going on there.
