### DISCUSSION TITLE
Override variables in dark mode

### DISCUSSION THREAD

**Discussion by mashehu** [twbs/bootstrap#37856] [Q&A] [answered]
Hi,

I would like to have for example dark tooltips or a darker shade for `success`. Do I have to write class specific rules or is there a way where I can overwrite the values of e.g. `$tooltip-color` or `$success`? I tried the following in my `variables.scss`, which didn't have any effect:
```
[data-bs-theme="dark"] {
  $green: #1a9655;
  $tooltip-color: $body-color-dark;
  $tooltip-bg: $body-bg-dark;
}

**Comment by julien-deramond** [comment, marked as answer]
Hey @mashehu
You can do the following:
```scss
@if $enable-dark-mode {
  @include color-mode(dark) {
    .tooltip {
      --bs-tooltip-bg: green;
      --bs-tooltip-color: purple;
    }
  }
}
```

If you don't have access to `$enable-dark-mode` and/or `color-mode` mixin you can do directly:

```scss
[data-bs-theme="dark"] {
  .tooltip {
    --bs-tooltip-bg: green;
    --bs-tooltip-color: purple;
  }
}
```
