### DISCUSSION TITLE
Form validation with form-floating

### DISCUSSION THREAD

**Discussion by BSarmady** [twbs/bootstrap#37966] [Q&A]
version 5.2 and above has interesting form input called floating labels which looks a lot like material (android).

There is no example in [floating labels document](https://getbootstrap.com/docs/5.2/forms/floating-labels/) to show both error and label on top of the text.

![Invalid Input](https://user-images.githubusercontent.com/2040435/215253959-54114e5c-e517-4c5b-b091-2d851bf74336.jpg)

Currently I'm doing this

```css
input.is-invalid ~ label.invalid {display:inline !important;}
input.is-invalid ~ label.label {display:none !important;}

input:not(.is-invalid) ~ label.invalid {display:none !important;}
input:not(.is-invalid) ~ label.label {display:inline !important;}
```

```html
<div class="form-floating mb-3">
  <input type="text" class="form-control" id="edt_inputname" placeholder="&nbsp;" value="">
  <label class="label" for="edt_inputname">enter value</label>
  <label class="invalid text-danger" for="edt_inputname">Invalid input</label>
</div>
```

Is there a ready to use bootstrap CSS to achieve this ? Of course I still need a javascript to verify input validity but that is out of scope of this question.
