### DISCUSSION TITLE
Why I can applied a specific color value for $primary variable in dark mode?

### DISCUSSION THREAD

**Discussion by devhoussam1998** [twbs/bootstrap#38255] [Q&A] [answered]
Why I can applied a specific color value for $primary variable in dark mode?

<img width="290" alt="Screenshot 2023-03-17 at 01 49 12" src="https://user-images.githubusercontent.com/121255432/225783642-effac967-fec3-444e-a502-d18e9547e8c3.png">

<img width="213" alt="Screenshot 2023-03-17 at 01 46 10" src="https://user-images.githubusercontent.com/121255432/225783668-008d1fd6-32a9-42c7-9ee9-25d1d39ea6e9.png">

```
_root.scss

@if $enable-dark-mode {
  @include color-mode(dark, true) {
    --#{$prefix}primary: #{$primary-dark};
    --#{$prefix}primary-rgb: #{to-rgb($primary-dark)};
  }
}

_variables-dark.scss

$primary-dark: #10c62e;

_variables.scss

$primary: #c61056;

plugins.scss

// Bootstrap

// Configuration

@import "~bootstrap/scss/functions";
@import "./variables";
@import "./variables-dark";
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/variables-dark";
@import "~bootstrap/scss/maps";
@import "~bootstrap/scss/mixins";
@import "~bootstrap/scss/utilities";

// Layout & components
@import "./root";
@import "~bootstrap/scss/root";
@import "~bootstrap/scss/reboot";
@import "~bootstrap/scss/type";
@import "~bootstrap/scss/images";
@import "~bootstrap/scss/containers";
@import "~bootstrap/scss/grid";
@import "~bootstrap/scss/tables";
@import "~bootstrap/scss/forms";
@import "~bootstrap/scss/buttons";
@import "~bootstrap/scss/transitions";
@import "~bootstrap/scss/dropdown";
@import "~bootstrap/scss/button-group";
@import "~bootstrap/scss/nav";
@import "~bootstrap/scss/navbar";
@import "~bootstrap/scss/card";
@import "~bootstrap/scss/accordion";
@import "~bootstrap/scss/breadcrumb";
@import "~bootstrap/scss/pagination";
@import "~bootstrap/scss/badge";
@import "~bootstrap/scss/alert";
@import "~bootstrap/scss/progress";
@import "~bootstrap/scss/list-group";
@import "~bootstrap/scss/close";
@import "~bootstrap/scss/toasts";
@import "~bootstrap/scss/modal";
@import "~bootstrap/scss/tooltip";
@import "~bootstrap/scss/popover";
@import "~bootstrap/scss/carousel";
@import "~bootstrap/scss/spinners";
@import "~bootstrap/scss/offcanvas";
@import "~bootstrap/scss/placeholders";

// Helpers

@import "~bootstrap/scss/helpers";

// Utilities

@import "~bootstrap/scss/utilities/api";
```

**Comment by julien-deramond** [comment, marked as answer]
You can try something like this, seems to work well. The order of declaration is important.

```scss
// @import "../node_modules/bootstrap/scss/bootstrap";

// Custom.scss
// Option B: Include parts of Bootstrap

// 1. Include functions first (so you can manipulate colors, SVGs, calc, etc)
@import "../node_modules/bootstrap/scss/functions";

// 2. Include any default variable overrides here
$primary: #10c62e;
$primary-dark: #c61056;

// 3. Include remainder of required Bootstrap stylesheets (including any separate color mode stylesheets)
@import "../node_modules/bootstrap/scss/variables";
@import "../node_modules/bootstrap/scss/variables-dark";

// 5. Include remainder of required parts
@import "../node_modules/bootstrap/scss/maps";
@import "../node_modules/bootstrap/scss/mixins";
@import "../node_modules/bootstrap/scss/root";

// 6. Optionally include any other parts as needed
@import "../node_modules/bootstrap/scss/utilities";
@import "../node_modules/bootstrap/scss/reboot";
@import "../node_modules/bootstrap/scss/type";
@import "../node_modules/bootstrap/scss/images";
@import "../node_modules/bootstrap/scss/containers";
@import "../node_modules/bootstrap/scss/grid";
@import "../node_modules/bootstrap/scss/helpers";

// 7. Optionally include utilities API last to generate classes based on the Sass map in `_utilities.scss`
@import "../node_modules/bootstrap/scss/utilities/api";

// 8. Add additional custom code here
@import "../node_modules/bootstrap/scss/alert";
@import "../node_modules/bootstrap/scss/tooltip";

@if $enable-dark-mode {
  @include color-mode(dark, true) {
    --#{$prefix}primary: #{$primary-dark};
    --#{$prefix}primary-rgb: #{to-rgb($primary-dark)};
  }
}
```
