### DISCUSSION TITLE
How to switch between two diffirent $primary colors in diffirent theme modes (light/dark)

### DISCUSSION THREAD

**Discussion by devhoussam1998** [twbs/bootstrap#38259] [Q&A] [answered]
here is an example but it's not work as expected: https://stackblitz.com/edit/github-mpdkmh?file=scss/styles.scss

When I switch to light mode or dark mode, I wish to incorporate two distinct color values into the same $primary value, which will affect the style accordingly.

**Comment by julien-deramond** [comment, marked as answer]
There's no `$theme-color-dark` right now. I agree that it would be nice to have it.
Might land with https://github.com/twbs/bootstrap/pull/38136.

In the meantime, you can do something like this (see https://stackblitz.com/edit/github-mpdkmh-eykwbs?file=scss%2Fstyles.scss) so that your button change its color:

```scss
$primary: #c61056; // for light mode
$primary-dark: #10c62e; // for dark mode

// [...]

$theme-colors-dark: (
  'primary': $primary-dark,
);

// [...]

@if $enable-dark-mode {
  @include color-mode(dark, true) {
    @each $color, $value in $theme-colors-dark {
      @debug $value;
      .btn-#{$color} {
        @include button-variant($value, $value);
      }
    }
  }
}
```
