### DISCUSSION TITLE
Changing the primary color with color modes

### DISCUSSION THREAD

**Discussion by MaticSulc** [twbs/bootstrap#38419] [Q&A]
Is there a way to change the whole "primary" color scheme for a specific theme?
I want to apply a class/data attribute to the body/html tag, and then render a specific primary color based on that.

This doesn't work unfortunately. If this isnt't doable - is there an alternative approach?
```scss
[data-bs-theme="color-2"] {
	* {
		--bs-primary-rgb: #ff0000;
	}
}
```
