### DISCUSSION TITLE
How do I set different theme colours for dark and light mode in 5.3.0?

### DISCUSSION THREAD

**Discussion by cuboci** [twbs/bootstrap#38693] [Q&A]
I'd like to use different `primary`/`danger`/etc. colours for light and dark mode, especially for buttons. However, the `btn-variant-loop` (in `_buttons.scss`) directly cycles through `$theme-colors` and it only adjusts the hover/active shading depending on the theme. As far as I can see, there's only a single `$theme-colors` map and no way to specify different ones in Sass for light and dark mode. Am I overlooking something or is this just not possible?

**Comment by julien-deramond** [comment]
I'm a bit short in time so this is just a quick answer that isn't maybe the best option, but you might be able to override the buttons rendering by doing something like this:

```scss
// Override light mode

// Defining your own button colors map for the light mode (that could be a variant of `$theme-colors`)
$theme-colors-custom-btn-colors: (
  "primary": #fd0
) !default;

@each $color, $value in $theme-colors-custom-btn-colors {
  .btn-#{$color} {
    @include button-variant($value, $value); // The other params could be used as well for fine-grained definition
  }
}

// Override dark mode

// Defining your own button colors map for the dark mode (that could be a variant of `$theme-colors`)
$theme-colors-custom-btn-dark-colors: (
  "primary": #00f
) !default;

@each $color, $value in $theme-colors-custom-btn-dark-colors {
  @include color-mode(dark) {
    .btn-#{$color} {
      @include button-variant($value, $value); // The other params could be used as well for fine-grained definition
    }
  }
}
```

Hope it can help :)
