### DISCUSSION TITLE
How to change the carousel color buttons ?

### DISCUSSION THREAD

**Discussion by Awazleon** [twbs/bootstrap#38789] [Q&A] [answered]
Hello,
I'm really happy withe latest BS5 version, especially with the introduction of the dark mode. I set the data-bs-theme="dark" in the HTML tag and that's perfect
I found an annoying point when using the carousel? The indicators as well the arrow buttons are black and I don't find that as accurate as white color in this specific case. I tried to add the data-bs-theme="light" within the carousel init as following : 
`<div id="carou" class="carousel slide pb-1" data-bs-theme="light">`
but nothing change.
Do I'm wrong somewhere or is it only working with specific components ?

**Comment by julien-deramond** [comment, marked as answer]
Hey @Awazleon

You're using the right approach. However, it does not work yet in all cases for components that way depending on how they are developed.
Here, it's because we use `filter: $carousel-dark-control-icon-filter;` (a Sass var) in our code which produces in your use case a static CSS rule (not dynamic with CSS variables):

```css
[data-bs-theme=dark] .carousel .carousel-control-prev-icon,
[data-bs-theme=dark] .carousel .carousel-control-next-icon, [data-bs-theme=dark].carousel .carousel-control-prev-icon,
[data-bs-theme=dark].carousel .carousel-control-next-icon {
  filter: invert(1) grayscale(100);
}
```

We don't have explicit `[data-bs-theme=light] .carousel*` rules so the dark theme will be always displayed even if there are contextual light theme components within.

As a patch, I think you could add something like the following CSS rule (or a more precise one) to your project to handle the color of the indicators (reverting the applied filter):

```css
[data-bs-theme="light"] .carousel .carousel-control-prev-icon,
[data-bs-theme="light"] .carousel .carousel-control-next-icon,
[data-bs-theme="light"].carousel .carousel-control-prev-icon,
[data-bs-theme="light"].carousel .carousel-control-next-icon {
  filter: none;
}
```

/cc @mdo for info about this use case. We might reference this issue somewhere for the next batch of modifications regarding color modes.
