### DISCUSSION TITLE
Unable to remove default blue outline and background color

### DISCUSSION THREAD

**Discussion by Mamunson** [twbs/bootstrap#39019] [Q&A]
Hi there,

I'm trying to make the border outline and background color white when I click on an item but with no success (It's always showing the default blue color. This is the accordion I'm using:

`    

    <div class="accordion accordion-flush" id="accordionFlushExample">
      <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingOne">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
            Accordion Item #1
          </button>
        </h2>
        <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
          <div class="accordion-body">Placeholder content for this accordion, which is intended to demonstrate the <code>.accordion-flush</code> class. This is the first item's accordion body.</div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingTwo">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
            Accordion Item #2
          </button>
        </h2>
        <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
          <div class="accordion-body">Placeholder content for this accordion, which is intended to demonstrate the <code>.accordion-flush</code> class. This is the second item's accordion body. Let's imagine this being filled with some actual content.</div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingThree">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
            Accordion Item #3
          </button>
        </h2>
        <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
          <div class="accordion-body">Placeholder content for this accordion, which is intended to demonstrate the <code>.accordion-flush</code> class. This is the third item's accordion body. Nothing more exciting happening here in terms of content, but just filling up the space to make it look, at least at first glance, a bit more representative of how this would look in a real-world application.</div>
        </div>
      </div>
    </div>`

I added this to the CSS file with no success:

`
.accordion-border-color {
  border-color: #fff;
  outline-color: #fff;
}

.accordion-button-active-bg {
  background-color: #fff;
  border-color: #fff;
  outline-color: #fff;
}

.accordion-button-active-color {
  color: #fff;
}

.accordion-button-focus-border-color {
  color: #fff;
}
.accordion-button-focus-box-shadow {
  color: #fff;
}
`

Then I tried this CSS separately with no success either:

`.accordion-button,
.accordion-button:visited,
.accordion-button:hover,
.accordion-button:focus,
.accordion-button:active {
  background-color: #fff;
  border-color: #fff;
  outline-color: #fff;
}`

The bootstrap-min.css file has Bootstrap  v5.3.0-alpha1

Grateful for your guidance.

**Comment by nkdas91** [comment]
Hi @Mamunson 

The following CSS should work:

```css
.accordion {
    --bs-accordion-btn-focus-box-shadow: none; /* Removes the focus box shadow. Not recommended to remove this. */
    --bs-accordion-btn-focus-border-color: #fff; /* Sets the border color. accordion-button doesn't have a border by the way. */
    --bs-accordion-active-bg: #fff; /* Sets the background color. */
}
```

**Comment by Mamunson** [comment]
Hi Neeraj,

Many thanks, it worked :+1: 

I've a similar issue with this code as the div which contains the two images has a grey border/outline. I tried it to override it with CSS but with no success:

```html
<div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle custom-btn" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            Holzart
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-5 image-column"> 
                            <div class="image-container">
                                <img src="content/unsplash.jpg" alt="Image 1" class="img-fluid">
                            </div>
                            <div class="image-container">
                                <img src="content/unsplash.jpg" alt="Image 2" class="img-fluid">
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
        <button class="btn btn-secondary dropdown-toggle custom-btn" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            Bezug
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-5 image-column"> 
                            <div class="image-container">
                                <img src="content/unsplash.jpg" alt="Image 1" class="img-fluid">
                            </div>
                            <div class="image-container">
                                <img src="content/unsplash.jpg" alt="Image 2" class="img-fluid">
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
```

```css
.custom-btn {
  min-width: 150px; 
  height: 100px;
  border-radius: 4%;
}

.custom-btn:focus {
  border: 2px solid white; 
  outline: none; 
}

.image-container {
  margin-bottom: 10px; 
  border-color: #fff;
}

.image-container img {
  border-radius: 4%;
  border: solid 2px #dbdbcf;
  padding: 2px;
}

.dropdown-menu {
  --bs-dropdown-color: #fff;
}

.custom-dropdown-menu {
  padding: 0;
  margin: 0;
  width: auto; /* Default width */
}

.col-md-12:focus {
  outline: none;
}
```

Grateful if you can guide me as to what to do about it.

**Reply by nkdas91** [reply]
Hi @Mamunson,

I am assuming you would like to remove the grey border from the ```.dropdown-menu```.

Two ways to do this:
1. Remove the border
```css
.dropdown-menu {
  --bs-dropdown-border-width: 0;
}
```

2. Make the border color transparent
```css
.dropdown-menu {
  --bs-dropdown-border-color: transparent;
}
```

Here are all the CSS variables that you can use to easily modify a Dropdown menu: https://getbootstrap.com/docs/5.3/components/dropdowns/#variables

Likewise, every other Bootstrap component can be modified.
