### DISCUSSION TITLE
Dark mode for mark tag (text highlighting)

### DISCUSSION THREAD

**Discussion by angely-dev** [twbs/bootstrap#39139] [Ideas] [answered]
Hello,

I'm using the `<mark>` tag quite often, e.g.:

![image](https://github.com/twbs/bootstrap/assets/4362224/5b466438-9d7e-4131-9ad9-cb274639e9f2)

But I find it too bright in dark mode:

![image](https://github.com/twbs/bootstrap/assets/4362224/2a7bbd64-6ab3-4c75-9b78-2d7af7e2ec3a)

In my specific case (`bg-light-subtle` as background color), I'd prefer something like:

![image](https://github.com/twbs/bootstrap/assets/4362224/e86f6412-8e9b-4fc1-9cba-e0b906bf5ddb)

So I ended up using this CSS snippet:

```css
[data-bs-theme=dark] { --bs-highlight-bg: var(--bs-gray-700); }
```

Questions: 

* Don't you find it too bright too in dark mode?
* Does Bootstrap plan to implement a dark mode version of `<mark>`?

[Current implementation](https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.css) is:

```css
:root,
[data-bs-theme=light] {
--bs-highlight-bg: #fff3cd;
}

[data-bs-theme=dark] {
/* No color override for --bs-highlight-bg in dark mode */
}

mark, .mark {
  padding: 0.1875em;
  background-color: var(--bs-highlight-bg);
}
```

Thanks!
