### DISCUSSION TITLE
Overriding default theme colors in a custom color mode

### DISCUSSION THREAD

**Discussion by nfreader** [twbs/bootstrap#39149] [Q&A] [answered]
Hello!

I'm trying to implement [a custom color mode](https://getbootstrap.com/docs/5.3/customize/color-modes/). I understand how the `data-theme` selector works, but I'm having trouble overriding color variables in sass. 

Here's what I've got so far in `ntos.scss`: 
```scss
[data-bs-theme="ntos"] {

  $font-family-base: Verdana, sans-serif;

  $ntos-colors: (
    "primary":    #3E6189,
    "secondary":  $secondary,
    "success":    #4D9121,
    "info":       #009A93,
    "warning":    #CD7A0D,
    "danger":     #BD2020,
    "light":      #646464,
    "dark":       $dark,
    "yellow":     $yellow-400
  );

  $theme-colors: map-merge($ntos-colors, $theme-colors);

  body {
    background: url("../../templates/assets/statbus-star.svg") center/40%
        no-repeat,
      linear-gradient(to bottom, #252525 0%, #202020 100%), #252525;
  }
  .breadcrumb-item a,
  a.ntos {
    border: 1px solid $white;
    padding: $spacer * 0.25;
    text-decoration: none;
    background: $primary;
    color: $white;
  }
}
```
The regular CSS selectors work great, but the sass variables don't do anything. I think I'm misinterpreting the documentation.

This is what my root stylesheet looks like:

```scss
// 1. Include functions first (so you can manipulate colors, SVGs, calc, etc)
@import "~bootstrap/scss/functions";

// 2. Include any default variable overrides here

$enable-cssgrid: true;

// 3. Include remainder of required Bootstrap stylesheets (including any separate color mode stylesheets)
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/variables-dark";

// 4. Include any default map overrides here
@import "statbus"; //Bootstrap customizations, regardless of color scheme
@import "ntos"; //Color scheme & design based on tgui

// 5. Include remainder of required parts
@import "~bootstrap/scss/maps";
@import "~bootstrap/scss/mixins";
@import "~bootstrap/scss/root";

// 6. Optionally include any other parts as needed

// scss-docs-start import-stack
// Configuration
@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/variables-dark";
@import "~bootstrap/scss/maps";
@import "~bootstrap/scss/mixins";
@import "~bootstrap/scss/utilities";

// Layout & components
@import "~bootstrap/scss/reboot";
@import "~bootstrap/scss/type";
@import "~bootstrap/scss/images";
@import "~bootstrap/scss/containers";
@import "~bootstrap/scss/grid";
@import "~bootstrap/scss/tables";
@import "~bootstrap/scss/forms";
@import "~bootstrap/scss/buttons";
@import "~bootstrap/scss/transitions";
@import "~bootstrap/scss/dropdown";
@import "~bootstrap/scss/button-group";
@import "~bootstrap/scss/nav";
@import "~bootstrap/scss/navbar";
@import "~bootstrap/scss/card";
@import "~bootstrap/scss/accordion";
@import "~bootstrap/scss/breadcrumb";
@import "~bootstrap/scss/pagination";
@import "~bootstrap/scss/badge";
@import "~bootstrap/scss/alert";
@import "~bootstrap/scss/progress";
@import "~bootstrap/scss/list-group";
@import "~bootstrap/scss/close";
@import "~bootstrap/scss/toasts";
@import "~bootstrap/scss/modal";
@import "~bootstrap/scss/tooltip";
@import "~bootstrap/scss/popover";
@import "~bootstrap/scss/carousel";
@import "~bootstrap/scss/spinners";
@import "~bootstrap/scss/offcanvas";
@import "~bootstrap/scss/placeholders";

// Helpers
@import "~bootstrap/scss/helpers";

// Utilities
@import "~bootstrap/scss/utilities/api";
// scss-docs-end import-stack


// 7. Optionally include utilities API last to generate classes based on the Sass map in `_utilities.scss`
@import "~bootstrap/scss/utilities/api";

// 8. Add additional custom code here
@import "~@fortawesome/fontawesome-free/css/all.css";
@import "~@fortawesome/fontawesome-free/css/v4-shims.css";
@import "~@fortawesome/fontawesome-free/css/v5-font-face.css";

.bi {
    width: 1em;
    height: 1em;
    vertical-align: -0.125em;
    fill: currentcolor;
}
```
Hoping someone can point me in the right direction! :)

**Comment by julien-deramond** [comment]
Quick question to understand precisely what you're trying to achieve here: do you want at the end to be able to do the following?

```html
<!-- Warning: this is pseudo-code -->
<button class="btn btn-primary">I'm a blue button like in Bootstrap theme</button>
<div data-bs-theme="dark">
  <button class="btn btn-primary">I'm a blue button like in Bootstrap theme (contextual dark mode)</button>
</div>
<div data-bs-theme="ntos">
  <button class="btn btn-primary">I'm a whatever color button in ntos theme (contextual)</button>
</div>
```

Or do you want rather to override the default style of Bootstrap so that `primary` is set to your "ntos" primary color, and so that Bootstrap default style is completely useless for your website which will use only the "ntos" style.

_Not linked to my question but I can see in your file that you import several times "~bootstrap/scss/functions", "~bootstrap/scss/variables", "~bootstrap/scss/variables-dark", "~bootstrap/scss/maps"; "~bootstrap/scss/mixins";_

**Reply by nfreader** [reply]
Yes, the NtOS color mode should be on the same "level" as dark and light mode.

<img width="183" alt="Screenshot 2023-09-05 at 15 27 00" src="https://github.com/twbs/bootstrap/assets/884548/cef80d7d-a4be-4ac3-bb03-1f7349758ccf">

Ideally my users will be able to switch seamlessly between the three modes.

> Not linked to my question but I can see in your file that you import several times "~bootstrap/scss/functions", "~bootstrap/scss/variables", "~bootstrap/scss/variables-dark", "~bootstrap/scss/maps"; "~bootstrap/scss/mixins";

Ooh thanks, I missed this.

**Reply by julien-deramond** [reply, marked as answer]
OK so NtOS can be considered as a separate theme on top of Bootstrap Light and Bootstrap Dark.
The idea here is to follow https://getbootstrap.com/docs/5.3/customize/color-modes/#custom-color-modes that you can define apparently within your `_ntos.scss` included as you've done it with `@import "ntos";`.

In this file it's possible to modify the values of the CSS vars that are provided by the framework. For example:

```scss
[data-bs-theme="ntos"] {
  --bs-body-color: var(--bs-white);
  --bs-body-color-rgb: #{to-rgb($white)};
  --bs-body-bg: var(--bs-blue);
  --bs-body-bg-rgb: #{to-rgb($blue)};
  --bs-tertiary-bg: #{$blue-600};

  .dropdown-menu {
    --bs-dropdown-bg: #{mix($blue-500, $blue-600)};
    --bs-dropdown-link-active-bg: #{$blue-700};
  }

  .btn-secondary {
    --bs-btn-bg: #{mix($gray-600, $blue-400, .5)};
    --bs-btn-border-color: #{rgba($white, .25)};
    --bs-btn-hover-bg: #{darken(mix($gray-600, $blue-400, .5), 5%)};
    --bs-btn-hover-border-color: #{rgba($white, .25)};
    --bs-btn-active-bg: #{darken(mix($gray-600, $blue-400, .5), 10%)};
    --bs-btn-active-border-color: #{rgba($white, .5)};
    --bs-btn-focus-border-color: #{rgba($white, .5)};
    --bs-btn-focus-box-shadow: 0 0 0 .25rem rgba(255, 255, 255, .2);
  }
}
```

But here, we are still using Bootstrap color palette. In your case, you'll probably want a different color palette, maybe some intermediate tokens like semantic tokens and so on.
You can then create all the Sass variables you want (or CSS variables) to handle that. For example:

```scss
[data-bs-theme="ntos"] {
  $primary: #4c0bce;

  /* ... */

  .btn-secondary {
    --bs-btn-bg: #{$primary}; // And your secondary button background color will be violet
    /* ... */
  }
}
```

This is basically what we are doing to handle the dark mode:
- Our [_root.scss](https://github.com/twbs/bootstrap/blob/main/scss/_root.scss) at then end of the file will redefine CSS vars
- Our [_variables-dark.scss](https://github.com/twbs/bootstrap/blob/main/scss/_variables-dark.scss) will define some specific Sass variables to be able to switch dynamically the content of the CSS vars
- There is more complexity with the maps within the framework we want to simplify in v6 with the `$theme-colors-*` but I think you can avoid this part to handle your own maps and override the CSS in your own way
- In some components in the framework, we need to do stuff like this too to override only a specific part (here to handle icons with CSS variables):

```css
@if $enable-dark-mode {
  @include color-mode(dark) {
    .accordion-button::after {
      --#{$prefix}accordion-btn-icon: #{escape-svg($accordion-button-icon-dark)};
      --#{$prefix}accordion-btn-active-icon: #{escape-svg($accordion-button-active-icon-dark)};
    }
  }
}
```

I think that's it.

There are several ways to organize your theme in terms of Sass and CSS properties.

I've never done the exercise to create a full theme that must work in cohabitation with the Bootstrap one, so maybe some information won't be too exact but I hope it can lead you to the right solution :)
