### DISCUSSION TITLE
Change bg color of focused floating labels

### DISCUSSION THREAD

**Discussion by Kiyotaka-Ayanokoj** [twbs/bootstrap#39230] [Q&A] [answered]
How do I change this bg when I focused an input element? I set bg-transparent or any other and it still keep that white background, I’m using React + Vite

I wanna remove this white background in the label element
![IMG_0878](https://github.com/twbs/bootstrap/assets/126770037/2cf5da85-bed5-4bab-99a3-c2ce7c3c33d2)

### What operating system(s) are you seeing the problem on?

iOS

### What browser(s) are you seeing the problem on?

Safari

### What version of Bootstrap are you using?

v5.3.2

**Comment by julien-deramond** [comment, marked as answer]
This is not the default rendering of the focused floating labels in dark mode (see https://getbootstrap.com/docs/5.3/forms/floating-labels/). If this is the default rendering that you can see with v5.3.2, could you please try to create a reproducible example by using CodePen or Stackblitz so that we could fix it?

Anyway, if you want to fix it on your side, I think you can override the rendering when focused with such a rule (to adapt to your needs):

```css
.form-floating label::after {
  background-color: #fd0 !important; /* !important might not be needed depending on your use case */
}
```

Since it is handled by `::after`, you won't be able to use a class provided by Bootstrap such as `.bg-*`.
