### DISCUSSION TITLE
For Bootstrap-icons 1.11.1, should I use sass to include the icons I needed only? Like Bootstrap? How to do this?

### DISCUSSION THREAD

**Discussion by chiahao** [twbs/bootstrap#39365] [Q&A] [answered]
Environment: jsp web application
For Bootstrap-icons 1.11.1, should I use sass to include the icons I needed only? Like Bootstrap? How to do this?
Or should I just include "bootstrap-icons.css"?
Thank you.

**Comment by julien-deramond** [comment, marked as answer]
For eco-design reasons, I'd avoid loading the entire `bootstrap-icons.css` file on your website.
In our examples, we use an internal sprite because it's rather handy for us and to share with folks (e.g. https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/examples/dashboard/index.html).
But there are various ways to do it depending on your use cases that are described in the [Install Icons doc](https://icons.getbootstrap.com/#install).

**Reply by chiahao** [reply]
I'm so sorry to bother again.
I've read the sample file in the link.
But I don't understand the class `bi` came from?

```html
<svg class="bi"><use xlink:href="#calendar3"/></svg>
```

It seams that it came from `bootstrap-icons.css`.
Does that mean I need to manually extract the `bi` class to minimize size?

**Reply by julien-deramond** [reply]
The documentation is not really clear about the `.bi` class indeed.
When you want to optimize the size, you're right, you'll need to define a `.bi` class somehow too because it's contained only in https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.css.

If you're embedding the icons into a font, you could use the same rule as defined in https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.css:

```css
.bi::before,
[class^="bi-"]::before,
[class*=" bi-"]::before {
  display: inline-block;
  font-family: bootstrap-icons !important; /* This is your font defined somewhere */
  font-style: normal;
  font-weight: normal !important;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  vertical-align: -.125em;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

If you don't use a font to group together the icons but use them just as SVGs you could also use a `.bi` class that you need to add to your project with the following content (this is the rule we use in our examples in Bootstrap documentation):

```css
.bi {
   vertical-align: -.125em;
   fill: currentColor;
}
```
