### DISCUSSION TITLE
Custom Position Values

### DISCUSSION THREAD

**Discussion by iTheMaverick** [twbs/bootstrap#39393] [Q&A] [answered]
What's the correct way of getting this to work? Closest example I could find was changing the colors so I pretty much followed that and just made it relevant to what I was doing but that didn't work.
![image](https://github.com/twbs/bootstrap/assets/141296807/3c64fe70-0136-42b2-ac49-6b685f833333)

**Comment by iTheMaverick** [comment]
Realized I probably should include this too so y'all know the above isn't *all* I'm doing 
![image](https://github.com/twbs/bootstrap/assets/141296807/9d099c22-e978-4d07-8c7e-be362a066bdf)
![image](https://github.com/twbs/bootstrap/assets/141296807/7ff4ed8b-9e8d-494e-b66e-483c78239339)

**Comment by julien-deramond** [comment]
It basically works the same way:

```scss
@import "../node_modules/bootstrap/scss/functions";

$position-values: (
  0: 0,
  50: 50%,
  60: 60%,
  65: 65%,
  /* ... */
);

@import "../node_modules/bootstrap/scss/variables";
@import "../node_modules/bootstrap/scss/variables-dark";
@import "../node_modules/bootstrap/scss/maps";
@import "../node_modules/bootstrap/scss/mixins";
@import "../node_modules/bootstrap/scss/utilities";
@import "../node_modules/bootstrap/scss/utilities/api";
```

The last one is pretty important, otherwise, your utility won't be generated.

With my example (not containing all your values), here's what'll be generated:

```css
.top-0 {
  top: 0 !important;
}
.top-50 {
  top: 50% !important;
}
.top-60 {
  top: 60% !important;
}
.top-65 {
  top: 65% !important;
}
.bottom-0 {
  bottom: 0 !important;
}
.bottom-50 {
  bottom: 50% !important;
}
.bottom-60 {
  bottom: 60% !important;
}
.bottom-65 {
  bottom: 65% !important;
}
.start-0 {
  left: 0 !important;
}
.start-50 {
  left: 50% !important;
}
.start-60 {
  left: 60% !important;
}
.start-65 {
  left: 65% !important;
}
.end-0 {
  right: 0 !important;
}
.end-50 {
  right: 50% !important;
}
.end-60 {
  right: 60% !important;
}
.end-65 {
  right: 65% !important;
}
```
