### DISCUSSION TITLE
Making utilities responsive and adding more to fs-1, fs-2, etc...

### DISCUSSION THREAD

**Discussion by do-kevin** [twbs/bootstrap#39455] [Q&A]
Hey folks,

I'm trying to learn how to extend Bootstrap's theme and utilities to be similar to Tailwind's. Right now, I can change the colors so far.
But how do I enable certain utility classes to be responsive and how would I add an additional `fs-{number}` to font size classes?

Here's what I got:

```scss
@import "../../../node_modules/bootstrap/scss/functions";
@import "../../../node_modules/bootstrap/scss/variables";
@import "../../../node_modules/bootstrap/scss/mixins/breakpoints";
@import "../../../node_modules/bootstrap/scss/utilities";
@import "../../../node_modules/bootstrap/scss/utilities/api";

$primary: #fa963a;
$secondary: #fbe5d0;
$light: #fffaf5;

$utilities: map-merge(
  $utilities,
  (
    "border":
      map-merge(
        map-get($utilities, "border"),
        (
          responsive: true,
        )
      ),
  )
);

@import "../../../node_modules/bootstrap/scss/bootstrap";

```

Which gives me this error:

![Screenshot 2023-11-29 at 7 24 36 PM](https://github.com/twbs/bootstrap/assets/40156784/62efb607-6989-4895-95b9-b579161bfeed)

Is the order of my imports wrong? What am I missing?

**Comment by julien-deramond** [comment]
Hey @do-kevin
I haven't tested the result, but you're missing the following between `variables` and `mixins/breakpoints` imports to compile:
```scss
/* ... */
@import "../node_modules/bootstrap/scss/variables";
@import "../node_modules/bootstrap/scss/maps"; /* it contains `$theme-colors-rgb` */
@import "../node_modules/bootstrap/scss/mixins"; /* it contains `generate-utility()` */
@import "../node_modules/bootstrap/scss/mixins/breakpoints";
/* ... */
```

**Reply by do-kevin** [reply]
Thank you @julien-deramond,

So here's what I got now and I'm not getting errors:
```scss
@import "../../../node_modules/bootstrap/scss/functions";

$primary: #fa963a;
$secondary: #fbe5d0;
$light: #fffaf5;

@import "../../../node_modules/bootstrap/scss/variables";
@import "../../../node_modules/bootstrap/scss/variables-dark";

@import "../../../node_modules/bootstrap/scss/maps";
@import "../../../node_modules/bootstrap/scss/mixins";

$utilities: (
  "border": (
    property: border,
    values: (
      null: var(--#{$prefix}border-width) var(--#{$prefix}border-style)
        var(--#{$prefix}border-color),
      0: 0,
    ),
  ),
  "border-top": (
    property: border-top,
    values: (
      null: var(--#{$prefix}border-width) var(--#{$prefix}border-style)
        var(--#{$prefix}border-color),
      0: 0,
    ),
  ),
  "border-end": (
    property: border-right,
    class: border-end,
    values: (
      null: var(--#{$prefix}border-width) var(--#{$prefix}border-style)
        var(--#{$prefix}border-color),
      0: 0,
    ),
  ),
  "border-bottom": (
    property: border-bottom,
    values: (
      null: var(--#{$prefix}border-width) var(--#{$prefix}border-style)
        var(--#{$prefix}border-color),
      0: 0,
    ),
  ),
  "border-start": (
    property: border-left,
    class: border-start,
    values: (
      null: var(--#{$prefix}border-width) var(--#{$prefix}border-style)
        var(--#{$prefix}border-color),
      0: 0,
    ),
  ),
  "border-color": (
    property: border-color,
    class: border,
    local-vars: (
      "border-opacity": 1,
    ),
    values: $utilities-border-colors,
  ),
  "subtle-border-color": (
    property: border-color,
    class: border,
    values: $utilities-border-subtle,
  ),
  "border-width": (
    property: border-width,
    class: border,
    values: $border-widths,
  ),
  "border-opacity": (
    css-var: true,
    class: border-opacity,
    values: (
      10: 0.1,
      25: 0.25,
      50: 0.5,
      75: 0.75,
      100: 1,
    ),
  ),
);

@import "../../../node_modules/bootstrap/scss/utilities";
@import "../../../node_modules/bootstrap/scss/utilities/api";

@import "../../../node_modules/bootstrap/scss/bootstrap";

```

However, I'm testing border's responsiveness and it's not working. Is it `border-{breakpoint}-top` and `border-{breakpoint}-primary`?

Also, how should I go about customizing a Bootstrap btn's :active and :hover styles?

Here is the project I'm working on for this: https://github.com/do-kevin/Zephyr-Node/blob/chore-custom-theme/client2/src/assets/sass/custom.scss
