### DISCUSSION TITLE
Support for right-to-left text (dir="rtl")

### DISCUSSION THREAD

**Discussion by David-Maran** [twbs/bootstrap#39485] [Q&A]
I read this :

```css
/* Traditional */
body {
  margin-left: 1rem;
}

body[dir="rtl"] {
  margin-left: 0; /* reset left margin */
  margin-right: 1rem; /* apply to the right */
  text-align: right; /* push text to the other side */
}
```

… there’s no longer a need to rest things as long as we’re working with logical properties:

```css
/* Much easier! */
body {
  margin-inline-start: 1rem;
}
```

Is this 'new' way is the best?
