### DISCUSSION TITLE
v5.3.0 Table variants (colors) not changing from light mode to dark mode when system settings change

### DISCUSSION THREAD

**Discussion by emmahsax** [twbs/bootstrap#39482] [Q&A]
I am using bootstrap in a Jekyll-built website with bootstrap's tables.

On Bootstrap `v5.3.0-alpha3`, I can use the default variant in order to have the tables change their background color automatically when the computer/mobile system's light/dark mode changes.

But starting in `v5.3.0`, the default variant no longer works like that (on my website at least). Instead, setting no variant means that the table just looks like light mode all the time, even when switching the computer system to dark mode.

I bypassed the issue by setting this in my code (allows me to fully customize the background colors of all tables based on `prefers-color-scheme: dark`):

```css
html {
  --table: #606c71;
  --table-background: #eff0f1;
}

@media (prefers-color-scheme: dark) {
  html {
    --table: #cfd4d6;
    --table-background: #525252;
  }
}

.table {
  --bs-table-bg: var(--table-background);
  --bs-table-color: var(--table);
}
```

But I'd prefer if it just works when the system settings change automatically.

Here is a video of the CSS working on `v5.3.0-alpha3`: https://github.com/twbs/bootstrap/assets/7562793/30d30c1c-1965-44e1-ab4a-75896b5f6426

Here is a video of the CSS not working on `v5.3.0`: https://github.com/twbs/bootstrap/assets/7562793/673e4550-0dd3-4418-86b1-f53febd5687d
