### DISCUSSION TITLE
Range component inside a card is impossible to see

### DISCUSSION THREAD

**Discussion by gumbarros** [twbs/bootstrap#39707] [Q&A]
Is there a way to change the range line color?

https://github.com/JJConsulting/JJMasterData/issues/180

**Comment by julien-deramond** [comment]
Hey @gumbarros 

If you're [customizing our Sass](https://getbootstrap.com/docs/5.3/customize/sass/), you can override the value of `$form-range-track-bg`.

If you override the style of Bootstrap directly in CSS, you'll need to override these rules (foundable by searching for `$form-range-track-bg` in https://github.com/twbs/bootstrap/blob/main/scss/forms/_form-range.scss):

```css
.form-range::-webkit-slider-runnable-track {
  background-color: #fd0;
}

.form-range::-moz-range-track {
  background-color: #fd0;
}
```
