### DISCUSSION TITLE
The problem with the url() function when using data URL

### DISCUSSION THREAD

**Discussion by addison74** [twbs/bootstrap#39844] [Q&A]
I am using OpenMage with Bootstrap 5.2.3. I discovered this issue when I tried implementing a modal. The X was not appearing in the box, then I inspected the CSS code.

This is the **Bootstrap CSS file** content for the **.btn-close** class:

```scss
.btn-close {
  box-sizing: content-box;
  width: 1em;
  height: 1em;
  padding: 0.25em 0.25em;
  color: #000;
  background: transparent url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23000'%3e%3cpath d='M.293.293a1 1 0 0 1 1.414 0L8 6.586 14.293.293a1 1 0 1 1 1.414 1.414L9.414 8l6.293 6.293a1 1 0 0 1-1.414 1.414L8 9.414l-6.293 6.293a1 1 0 0 1-1.414-1.414L6.586 8 .293 1.707a1 1 0 0 1 0-1.414z'/%3e%3c/svg%3e") center/1em auto no-repeat;
  border: 0;
  border-radius: 0.375rem;
  opacity: 0.5;
}
```

This is the **CSS file from the browser cache** for the same class:

```scss
.btn-close {
  box-sizing: content-box;
  width: 1em;
  height: 1em;
  padding: 0.25em 0.25em;
  color: #000;
  background: transparent url("https://www.mydomain.tld/skin/frontend/default/custom_theme/css/data:image/svg+xml,%3csv")xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23000'%3e%3cpath d='M.293.293a1 1 0 0 1 1.414 0L8 6.586 14.293.293a1 1 0 1 1 1.414 1.414L9.414 8l6.293 6.293a1 1 0 0 1-1.414 1.414L8 9.414l-6.293 6.293a1 1 0 0 1-1.414-1.414L6.586 8 .293 1.707a1 1 0 0 1 0-1.414z'/%3e%3c/svg%3e") center/1em auto no-repeat;
  border: 0;
  border-radius: 0.375rem;
  opacity: 0.5;
}
```

As can be seen, the path where the bootstrap.css file is located was taken in the background url. How could I avoid this issue and stop adding the path? 

Thank you.
