### DISCUSSION TITLE
Add sum style for Links color and offset

### DISCUSSION THREAD

**Discussion by abdousami02** [twbs/bootstrap#40705] [Ideas]
Hello,
sum time where use `<a>` tag I want to **clear all style** `(color and underline)`  from global pages.
I suggest for adding this class for more controlled to link:

```css
/*
* this for unset all style of link
*/
.link-none {
    color: inherit;
    text-decoration: none;
}

/*
* this to delete underlinke 
* instead ( link-underline link-underline-opacity-0)
*/
.link-offset-0 {
    text-decoration: none;
}
```
