### DISCUSSION TITLE
Bootstrap Offcanvas Nav Icon Issue

### DISCUSSION THREAD

**Discussion by wdejesus1981** [twbs/bootstrap#40758] [Q&A]
Hi Everyone,

I am using Bootstraps off-canvas navigation for my new site. I started styling in css and using Font Awesome for the parent icons, but when you get to the drop-down portion and add the icons through CSS like I did for the parent items they stack on top of one another. The parent navigation was easy in adding a float, but the drop-down does not accept the same styling.

I've attached an image for you to review.
![bootstrap-nav](https://github.com/user-attachments/assets/352ea9d4-88f3-4349-9e0e-ebe326d790f0)

![bootstrap-nav](https://github.com/user-attachments/assets/18ca8979-f39c-4c76-b901-b8bab467b723)

Thank you!

Will

**Comment by wdejesus1981** [comment]
This is also the code I am using if it helps.

```css
.mainNavCustom li:before{
	color:#fff;
	content: "\f054"; /* FontAwesome Unicode */
	font-family: FontAwesome;
	display: inline-block;
	margin-left: 10px; /* same as padding-left set on li */
	width: 1.3em; /* same as padding-left set on li */
	font-style:normal;
	float:left;
	padding-top:8px;
}
```
