### DISCUSSION TITLE
Class text balanced

### DISCUSSION THREAD

**Discussion by abielmagudev** [twbs/bootstrap#41368] [Ideas] [answered]
Hi friends, can you add a class for balanced text?

```css
.text-balanced {
  text-wrap: balance;
}
```

```html
<p class="text-balanced">This is a text balanced by a class of CSS.</p>
```
