### DISCUSSION TITLE
Problem with bootstrap in angular

### DISCUSSION THREAD

**Discussion by J4KU8Dev** [twbs/bootstrap#41374] [Q&A] [answered]
I need help with my code. I added binding to my table. Its changing class: bg-info to tr odd and bg-warning to tr even. You can see, that is working when i will turn on console, but style doesn't change. For example, bootstrap is working for table( table-bordered).
![problem2](https://github.com/user-attachments/assets/514c2612-a5bb-4119-a241-707d1f058da7)
![problem](https://github.com/user-attachments/assets/45e537e5-8020-4c2b-af1c-d507c3232b8f)

**Comment by julien-deramond** [comment, marked as answer]
If you want to use `.bg-` classes, you'll need to apply them directly to each `<td>` or `<th>`, rather than to the `<tr>`.  
Alternatively, you can use `.text-bg-` classes, which apply both background and corresponding text colors.

Another approach—depending on your use case—would be to customize the table styling using CSS variables:

1. Assign an `id` (such as `myTable`) or `class` to your table.
2. Redefine the striped row background color using CSS, like this:

```css
#myTable {
  --bs-table-striped-bg: var(--bs-warning-bg-subtle);
  /* Do the same thing for the "normal" bg color, and for the text colors */
}
```
