### DISCUSSION TITLE
--bs-dropdown-box-shadow is set, but never used.

### DISCUSSION THREAD

**Discussion by jcoyne** [twbs/bootstrap#41570] [Q&A]
Should this rule exist?

```css
.dropdown-menu { 
  box-shadow: var(--bs-dropdown-box-shadow);
}
```
