### ISSUE TITLE
add box shadow style for focused [contenteditable] element

### ISSUE THREAD

**Issue by comerc** [twbs/bootstrap#15486]
like other form elements

**Comment by cvrebert** [comment]
We probably should require the `[contenteditable]` element to be a descendant of an element with some new class, to avoid conflicts.

**Comment by comerc** [comment]
```css
[contenteditable] { padding: 5px; outline: 0px solid transparent; border-radius: 3px; }
[contenteditable]:not(:focus) { border: 1px dashed #ddd; }
[contenteditable]:focus { border: 1px solid #51a7e8; box-shadow: inset 0 1px 2px rgba(0,0,0,0.075),0 0 5px rgba(81,167,232,0.5); }
```
I use this workaround, but I dont see border-animation for focused field, like for input-fields.

**Comment by cvrebert** [comment]
I think you'd need https://github.com/twbs/bootstrap/blob/fb6622a7d44c99323bea5bd69cb0604470bbe21a/less/forms.less#L128 for the animation.

**Comment by comerc** [comment]
I found very simle solution
```css
[contenteditable].form-control { height: initial; }
```
Thanks!
