### ISSUE TITLE
radio-inline/checkbox-inline positioning issue

### ISSUE THREAD

**Issue by OrganicPanda** [twbs/bootstrap#15652]
I'm not sure if this is on purpose or if my HTML is wrong but the `radio-inline` and `checkbox-inline` components seem to be positioned incorrectly. They are missing a container that has positioning ( `position: relative`) which makes them overflow and behave weirdly when used in an `overflow: auto` context.

[Example and fix](http://jsbin.com/juvemipuli/2/edit?html,css,output): http://jsbin.com/juvemipuli/2/edit?html,css,output

Fix:

```css
.radio-inline, .checkbox-inline {
  position: relative;
}
```
