### ISSUE TITLE
Improve grid system: .float-right-md

### ISSUE THREAD

**Issue by comerc** [twbs/bootstrap#15663]
for example:

```html
<div class="row">
    <div class="col-xs-12 col-md-8 float-right-md">always on top</div>
    <div class="col-xs-12 col-md-4" style="height: 100px;">left or bottom</div>
    <div class="col-xs-12 col-md-8">footer after #top or #bottom</div>
</div>
```

```css
/* if -md */ 
.float-right-md { float: right; }
```
