### ISSUE TITLE
Is line-height of input redundancy ?

### ISSUE THREAD

**Issue by Softor** [twbs/bootstrap#15675]
Please focus on line-height of input at:
https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css#L144
```css
input {
  line-height: normal;
}
```
and
https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css#L1095
```css
input,
button,
select,
textarea {
  font-family: inherit;
  font-size: inherit;
  line-height: inherit;
}
```
