### ISSUE TITLE
navbar-text floating to right in top fixed fluid container navbar issue in 3.3.2

### ISSUE THREAD

**Issue by ronypur** [twbs/bootstrap#15706]
I found a problem when trying to add .navbar-text .navbar-right in top-fixed-navbar with fluid container using 3.3.2. The text doesn't have negative right margin so that it too close to screen border. It work just fine if using nav list. [Here example of the problem](http://www.bootply.com/mvsni9t5bI). It has negative right margin when using 3.1.1.

**Comment by kkirsche** [comment]
@cvrebert I think I can put together a fix for this pretty easily but what does the `~` do here:
https://github.com/twbs/bootstrap/blob/master/less/navbar.less#L385

Wasn't able to find it clearly in the LESS documentation so want to ask about it and understand it better before putting together a fix

**Comment by cvrebert** [comment]
@kkirsche https://developer.mozilla.org/en-US/docs/Web/CSS/General_sibling_selectors

**Comment by ronypur** [comment]
@kkirsche i solved this by adding the old 3.1.1 css style in navbar, but i'm not sure if this is the right approach.
```css
.navbar-text.navbar-right:last-child{
    margin-right: 0px;
}
```

**Comment by kkirsche** [comment]
Thanks, @cvrebert / @ronypur. 

Fix: 
```css
.container-fluid > .navbar-text.navbar-right:last-child{
    margin-right: 0px;
}
```

http://jsfiddle.net/1L3oub0o/ (moved to JSFiddle just to reduce the amount of code displayed in the CSS window). This spacing issue doesn't seem to occur within `.container` but rather only on `.container-fluid`.

**Comment by smisch** [comment]
@kkirsche The fix does not work in your own example because the .navbar-text is not a child of .container-fluid. It's a child of .navbar-collapse. The example is ineligible because you're using .container instead of .container-fluid. 

I propose either using (without ">"): http://jsfiddle.net/uzgf29w4/
```css
.container-fluid .navbar-text.navbar-right:last-child{
    margin-right: 0px;
}
```

or http://jsfiddle.net/gbh5uu6m/

```css
.container-fluid > .navbar-text.navbar-right:last-child,
.container-fluid > .navbar-collapse > .navbar-text.navbar-right:last-child{
    margin-right: 0px;
}
```
