### ISSUE TITLE
Off Canvas suggestion for next versions

### ISSUE THREAD

**Issue by mewsoft** [twbs/bootstrap#15796]
I'd recommend adding off canvas as a ready built in feature in the next upgrade with simple interface like this one:

http://foundation.zurb.com/docs/components/offcanvas.html

Bootstrap is built basically to support mobile devices and off canvas is a must feature used almost in every application so it should be easy to integrate.

**Comment by kkirsche** [comment]
Look at http://getbootstrap.com/examples/offcanvas/ when it shrinks. This is essentially what is being asked for just at full size which I'm sure could be done

**Comment by kkirsche** [comment]
Should be:

```html
<button type="button" class="btn btn-primary" data-toggle="offcanvas">Toggle nav</button>
```

then for the actual menu:
```html
<div class="sidebar-offcanvas" id="sidebar">
          <div class="list-group">
            <a href="#" class="list-group-item active">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
          </div>
        </div>
```

And pull in off-canvas CSS:
```css
/*
 * Off Canvas
 * --------------------------------------------------
 */
@media screen and (max-width: 767px) {
  .row-offcanvas {
    position: relative;
    -webkit-transition: all .25s ease-out;
         -o-transition: all .25s ease-out;
            transition: all .25s ease-out;
  }

  .row-offcanvas-right {
    right: 0;
  }

  .row-offcanvas-left {
    left: 0;
  }

  .row-offcanvas-right
  .sidebar-offcanvas {
    right: -50%; /* 6 columns */
  }

  .row-offcanvas-left
  .sidebar-offcanvas {
    left: -50%; /* 6 columns */
  }

  .row-offcanvas-right.active {
    right: 50%; /* 6 columns */
  }

  .row-offcanvas-left.active {
    left: 50%; /* 6 columns */
  }

  .sidebar-offcanvas {
    position: absolute;
    top: 0;
    width: 50%; /* 6 columns */
  }
}
```

I agree it could be better documented and built in but nonetheless, that should be a starting point for you :+1:
