### ISSUE TITLE
modal-backdrop: missed "bottomL 0;" style!

### ISSUE THREAD

**Issue by DOrlov77** [twbs/bootstrap#15813]
in v3.3.1:

```css
.modal-backdrop {
  position: absolute;
  top: 0;
  right: 0;
  left: 0;
  background-color: #000;
}
```
