### ISSUE TITLE
Modal makes `position: fixed` elements relative to itself

### ISSUE THREAD

**Issue by cvillemure** [twbs/bootstrap#15856]
See a jsFiddle in Chrome 40: http://jsfiddle.net/3kgbG/595/

When you open the modal with the button, the red div is positionned relative to the modal.

We were able to fix this issue by overriding this chuck of code in modal.less

```less
.modal.in .modal-dialog {
 // Fixes a bug in chrome.
 // When some element inside the modal has position:fixed, the transforms have a weird effect of miscalculating the element's position
 -webkit-transform: none;
 -ms-transform: none; // IE9 only
 transform: none;
}
```
