### ISSUE TITLE
Improvements for the getting started "Narrow jumbotron" example layout

### ISSUE THREAD

**Issue by dragonprojects** [twbs/bootstrap#15911]
Hi,

I like it to use the getting started layouts and would like to give some improvements for the getting started "Narrow jumbotron" example layout.

- The footer should have the same margin to the content as the header, independ on there is a row marketing which has the margin or another content:
```css
footer {
    margin-top: 30px;
}
```
- The navigation should not be missplaced if the header h3 is empty without text:
```css
.header h3:empty {
    padding-bottom: 59px;
}
```

Hope both CSS are ok, I'm not that expert. But I think both would be nice to make this example layout more flexible.

Best regards, Sharaal
