### ISSUE TITLE
Inheriting Bootstrap classes doesn't inherit nested/psuedo selectors

### ISSUE THREAD

**Issue by theonlylawislove** [twbs/bootstrap#15963]
I have a input control framework that uses it's own classes. I would like to remove the vendor-provided theme and modify their classes to "extend/inherit" Bootstrap classes. That way, I don't have to change their rendered markup, and at the same time, I can use bootstrap styles without explicit styles, allowing future upgrades and bug fixes to Bootstrap to carry over to my vendor's theme.

The problem is that, when inheriting classes, the classes inherit have to be coded (in less) a certain way so that derived types will also contain all contextual/pseudo selectors as well.

Let me illustrate.

The following less...

```
.bootstrap-class {
    background:red;
}
.bootstrap-class input {
    background:blue;
}

.vendor-control {
    .bootstrap-class;
}
```
..will be rendered as...
```
.bootstrap-class {
  background: red;
}
.bootstrap-class input {
  background: blue;
}
.vendor-control {
  background: red;
}
```
See the problem? The nested ```input``` isn't styled for the derived ```.vendor-control``` class. 
However, if you write your less like this...

```
.bootstrap-class {
    background:red;
    input {
        background:blue;
    }
}

.vendor-control {
    .bootstrap-class;
}
```
..the rendered markup will be...
```
.bootstrap-class {
  background: red;
}
.bootstrap-class input {
  background: blue;
}
.vendor-control {
  background: red;
}
.vendor-control input {
  background: blue;
}
```
This would greatly simplify the extension of vendor controls. For example, I can imagine a single "Kendo UI" less file that simply sets up inheritance, and the entire framework would, from then on, be entirely Bootstrap. Currently, Kendo UI provides a theme that looks like Bootstrap out-of-the-box, but imagine a less file that makes Kendo UI look like any customized Bootstrap layout, instantly, complete with all the "has-feedback" classes and what-not.

With that said, would you guys entertain a PR with these changes? The changes would be similar to the following.

This...
```
.radio input[type="radio"],
.radio-inline input[type="radio"],
.checkbox input[type="checkbox"],
.checkbox-inline input[type="checkbox"] {
  position: absolute;
  margin-left: -20px;
  margin-top: 4px \9;
}
```
...would be changed to...
```
.radio,
.radio-inline {
    input[type="radio"] {
        position: absolute;
        margin-left: -20px;
        margin-top: 4px \9;
    }
}
.checkbox,
.checkbox-inline {
    input[type="checkbox"] {
        position: absolute;
        margin-left: -20px;
        margin-top: 4px \9;
    }
}
```

**Comment by kkirsche** [comment]
This seems to me as though there would be a lot of code duplication or this would require a lot of mixins. I don't see this being put into V3 as its ending its life in prep for V4 but an admin would have to say for sure.

**Comment by cvrebert** [comment]
Have you tried `@extend`-ing the Bootstrap classes instead?

**Comment by theonlylawislove** [comment]
@cvrebert, Yes. The issue is the same, but the rendered markup is a little different.

This...
```
.bootstrap-class {
    background:red;
}
.bootstrap-class input {
    background:blue;
}

.vendor-control {
    &:extend(.bootstrap-class);
}
```

..is rendered as...
```
.bootstrap-class,
.vendor-control {
  background: red;
}
.bootstrap-class input {
  background: blue;
}
```

**Comment by theonlylawislove** [comment]
In addition, I don't think @extend works 100% as we intend here. In the following example, using the class as a mixin works, and @extend doesn't.

```
.bootstrap-class {
    background:red;
    input {
        background:blue;
        &:hover {
            background:green;
        }
    }
}

.vendor-control {
    .bootstrap-class;
}
```
..transforms to...
```
.bootstrap-class {
  background: red;
}
.bootstrap-class input {
  background: blue;
}
.bootstrap-class input:hover {
  background: green;
}
.vendor-control {
  background: red;
}
.vendor-control input {
  background: blue;
}
.vendor-control input:hover {
  background: green;
}
```
... which is correct. However, this...

```
.bootstrap-class {
    background:red;
    input {
        background:blue;
        &:hover {
            background:green;
        }
    }
}

.vendor-control {
    &:extend(.bootstrap-class);
}
```
...renders to...
```
.bootstrap-class,
.vendor-control {
  background: red;
}
.bootstrap-class input {
  background: blue;
}
.bootstrap-class input:hover {
  background: green;
}
```
which is *NOT* correct.

I'm not seeing the purpose of @extend in general, compared to using the class as a mixin, but I don't know.

**Comment by DaSchTour** [comment]
Well I guess there is a general misconception about less. Maybe you should try this:

```less
.bootstrap-class {
  background:red;
    input {
      background:blue;
    }
}

.vendor-control {
    .bootstrap-class();
}
```

which will become this:

```css
.bootstrap-class {
  background: red;
}
.bootstrap-class input {
  background: blue;
}
.vendor-control {
  background: red;
}
.vendor-control input {
  background: blue;
}
```

**Comment by theonlylawislove** [comment]
Ya, I found that out.

The problem still remains though. Throughout Bootstrap, they use...

```
.class-name input {
   display: block;
}
```
...instead of...
```
.class-name {
   input {
      display: block;
   }
}
```

**Comment by DaSchTour** [comment]
Oh yes, I see.

So I guess instead of:
```less
.radio,
.checkbox {
  position: relative;
  display: block;
  margin-top: 10px;
  margin-bottom: 10px;

  label {
    min-height: @line-height-computed; // Ensure the input doesn't jump when there is no text
    padding-left: 20px;
    margin-bottom: 0;
    font-weight: normal;
    cursor: pointer;
  }
}
.radio input[type="radio"],
.radio-inline input[type="radio"],
.checkbox input[type="checkbox"],
.checkbox-inline input[type="checkbox"] {
  position: absolute;
  margin-left: -20px;
  margin-top: 4px \9;
}

.radio + .radio,
.checkbox + .checkbox {
  margin-top: -5px; // Move up sibling radios or checkboxes for tighter spacing
}

// Radios and checkboxes on same line
.radio-inline,
.checkbox-inline {
  position: relative;
  display: inline-block;
  padding-left: 20px;
  margin-bottom: 0;
  vertical-align: middle;
  font-weight: normal;
  cursor: pointer;
}
.radio-inline + .radio-inline,
.checkbox-inline + .checkbox-inline {
  margin-top: 0;
  margin-left: 10px; // space out consecutive inline controls
}
```

we should have something like this

```less
.radio,
.checkbox {
  position: relative;
  display: block;
  margin-top: 10px;
  margin-bottom: 10px;
 &-inline {
  display: inline-block;
  padding-left: 20px;
  margin-bottom: 0;
  vertical-align: middle;
  font-weight: normal;
  cursor: pointer;
 input[type="radio"], input[type="checkbox"] {
   position: absolute;
  margin-left: -20px;
  margin-top: 4px \9;
 }
+ .radio-inline, + .checkbox-inline {
  margin-top: 0;
  margin-left: 10px; // space out consecutive inline controls
 }
}
+ .radio, + .checkbox {
margin-top: -5px; // Move up sibling radios or checkboxes for tighter spacing
}

  label {
    min-height: @line-height-computed; // Ensure the input doesn't jump when there is no text
    padding-left: 20px;
    margin-bottom: 0;
    font-weight: normal;
    cursor: pointer;
  }
}
```

But I guess you see the dilemma, as this will not result in the expected CSS.
