### ISSUE TITLE
.container should be available as a mixin

### ISSUE THREAD

**Issue by jmotes** [twbs/bootstrap#15997]
First off, I do understand that CSS classes can be used as mixins. Please continue reading for a detailed explanation why I think the .container functionality should be available as a pure mixin.

Side note: this is somewhat related to #14276, but I think it's different enough or at least hopefully explained well enough to warrant a separate issue. #14276 doesn't state the problem clearly and mainly concentrates on a possible solution (which isn't backwards compatible, so I don't recommend it).

I'm using the Bootstrap mixins/classes with LESS for more semantic markup; using mixins instead of adding the classes to the HTML. However, to use .container() in my less files, I have to include the whole less/grid.less file that includes the other grid classes. This results in about <strong>30KB of CSS classes being dumped into my compiled CSS that I don't need</strong> since I won't be adding them to my HTML tags.

I can work around this by copying just the .container code to my own file and changing it to just be a mixin, but seems to me that this should be available by default since Bootstrap 3 already includes so much to support semantic markup.

I think this could be implemented just by moving the code for the .container class to less/mixins/grid.less (adding parentheses to make it a pure mixin of course), re-naming it, and then calling it from less/grid.less for the .container class.

**Comment by jmotes** [comment]
@cvrebert, do you have any thoughts on this...Would it be helpful if I did a pull request showing my proposed solution?

**Comment by dffp** [comment]
Sounds square

**Comment by mdo** [comment]
To clarify, you want the following code available as a mixin, right?

```less

.container {
  .container-fixed();

  @media (min-width: @screen-sm-min) {
    width: @container-sm;
  }
  @media (min-width: @screen-md-min) {
    width: @container-md;
  }
  @media (min-width: @screen-lg-min) {
    width: @container-lg;
  }
}
```

If so, I don't think we'll go that route in v3. It's an extra abstraction that will add complications too close to the end of life for this version. I'm unsure we'd even do this in v4, but I do understand the urge to have more semantic markup. Lots of changes will be coming for that in the next major release.
