### ISSUE TITLE
Missing Breadcrumb separator: "invalid property value"

### ISSUE THREAD

**Issue by klausbadelt** [twbs/bootstrap#16009]
In at least Chrome, the default breadcrumb separator throws an "invalid property value" error on the li.before content: tag, as it's missing surrounding quotes. Maybe this happened after adding the unicode space, making the content more than a single character? In any case, quotes around the value fix this:

`_breadcrumbs.scss`
```css
    + li:before {
      content: "#{$breadcrumb-separator}\00a0"; // Unicode space added since inline-block means non-collapsing white-space
      padding: 0 5px;
      color: $breadcrumb-color;
    }
```
