### ISSUE TITLE
Sidebar of Dashboard example is hidden on mobile

### ISSUE THREAD

**Issue by marius00** [twbs/bootstrap#16027]
URL: http://getbootstrap.com/examples/dashboard/
Client: Safari on iPhone 5S, iOS 7.1.2 (can't seem to extract the safari version number, but should only be one for 7.1.2)

The sidebar is not visible on mobile.

Unsure if its intended or not, but for "mobile first" I would expect said content to be available somehow.

**Comment by fchiumeo** [comment]
see the dashboard.css file
```css
/* Hide for mobile, show later */
.sidebar {
  display: none;
}
```
