### ISSUE TITLE
Add variables for <legend> styles

### ISSUE THREAD

**Issue by julzmon** [twbs/bootstrap#16051]
For accessibility reasons we wrap our radio and checkboxes with a `<fieldset>` and use `<legend class="control-label">` to make it look like a standard label. I would like to suggest removing and creating vars for hardcoded font-size, bottom-margin and border-bottom.

**Comment by mdo** [comment]
What exactly are these accessibility reasons for that particular example?

**Comment by patrickhlauke** [comment]
i'll hazard a guess that @julzmon has something like
```
<fieldset>
<legend>Do you like cheese?</legend>
<label><input type="radio" ...> Yes<label>
<label><input type="radio" ...> No</label>
</fieldset>
```
possibly styled to be horizontal, on a single line...and wants to have consistent styling where the ``<legend>`` text looks the same as the Yes/No ``<label>``s

**Comment by mdo** [comment]
That's not an accessibility concern though right? Just a markup preference.

**Comment by patrickhlauke** [comment]
The markup like that is necessary for accessibility, in situations like that (groups of radio buttons). The fact that OP would like a simple way to make the ``<legend>`` to be easily stylable to appear like ``<label>`` without having to make their own custom styles is a feature request (which would make sense to me).

**Comment by mdo** [comment]
Yeah, I hear that. Just wanted to better understand the request.

Since we're not doing new features though, and I don't really believe adding variables would help much here, I'm inclined to punt as a won't fix. Thoughts?

**Comment by patrickhlauke** [comment]
Not being too up on LESS, I'm not quite sure how involved the request would be. If it's only a case of adding the same variables to ``legend`` styling that are applied to ``label``, it may be a low-hanging fruit?

**Comment by mdo** [comment]
There are many `<legend>` styles we apply:

```less
legend {
  display: block;
  width: 100%;
  padding: 0;
  margin-bottom: @line-height-computed;
  font-size: (@font-size-base * 1.5);
  line-height: inherit;
  color: @legend-color;
  border: 0;
  border-bottom: 1px solid @legend-border-color;
}
```

Adding more variables doesn't seem like it'd make much of a difference. Come v4 though we can perhaps remove some of these resets.
