### ISSUE TITLE
namespacing bootstrap undesirably extends clearfix with parent tag

### ISSUE THREAD

**Issue by craigmichaelmartin** [twbs/bootstrap#16077]
Because of the (understandable) reason `&:extend` was employed for `clearfix` (cf 0016c17f9307bc71fc96d8d4680a9c861f137cae), namespacing bootstrap does not work correctly.

Because of the use of extends, with the namespace of bootstrap to 'twitter-bootstrap' the css compiles with the redundant twitter-bootstrap class for all elements extending clearfix.
Less:
```less
.twitter-bootstrap {
    @import "../components/bootstrap/less/bootstrap.less"
}
```
CSS:
```css
.twitter-bootstrap .clearfix:before,
.twitter-bootstrap .clearfix:after,
.twitter-bootstrap .twitter-bootstrap .container-limited:before,
.twitter-bootstrap .twitter-bootstrap .container-limited:after,
.twitter-bootstrap .twitter-bootstrap .container:before,
.twitter-bootstrap .twitter-bootstrap .container:after,
.twitter-bootstrap .twitter-bootstrap .container-fluid:before,
.twitter-bootstrap .twitter-bootstrap .container-fluid:after,
.twitter-bootstrap .twitter-bootstrap .row:before,
.twitter-bootstrap .twitter-bootstrap .row:after,
.twitter-bootstrap .twitter-bootstrap .form-horizontal .form-group:before,
.twitter-bootstrap .twitter-bootstrap .form-horizontal .form-group:after,
.twitter-bootstrap .twitter-bootstrap .btn-toolbar:before,
.twitter-bootstrap .twitter-bootstrap .btn-toolbar:after,
.twitter-bootstrap .twitter-bootstrap .btn-group-vertical > .btn-group:before,
.twitter-bootstrap .twitter-bootstrap .btn-group-vertical > .btn-group:after,
.twitter-bootstrap .twitter-bootstrap .nav:before,
.twitter-bootstrap .twitter-bootstrap .nav:after,
.twitter-bootstrap .twitter-bootstrap .navbar:before,
.twitter-bootstrap .twitter-bootstrap .navbar:after,
.twitter-bootstrap .twitter-bootstrap .navbar-header:before,
.twitter-bootstrap .twitter-bootstrap .navbar-header:after,
.twitter-bootstrap .twitter-bootstrap .navbar-collapse:before,
.twitter-bootstrap .twitter-bootstrap .navbar-collapse:after,
.twitter-bootstrap .twitter-bootstrap .pager:before,
.twitter-bootstrap .twitter-bootstrap .pager:after,
.twitter-bootstrap .twitter-bootstrap .panel-body:before,
.twitter-bootstrap .twitter-bootstrap .panel-body:after,
.twitter-bootstrap .twitter-bootstrap .modal-footer:before,
.twitter-bootstrap .twitter-bootstrap .modal-footer:after,
.twitter-bootstrap .twitter-bootstrap .dashboard .alerts-main .sections > li ul li:before,
.twitter-bootstrap .twitter-bootstrap .dashboard .alerts-main .sections > li ul li:after,
.twitter-bootstrap .twitter-bootstrap .dashboard .alerts-main .sections > li ul li:before,
.twitter-bootstrap .twitter-bootstrap .dashboard .alerts-main .sections > li ul li:after {
    content: " ";
    display: table;
}
.twitter-bootstrap .clearfix:after,
.twitter-bootstrap .twitter-bootstrap .container-limited:after,
.twitter-bootstrap .twitter-bootstrap .container:after,
.twitter-bootstrap .twitter-bootstrap .container-fluid:after,
.twitter-bootstrap .twitter-bootstrap .row:after,
.twitter-bootstrap .twitter-bootstrap .form-horizontal .form-group:after,
.twitter-bootstrap .twitter-bootstrap .btn-toolbar:after,
.twitter-bootstrap .twitter-bootstrap .btn-group-vertical > .btn-group:after,
.twitter-bootstrap .twitter-bootstrap .nav:after,
.twitter-bootstrap .twitter-bootstrap .navbar:after,
.twitter-bootstrap .twitter-bootstrap .navbar-header:after,
.twitter-bootstrap .twitter-bootstrap .navbar-collapse:after,
.twitter-bootstrap .twitter-bootstrap .pager:after,
.twitter-bootstrap .twitter-bootstrap .panel-body:after,
.twitter-bootstrap .twitter-bootstrap .modal-footer:after,
.twitter-bootstrap .twitter-bootstrap .dashboard .alerts-main .sections > li ul li:after,
.twitter-bootstrap .twitter-bootstrap .dashboard .alerts-main .sections > li ul li:after {
    clear: both;
}
```

While this arguably is not an issue with bootstrap, per se, it seems to me a perhaps heavy handed design choice that affects its integration with custom less. Am I mistaken on this?

(I was able to continue using bootstrap by extending clearfix afterward (below), with the downside of still having the extra undesirable albeit harmless css.)
```less
.twitter-bootstrap {
    @import "../components/bootstrap/less/bootstrap.less"
}
.clearfix {
     &:extend(.twitter-bootstrap .clearfix all);
}
```
