### ISSUE TITLE
<table class="visible-*"> is display:block when shown

### ISSUE THREAD

**Issue by divinespear** [twbs/bootstrap#16166]
I cannot say english well, so I'll tell with generated css directly.

affected: 3.3.4 and all below.
```css
...
  .visible-xs {
    display: block !important;
  }
  table.visible-xs {
    display: table;
  }
  tr.visible-xs {
    display: table-row !important;
  }
  th.visible-xs,
  td.visible-xs {
    display: table-cell !important;
  }
...
```

As see above, all tables with .visible-* will display as block instead table, and every tr doesn't fill whole width.
