### ISSUE TITLE
Chrome userAgent styles for input[type="date"] etc change display style to inline-flex

### ISSUE THREAD

**Issue by AshCoolman** [twbs/bootstrap#16338]
I'm not familiar with this repository, and I can't ascertain the bootstrap attitude toward _userAgent styles_. Regardless, Chrome OSX 42.0.2311.90 changes the ```display``` style of html5 time elements and assumes ```monospace```. Possibly no action should be taken, but maybe bootstrap should treat this input type differently? 

```css
input[type="date" i], input[type="datetime-local" i], input[type="month" i], input[type="time" i], input[type="week" i] {
  align-items: center;
  display: -webkit-inline-flex; /* Dangerous? */
  font-family: monospace;
  overflow: hidden;
  padding: 0px;
  -webkit-padding-start: 1px;
}
```
