### ISSUE TITLE
Carousel control is vertically off center for small screens

### ISSUE THREAD

**Issue by rlindner81** [twbs/bootstrap#16371]
Try any carousel control and reduce the screen width below 768px and you will see the glyphicon-chevron left and right jump below the vertical center.

Fortunately the fix is easy. In less/carousel.less after line 132 add the fix line
```css
  // Toggles
  .icon-prev,
  .icon-next,
  .glyphicon-chevron-left,
  .glyphicon-chevron-right {
    position: absolute;
    top: 50%;
    margin-top: -10px; /* fix */
    z-index: 5;
    display: inline-block;
  }
```

As pointed out by @peterblazejewicz, the correct margin-top styling already exists for the .icon-* classes. So this line, could be removed after the change above. In less/carousel.less line 150 
```css
  .icon-prev,
  .icon-next {
    width:  20px;
    height: 20px;
    /* margin-top: -10px; remove */
    line-height: 1;
    font-family: serif;
  }
```
