### ISSUE TITLE
Media print query should force none transitions

### ISSUE THREAD

**Issue by ramyhhh** [twbs/bootstrap#16496]
Hello ... a lot of websites built over bootstrap uses the css3 transitions to create animations  unaware to the fact that a browser such as chrome (has print preview) could render the print page in a time before elements are able to hide completely thus causing weird shapes to be printed.
So my suggestion is to add transition:none to turn off all  transition inside print query
```css
@media print {
* {
        -webkit-transition:none!important;
        -moz-transition:none!important;
        -ms-transition:none!important;
        -o-transition:none!important;
        transition:none!important
    }
}
```
