### ISSUE TITLE
Popover breaks modal-footer button spacing

### ISSUE THREAD

**Issue by acshef** [twbs/bootstrap#16515]
Fiddle is here: http://jsfiddle.net/mt8pwL4L/

The popover (which gets placed in the DOM between the two `.btn` elements) breaks the following CSS:
```css
.modal-footer .btn+.btn {
  margin-bottom: 0;
  margin-left: 5px;
}
```
![image](https://cloud.githubusercontent.com/assets/9013284/7733030/9c44078a-fee9-11e4-9fe4-5d85df67d465.png)

Technically, the selector ~~`.modal-footer .btn+.popover+.btn`~~ `.modal-footer .popover+.btn` will catch this, and I'm sure this would also apply to `tooltips`
