### ISSUE TITLE
Responsive .h1, .h2, .h3, .h4, .h5, .h6

### ISSUE THREAD

**Issue by maimairel** [twbs/bootstrap#16523]
Hi, 

I don't know if someone has ever requested this before, but adding responsive headings like I did below would be very useful :)

```css
@media (min-width: @screen-xs-min) {

	.h1-xs,
	.h2-xs,
	.h3-xs {
		margin-top: @line-height-computed;
		margin-bottom: (@line-height-computed / 2);

		small,
		.small {
			font-size: 65%;
		}
	}

	.h4-xs,
	.h5-xs,
	.h6-xs {
		margin-top: (@line-height-computed / 2);
		margin-bottom: (@line-height-computed / 2);

		small,
		.small {
			font-size: 75%;
		}
	}

	.h1-xs { font-size: @font-size-h1; }
	.h2-xs { font-size: @font-size-h2; }
	.h3-xs { font-size: @font-size-h3; }
	.h4-xs { font-size: @font-size-h4; }
	.h5-xs { font-size: @font-size-h5; }
	.h6-xs { font-size: @font-size-h6; }
}

@media (min-width: @screen-sm-min) {

	.h1-sm,
	.h2-sm,
	.h3-sm {
		margin-top: @line-height-computed;
		margin-bottom: (@line-height-computed / 2);

		small,
		.small {
			font-size: 65%;
		}
	}

	.h4-sm,
	.h5-sm,
	.h6-sm {
		margin-top: (@line-height-computed / 2);
		margin-bottom: (@line-height-computed / 2);

		small,
		.small {
			font-size: 75%;
		}
	}

	.h1-sm { font-size: @font-size-h1; }
	.h2-sm { font-size: @font-size-h2; }
	.h3-sm { font-size: @font-size-h3; }
	.h4-sm { font-size: @font-size-h4; }
	.h5-sm { font-size: @font-size-h5; }
	.h6-sm { font-size: @font-size-h6; }
}

@media (min-width: @screen-md-min) {

	.h1-md,
	.h2-md,
	.h3-md {
		margin-top: @line-height-computed;
		margin-bottom: (@line-height-computed / 2);

		small,
		.small {
			font-size: 65%;
		}
	}

	.h4-md,
	.h5-md,
	.h6-md {
		margin-top: (@line-height-computed / 2);
		margin-bottom: (@line-height-computed / 2);

		small,
		.small {
			font-size: 75%;
		}
	}

	.h1-md { font-size: @font-size-h1; }
	.h2-md { font-size: @font-size-h2; }
	.h3-md { font-size: @font-size-h3; }
	.h4-md { font-size: @font-size-h4; }
	.h5-md { font-size: @font-size-h5; }
	.h6-md { font-size: @font-size-h6; }
}

@media (min-width: @screen-lg-min) {

	.h1-lg,
	.h2-lg,
	.h3-lg {
		margin-top: @line-height-computed;
		margin-bottom: (@line-height-computed / 2);

		small,
		.small {
			font-size: 65%;
		}
	}

	.h4-lg,
	.h5-lg,
	.h6-lg {
		margin-top: (@line-height-computed / 2);
		margin-bottom: (@line-height-computed / 2);

		small,
		.small {
			font-size: 75%;
		}
	}

	.h1-lg { font-size: @font-size-h1; }
	.h2-lg { font-size: @font-size-h2; }
	.h3-lg { font-size: @font-size-h3; }
	.h4-lg { font-size: @font-size-h4; }
	.h5-lg { font-size: @font-size-h5; }
	.h6-lg { font-size: @font-size-h6; }
}
```

Thanks!
