### ISSUE TITLE
add a variable for \00a0 unicode character for breadcrumb

### ISSUE THREAD

**Issue by gniquil** [twbs/bootstrap#16576]
Currently, in the breadcrumb file:

```less
    + li:before {
      content: "@{breadcrumb-separator}\00a0"; // Unicode space added since inline-block means non-collapsing white-space
      padding: 0 5px;
      color: @breadcrumb-color;
    }
```

Once it's transpiled to sass, then processed through a Sass engine, the slash in "\00a0" gets doubled to "\\00a0" causing the breadcrumb to display incorrectly. We can easily factor this unicode out into a variable, which Sass will then properly escape it. 

I will submit a PR for it. For reference, here are 2 issues downstream:

https://github.com/twbs/bootstrap-sass/pull/911

https://github.com/lifegadget/ember-cli-bootstrap-sassy/issues/22

**Comment by mdo** [comment]
Can it not be escaped inline?

**Comment by gniquil** [comment]
According to this link:

http://stackoverflow.com/questions/21608762/sass-variable-interpolation-with-backslash-in-output

Sass has issue with it, hence the solution there is move the unicode character into a variable. :(

**Comment by kkirsche** [comment]
I haven't tested it myself @mdo but
http://stackoverflow.com/questions/21641833/how-to-use-a-single-backslash-in-string-interpolation-in-sass says

In Sass v3.3 you can get around this problem by using the new str-slice() function and doing something like this:

```css
@mixin make-icon ($name, $code) {
  .#{$name}::before {
    content: str-slice("\x",1,1) + $code;
  }
}

@include make-icon('foo', 4556);
```

which should output:

```css
.foo::before {
  content: "\4556";
}
```

**Comment by gniquil** [comment]
You know what, I just reran boostrap-sass again and it seems the problem had gone away. Really not sure why, but I will close it for now. Sorry for the smoke :(.

**Comment by xskif** [comment]
The problem still there. I have double slashes in output.

**Comment by cvrebert** [comment]
@xskif Please open an issue in https://github.com/twbs/bootstrap-sass/issues with more details.

**Comment by orrd** [comment]
@cvrebert Someone from bootstrap-sass already [referred this issue](https://github.com/twbs/bootstrap-sass/pull/911 from there) "upstream" back to the main bootstrap repository here.    It seems bootstrap and bootstrap-sass are both saying it's the problem of the other repository. 

I'm having the same issue and am just hoping someone knows how to fix it.

**Comment by kkirsche** [comment]
Broken link @orrd fixed link:
https://github.com/twbs/bootstrap-sass/pull/911

**Comment by cvrebert** [comment]
I've asked @orrd to open a new (detailed) bug report in bootstrap-sass.

**Comment by mrliptontea** [comment]
There is very simple workaround, just replace interpolation with concatenation:

```css
    + li:before {
      content: $breadcrumb-separator + "\00a0";
      padding: 0 5px;
      color: $breadcrumb-color;
    }
```

I think this could be noted for converter.
