### ISSUE TITLE
Wrapping elements auto-clear

### ISSUE THREAD

**Issue by schungx** [twbs/bootstrap#16618]
I've read some on-line discussions about automatically clearing items of lists that are of variable lengths, with different number of columns for different viewport sizes.

Currently you have to do the math yourself, and put in a whole bunch of `visible-**` classes to `clearfix` div's at the right places.

Can't we do something simple to automatically clear these list items, provided that list items are all that are under the `ul` or `ol` tags?  Something like:

```css
    .wrapclear {
    	display: none;
    	clear: both;
    }

    .row.wrap-xs-1 .wrapclear,
    .row.wrap-xs-2 .wrapclear:nth-child(4n),
    .row.wrap-xs-3 .wrapclear:nth-child(6n),
    .row.wrap-xs-4 .wrapclear:nth-child(8n),
    .row.wrap-xs-5 .wrapclear:nth-child(10n),
    .row.wrap-xs-6 .wrapclear:nth-child(12n) {
    	display: block;
    }

    @media (min-width: 480px) {
    	.row.wrap-ms-2 .wrapclear:nth-child(n),
    	.row.wrap-ms-3 .wrapclear:nth-child(n),
    	.row.wrap-ms-4 .wrapclear:nth-child(n),
    	.row.wrap-ms-5 .wrapclear:nth-child(n),
    	.row.wrap-ms-6 .wrapclear:nth-child(n) {
    		display: none;
    	}

    	.row.wrap-ms-1 .wrapclear,
    	.row.wrap-ms-2 .wrapclear:nth-child(4n),
    	.row.wrap-ms-3 .wrapclear:nth-child(6n),
    	.row.wrap-ms-4 .wrapclear:nth-child(8n),
    	.row.wrap-ms-5 .wrapclear:nth-child(10n),
    	.row.wrap-ms-6 .wrapclear:nth-child(12n) {
    		display: block;
	}
    }

    @media (min-width: 768px) {
    	.row.wrap-sm-2 .wrapclear:nth-child(n),
    	.row.wrap-sm-3 .wrapclear:nth-child(n),
    	.row.wrap-sm-4 .wrapclear:nth-child(n),
    	.row.wrap-sm-5 .wrapclear:nth-child(n),
    	.row.wrap-sm-6 .wrapclear:nth-child(n) {
    		display: none;
    	}

    	.row.wrap-sm-1 .wrapclear,
    	.row.wrap-sm-2 .wrapclear:nth-child(4n),
    	.row.wrap-sm-3 .wrapclear:nth-child(6n),
    	.row.wrap-sm-4 .wrapclear:nth-child(8n),
    	.row.wrap-sm-5 .wrapclear:nth-child(10n),
    	.row.wrap-sm-6 .wrapclear:nth-child(12n) {
    		display: block;
    	}
    }

    @media (min-width: 992px) {
    	.row.wrap-md-2 .wrapclear:nth-child(n),
    	.row.wrap-md-3 .wrapclear:nth-child(n),
    	.row.wrap-md-4 .wrapclear:nth-child(n),
     	.row.wrap-md-5 .wrapclear:nth-child(n),
    	.row.wrap-md-6 .wrapclear:nth-child(n) {
		display: none;
    	}

    	.row.wrap-md-1 .wrapclear,
    	.row.wrap-md-2 .wrapclear:nth-child(4n),
    	.row.wrap-md-3 .wrapclear:nth-child(6n),
    	.row.wrap-md-4 .wrapclear:nth-child(8n),
    	.row.wrap-md-5 .wrapclear:nth-child(10n),
    	.row.wrap-md-6 .wrapclear:nth-child(12n) {
    		display: block;
    	}
    }

    @media (min-width: 1200px) {
    	.row.wrap-lg-2 .wrapclear:nth-child(n),
    	.row.wrap-lg-3 .wrapclear:nth-child(n),
    	.row.wrap-lg-4 .wrapclear:nth-child(n),
    	.row.wrap-lg-5 .wrapclear:nth-child(n),
    	.row.wrap-lg-6 .wrapclear:nth-child(n) {
    		display: none;
    	}

    	.row.wrap-lg-1 .wrapclear,
    	.row.wrap-lg-2 .wrapclear:nth-child(4n),
    	.row.wrap-lg-3 .wrapclear:nth-child(6n),
    	.row.wrap-lg-4 .wrapclear:nth-child(8n),
    	.row.wrap-lg-5 .wrapclear:nth-child(10n),
    	.row.wrap-lg-6 .wrapclear:nth-child(12n) {
    		display: block;
    	}
    }
```
This way, we can do:
```html
    <ul class="row wrap-xs-1 wrap-sm-2 wrap-md-3">
        <li class="col-xs-12 col-sm-6 col-md-4"> ... </li>
        <div class="wrapclear"></div>
        <li class="col-xs-12 col-sm-6 col-md-4"> ... </li>
        <div class="wrapclear"></div>
        <li class="col-xs-12 col-sm-6 col-md-4"> ... </li>
        <div class="wrapclear"></div>
                        :
    </ul>
```
The math is then done automatically.  In this exampnle, `wrap-sm-2` means "wrap to two columns on small devices".

I was hoping to find a pure CSS way to automatically insert the `col-**-**` classes based on the number of columns to wrap, but couldn't do it without duplicating a lot of bootstrap or without scripting.  However, if changes are made to include this style inside the main bootstrap blocks, then it will be just a simple matter of adding more selectors to the correct blocks.
