### ISSUE TITLE
Customizer does not update border-color for button hover and panels.

### ISSUE THREAD

**Issue by zlepper** [twbs/bootstrap#16635]
When making a theme with the bootstrap customizer the border-color does not get overridden in the :hover state by the theme, so it will remain blue. 

To reproduce:
1. Go to customize
2. Change brand-primary to some other color like green
3. 
![capture](https://cloud.githubusercontent.com/assets/1499810/8148125/087cbf4e-128d-11e5-831f-ee1725fd8838.PNG)
As you can see the border-color is still blue, while it should be green. 

This happens on buttons in the :hover move and on panels in generally.

**Comment by kkirsche** [comment]
I wasn't able to duplicate this. My entering `#FF0000` as brand primary without any other changes correctly resulted in the following red `.btn-primary`:

```css
.btn-primary {
  color: #ffffff;
  background-color: #de0000;
  border-color: #c40000;
}
.btn-primary:hover,
.btn-primary:focus,
.btn-primary.focus,
.btn-primary:active,
.btn-primary.active,
.open > .dropdown-toggle.btn-primary {
  color: #ffffff;
  background-color: #ab0000;
  border-color: #870000;
}
```
