### ISSUE TITLE
color: transparent;

### ISSUE THREAD

**Issue by gubaidulin** [twbs/bootstrap#16678]
My LESS says:
'Expected a color. Got: transparent'

It would be better to change like this:
```LESS
.hide-text() {
  font: ~"0/0" a;
  /* color: transparent; */
  color: rgba(0,0,0,0);
  text-shadow: none;
  background-color: transparent;
  border: 0;
}
```
