### ISSUE TITLE
Improve carousel CSS

### ISSUE THREAD

**Issue by jlawton2** [twbs/bootstrap#16711]
First, awesome job guys! I love using Bootstrap, and appreciate all of the hard-work-made easy!

That said, at first glance I feel like carousel has been put together without much additional development. Some of this is theme changes, but in my opinion, this would greatly improve ```.carousel```. Changes/improvements are as follows:
* ```.carousel-caption```
  * Added gradient for improved readability in front of images.
* ```.carousel-control```
  * Removed gradient to match better to prior change.
  * Added gradient to ```.carousel-control span ``` controllers to match better to prior change.
* ```img```
  * Centered.
  * Forced ```max-height``` (smaller on ```xs```).
  * Defaults ```img``` to ```overflow: hidden```.
  *  Fit ```img``` to fit with optional class ```scale```.

I've appended the following changes to the native Bootstrap CSS.
```css
		.carousel-control {
			min-width: 10px;
			max-width: 100px;
		}
		.carousel-control, .carousel-control.left, .carousel-control.right {
			background-image: none;
		}
		.carousel-control span {
			width: auto !important;
			height: auto !important;
			border-radius: 50%;
			padding: 5px;
			background-image: -webkit-radial-gradient(circle at center, rgba(0,0,0,.0001) 0,rgba(0,0,0,.5) 100%);
			background-image: -o-radial-gradient(circle at center, rgba(0,0,0,.0001) 0,rgba(0,0,0,.5) 100%);
			background-image: radial-gradient(circle at center, rgba(0,0,0,.0001) 0,rgba(0,0,0,.5) 100%);100%);
		}
		.carousel-inner > .item > img {
			overflow: hidden;
		}
		.carousel-inner > .item, .carousel-inner > .item > img.scale {
			max-height: 200px;
		}
		@media screen and (min-width: 768px) {
			.carousel-inner > .item, .carousel-inner > .item > img.scale {
				max-height: 400px;
			}
		}
		.carousel-caption {
			left: 0 !important;
			right: 0 !important;
			background-image: -webkit-linear-gradient(top,rgba(0,0,0,0) 0,rgba(0,0,0,.5) 100%);
			background-image: -o-linear-gradient(top,rgba(0,0,0,0) 0,rgba(0,0,0,.5) 100%);
			background-image: -webkit-gradient(linear,left top,left bottom,from(rgba(0,0,0,0)),to(rgba(0,0,0,.5)));
			background-image: linear-gradient(to bottom,rgba(0,0,0,0) 0,rgba(0,0,0,.5) 40%);
			bottom: 0px;
			padding: 0 40px 50px 40px;
			width: 100%;
		}
```

Try it out and let me know what you think. Thanks!
