### ISSUE TITLE
add docs about scale .img-responsive svg for IE 11

### ISSUE THREAD

**Issue by evilebottnawi** [twbs/bootstrap#16782]
```css
@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
    width: 100%;
}
```
Before hack:
![ie11 - win8 1](https://cloud.githubusercontent.com/assets/4567934/8568590/a888ebf0-2577-11e5-8508-588b95767d90.jpeg)
After hack:
![ie11 - win8 1 - 2](https://cloud.githubusercontent.com/assets/4567934/8568605/d38e1956-2577-11e5-989a-60bd6b59abb6.jpeg)

**Comment by cvrebert** [comment]
Please post a [JS Bin](http://jsbin.com) demonstrating the problem and proposed fix.
And feel free to [open a pull request](https://github.com/twbs/bootstrap/pulls) for your proposed fix.

**Comment by evilebottnawi** [comment]
@cvrebert 
IE version: 11.0.9600.17842
Update Version: 11.0.20 (KB3058515)
Without hack: http://output.jsbin.com/vurutizura/
With hack: http://jsbin.com/gulorudeyu/

**Comment by Johann-S** [comment]
Confirmed on : 
Win7 IE version: 11.0.9600.17843 
Update Version: 11.0.20 (KB3058515)

**Comment by cvrebert** [comment]
X-Ref: #10073, #13996

**Comment by cvrebert** [comment]
@evilebottnawi That hack isn't feasible. It will cause non-SVG images to be stretched beyond their natural dimensions, which is undesirable; see #13996.

**Comment by evilebottnawi** [comment]
@cvrebert hwo about use hack for class .img-responsive with filename end on .svg?

**Comment by evilebottnawi** [comment]
@cvrebert hack with
```css 
.img-responsive {
    width: 100% \9;
}
```
Not working in ie11 and no docs about this bugs

**Comment by cvrebert** [comment]
> how about use hack for class .img-responsive with filename end on .svg?

We ruled that out in the previous issues.

**Comment by evilebottnawi** [comment]
@cvrebert 
```less
.img-responsive {
    width: 100% \9;

    @media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
        &[src$="svg"],
        .thumbnail > img[src$="svg"],
        .thumbnail a > img[src$="svg"],
        .carousel-inner > .item > img[src$="svg"],
        .carousel-inner > .item > a > img[src$="svg"] {
            width: 100%;
        }
    }
}
```
How about this construction, working in IE8-IE10, and IE11, http://dev.l-c-n.com/CSS3-selectors/browser-support.php, may be working in IE7, need testing
