### ISSUE TITLE
Rename center-block to block-center.

### ISSUE THREAD

**Issue by nagy-tamas** [twbs/bootstrap#16792]
As I see, everywhere in the code the convention for naming classes is to have the element's name in the first place, then a dash, and finally the modifier. For example: text-center, img-responsive, btn-lg.
The center-block is an exception. It would be nice to have the same convention here as above, eg. block-center.

**Comment by kkirsche** [comment]
While this makes sense, I doubt it's something that will be done in V3 due to the semantic change of this. This would be a major change, in my opinion, as it would break the API.

Instead of renaming, I'd be interested in hearing if aliasing the class would be something the core team would be open to. E.g.:

```css
.center-block {
    display: block;
    margin-left: auto;
     margin-right: auto;
}
.block-center {
    .center-block;
}
```
