### ISSUE TITLE
Incorrect checkbox margin

### ISSUE THREAD

**Issue by nhahv** [twbs/bootstrap#16829]
I found this bug from version > 3.1.1.
Please fix this
File: bootstrap.css
```css
.checkbox input[type=checkbox], .checkbox-inline input[type=checkbox],
.radio input[type=radio], .radio-inline input[type=radio] {
    position: absolute;
    margin-top: 4px\9;
    margin-left: -20px
}
```
File: forms.less
```less
.radio input[type="radio"],
.radio-inline input[type="radio"],
.checkbox input[type="checkbox"],
.checkbox-inline input[type="checkbox"] {
  position: absolute;
  margin-left: -20px;
  margin-top: 4px \9;
}
```

![screen shot 2015-07-15 at 11 26 44 pm](https://cloud.githubusercontent.com/assets/4364929/8703721/04dfa9b2-2b49-11e5-8a99-215eab43932f.png)
