### ISSUE TITLE
$*-bg properties should use `background` instead of `background-color` for greater flexibility

### ISSUE THREAD

**Issue by jacobp100** [twbs/bootstrap#17044]
Is there a technical reason all these properties set these to the `background-color` rather than the `background`? With the latter, you can set the colour *and* gradients and images.

**Comment by cvrebert** [comment]
In many cases, these variables end up being used in calculations for deriving related colors, which won't work for non-color values. For example, the button mixins calculate the button's "active" state's color based on the button's normal background color: https://github.com/twbs/bootstrap/blob/c9a5f82357c704908e80615943864e6e3abc37b9/scss/mixins/_buttons.scss#L13

**Comment by jacobp100** [comment]
I see. I did similar stuff recently, and ended up making a function that gets the base colour. Provided you give a colour in your background definition, it will find it. Snippet below.

```scss
@function base-colour($color) {
  $type: type-of($color);
 
  @if $type == 'list' {
    @each $i in $color {
      $i-type: type-of($i);
     
      @if $i-type == 'list' {
        @return base-colour($i);
      } @else if $i-type == 'color' {
        @return $i;
      }
    }
  } @else if $type == 'color' {
    @return $color;
  }

  @error 'Failed to find base colour';
}

.blue {
  $test: url(test), linear-gradient(to bottom, red, blue) brown;
  color: base-colour($test);
}
```
