### ISSUE TITLE
progress only partially supported in Microsoft Edge in v4

### ISSUE THREAD

**Issue by impulz** [twbs/bootstrap#17073]
Microsoft Edge (as well as IE10) does not support the background-color/background property on progress[value], causing Context Alternatives and Striped not to work.
Context Alternatives could be implemented using color like this (as per https://css-tricks.com/html5-progress-element/)
```css
.progress-success[value] {
  color: #5cb85c;
}
```
