### ISSUE TITLE
Switch to enable responsive typography 

### ISSUE THREAD

**Issue by jacobmohl** [twbs/bootstrap#17095]
Either I am missing something in the documentation or it would be nice to add a switch to variables to enable usage of responsive typography. 

For now I suppose the developer should implement by him self and use the prepared size variables!

**Comment by cvrebert** [comment]
We already use `rem` units in v4. Isn't the rest just a matter of
```css
@media (min-width: AAApx) {
  html { font-size: BBBpx }
}
@media (min-width: CCCpx) {
  html { font-size: DDDpx }
}
```
?
Or are you suggesting the addition of such media queries, or...?

**Comment by jacobmohl** [comment]
I have implemented it this way, because the different base-sizes is already available in variables. So it seems easy to add a switch to improve easie of use.

```scss
html {
    font-size: $font-size-xs;
}
    
@include media-breakpoint-up(sm) {
    html {
        font-size: $font-size-sm;
    }
}

@include media-breakpoint-up(md) {
    html {
        font-size: $font-size-base;
    }
}

@include media-breakpoint-up(lg) {
    html {
        font-size: $font-size-lg;
    }    
}
```
