### ISSUE TITLE
Remove JSCS in favor of more complete ESLint

### ISSUE THREAD

**Issue by baer** [twbs/bootstrap#17102]
ESLint has all the same rules as JSCS so there should be no reason to use [both tools](https://github.com/twbs/bootstrap/tree/v4-dev/js). Furthermore it would be good to update the eslint config by extending an existing one using a project like [eslint-config-defaults](https://github.com/walmartlabs/eslint-config-defaults) which would make your config something like:

```yaml
---
"extends":
  - "defaults/configurations/walmart/es6-browser"

"rules":
  "something-you-disagree-with": 0
  ...
```

(Disclaimer: I maintain eslint-config-defaults so of course I think it's great)
