### ISSUE TITLE
v4 - A suggestion: More flexible responsive utility classes

### ISSUE THREAD

**Issue by monoblaine** [twbs/bootstrap#17124]
In v3, I'm currently using the following additional responsive utilities, and I was hoping to get your opinion/approval for making it into a feature of v4. Bootstrap currently has the following responsive utility classes:

```css
.visible-xs-*
.visible-sm-*
.visible-md-*
.visible-lg-*
.hidden-xs
.hidden-sm
.hidden-md
.hidden-lg
```
where the "*" is either `block`, `inline` or `inline-block`.

Currently the only way to do something like "Show *this* for `md` and above, hide *that* for `sm` and below" is:

```html
<div>
    <div class="visible-md-block visible-lg-block"></div>
    <div class="hidden-xs hidden-sm"></div>
</div>
```

Besides, v4 has one more responsive breakpoint now, `xl`.

# Additional responsive utility classes

```less
// visible-x when greater than or equal to @screen-(xs|sm|md|lg)-min
.visible-gteq-xs-block,
.visible-gteq-sm-block,
.visible-gteq-md-block,
.visible-gteq-lg-block,

.visible-gteq-xs-inline,
.visible-gteq-sm-inline,
.visible-gteq-md-inline,
.visible-gteq-lg-inline,

.visible-gteq-xs-inline-block,
.visible-gteq-sm-inline-block,
.visible-gteq-md-inline-block,
.visible-gteq-lg-inline-block {
    display: none !important;
}

// block
.visible-gteq-xs-block {
    @media (min-width: @screen-xs-min) {
        display: block !important;
    }
}

.visible-gteq-sm-block {
    @media (min-width: @screen-sm-min) {
        display: block !important;
    }
}

.visible-gteq-md-block {
    @media (min-width: @screen-md-min) {
        display: block !important;
    }
}

.visible-gteq-lg-block {
    @media (min-width: @screen-lg-min) {
        display: block !important;
    }
}

// inline
.visible-gteq-xs-inline {
    @media (min-width: @screen-xs-min) {
        display: inline !important;
    }
}

.visible-gteq-sm-inline {
    @media (min-width: @screen-sm-min) {
        display: inline !important;
    }
}

.visible-gteq-md-inline {
    @media (min-width: @screen-md-min) {
        display: inline !important;
    }
}

.visible-gteq-lg-inline {
    @media (min-width: @screen-lg-min) {
        display: inline !important;
    }
}

// inline-block
.visible-gteq-xs-inline-block {
    @media (min-width: @screen-xs-min) {
        display: inline-block !important;
    }
}

.visible-gteq-sm-inline-block {
    @media (min-width: @screen-sm-min) {
        display: inline-block !important;
    }
}

.visible-gteq-md-inline-block {
    @media (min-width: @screen-md-min) {
        display: inline-block !important;
    }
}

.visible-gteq-lg-inline-block {
    @media (min-width: @screen-lg-min) {
        display: inline-block !important;
    }
}

/*
 * visible-x when less than @screen-(sm|md|lg)-min
 */
.visible-lt-sm-block,
.visible-lt-md-block,
.visible-lt-lg-block,

.visible-lt-sm-inline,
.visible-lt-md-inline,
.visible-lt-lg-inline,

.visible-lt-sm-inline-block,
.visible-lt-md-inline-block,
.visible-lt-lg-inline-block {
    display: none !important;
}

// block
.visible-lt-sm-block {
    @media (max-width: @screen-xs-max) {
        display: block !important;
    }
}

.visible-lt-md-block {
    @media (max-width: @screen-sm-max) {
        display: block !important;
    }
}

.visible-lt-lg-block {
    @media (max-width: @screen-md-max) {
        display: block !important;
    }
}

// inline
.visible-lt-sm-inline {
    @media (max-width: @screen-xs-max) {
        display: inline !important;
    }
}

.visible-lt-md-inline {
    @media (max-width: @screen-sm-max) {
        display: inline !important;
    }
}

.visible-lt-lg-inline {
    @media (max-width: @screen-md-max) {
        display: inline !important;
    }
}

// inline-block
.visible-lt-sm-inline-block {
    @media (max-width: @screen-xs-max) {
        display: inline-block !important;
    }
}

.visible-lt-md-inline-block {
    @media (max-width: @screen-sm-max) {
        display: inline-block !important;
    }
}

.visible-lt-lg-inline-block {
    @media (max-width: @screen-md-max) {
        display: inline-block !important;
    }
}

// hidden
.hidden-lt-sm {
    @media (max-width: @screen-xs-max) {
        .responsive-invisibility();
    }
}

.hidden-lt-md {
    @media (max-width: @screen-sm-max) {
        .responsive-invisibility();
    }
}

.hidden-lt-lg {
    @media (max-width: @screen-md-max) {
        .responsive-invisibility();
    }
}
```

***
**gt:** "Greater than"
**gteq:** "Greater than or equal to"
**lt:** "Less than"
**lteq:** "Less than or equal to"
***

# A use case

Using the code above, the following example means that "Show me both the images and the text for `md` and above, and hide the text for those below that (`sm` and `xs`)"

```html
<ul class="list-inline">
    <li>
        <img src="foo.png" alt="">
        <span class="hidden-lt-md">Item #1</span>
    </li>
    
    <li>
        <img src="bar.png" alt="">
        <span class="hidden-lt-md">Item #2</span>
    </li>
    
    <li>
        <img src="baz.png" alt="">
        <span class="hidden-lt-md">Item #3</span>
    </li>
</ul>
```
