### ISSUE TITLE
Use font-size to set component size variation

### ISSUE THREAD

**Issue by annamalai-saro** [twbs/bootstrap#17199]
For example : There are different variation of buttons..

.btn-lg
.btn-sm

For variation...button's **padding,line-height,font size,border radius** are changed...

Instead how about **em** units

```css
html
{
   font-size:16px;
}
.btn
{
  padding: 1em 1.2em;
  color: #fff;
  border-radius: 0.2rem;
}
```
For **.btn-sm** , just change its **font size**
```css
.btn-sm { font-size: 0.875em }
```

Working with em is a pain ( When nesting elements ) , but code can be reduced ..Its applicable for Buttons , Input box etc...,

Idea from http://simurai.com/blog/2013/07/03/sizing-components/
