### ISSUE TITLE
Modal animations for v4 - some examples

### ISSUE THREAD

**Issue by durkes** [twbs/bootstrap#17219]
I did not believe a pull request was appropriate yet, but I wanted to provide some SCSS additions and some example HTML for easily adding additional animations for modals.

Currently, all animations still require .fade since the JS is looking for fade. I'm proposing this is a starting point to evolve to the final solution.

_modal.scss

``` scss
.modal {
  &.scale {
    .modal-dialog {
      transition-property: all;
      transform: scale(0.75);
    }

    &.in .modal-dialog {
      transform: scale(1);
    }
  }

  &.from-left {
    .modal-dialog {
      transition-property: all;
      transform: translateX(-100%);
    }

    &.in .modal-dialog {
      transform: translateX(0);
    }
  }

  &.from-right {
    .modal-dialog {
      transition-property: all;
      transform: translateX(100%);
    }

    &.in .modal-dialog {
      transform: translateX(0);
    }
  }

  &.from-bottom {
    .modal-dialog {
      transition-property: all;
      transform: translateY(100%);
    }

    &.in .modal-dialog {
      transform: translateY(0);
    }
  }

  &.from-front {
    .modal-dialog {
      transition-property: all;
      transform: scale(3);
    }

    &.in .modal-dialog {
      transform: scale(1);
    }
  }

  &.newspaper {
    .modal-dialog {
      transition-property: all;
      transform: scale(0) rotate(540deg);
    }

    &.in .modal-dialog {
      transform: scale(1) rotate(0deg);
    }
  }
}
```

HTML testing

``` html
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#md-fade-scale">Modal: fade scale</button>
    <div class="modal fade scale" id="md-fade-scale" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              <span class="sr-only">Close</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#md-from-right">Modal: from right</button>
    <div class="modal fade from-right" id="md-from-right" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              <span class="sr-only">Close</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#md-from-left">Modal: from left</button>
    <div class="modal fade from-left" id="md-from-left" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              <span class="sr-only">Close</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#md-from-bottom">Modal: from bottom</button>
    <div class="modal fade from-bottom" id="md-from-bottom" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              <span class="sr-only">Close</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#md-from-front">Modal: from front</button>
    <div class="modal fade from-front" id="md-from-front" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              <span class="sr-only">Close</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#md-newspaper">Modal: newspaper</button>
    <div class="modal fade newspaper" id="md-newspaper" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              <span class="sr-only">Close</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>
```
