### ISSUE TITLE
v4 - File browser component suggestion (with JavaScript)

### ISSUE THREAD

**Issue by monoblaine** [twbs/bootstrap#17278]
I suggest changing the `.file-custom` class as follows, and use some script:

# Before

```less
.file-custom::after {
    content: "Choose file...";
}
```

# After

```less
.file-custom {
    /* the rest of the rules are omitted. */
    overflow: hidden;
    white-space: nowrap;
}

.file-custom:empty::after {
    content: "Choose file...";
}
```

# Script

```js
(function ($) {
    var doc = document,
        supportsMultipleFiles = "multiple" in doc.createElement("input");

    $(doc).on("change", ".file > input[type=file]", function () {
        var input = this,
            fileNames = [],
            label = input.nextElementSibling,
            files, len, i = -1, labelValue;
            
        if (supportsMultipleFiles) {
            len = (files = input.files).length;
            
            while (++i < len) {
                fileNames.push(files[i].name);
            }
        }
        else {
            fileNames.push(input.value.replace(/\\/g, "/").replace(/.*\//, "")); // Removes the path info ("C:\fakepath\" or sth like that)
        }
        
        label.textContent = labelValue = fileNames.length === 0 ? "" : fileNames.join(", ");
        label.setAttribute("title", labelValue);
    });
})(jQuery);
```

# Example

https://jsbin.com/kimaju/edit?html,css,js,output
