### ISSUE TITLE
datetime-local, date, month, time <input>s are taller than other <input>s in Chrome/Edge

### ISSUE THREAD

**Issue by heruan** [twbs/bootstrap#17308]
Why inside an `input-group` the `input` type `datetime-local` gets a different height from other `form-control`s? See https://jsfiddle.net/02z6gh62/2/ (I'm using Chrome)

I've found this
````css
@media screen and (-webkit-min-device-pixel-ratio: 0)
.input-group-sm input[type=date].form-control,
.input-group-sm input[type=time].form-control,
.input-group-sm input[type=datetime-local].form-control,
.input-group-sm input[type=month].form-control,
input[type=date].input-sm, input[type=time].input-sm,
input[type=datetime-local].input-sm,
input[type=month].input-sm {
    line-height: 1.95rem;
}
````
and setting `line-height` to `1rem` works perfectly fine in Chrome, then I wonder why it's forced to 1.95.
