### ISSUE TITLE
v4 - Missing former panel style for cards

### ISSUE THREAD

**Issue by TheZoker** [twbs/bootstrap#17316]
Here are my suggestions for the former panel style:
![img_2015 08 25_21h01m59s_002_](https://cloud.githubusercontent.com/assets/1368405/9476618/e06bca26-4b6d-11e5-9972-37a22f407f96.png)

## 1. Split classes into `card-primary-outline` and `card-primary-fill`
**SCSS**
```scss
$primary: #0275d8;
$warning: #f0ad4e;

.card-primary {
  &-outline {
    border-color: $primary;
  }
  &-fill {
    background-color: $primary;
    color: #FFF;
  }
}

.card-warning {
  &-outline {
    border-color: $warning;
  }
  &-fill {
    background-color: $warning;
    color: #FFF;
  }
}
```
**Example** https://jsbin.com/kifejew/edit?html,css,output
```html
<div class="card card-primary-outline">
	<div class="card-header card-primary-fill">
		Featured
	</div>
	<div class="card-block">
		<h4 class="card-title">Special title treatment</h4>
		<p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
		<a href="#" class="btn btn-primary">Go somewhere</a>
	</div>
	<div class="card-footer">
		2 days ago
	</div>
</div>
<div class="card card-warning-outline">
	<div class="card-header card-warning-fill">
		Featured
	</div>
	<div class="card-block">
		<h4 class="card-title">Special title treatment</h4>
		<p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
		<a href="#" class="btn btn-warning">Go somewhere</a>
	</div>
	<div class="card-footer">
		2 days ago
	</div>
</div>
```
## 2. Split classes into `card-primary-outline` and `card-primary-fill` and add class `card-primary-header`
`card-primary-fill` can be added to every color class (like primary, warning etc.) and applies the right color.
**SCSS**
```scss
$primary: #0275d8;
$warning: #f0ad4e;

.card-primary {
  &-outline {
    border-color: $primary;
  }
  &-header {
    background-color: $primary;
    color: #FFF;
  }
  &-fill {
    border-color: $primary;
    background-color: $primary;
  }
}

.card-warning {
  &-outline {
    border-color: $warning;
  }
  &-header {
    background-color: $warning;
    color: #FFF;
  }
  &-fill {
    border-color: $warning;
    background-color: $warning;
  }
}
```
**Example** https://jsbin.com/jixuyo/2/edit?html,css,output
```html
<div class="card card-primary-outline">
  <div class="card-header card-primary-header">
      Featured
  </div>
  <div class="card-block">
      <h4 class="card-title">Special title treatment</h4>
      <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
      <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
  <div class="card-footer">
      2 days ago
  </div>
</div>
<div class="card card-warning-fill card-inverse">
  <div class="card-header card-warning-header">
      Featured
  </div>
  <div class="card-block">
      <h4 class="card-title">Special title treatment</h4>
      <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
      <a href="#" class="btn btn-warning">Go somewhere</a>
  </div>
  <div class="card-footer">
      2 days ago
  </div>
</div>
```

These are just suggestions. 
Open for discussion :)

---
BTW, in the current v4 code there are some issues, if you use `card-primary` with `card-header`or `card-footer`:
![img_2015 08 25_22h13m10s_003_](https://cloud.githubusercontent.com/assets/1368405/9478198/a587217c-4b76-11e5-8f3a-11dd78bd9f44.png)
![img_2015 08 25_22h13m34s_004_](https://cloud.githubusercontent.com/assets/1368405/9478218/bc0ab206-4b76-11e5-872a-5c8ce365a8ed.png)
