### ISSUE TITLE
Separately enable `$border-width` on `.btn` and `.form-control` elements

### ISSUE THREAD

**Issue by coltonbrugger** [twbs/bootstrap#17361]
### Goal

To be able to enable/disable borders on form controls and buttons separately. We oft like to leave borders on form controls but prefer to have flat, borderless buttons. But to do that (borderless buttons) and maintain consistent heights with form controls is a pain with currently-available variables.

Would love to hear thoughts from others on this.

### Potential Solution

1) add two new variables: `enable-border-btn` and `$enable-border-control`
2) add statements to control presence of borders & calculations to ensure padding is correct with/without the borders

Example code that I think would achieve such is below. I'm happy to develop the PR if this feature/concept would be considered.

##### `_variables.scss`
```scss
// primary variable remains: border width (when shown) on any element
$border-width:               .0625rem !default;

// (new definitions) whether borders are shown on `btn`/`form control` elements
$enable-border-btn:          true !default;
$enable-border-control:      true !default;

// added after default declarations of said variables, 
// to account add extra padding when borders are disabled
@if $enable-border-control == false {
  $input-padding-x:          $input-padding-x + $border-width;
  $input-padding-y:          $input-padding-y + $border-width;

  $input-padding-x-sm:       $input-padding-x-sm + $border-width;
  $input-padding-y-sm:       $input-padding-y-sm + $border-width;

  $input-padding-x-lg:       $input-padding-x-lg + $border-width;
  $input-padding-y-lg:       $input-padding-y-lg + $border-width;
}
```

##### `_buttons.scss`
```scss
.btn {
  ...
  @if $enable-border-btn {
    border: $border-width solid transparent;
  }
  ...
}
```

##### `mixins/_buttons.scss`
```scss
@mixin button-size($padding-y, $padding-x, $font-size, $line-height, $border-radius) {
  @if $enable-border-btn {
    padding: $padding-y $padding-x;
  } @else {
    padding: ($padding-y + $border-width) ($padding-x + $border-width);
  }
  font-size: $font-size;
  line-height: $line-height;
  @include border-radius($border-radius);
}
```

##### `_forms.scss`
```scss
.form-control {
  ...
  @if $enable-border-control {
    border: $border-width solid $input-border;
  }
  ...
}
```
