### ISSUE TITLE
v4 alpha - nested dropdown menu

### ISSUE THREAD

**Issue by elgubenis** [twbs/bootstrap#17408]
hi folks, i've got the following but i have no idea how to extend my dropdown menu to have a sub-menu inside, is there any official way yet?
<img width="167" alt="screen shot 2015-08-31 at 08 11 40" src="https://cloud.githubusercontent.com/assets/7453396/9579393/ed4d5edc-4fb7-11e5-8da7-b0d81c578d22.png">

```html
<button class="btn btn-transparent btn-secondary btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#">
          <i class="fa fa-fw fa-git"></i>&nbsp; Git
        </a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-fw fa-book"></i>&nbsp; npm
        </a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-fw fa-eyedropper"></i>&nbsp; Profiling
        </a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">
          <i class="fa fa-fw fa-cog"></i>&nbsp; Process
        </a>
      </div>
```

**Comment by elgubenis** [comment]
oh .. i see #16387 :(

**Comment by elgubenis** [comment]
if anybody else is interested, here is a solution:

```css
.dropdown-submenu { position: relative }
.dropdown-submenu>.dropdown-menu {
    top: 0;
    left: 100%;
    margin-top: -6px;
    margin-left: -1px;
    -webkit-border-radius: 4px;
    -moz-border-radius: 4px;
    border-radius: 4px;
}
.dropdown-submenu:hover>.dropdown-menu { display: block }
.dropdown-submenu>a:after {
    display: block;
    content: " ";
    float: right;
    width: 0;
    height: 0;
    border-color: transparent;
    border-style: solid;
    border-width: 5px 0 5px 5px;
    border-left-color: #ccc;
    margin-top: 5px;
    margin-right: -10px;
}
.dropdown-submenu:hover>a:after { border-left-color: #ccc }
.dropdown-submenu.pull-left { float: none }
.dropdown-submenu.pull-left>.dropdown-menu {
    left: -100%;
    margin-left: 10px;
    -webkit-border-radius: 4px;
    -moz-border-radius: 4px;
    border-radius: 4px;
}
```

```html
    <div class="btn-group pull-right">
      <button class="btn btn-transparent btn-secondary btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
      <div class="dropdown-menu">
        <li class="dropdown-item dropdown-submenu">
          <a tabindex="-1" href="#">
            <i class="fa fa-fw fa-git"></i>&nbsp; Git
          </a>
          <ul class="dropdown-menu">
            <li>
              <a href="#" bypass class="dropdown-item interaction" data-module="git" data-action="status">
                <i class="fa fa-fw fa-flag"></i>&nbsp; status
              </a>
            </li>
            <li>
              <a href="#" bypass class="dropdown-item interaction" data-module="git" data-action="compare">
                <i class="fa fa-fw fa-files-o"></i>&nbsp; compare
              </a>
            </li>
            <li>
              <a href="#" class="dropdown-item" bypass>
                <i class="fa fa-fw fa-cloud-download"></i>&nbsp; pull
              </a>
            </li>
          </ul>
        </li>
      </div>
    </div>
```
