### ISSUE TITLE
Make the navbar without JavaScript

### ISSUE THREAD

**Issue by My1** [twbs/bootstrap#17540]
well topic says it all. also before anyone says that it's impossible, I have it working:
HTML
```html
 <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          
          <label for="resnav" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </label>
          <a class="navbar-brand" href="#top">Title</a>
        </div>
        <input type="checkbox" style="display:none" id="resnav" style="display:none;">
        <div id="navbar" class="navbar-collapse collapse">
        </div>
</div>
</nav>
```
CSS:
```css
/*js-less nav*/
@media (max-width: 768px) {

input[id="resnav"] + .collapse{
  display:none;
  transition: display 250ms;
}

input[id="resnav"]:checked + .collapse{
  display:block;
}
}
```

obviosly enough you need to include the bootstrap files and stuff.

I didnt get pretty CSS3 animations to work the way they should but that's not the problem

the reason is simple, I dont visit any bootstrap sites on my phone so I have no exact experience with bootstrap, but I have seen a lot of overscripted sites where the js fails to load properly, and then you have buttons that dont work at all.

and since jsfiddle and codepen both seem to be unable to work without js, you wont get any but you need to test yourself. (easiest way is either noscript for firefox or a second chrome profile)
