### ISSUE TITLE
.container has only max-width and not width

### ISSUE THREAD

**Issue by gseregni** [twbs/bootstrap#17621]
As of BS3 a .container was defined in this way :
```css
@media (min-width: 1200px) {
  .container {
    width: 1170px;
  }
}
```
Now only max-width is defined
```css
@media (min-width: 75em) {
  .container {
    max-width: 72.25rem;
  }
}
```

If i place a .container in a flex box or float it , this cause the container to shrink if content is not large enough.

This solves :
```css
@media (min-width: 75em) {
  .container {
    max-width: 72.25rem;
    width: 72.25rem;
  }
}
```
