### ISSUE TITLE
V4 :  Flexbox IE9 ?

### ISSUE THREAD

**Issue by a-moses** [twbs/bootstrap#17802]
[In theory  Flexbox not supported on IE9 ?!?](https://github.com/twbs/bootstrap/commit/56aadd25da32a447a98777f3424fd96316eddb24#commitcomment-13627580)

http://caniuse.com/#search=flex

**Comment by cvrebert** [comment]
Yes, that's why it's opt-in via the `$enable-flex` variable. It's disabled by default.

**Comment by a-moses** [comment]
haha OK thanks !

**Comment by efender** [comment]
You can use a trick:

**ie9.scss**
```scss
$ie: 9;
@import "imports";
```

**style.scss**
```scss
$ie: 99;
@import "imports";
```

**imports.scss**
```scss
/* floats for ie9, flex for others */
$enable-flex: if($ie > 9, true, false);

/* more css rules here */
/* and we can separate rules */
.class {
    @if $ie < 10 {
        /* for ie9 */
    } @else {
        /* for other browsers, no need ie9 hacks */
    }
}
```

**index.html**
```html
...
<head>
    <!--[if gt IE 9]><!--><link rel="stylesheet" href="css/style.css"/><!--<![endif]-->
    <!--[if IE 9]><link rel="stylesheet" href="css/ie9.css"/><![endif]-->
</head>
...
```
