### ISSUE TITLE
flex - classes with justify-content

### ISSUE THREAD

**Issue by marekkobida** [twbs/bootstrap#18024]
Why in Bootstrap does not exist classes like
```
.row-xs-start {
	justify-content: flex-start;
}

.row-xs-center {
	justify-content: center;
}

.row-xs-end {
	justify-content: flex-end;
}
```
And you could rename classes `.row-xs-top, .row-xs-center, .row-xs-bottom` to `.row-xs-top, .row-xs-middle, .row-xs-bottom` && `.col-xs-top, .col-xs-center, .col-xs-bottom` to `.col-xs-top, .col-xs-middle, .col-xs-bottom`

**Comment by matherton** [comment]
I guess if you want to have justified content in this way you could extend/overwrite existing classes? Not sure you would want to change the default bootstrap framework as it is a base for a lot of sites.

**Comment by marekkobida** [comment]
They added classes with align-items, align-self so why not justify-content? It is really important If I want to move .row to the end of container for example...

**Comment by jerivas** [comment]
Would love to see this. Just tried it out and works great. it's a few lines in `_grid.scss`:

```scss
// Vertical alignment for every column in row

@each $breakpoint in map-keys($grid-breakpoints) {
  @include media-breakpoint-up($breakpoint) {
    .row-#{$breakpoint}-top    { align-items: flex-start; }
    .row-#{$breakpoint}-middle { align-items: center; }
    .row-#{$breakpoint}-bottom { align-items: flex-end; }
  }
}

// Horizontal alignment for every column in row

@each $breakpoint in map-keys($grid-breakpoints) {
  @include media-breakpoint-up($breakpoint) {
    .row-#{$breakpoint}-left    { justify-content: flex-start; }
    .row-#{$breakpoint}-center  { justify-content: center; }
    .row-#{$breakpoint}-right   { justify-content: flex-end; }
    .row-#{$breakpoint}-around  { justify-content: space-around; }
    .row-#{$breakpoint}-between { justify-content: space-between; }
  }
}
```
![row](https://cloud.githubusercontent.com/assets/2391102/10825444/a5e712c6-7e2a-11e5-82b0-f3346198b4a2.png)
![rowmiddle](https://cloud.githubusercontent.com/assets/2391102/10825445/a5e7a4d4-7e2a-11e5-9c74-2d50f88183c8.png)
![row-between](https://cloud.githubusercontent.com/assets/2391102/10825578/44f5261e-7e2b-11e5-9016-1524de7e14e8.png)
![row-center](https://cloud.githubusercontent.com/assets/2391102/10825577/44f4d074-7e2b-11e5-97ac-a54acd54117f.png)
