### ISSUE TITLE
Data on IE versions affected by \9 hacks might be wrong

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18082]
In https://github.com/twbs/bootstrap/blob/726525c0cf4c1d61f4284bf3cb855c0a8f0d2f44/scss/_custom-forms.scss#L130 among other places, it's claimed that (ignoring IE<=8 since we don't support them) the `\9` hack only affects IE9. [Recent testing calls this into question](https://github.com/4ae9b8/browserhacks/issues/165#issuecomment-137941073), claiming the correct compatibility situation is:

``` scss
.selector { property: value \9; } // IE 6-8
.selector { property: value\9; } // IE 6-10
```

Note that this introduces the further wrinkle that whitespace affects the effect of the hack, which has minification implications.
Also note that the browserhacks.com site has bitrotted and isn't fully reliable anymore; see https://github.com/4ae9b8/browserhacks/issues/39#issuecomment-56337569
