### ISSUE TITLE
v4 .card-columns support for webkit + firefox

### ISSUE THREAD

**Issue by justiniso** [twbs/bootstrap#18236]
.card-columns is making use of the `column-count` and `column-gap` properties:

https://github.com/twbs/bootstrap/blob/v4.0.0-alpha/scss/_card.scss#L287

In order to support all modern browsers, please add:

```css
    -webkit-column-count: 3;
    -moz-column-count: 3;
    column-count: 3;

    -webkit-column-gap: 1.25rem;
    -moz-column-gap: 1.25rem;
    column-gap: 1.25rem;
```

**Comment by mrmlnc** [comment]
See compiled CSS file: https://github.com/twbs/bootstrap/blob/v4.0.0-alpha/dist/css/bootstrap.css#L4079-L4086
```css
.card-columns {
  -webkit-column-count: 3;
     -moz-column-count: 3;
          column-count: 3;
  -webkit-column-gap: 1.25rem;
     -moz-column-gap: 1.25rem;
          column-gap: 1.25rem;
}
```

Bootstrap uses [Autoprefixer](https://github.com/postcss/autoprefixer).
