### ISSUE TITLE
v3 .row add flex-wrap style breaks in safari

### ISSUE THREAD

**Issue by Wendong-Wu** [twbs/bootstrap#18306]
In safari, if bootstrap rows are added the following class:
**css**:
```css
.row-flex {
  display: -webkit-flex;
  -webkit-flex-wrap: wrap;
}
```

**html**:
```html
<div class="row row-flex">
    <div class="col-sm-4"></div>
    <div class="col-sm-8"></div>
</div>
```
[codepen demo](http://codepen.io/Wendong-Wu/pen/PPvzbz)
The children columns that are add up to 12 will break into two lines. This is caused by pseudo elements "before" and "after" in `.row`. The `content: ' '`  will have an impact on width in flexbox in Safari. But if we change the css to this, the problem will be fixed. 
**css**:
```css
.row-flex:before, .row-flex:after {
  width: 0;
}
```

However, the pseudo elements still occupy some tiny space in Safari's flexbox even if it is set to width 0. But I guess this is a Safari bug. 

Though this is a rare use case, I think adding `width: 0` to the pseudo elements in `.row` will be safer choice.
