### ISSUE TITLE
V4 SCSS inclusion via an underscored file

### ISSUE THREAD

**Issue by rosskevin** [twbs/bootstrap#18350]
In the repository, `bootstrap.scss` contains all the imports.  Unfortunately, since the file does not begin with an underscore, customization of bootstrap via variables breaks (the context is reset unless the file starts with an underscore).  Following the lead of v3 bootstrap-sass, please rename all non-underscored files as underscored files.  On the same note, you may want to change the directory structure to indicate top level vs subordinate includes.

To make v4 in the same vein as v3 bootstrap-sass:
```
bootstrap/
├── scss/
      ├── _bootstrap.scss
      ├── _bootstrap-flex.scss
      ├── _bootstrap-grid.scss
      ├── _bootstrap-reboot.scss
      ├── includes/
         ├── _variables.scss
         └── etc
```

I'm not sure if `includes` is the right subdir, anything will work...whatever makes sense.

Without this, a project customizing BS4 via variables would need to copy the contents of `bootstrap.scss` to affect all bootstrap variables and to have the app's custom styles depend on BS defined variables.

Sample usage app.scss:
```scss
$font-family-sans-serif: 'Roboto', 'Helvetica', 'Arial', sans-serif;
@import "../bower_components/bootstrap/scss/bootstrap";

.foo {
    font-size: $font-size-base;
}
```
