### ISSUE TITLE
Add responsive display:block/inline/inline-block utility classes

### ISSUE THREAD

**Issue by fridays** [twbs/bootstrap#18410]
It would be great to have some utility classes for each breakpoint:
```
.block
.block-sm
.block-md
.block-lg

.inline
.inline-sm
.inline-md
.inline-lg

.inline-block
.inline-block-sm
.inline-block-md
.inline-block-lg
```

**Comment by cvrebert** [comment]
Can you give some examples of where this would be useful?

**Comment by fridays** [comment]
I think it would be useful for arranging elements when a grid or floats don't fit. 

For example buttons that appear below each other on phones, but next to each other on higher screens:
```
<button class="btn block inline-sm-up">button 1</button>
<button class="btn block inline-sm-up">button 1</button>
```
Instead of buttons, this could be checkboxes, images or anything else.

**Comment by lancomega** [comment]
Do you find any solution, Iam interesting as well.

**Comment by fridays** [comment]
@lancomega You can use the following SCSS with v4 to make the classes available:
````scss
.block          { display: block; }
.inline         { display: inline; }
.inline-block   { display: inline-block; }

@each $breakpoint in map-keys($grid-breakpoints) {
  @include media-breakpoint-up($breakpoint) {
    .block-#{$breakpoint}           { display: block; }
    .inline-#{$breakpoint}          { display: inline; }
    .inline-block-#{$breakpoint}    { display: inline-block; }
  }
}
````
