### ISSUE TITLE
navbar-right and navbar-left are only functional inside of a navbar-collapse

### ISSUE THREAD

**Issue by erebel55** [twbs/bootstrap#18411]
The navbar-right and navbar-left css classes only work correctly if inside of a navbar-collapse. This isn't noted in the docs. However, we can easily see that it is true by looking at navbar.less lines 378 - 388.

```css
@media (min-width: @grid-float-breakpoint) {
  .navbar-left  { .pull-left(); }
  .navbar-right {
    .pull-right();
    margin-right: -@navbar-padding-horizontal;

    ~ .navbar-right {
      margin-right: 0;
    }
  }
}
```

This only pulls the navbar-right/left classes if the breakpoint is it. However, if we aren't using navbar-collapse we don't care about the breakpoint.

An example jsbin can be found here:
http://jsbin.com/rirese/edit?html,css,output

If you shrink the view to less than the breakpoint (768px) you will see the havoc.

We could possibly use :not css selector to find navbar-left/right's that are NOT a descendant of navbar-collapse and perform this pull-right/pull-left regardless of the breakpoint.
