### ISSUE TITLE
Add font-weight utility classes

### ISSUE THREAD

**Issue by agtuks** [twbs/bootstrap#18433]
```scss
// Text weights - https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#Common_weight_name_mapping
.text-black {
  font-weight: 900;
}

.text-extra-bold {
  font-weight: 800;
}

.text-bold {
  font-weight: 700;
}

.text-semi-bold {
  font-weight: 600;
}

.text-medium {
  font-weight: 500;
}

.text-normal {
    font-weight: 400;
}

.text-light {
  font-weight: 300;
}

.text-extra-light {
  font-weight: 200;
}

.text-thin {
  font-weight: 100;
}
```
[Pull request #18440 ](https://github.com/twbs/bootstrap/pull/18440)
