### ISSUE TITLE
.pull right doesnt supporting any more?

### ISSUE THREAD

**Issue by jek-fdrv** [twbs/bootstrap#18548]
I see now only
```css
.pull-right>.dropdown-menu{
    right:0;left:auto
}
```
But simple `.pull-right` doesnt exists any more?
