### ISSUE TITLE
.card flex rules break in Internet Explorer 10-11

### ISSUE THREAD

**Issue by HowlingEverett** [twbs/bootstrap#18569]
The card flex shorthand rule is:

```css
.card {
   flex: 1 0 0;
}
```

In Internet Explorer, the `flex-basis` rule of 0 causes the cards to ignore the `flex-grow` rule and size based on horizontal content-width.

Replacing the rule with:

```css
.card {
  flex: 1 0 1px;
}
```

fixes the issue in IE and still works as expected in other browsers (cards grow to fill the container but maintain equal width in relation to each other.)
