### ISSUE TITLE
Courier New for code,pre looks awful in Ubuntu Linux 15.10

### ISSUE THREAD

**Issue by gjcarneiro** [twbs/bootstrap#18609]
Please don't put  "Courier New" ahead of monospace:

```css
code,
pre {
  font-family: Monaco, Menlo, Consolas, "Courier New", monospace;
}
```

This causes Courier New to be used in Linux and it looks really awful.  I don't understand the need for overriding the default monospace font.  The default monospace font is usually the most readable on any system, trying to override is a very bad idea.
