### ISSUE TITLE
Add .col-*-offset-right-N classes

### ISSUE THREAD

**Issue by joomlaA1** [twbs/bootstrap#18983]
current offset is to left only...
[sm-2][sm-2 offset-2][sm-6]
[oo][__oo][oooooo]

i would like some offset right
ex.
[sm-2][sm-2 offset-right-2][sm-6]
[oo][oo__][oooooo]

sample code from stack overflow...
```less
.col-offset-right(@i, @type) when (@i >= 0) {
    .col-@{type}-offset-right-@{i} {
        margin-right: percentage((@i / @grid-columns));
    }
    .col-offset-right(@i - 1, @type);
};
.col-offset-right(@grid-columns, xs);
.col-offset-right(@grid-columns, sm);
.col-offset-right(@grid-columns, md);
.col-offset-right(@grid-columns, lg);
```
answered Jul 29 '15 at 22:29

user1809033

thanks
