### ISSUE TITLE
Redundant Headings re-declaration in _type.scss

### ISSUE THREAD

**Issue by atu-record** [twbs/bootstrap#18992]
On Line 24, the declarations are redundant.

if you write it DRY like this 
``` sass
h1, .h1 { font-size: $font-size-h1; }
h2, .h2 { font-size: $font-size-h2; }
h3, .h3 { font-size: $font-size-h3; }
h4, .h4 { font-size: $font-size-h4; }
h5, .h5 { font-size: $font-size-h5; }
h6, .h6 { font-size: $font-size-h6; }
```

the sass will still compile to 
``` css
h1 {
  font-size: 2.5rem; }

h2 {
  font-size: 2rem; }

h3 {
  font-size: 1.75rem; }

h4 {
  font-size: 1.5rem; }

h5 {
  font-size: 1.25rem; }

h6 {
  font-size: 1rem; }

.h1 {
  font-size: 2.5rem; }

.h2 {
  font-size: 2rem; }

.h3 {
  font-size: 1.75rem; }

.h4 {
  font-size: 1.5rem; }

.h5 {
  font-size: 1.25rem; }

.h6 {
  font-size: 1rem; }
```

and the ```<h1 class="h2">``` will still be styled as an h2

**Comment by cvrebert** [comment]
> the sass will still compile to

No, actually it compiles differently:

```
bootstrap (v4-dev) $ ./node_modules/.bin/node-sass -v
node-sass	3.4.2	(Wrapper)	[JavaScript]
libsass  	3.3.2	(Sass Compiler)	[C/C++]
bootstrap (v4-dev) $ cat foo.scss
```
```scss
@import "scss/variables";
h1, .h1 { font-size: $font-size-h1; }
h2, .h2 { font-size: $font-size-h2; }
h3, .h3 { font-size: $font-size-h3; }
h4, .h4 { font-size: $font-size-h4; }
h5, .h5 { font-size: $font-size-h5; }
h6, .h6 { font-size: $font-size-h6; }
```
```
bootstrap (v4-dev) $ ./node_modules/.bin/node-sass foo.scss 
```
```css
h1, .h1 {
  font-size: 2.5rem; }

h2, .h2 {
  font-size: 2rem; }

h3, .h3 {
  font-size: 1.75rem; }

h4, .h4 {
  font-size: 1.5rem; }

h5, .h5 {
  font-size: 1.25rem; }

h6, .h6 {
  font-size: 1rem; }
```
```
bootstrap (v4-dev) $
```
