### ISSUE TITLE
Allow using .nav-stacked with only .nav-link (without .nav-item)

### ISSUE THREAD

**Issue by MarkMurphy** [twbs/bootstrap#19040]
In the v4 docs there is this:

``` html
<nav class="nav nav-inline">
  <a class="nav-link active" href="#">Active</a>
  <a class="nav-link" href="#">Link</a>
  <a class="nav-link" href="#">Another link</a>
  <a class="nav-link disabled" href="#">Disabled</a>
</nav>
```

why not also have the option to use `nav-stacked` with this markup? ie. 

``` css
.nav-stacked .nav-item,
.nav-stacked > .nav-link {
  display: block;
  float: none;
}
.nav-stacked .nav-item+.nav-item,
.nav-stacked > .nav-link+.nav-link {
  margin-top: .2rem;
  margin-left: 0;
}
```
