### ISSUE TITLE
Double border on list-group in cards with no .card-block between the list-group and .card-{header,footer}

### ISSUE THREAD

**Issue by grizzm0** [twbs/bootstrap#19047]
List-group adds a double border to cards when the card is missing card-block.

JSFiddle: https://jsfiddle.net/rxkb95s5/1/

**Comment by mishra-ankit** [comment]
Would it be right to go with something like this ?
```css
.card-header + .list-group > .list-group-item:first-child {
    border-top: 0;
}
```
( Doesn't seems a good fix to me, though.)

I would love to pick it as my first contribution if no one has picked it yet.
@cvrebert Could you please suggest on the same, and guide me getting started.
