### ISSUE TITLE
.caret do not display

### ISSUE THREAD

**Issue by KevenYoung** [twbs/bootstrap#19052]
I found .caret class lost `border-top: 4px dashed `in `bootstrap.min.css`,
this causes we can not see .caret in dropdown button.
I think it was caused by the minify tool.

**Comment by cvrebert** [comment]
@KevenYoung What version of Bootstrap are you referring to?

**Comment by cvrebert** [comment]
After "unminifying" via
```
$ gsed -i 's/[;{]/&\n/g' dist/css/bootstrap.min.css && gsed -i 's/[}]/\n&\n/g' dist/css/bootstrap.min.css
```

Current `master` (91c8929b28f1fc45223d6422804f895ece107261):
```css
.caret{
display:inline-block;
width:0;
height:0;
margin-left:2px;
vertical-align:middle;
border-top:4px dashed;/* IT'S HERE */
border-top:4px solid\9;
border-right:4px solid transparent;
border-left:4px solid transparent
}
```

v3.3.6:
```css
.caret{
display:inline-block;
width:0;
height:0;
margin-left:2px;
vertical-align:middle;
border-top:4px dashed;/* IT'S HERE */
border-top:4px solid\9;
border-right:4px solid transparent;
border-left:4px solid transparent
}
```

As for v4, there `.caret` is a ghost which is in the process of being removed (see #17985).
