### ISSUE TITLE
.labels on multiple lines don't render correctly

### ISSUE THREAD

**Issue by tchoulihan** [twbs/bootstrap#19134]
When using `label label-default`, or any other label, I'd find that the label would often wrap incorrectly, like so:

http://jsfiddle.net/aRJr2/

I was able to fix this with the following css:

```css
.label {
  display: inline-table;
  line-height: initial;
}
```
