### ISSUE TITLE
Add support for progress bars within buttons

### ISSUE THREAD

**Issue by Kestanous** [twbs/bootstrap#19188]
Please consider adding support for a progress bar inside of a button:
```html
<button class="btn btn-primary btn-block">
  <progress class="progress progress-striped" value="25" max="100">25%</progress>
</button>
```
In this case I have added `btn-block` so the button does not shrink to nothing. A minor tweak to the margin may be all that is required.
```css
.btn .progress {
  margin: 0.313rem 0; /* just playing around this happen to be all I needed */
}
```
The current (alpha-2) default css has a bottom margin that messes with centering within .btn and the resulting button can effect alignment within a grid.

~Thanks
