### ISSUE TITLE
Missing col- prefix to col-*-offset-*

### ISSUE THREAD

**Issue by mstnorris** [twbs/bootstrap#19562]
The compiled css in the dist directory, and my compiled css using the SCSS from npm and Laravel Elixir (gulp) are missing the col- prefix to the col-*-offset-* classes.

I've posted a question on Stack Overflow to this effect as I thought it was me as one second it was working, and the next it wasn't so I am now thinking it was in when I ran `npm update` to get the latest and something changed in the last 24 hours or so.

The output for the column offsets is now just:

```css
  .offset-sm-4 {
    margin-left: 33.3333333333%; }
  .offset-sm-5 {
    margin-left: 41.6666666667%; }
  .offset-sm-6 {
    margin-left: 50%; }
  .offset-sm-7 {
```

Please advise if this is intentional (and therefore the docs need to be updated) or if this _is_ an error then how can I fix.

I'm now assuming it is intentional as the names have changed.
