### ISSUE TITLE
Using .show on inline items

### ISSUE THREAD

**Issue by jtrumbull** [twbs/bootstrap#19689]
When using the `.show` helper class on inline items, display is erroneously set to `block`.

I.e. using `.show` on `.pagination` items would render unexpected results ([jsFiddle](https://jsfiddle.net/joeycakes/L829kmvt/))
```html
<ul class="pagination">
  <li class="hide"><a href="#">First</a></li>
  <li class="hide show"><a href="#">Prev</a></li>
  ...
  <li class="hide show"><a href="#">Next</a></li>
  <li class="hide"><a href="#">Last</a></li>
</ul>
```

Would it make sense to add specific directives where `display: block` is inappropriate?

```css
.list-inline > li.show {
  display: inline!important;
}
.pagination > li.show {
  display: inline!important;
}
...
```
