### ISSUE TITLE
print grid columns

### ISSUE THREAD

**Issue by vinorodrigues** [twbs/bootstrap#19701]
It would be nice to have printing specific grid columns, i.e. `col-pr-*` that is nested in a @media print

I have an external mixin that uses:

```scss
$print-breakpoints: ( pr: 0 );

@media print {
  .hidden-pr,  // alias for .hidden-print
  .col-pr-0 { display: none !important; }
  @include make-grid-columns($grid-columns, $grid-gutter-width, $print-breakpoints);
}
```

(...but *make-grid-columns* does not add the `!important` bit to the end of the `width` in `col-pr-*` items ☹)

This would help in developing rich printed output and one could create printed media that behaves differently to the screen versions.  e.g. one could print only the content of a page with side bar:

```html
<div class="row">
  <div class="col-md-4 col-pr-0">
    Sidebar here, but not printed
  </div>
  <div class="col-md-8 col-pr-12">
    Content here, but full width when printed
  </div>
</div>
```
