### ISSUE TITLE
Add text color argument to .bg-variant mixin

### ISSUE THREAD

**Issue by praveenpuglia** [twbs/bootstrap#19854]
While extending bootstrap for my own project I realized that I had to create many more background utility classes based on 7 grays I have in my project. I thought of using the existing `bg-variant()` mixin for creating for the variant but I see that the `color` property is hard coded to be `#fff !important`. 

https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_background-variant.scss#L5

This doesn't really work well for lighter colors. Can the mixin be changed to accomodate a `text-color` argument and have it set to `#fff` as default rather than hard coding it?

```scss
@mixin bg-variant($parent, $color, $text-color:#fff) {
  #{$parent} {
    color: $text-color !important;
    background-color: $color !important;
  }
  a#{$parent} {
    @include hover-focus {
      background-color: darken($color, 10%) !important;
    }
  }
}
```
 This definitely requires some additional changes in the references but it makes it possible for the text color to be adjusted while creating these classes.

**Comment by mdo** [comment]
Going to probably avoid doing this and instead opt for those utilities to have a single declaration—`background-color`—and leave the `color` to another utility. Haven't put toooo much thought into it, but definitely want to try that out.

**Comment by praveenpuglia** [comment]
Eager to know how that'll work. Set `color` from another mixin?

**Comment by franz-josef-kaiser** [comment]
I'd suggest to combine that with an auto-adjusting approach:

```scss

@mixin bg-variant($parent, $bg-color, $text-color:#fff) {
	#{$parent} {
		@if( lightness($bg-color) > 50 ) {
			color: darken($text-color,lightness($bg-color)) !important;
		} @else {
			color: $text-color !important;
		}
		background-color: $bg-color !important;
	}
	a#{$parent} {
		@include hover-focus {
			background-color: darken($bg-color, 10%) !important;
		}
	}
}
```

Above is a very simplified approach. It might benefit from trying this with a variant of background-color sets and maybe use `hue()` and/ or `saturation()` to calculate a working text `color`.
