### ISSUE TITLE
No -webkit and -moz vendor prefixes for @viewport

### ISSUE THREAD

**Issue by Ryuno-Ki** [twbs/bootstrap#19871]
The documentation at https://github.com/twbs/bootstrap/blob/10606a73bcbfc6c723d60e2a1069c921afff0d2a/docs/_includes/getting-started/browser-device-support.html#L154 is wrong.

According to [Can I Use?](http://caniuse.com/#feat=css-deviceadaptation) and [WebPlatform.org](https://docs.webplatform.org/wiki/css/atrules/@viewport) the only supported vendor prefixes are
```css
@-ms-viewport       { width: device-width; }
@-o-viewport        { width: device-width; }
@viewport           { width: device-width; }
```

gulp-csslint threw a parser error in my project.
