### ISSUE TITLE
.col-xs-12 can overflow its row when Flexbox is enabled

### ISSUE THREAD

**Issue by rubenvincenten** [twbs/bootstrap#19965]
Imagine the following structure with `$enable-flex: true`:

```html
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-4">This is supposed to be full width at mobile screens</div>
   </div>
</div>
```

When on mobile screens, the col expands to the content width(for large images, it overflows the row width!!), while it should expand to the container width (fluid @ `100vw`)

I fixed this with some simple scss:
```scss
.col-xs-12 {
  @include media-breakpoint-down(xs) {
    flex-grow: 1;
  }
}
```
I'm not sure how this would play out with higher breakpoints however. Is there any other way to resolve this maybe?

UPDATE: I'm now adding an extra class to the grid rows if there's only .col-xs-12 elements inside that row.

```scss
@include media-breakpoint-down(xs) {
  .row.no-flexbox-xs {
    display: block;
  }
}
```
