### ISSUE TITLE
.modal-dialog on narrow SM screen has no horizontal margin

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#19973]
Refs https://github.com/twbs/bootstrap/issues/19969#issuecomment-221954529

**Comment by RyanZim** [comment]
Testcase: https://jsfiddle.net/x1qpe0mm/

**Comment by cvrebert** [comment]
(The test requires the viewport to be between 544px and 599px.)

**Comment by rwaltenberg** [comment]
A left/right padding to the .modal-dialog would do the job:

```css
@media (min-width: 544px) {
  .modal-dialog {
    max-width: 600px;
    margin: 30px auto;
    padding: 0 10px;
  }
}
```
