### ISSUE TITLE
Justified navbar missing classes [v4]

### ISSUE THREAD

**Issue by wifiextender** [twbs/bootstrap#20031]
The issue - https://v4-alpha.getbootstrap.com/examples/justified-nav/

![screen shot 2016-06-03 at 18 56 33](https://cloud.githubusercontent.com/assets/4725121/15786269/02590216-29bc-11e6-9da7-70645c9f64ea.png)

Expected result

![screen shot 2016-06-03 at 18 55 59](https://cloud.githubusercontent.com/assets/4725121/15786268/023a5cee-29bc-11e6-873c-43b127ed7ee5.png)

The classes that fixed the issue:

```css
.nav-justified > li {
   display: table-cell;
   width: 1%; 
   float: none;
   position: relative;
}

.nav > li > a {
    position: relative;
    display: block;
    padding 10px 15px;
}
```

Slightly modified **ie10-viewport-bug-workaround.js**

```javascript
/*!
 * IE10 viewport hack for Surface/desktop Windows 8 bug
 * Copyright 2014-2015 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 */

// See the Getting Started docs for more information:
// http://getbootstrap.com/getting-started/#support-ie10-width

(function () {
  'use strict';
  var msViewportStyle = null;

  if (navigator.userAgent.match(/IEMobile\/10\.0/)) {
    msViewportStyle = document.createElement('style');
    msViewportStyle.appendChild(
      document.createTextNode(
        '@-ms-viewport{width:auto!important}'
      )
    );
    document.getElementsByTagName('head')[0]
      .appendChild(msViewportStyle);
  }

})();
```
