### ISSUE TITLE
Add user-select:none to text-hide mixin?

### ISSUE THREAD

**Issue by niftylettuce** [twbs/bootstrap#20087]
Right now I don't see a `user-select` mixin for alpha v4.  Can we get this in?  I didn't see any other similar issues.

**Comment by niftylettuce** [comment]
The reason I ask is because we have a `text-hide` mixin, but the text hidden is still selectable.  So I wanted to hide it from being even selected, and I tried `user-select: none` but it didn't work in Chrome (it needs `-webkit-user-select: none;` instead of `user-select: none;` despite Chrome having support for it per http://caniuse.com/#search=user-select

Mixin as:

```scss
@mixin user-select($select) {
  -webkit-user-select: $select;
     -moz-user-select: $select;
      -ms-user-select: $select; // IE10+
          user-select: $select;
}
```

Usage as:

```scss
@include user-select(none);
```

Would be cool to get this added to `text-hide` itself!  Since our intent is to hide it completely, right?
