### ISSUE TITLE
Wrong vertical alignment for input-group with radio or checkbox

### ISSUE THREAD

**Issue by praveenpuglia** [twbs/bootstrap#20271]
Here, [ in this docs section](http://v4-alpha.getbootstrap.com/components/input-group/#checkboxes-and-radio-addons), the radio and the checkbox, used as addon to input do not vertically align center as expected. They are a little bit above the horizontal center line.

Here's the screenshot.
![image](https://cloud.githubusercontent.com/assets/313363/16731555/75a13d40-4796-11e6-87b7-5572632f3fab.png)

Adding a `vertical-align: middle` property to the following rule in **_input-group.scss** fixes the problem though.

```scss
.input-group-addon input[type=checkbox], 
.input-group-addon input[type=radio] {
  vertical-align: middle;
}
```

Here's the output screenshot.
![image](https://cloud.githubusercontent.com/assets/313363/16731647/e9bc21cc-4796-11e6-819c-be2a052768d5.png)

Should I send a PR for it? or the issue's source is something else?
