### ISSUE TITLE
.c-select-sm and .c-select-lg missing

### ISSUE THREAD

**Issue by niftylettuce** [twbs/bootstrap#20316]
If you have `.c-select form-control form-control-lg` it does not use proper padding and so it is not a `lg`, it's tiny.

**Comment by niftylettuce** [comment]
Temporary fix:

```scss
select.c-select.form-control-lg {
  padding: $input-padding-y-lg $input-padding-x-lg;
}
```
