### ISSUE TITLE
.list-group-flush within .card causes double border

### ISSUE THREAD

**Issue by jabbett** [twbs/bootstrap#20395]
Saw this locally when I upgraded to alpha 3, confirmed in the [public documentation](http://v4-alpha.getbootstrap.com/components/card/#content-types):

![image](https://cloud.githubusercontent.com/assets/923971/17222762/e0a77968-54c7-11e6-82bd-c84e6252b302.png)

Seeing this in Chrome 51, Firefox 46, and Safari 9.1.2.

**Comment by judetucker** [comment]
+1 For me as well when migrating. 

Also occurring in the plain list-in-a-card example. 

![screen shot 2016-07-28 at 10 45 16 am](https://cloud.githubusercontent.com/assets/4511852/17223243/860ff7b2-54b0-11e6-9a07-18fa5492488d.png)

Potentially this commit removed the different border when list groups are flush.
https://github.com/twbs/bootstrap/commit/955e0405ea04e8bce3fa8395cd5e1c4030c4947a#diff-cd8ec88dc7823a5c78f7111e37a78adbL37

**Comment by Starsam80** [comment]
I thought that mdo fixed these with #19861 and #19885, but I guess he never fixed/reverted _all_ of the changes he made.

**Comment by jenskanis** [comment]
Also occurring for me:

![screen shot 2016-08-05 at 11 16 59](https://cloud.githubusercontent.com/assets/1345437/17432183/2dd7212a-5afe-11e6-9166-4d86d785e1fd.png)

**Comment by judetucker** [comment]
Happy Friday @mdo / @cvrebert! Since this seems to be a common problem and since the fix seems pretty benign, can this be added to the alpha.3.1 patch release?

**Comment by judetucker** [comment]
Hi @mdo, just wanted to follow up on this since its still present in the alpha.4 (http://v4-alpha.getbootstrap.com/components/card/#content-types)

Any chance this fix can catch the alpha.5 milestone?

**Comment by betorina** [comment]
Temporary fix / monkey patch:

```css
// Documentation example: Remove double borders
.card > .list-group > .list-group-item {
  border-left: 0;
  border-right: 0;
}
```
```css
// Plain list card example: Remove also first + last border
.card > .list-group > .list-group-item {
  border-left: 0;
  border-right: 0;
  &:first-of-type {
    border-top: 0;
  }
  &:last-of-type {
    border-bottom: 0;
  }
}
```

**Comment by jabbett** [comment]
The above fix works when the `.list-group` is the only element within the `.card`. The following version allows for the `.list-group` to be combined with other elements within `.card`

```less
.card > .list-group {
  > .list-group-item {
    border-left: 0;
    border-right: 0;
  }
  &:first-child .list-group-item:first-of-type {
    border-top: 0;
  }

  &:last-child .list-group-item:last-of-type {
    border-bottom: 0;
  }
}
```
