### ISSUE TITLE
Add class for centering justified text

### ISSUE THREAD

**Issue by dkrutsko** [twbs/bootstrap#20398]
I have come across use cases where you might want to center justified texts for improved design. I would like to propose a new class, `.text-justify-center`, which centers the last line of justified text. [Most](http://caniuse.com/#feat=css-text-align-last) browsers support this feature except for Safari. If the browser does not support it, this class simply makes the text justified as `.text-justify` does. Below is the implementation:

```css
.text-justify-center {
  text-align: justify !important;
  text-align-last: center !important;
}
```
