### ISSUE TITLE
Menu too high when changing li padding

### ISSUE THREAD

**Issue by stphdenis** [twbs/bootstrap#20573]
When we do :
```css
li {
    padding: 15px;
}
```
the padding of `.navbar-nav > li` get `15px` giving a menu much higher.
To go back to the original size, we have to add in our own css file :
```css
.navbar-nav > li {
  padding: 0px;
}
```
So could we add to `.navbar-nav` block of `navbar.less` file the following code if it is the good solution :
```less
  > li {
    padding:    0px;
  }
```
