### ISSUE TITLE
v4: a.text-muted:hover broken

### ISSUE THREAD

**Issue by tordans** [twbs/bootstrap#20619]
I just updated my rails app to bootstrap (4.0.0.alpha3.1).

No all links `a.text-muted` are broken, the `:hover` does not work anymore.

The issue seems to be, that his line …
```css
/* line 4, /.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bootstrap-4.0.0.alpha3.1/assets/stylesheets/bootstrap/mixins/_text-emphasis.scss */
.text-muted {
  color: #818a91 !important;
}
```

… overwrites this line:
```css
/* line 21, /.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bootstrap-4.0.0.alpha3.1/assets/stylesheets/bootstrap/mixins/_hover.scss */
a.text-muted:focus, a.text-muted:hover {
  color: #687077;
}
```
