### ISSUE TITLE
.col-form-label should right align text

### ISSUE THREAD

**Issue by rexcfnghk** [twbs/bootstrap#20643]
- Operating system and version: Windows 10
- Browser and version: Chrome 53
- Reduced test cases: http://v4-alpha.getbootstrap.com/components/forms/#using-the-grid

To keep it consistent with Bootstrap 3's [horizontal form](http://getbootstrap.com/css/#forms-horizontal), text should be aligned to the right.

As a supporter for right-aligned labels, it is suggested that [right-aligned labels have a lighter cognitive workload for users](http://ux.stackexchange.com/a/8874/46177)

**Comment by mdo** [comment]
Going to leave them as-is for now, thanks though. It's easier to override the default and inherited left alignment than it is to set our own and ask that it work for all implementations.

**Comment by roger2hk** [comment]
The following sample code is for those who would like to keep the v3 label text align right behavior in v4.
```css
@media (min-width: 768px) {
  .form-group .row > .col-form-label {
    text-align: right;
  }
}
```
