### ISSUE TITLE
Add .list-inline variant with separators between items

### ISSUE THREAD

**Issue by benwa** [twbs/bootstrap#20719]
I would like to request a separator option for `.list-inline`.  Similar to how breadcrumbs currently work in that between each `.list-inline-item` is a `|`.

http://codepen.io/_benwa/pen/NRNRWO?editors=1100#0

**Comment by tomlutzenberger** [comment]
Why not

```css
.list-inline-item + .list-inline-item {
  border-left: 1px solid currentColor;
}
```

It does the same and you can adjust thickness, style, color and spacing (via padding).
