### ISSUE TITLE
Select doesn't have the same height as input

### ISSUE THREAD

**Issue by natcohen** [twbs/bootstrap#20809]
If you create a select and an input next to each other, you will see that the select is bigger than the input... they should have the same height!

https://jsfiddle.net/zk6akjL1/2/

**Comment by jipexu** [comment]
yes this is from long time ... if you use custom-select class it's ok ..

**Comment by natcohen** [comment]
@jipexu if you think I made a mistake, please provide a working example by modifying my fiddle...

**Comment by jipexu** [comment]
you right i have 35 and 38 px  ... so it's come with alpha 04

**Comment by cvrebert** [comment]
@natcohen Using `.custom-select` and `.form-control` on the same element, like in your example, is invalid.

**Comment by mihaistoie** [comment]
source of bug : _forms.scss line 59
```css
select.form-control {
  &:not([size]):not([multiple]) {
    height: $input-height;  //<-- 2.5 rem
  }
// ...
```
A solution that works on IE/Firefox/Chrome

```css
select.form-control {
  &:not([size]):not([multiple]) {
    //simulate line-height: 1.25  for selects
    box-sizing: content-box;
    height: 1.25rem;  
  }
// ...
```
