### ISSUE TITLE
abbr[title] still has border-bottom on v4-dev

### ISSUE THREAD

**Issue by davidstosik** [twbs/bootstrap#20908]
Hello,

I wanted to comment on #16574, but it is closed and I can't reopen it, so I was not sure that would notify anyone. Sorry in advance if creating a new issue was bad.

The problem (abbr[title] should not have border-bottom) is still here on `v4-dev`. I get underline and dotted border-bottom:

![image](https://cloud.githubusercontent.com/assets/816901/19415313/a01c0782-93a7-11e6-9306-2e2293e1cf85.png)

(Screenshot was taken on Chrome v53 for Mac.)
[Here is a JSBin too.](https://jsbin.com/birowesido/edit?html,output)

[_normalize.scss:112](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_normalize.scss#112)

``` scss
//
// 1. Remove the bottom border in Firefox 39-.
// 2. Add the correct text decoration in Chrome, Edge, IE, Opera, and Safari.
//

abbr[title] {
  border-bottom: none; // 1
  text-decoration: underline; // 2
  text-decoration: underline dotted; // 2
}

```

[_reboot.scss:114](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_reboot.scss#L114)

``` scss
// Abbreviations and acronyms
abbr[title],
// Add data-* attribute to help out our tooltip plugin, per https://github.com/twbs/bootstrap/issues/5257
abbr[data-original-title] {
  cursor: help;
  border-bottom: 1px dotted $abbr-border-color;
}
```

In the resulting `boostrap.css`, the [reboot part](https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L351) goes lower than the [normalize part](https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L65), and the border ends up being shown.
