### ISSUE TITLE
fieldset[disabled] should not disable all .btn

### ISSUE THREAD

**Issue by llafuente** [twbs/bootstrap#21183]
Hi,

I was playing with `<fieldset disabled="disabled">` to disable all fields in my app. But found something odd, it also disable my "buttons", I mean **.btn** class not button tag.
I carefully choose `<div class="btn ...">...</div>` for those buttons so they won't be disabled by the browser. The odd behaviour is that they work but the style is disabled.

I override that behaviour using a custom class, and I think It should be added to bootstrap or use a more restrictive css: `fieldset[disabled] .btn` is not good enough shoud be `fieldset[disabled] button.btn, fieldset[disabled] a.btn` (and anything I'm missing, but not div!)

For reference this is my workaround atm add `never-disabled` class to each button.
```css
  .btn.never-disabled[disabled], fieldset[disabled] .btn.never-disabled {
    opacity: 1 !important;
    cursor: pointer !important;
  }
```

POC: https://plnkr.co/edit/Qd5WzKGzpj3xgAjdgoZV?p=preview
