### ISSUE TITLE
SVG background icons not shown in Windows High Contrast Mode

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#21269]
successor to https://github.com/twbs/bootstrap/pull/21268 for v4. while the way icons (such as the hamburger menu) are coded is different (SVG background rather than 3 empty spans), these backgrounds (likely in all other places where SVG backgrounds are currently used) still disappear in WHCM.

<img width="960" alt="capture" src="https://cloud.githubusercontent.com/assets/895831/20806645/219a421a-b7fc-11e6-9d92-75f8e48d600d.PNG">

**Comment by joe-watkins** [comment]
Tnx for firing this up @patrickhlauke :) 

Are foreground `.svg` images an option for critical controls like this?

**Comment by patrickhlauke** [comment]
they'll probably have to be. or we provide some high contrast media query stuff https://msdn.microsoft.com/en-us/library/windows/apps/hh465764.aspx or similar...

**Comment by joe-watkins** [comment]
CSS generated content with the media query could be an option if foreground images aren't possible. May be too opinionated for a generic control.. maybe a warning comment in the docs would do?

``` CSS
@media screen and (-ms-high-contrast: active) {
    .navbar-toggler {
        width: auto;
    }
    .navbar-toggler:after {
        content: "menu";
    }
}
```

![mq-hack](https://cloud.githubusercontent.com/assets/3695795/20846863/783725dc-b880-11e6-8bb9-60f5b5d7d4af.png)
