### ISSUE TITLE
Confusing naming of breakpoint mixin @include media-breakpoint-down('x')

### ISSUE THREAD

**Issue by Thumbleweed** [twbs/bootstrap#21267]
I find the naming of the media-breakpoint-down mixin really confusing. 

given the following css:

`@media (max-width: 767px) {
   color: green;
}`

i would expect to write the following:
`@include media-breakpoint-down('md') {
   color: green
}`
=> "everything less than 'md' should be green"

the way it really works is like this:
`@include media-breakpoint-down('sm') {
   color: green
}`
=> "everything less than 'sm' and everything less than 'sm' his next breakpoint should be green"

Kind regards,
Peter

**Comment by mdo** [comment]
How it works today is the correct behavior. Here's an example.

```sass
// Input
@include media-breakpoint-down(md) {
  .element { display: block; }
}

// Output
@media (max-width: 991px) {
  .element {
    display: block;
  }
}
```

**Comment by Thumbleweed** [comment]
Hi,

Although your example is correct, i'm not convinced that it is the correct behaviour.
Since the variable.scss states the following:

```scss
$grid-breakpoints: (
  xs: 0,
  sm: 576px,
  md: 768px,
  lg: 992px,
  xl: 1200px
) !default;
```

i would expect your example to output the following:

```scss
// Input
@include media-breakpoint-down(md) {
  .element { display: block; }
}
```
```css
// Output
@media (max-width: 767px) {
  .element {
    display: block;
  }
}
```

Regards,
Peter
