### ISSUE TITLE
Dropdown item active focus state

### ISSUE THREAD

**Issue by Mevrael** [twbs/bootstrap#21284]
Currently there is active class for dropdown items which adds dark blue background by default, however, it doesn't have any hover and focus style changes.

I have a custom multiple select based on BS4 dropdown. When there are many items selected and navigating menu with arrow up/down keys I have no idea which menu item is currently in focus like I can see it when item is not active and have a light grey bg when hovered/focused.

What about adding another variable(s) and state here, may be another bg or even an inner shadow (border without breaking box size)?

```scss
  // Active state
  &.active {

    // move default styles here and change hover-focus

    @include plain-hover-focus {
      color: $dropdown-link-active-color;
      text-decoration: none;
      background-color: $dropdown-link-active-bg;
      outline: 0;
    }
}
```

Variable name suggestions:

$dropdown-link-active-hover-color;
$dropdown-link-active-hover-bg;
$dropdown-link-active-hover-border;
