### ISSUE TITLE
Feature Request: Card Flip animation

### ISSUE THREAD

**Issue by IamManchanda** [twbs/bootstrap#21320]
I want to add a new feature request for bootstrap 4 : **Card Flips** . I am using this in my projects from quite some time and i felt that this should be contributed as its a cool feature if added in bootstrap 4!

Here is the codepen --> http://codepen.io/IamManchanda/pen/zoaWdW
**Update:** Codepen with multiple rows --> http://codepen.io/IamManchanda/full/GNVKOQ/

and here is the simple and small **SCSS** for the same.

```css
.card-flip {
  perspective: 1000px;
  &:hover .flip, &.hover .flip {
    transform: rotateY(180deg);
  }
}
.card-flip, .front, .back {
  width: 100%;
  height: 480px;
}
.flip {
  transition: 0.6s;
  transform-style: preserve-3d;
  position: relative;
}
.front, .back {
  backface-visibility: hidden;
  position: absolute;
  top: 0;
  left: 0;
}
.front {
  z-index: 2;
  transform: rotateY(0deg);
}
.back {
  transform: rotateY(180deg);
}
```

and also a very simple and one line javascript ,

```javascript
document.querySelector(".card-flip").classList.toggle("flip");
```
