### ISSUE TITLE
z-index for .btn that are state-modified direct descendants of .btn-group

### ISSUE THREAD

**Issue by JrFolk** [twbs/bootstrap#21348]
I was wondering what the impetus was behind [this z-index rule](https://github.com/twbs/bootstrap/blob/d04eb86715ea5842e9032e5c3bc3b70622b15fcd/dist/css/bootstrap.css#L3196e):

```css
.btn-group > .btn:hover,
.btn-group-vertical > .btn:hover,
.btn-group > .btn:focus,
.btn-group-vertical > .btn:focus,
.btn-group > .btn:active,
.btn-group-vertical > .btn:active,
.btn-group > .btn.active,
.btn-group-vertical > .btn.active {
  z-index: 2;
}
```

It kinda catches you by surprise sometimes, appearently.  I'm trying to decide between having to search codebases for any instances and wrap the contents of all `.btn-group`s in a `<span>`, overriding the rule in some way, or globally overriding the rule on my stylesheet.  The latter would be easier and *seems* to work at first glance, but since the rule is there in first place I'm afraid of it potentially breaking other behavior.

Thank you for your time.
