### ISSUE TITLE
[v4 css] inverted table styling

### ISSUE THREAD

**Issue by Mottie** [twbs/bootstrap#21585]
When inverting a table style using the `table-inverse` class ([demo](http://codepen.io/Mottie/pen/OWVgYZ)):

1. **Striping**<br>
   With a "table-striped" class, the stripes are not discernibly different. In the css, the definition is the same as for the non-inverted row styling:

   ```css
   .table-striped tbody tr:nth-of-type(odd) {
     background-color: rgba(0, 0, 0, .05); /* $table-bg-accent; */
   }
   ```

2. Borders<br>
   The border styling of the non-inverted tables is a very subtle, using a border color of `#eceeef`. On inverted tables, we see `#fff`! It's way to bright!

   ```css
   .table-inverse td,
   .table-inverse th,
   .table-inverse thead th {
     border-color: #fff; /* $body-bg */
   }
   ```

3. Hover<br>
   Hovering isn't as bad when no stripe is applied to the table; but when a stripe is applied, the hover is only slightly more discernible than the row color ([demo](http://codepen.io/Mottie/pen/vgOJOW))!

   ```css
   .table-hover tbody tr:hover {
     background-color: rgba(0, 0, 0, .075) /* $table-bg-hover */
   }
   ```

This may not seem like a big deal to some of you young 'uns out there, but for elderly and visually impaired users, it would make a difference.
