### ISSUE TITLE
Centering Logo with Alpha 6 Navbar

### ISSUE THREAD

**Issue by JayteeNZ** [twbs/bootstrap#21605]
I'm not overly familiar with Flexbox but i've updated to Alpha 6 and of course due to the new changes, my navbar broke.

I used to use ``mx-auto`` on my nav logo and then set a width to center it on the navbar but i can't seem to find a way to do this now with A6.

I can get it to 'partially' center in that its offset by a few pixels but as soon as i add another link on either side, it moves.

Any suggestions how to do this? Or would it be possible to push a PR to add a class to do this?

Cheers

**Comment by svenluijten** [comment]
I'm assuming you mean this strange behaviour? 
![bootstrap-navbar](https://cloud.githubusercontent.com/assets/11269635/21749499/c2cf796e-d59f-11e6-963b-d6bfdf1015b4.gif)

I've noticed it as well and found a relatively simple fix. Just add this to your custom CSS file and it won't happen anymore: 

```css
@include media-breakpoint-down(xs) {
    .container {
        margin-left: 0;
        margin-right: 0;
    }
}
```
