### ISSUE TITLE
Placeholder is visually indistinguishable from normal text

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#21624]
The placeholder is almost visually indistinguishable from normal text input.
This is confusing and dangerous. The placeholder text ought to be brighter/dimmer.

This was fine in v4.0.0-alpha.5 but is a regression in v4.0.0-alpha.6.
The color is defined by the `$input-color-placeholder` variable in `/scss/_variables.scss`.
From alpha5 to alpha5 it was changed from `#999` to `$gray-light`. 

## Screenshot
![image](https://cloud.githubusercontent.com/assets/10222521/21770448/a0996d3e-d683-11e6-9654-52ac65b7ff65.png)

**Comment by mdo** [comment]
Closing per https://github.com/twbs/bootstrap/pull/21782#issuecomment-274284975.

**Comment by vanillajonathan** [comment]
So is any fix planned for this issue?

Until then, I have the following code in a CSS file that I load after Bootstrap.

```css
/* Temporary code to workaround a regression in Bootstap 4.0alpha6,
    remove this code when Bootstrap is updated with a new release. */
.form-control::-webkit-input-placeholder {
  color: #999;
}

.form-control::-moz-placeholder {
  color: #999;
}

.form-control:-ms-input-placeholder {
  color: #999;
}

.form-control::placeholder {
  color: #999;
}
```
