### ISSUE TITLE
Carousel plugin dont save aspect ratio of images

### ISSUE THREAD

**Issue by dmitry-git** [twbs/bootstrap#21658]
Carousel plugin dont save aspect ratio of images when container (.carousel-item.active, .carousel-item-next, .carousel-item-prev) width < image width.

OS: Windows 10,
Brousers: Chrome (55.0.2883.87 m 64-bit), Opera (42.0.2393.94), Edge.

[jsfiddle](https://jsfiddle.net/y139sz50/) - a link to the reduced test case

**Comment by dmitry-git** [comment]
Problem with CSS3 "display: flex;"

I used this style to fix it:
```CSS
        .carousel-item.active,
        .carousel-item-next,
        .carousel-item-prev {
            display: block;
        }
```

But it is no CSS3 FLEX :(
