### ISSUE TITLE
navbar comes vertical when we use bootstrap navbar code. i wrote correct code for that 

### ISSUE THREAD

**Issue by samrandhawa4** [twbs/bootstrap#21694]
Here  is the correct css for navbar class of bootstrap.css file 
```css
.navbar-nav {
  display: -webkit-box; 
  display: -ms-flexbox; 
  display: flex; 
  -webkit-box-orient: vertical; 
  -webkit-box-direction: normal; 
  -ms-flex-direction: row; 
  flex-direction: row; 
  padding-left: 0; 
  margin-bottom: 0; 
  list-style: none;
}

.navbar-brand { 
  display: inline-block;
  margin-right: 1rem; 
  line-height: inherit; 
  white-space: nowrap;
}
```
