### ISSUE TITLE
Google Chrome print first-letter

### ISSUE THREAD

**Issue by TheSharpieOne** [twbs/bootstrap#21926]
Similar to #21092 (in the styles which are causing an issue).

I have noticed when printing in Google Chrome (may be a browser issue, but bootstrap's specific styles trigger it), that the first letter is shifted up or down (see test case and screenshots).

Removing the following seems to fix the issue.
```css
@media print
_print.scss:13
*, :after, :before, :first-letter, blockquote:first-line, div:first-line, li:first-line, p:first-line {
    text-shadow: none!important;
    box-shadow: none!important;
}
```

- Operating system and version Mac OS X 10.11
- Browser and version Chrome 56
- Reduced test cases: [JS Bin](https://jsbin.com/roqupegoji/1/edit?html,output) (you will need to print the [output](https://output.jsbin.com/roqupegoji/1/), not the editor)

![image](https://cloud.githubusercontent.com/assets/664714/22659870/5b479ae4-ec6d-11e6-9b06-d0bb184afff3.png)

(Yes, it prints the same way it looks in the preview seen above)

markup used:
```html
<div class="container">
  <div class="row">
    <div>
      <h1>
        Hello there
      </h1>
    </div>
  </div>
</div>
```
**Note**: the `<div>` around the `<h1>` may seem superfluous, but it would contain classes and such for other styling which was removed to reduce the test case. It is important that the content is wrapped. 
The `<h1>` can also be replaced by `<small>` (and maybe more tags) which is case a similar defect, but shift the first character up instead of down.
