### ISSUE TITLE
Cannot change carousel control colors in v4 alpha 6

### ISSUE THREAD

**Issue by tab00** [twbs/bootstrap#21985]
It appears that the left and right icons of the carousel are now SVG images instead of chevron characters. In the browser inspector I see the following style definition for the `<span class="carousel-control-next-icon" aria-hidden="true"></span>` element:

> .carousel-control-next-icon {
>     background-image: url(data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' f…%3Cpath d='M1.5 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E);
> }

Since the icon is now an image, would this be the reason for the inability to change its color?

**Comment by Johann-S** [comment]
IMO the only way to change color is to override ``.carousel-control-next-icon`` and change SVG code for example : 
```css
.carousel-control-next-icon {
    background-image : url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23ff0000' viewBox='0 0 8 8'%3E%3Cpath d='M1.5 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E")
    color: black;
}
```
I changed ``fill`` attribut to ``%23ff0000`` to produce a red chevron (original ``fill`` attribut was ``%23fff``)
