### ISSUE TITLE
[Feature Request]: Prevent new-line in breadcrumbs.

### ISSUE THREAD

**Issue by 6temes** [twbs/bootstrap#21991]
In the way breadcrumbs are currently designed, they tend to generate a newline when the screen is too narrow or the breadcrumb is too long:

I posted the [question][0] in StackOverflow and I got a great [answer][1] that solves the problem.

Basically, the idea would be to add this a new beavior called `.no-new-line` and the code would be like this:

```scss
.breadcrumb.no-new-line {
  margin-right: $grid-gutter-width-base / 2;
  overflow-x: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;

  .breadcrumb-item {
    float: none;
  }
}
```

(this SCSS is based on the CSS of the [original author][2])

Would it be possible to include a cleaned-up version of this code in Bootstrap? This feature makes sense in a lot of use cases IMHO.

[0]: http://stackoverflow.com/q/42239096/2995613
[1]: http://stackoverflow.com/a/42239129/2995613
[2]: http://stackoverflow.com/users/1123505/michael-coker

**Comment by mdo** [comment]
I don't think this is something we should automatically enforce for everyone—what if you want it to automatically wrap? I imagine the most straight forward option would be adding a truncation utility (see #19314). We'll get to that one in a future release :).

**Comment by AlessandroVecchi** [comment]
I use simply:
```
.breadcrumb-item { 
  float: none;
  display: inline;
}
```

**Comment by abrambailey** [comment]
I can't figure out how to get this working with any of the supplied code.

**Comment by abrambailey** [comment]
I couldn't fix this problem until adding some explicit width to the breadcrumb li elements. So here's my code, essentially:

```html
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item text-truncate"><a href="#">Home</a></li>
    <li class="breadcrumb-item text-truncate"><a href="#">Library</a></li>
    <li class="breadcrumb-item text-truncate active" aria-current="page">Data</li>
  </ol>
</nav>
```

```css
ol.breadcrumb li:first-child:nth-last-child(1) {
  max-width: 100%;
}

ol.breadcrumb li:first-child:nth-last-child(2),
ol.breadcrumb li:first-child:nth-last-child(2) ~ li {
    max-width: 50%;
}

ol.breadcrumb li:first-child:nth-last-child(3),
ol.breadcrumb li:first-child:nth-last-child(3) ~ li {
    max-width: 33.3333%;
}

ol.breadcrumb li:first-child:nth-last-child(4),
ol.breadcrumb li:first-child:nth-last-child(4) ~ li {
    max-width: 25%;
}
```
