### ISSUE TITLE
Cannot Override $carousel-control-color in _custom.scss

### ISSUE THREAD

**Issue by aprildh31** [twbs/bootstrap#22120]
Commit 85531fd9fbc482f2010aca56f5ff7fb8be3d342e breaks overriding the carousel control color (`$carousel-control-color`) in _custom.scss. Carousel control color can only be changed in _variables.scss. The function `str-replace()` appears to evaluated before variables are read from _custom.scss.

**Comment by mdo** [comment]
At this point I'm most inclined to simply remove `_custom.scss`. It's never going to solve very problem for folks, nor will it work in every situation.

**Comment by vanduynslagerp** [comment]
If you define your overwrite in `_custom.scss` without the `!default`, for example `$carousel-control-color: green` in `_custom.scss`, then it produces the css:

```css
.carousel-control-prev-icon {
  background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='green' viewBox='0 0 8 8'%3E%3Cpath d='M4 0l-4 4 4 4 1.5-1.5-2.5-2.5 2.5-2.5-1.5-1.5z'/%3E%3C/svg%3E");
}
```

The `green` color has been applied.
