### ISSUE TITLE
Question regarding media-breakpoint-between

### ISSUE THREAD

**Issue by ksrb** [twbs/bootstrap#22245]
I was trying out `@media-breakpoint-between` but it doesn't behave the way I expected.

**Given:**
```scss
@include media-breakpoint-between(sm, md) {
  div {
    background: tomato;
  }
}
```
**Actual:**
```css
@media (min-width: 576px) and (max-width: 991px) {
  div {
    background: tomato;
  }
}
```

**Expected:**
```css
@media (min-width: 576px) and (max-width: 768px) {
  div {
    background: tomato;
  }
}
```

Example with extracted code in [sassmeister](http://www.sassmeister.com/gist/dff16afd7bdd91b8c89e68f33138b0a4).

Respective files:

- https://github.com/twbs/bootstrap/blob/78fc4d23fcefe31397444b75f43728c38e13c590/scss/mixins/_breakpoints.scss
- https://github.com/twbs/bootstrap/blob/78fc4d23fcefe31397444b75f43728c38e13c590/scss/_variables.scss#L181-L187

**Comment by ksrb** [comment]
FYI is breakpoint-max is changed from:
```scss
@function breakpoint-max($name, $breakpoints: $grid-breakpoints) {
  $next: breakpoint-next($name, $breakpoints);
  @return if($next, breakpoint-min($next, $breakpoints) - 1px, null);
}
```
To:
```scss
@function breakpoint-max($name, $breakpoints: $grid-breakpoints) {
  @return if($name, breakpoint-min($name, $breakpoints) - 1px, null);
}
```
It works as expected.

**Comment by mdo** [comment]
That's not the right fix I think @ksrb; that doesn't snag the next breakpoint at all. I think what we need to do is clear up the nested mixins on the `between` mixin and then not reuse that one for the `only` mixin. Doesn't make sense to map those to one another.

Change I'm suggesting is explicit min and max mapping:

```scss
// source
@mixin media-breakpoint-between($lower, $upper, $breakpoints: $grid-breakpoints) {
  $min: breakpoint-max($lower, $breakpoints);
  $max: breakpoint-max($upper, $breakpoints);

  @media (min-width: $min) and (max-width: $max) {
    @content;
  }
}

@mixin media-breakpoint-only($name, $breakpoints: $grid-breakpoints) {
  $min: breakpoint-min($name, $breakpoints);
  $max: breakpoint-max($name, $breakpoints);

  @media (min-width: $min) and (max-width: $max) {
    @content;
  }
}

// examples
.test {
  @include media-breakpoint-between(sm, md) {
    background: red;
  }
}
.test2 {
  @include media-breakpoint-only(sm) {
    background: blue;
  }
}
```

Which outputs this:

```css
@media (min-width: 767px) and (max-width: 991px) {
  .test {
    background: red;
  }
}

@media (min-width: 576px) and (max-width: 767px) {
  .test2 {
    background: blue;
  }
}
```
