### ISSUE TITLE
Paragraph tag margins

### ISSUE THREAD

**Issue by hypeJunction** [twbs/bootstrap#22290]
I'd like to propose that you don't add margins to only-child paragraphs, they usually end up having extra unwanted bottom margin that we have to remove in our styles:

```css
p:only-child {
    margin-bottom: 0;
}
```
