### ISSUE TITLE
Border hidden in input groups w/ feedback state

### ISSUE THREAD

**Issue by claudioalmeiida** [twbs/bootstrap#22367]
When I add any of the has-danger, has-warning or has-success classes in an input group, it looks like this, missing the right border.

<img width="399" alt="image" src="https://cloud.githubusercontent.com/assets/942899/24771572/19628830-1adc-11e7-96d6-0ef5f46291c3.png">

**Comment by peterblazejewicz** [comment]
You should see css generated from:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_forms.scss#L28-L32
```css
.has-danger .input-group-addon {
  color: #d9534f;
  border-color: #d9534f;
  background-color: #fdf7f7;
}
```
Mind posting JSBIN sample?
