### ISSUE TITLE
Navbar-expand and paddings

### ISSUE THREAD

**Issue by danijelGombac** [twbs/bootstrap#22471]
Bootstrap v4dev

I don't know if I understood, .navbar-expand is used when you want the .navbar is always expanded?

I try this way, but when i use .navbar-expand, the paddings are removed from container and the content is larger then the other part.

https://jsbin.com/zoyuqiteri/edit?html,output

**Comment by mdo** [comment]
Yes, we toggle the padding and margin a bit to make the navbar behave as we want it to. As I recall there wasn't much of a way around it.

**Comment by alanstratos** [comment]
I don't know if this problem has been addressed but this happens with all other expands as well (navbar-expand-sm, navbar-expand-md, lg, etc)

In this particular case, these lines are causing this problem:
`
.navbar-expand > .container,
.navbar-expand > .container-fluid {
    padding-right: 0;
    padding-left: 0;
}
`
Which can be solved by wrapping them only in the media they should be valid
`
@media (max-width: 585px) {
    .navbar-expand > .container,
    .navbar-expand > .container-fluid {
        padding-right: 0;
        padding-left: 0;
    }
}
`

All other expands are fixed by including them inside this media as well.

As of now, for example, navbar-expand-md loses its .container padding from 585px to 767px screens.
This is because of this code
`
@media (max-width: 767px) {
  .navbar-expand-md > .container,
  .navbar-expand-md > .container-fluid {
    padding-right: 0;
    padding-left: 0;
  }
}
`

Simply by adjusting its max-width to 585 (xs screen) solves this problem.
I don't seem to understand the reason behind toggling the padding like this, as navbars are still behaving as expected after this fix. This is the reason this seems like a problem. Am I missing something? @mdo

**Comment by maniqui** [comment]
I've noticed this same issue. 
In case it's not clear what's happening, here is an screenshot of the issue happening on Bootstrap v4-alpha website. 
As you can see, the `container` inside `navbar-toggleable` (or `navbar-expand` if you are in `v4-dev`),  is missing its horizontal padding, and so, the Bootstrap brand and the hamburguer menu are misaligned. 

![image](https://user-images.githubusercontent.com/333695/27752422-490c3e00-5db7-11e7-9a49-c3e6a3efa9c0.png)

As others, I also don't understand the reason behind toggling the padding.

The issue is both present in `alpha-6` release and `v4-dev` branch.

**Comment by maniqui** [comment]
For anyone compiling Bootstrap from SASS sources, you can restore the horizontal padding on `.navbar-expand-*` elements by monkeypatching your code in a custom SASS file (imported below `_navbar.scss`) that generates the very same `.navbar-expand-*` classes, allowing those classes to have more precedence.

In your custom SASS file, you add:

```scss
// Generate series of `.navbar-expand-*` responsive classes for configuring
// where your navbar collapses.
.navbar-expand {
  @each $breakpoint in map-keys($grid-breakpoints) {
    $next: breakpoint-next($breakpoint, $grid-breakpoints);
    $infix: breakpoint-infix($next, $grid-breakpoints);

    &#{$infix} {
      @include media-breakpoint-down($breakpoint) {
        > .container,
        > .container-fluid {
          padding-right: $navbar-padding-x;
          padding-left: $navbar-padding-x;
        }
      }
    }
  }
}
```

As you can see, it's the very same code taken from `bootstrap/scss/_navbar.css` but only monkeypatching the relevant parts to restore the horizontal padding (using `$navbar-padding-x` variable).
