### ISSUE TITLE
Modal pointer events

### ISSUE THREAD

**Issue by tinchou** [twbs/bootstrap#22493]
I'd like to suggest adding pointer events to the Modal component.

The addition would be something similar to:

```scss
.modal {
    pointer-events: none;

    .modal-dialog {
        pointer-events: auto;
    }
}
```

The idea is to allow click events to fall through to the `modal-backdrop`, which is covered by `modal`. This is very important to allow people not using the JS library to build on top of Bootstrap.

In my case, I'm using Angular and without that bit I can't bind a click handler to close the modal when tapping the backdrop:

```html
<div class="modal fade show">
    <div class="modal-dialog" role="document">
        <!-- content -->
    </div>
</div>
<div class="modal-backdrop fade show" *ngIf="show" (click)="closeModal()"></div>
```

Thanks!

**Comment by patrickhlauke** [comment]
You'd probably even want to go a step further and use
```
.modal {
    pointer-events: none;

    .modal-content {
        pointer-events: auto;
    }
}
```
`.modal-content` rather than `.modal-dialog`

**Comment by tinchou** [comment]
Just realized your suggestion doesn't scroll. I'm using `modal-dialog` instead of `modal` now:

```scss
.modal-dialog {
    pointer-events: none;

    .modal-content {
        pointer-events: auto;
    }
}
```
