### ISSUE TITLE
The latest Chrome update adds underline to <abbr> elements

### ISSUE THREAD

**Issue by JamesDonnelly** [twbs/bootstrap#22562]
Chrome v58 (on Windows, at least) has introduced the following default styling to `<abbr>` elements:

```css
abbr[title], acronym[title] {
  text-decoration: underline dotted;
}
```

Bootstrap sticks a dotted `border-bottom` on `<abbr>` elements:

```css
abbr[title] {
  border-bottom: 1px dotted;
}
```

This leads to a double-border effect being applied to these elements:

![Example](http://i.imgur.com/9reMhYA.png)

I've overwritten this by simply setting the `text-decoration` to `none`, but this is probably something Bootstrap will want to incorporate itself.
