### ISSUE TITLE
.input-group .form-control has width: 1%

### ISSUE THREAD

**Issue by hnguyenec** [twbs/bootstrap#22629]
I have been using bootstrap4.alpha.4 with [ng2.angular-formly.com](url) and it renders correctly

Recently, I have upgraded to alpha.6
For Input with addon, input is rendered very narrow, inspect that element with DevTool, I can see 
```css
.input-group .form-control {
width: 1%
}
```

![image](https://cloud.githubusercontent.com/assets/635548/26103911/03901ed8-3a7f-11e7-81f5-606c927093a0.png)
