### ISSUE TITLE
Overlapping of navbar-toggler & navbar-brand on mobile

### ISSUE THREAD

**Issue by thykes** [twbs/bootstrap#22817]
The demo navbar when a container is added to it is centers both the navbar-brand link and the navbar-toggler in mobile responsive site. 

![screen shot 2017-06-13 at 4 43 59 pm](https://user-images.githubusercontent.com/5092546/27106101-925967da-5057-11e7-8205-fe6e43d3d02c.png)

https://v4-alpha.getbootstrap.com/examples/navbars/

**Comment by rafalp** [comment]
Please use search function, this issue was reported many times and it's fixed in next release for quite a while too.

**Comment by afuno** [comment]
Temporary solution. If you can not sleep :)

```scss
@media (max-width: 575px) {
  .navbar.main {
    .container {
      margin-left: 0;
      margin-right: 0;
    }
  }
}
```
