### ISSUE TITLE
margin in .h1-.h5 classes in v4

### ISSUE THREAD

**Issue by wojtask9** [twbs/bootstrap#22933]
Currently .h1-.h5 classes adds `margin-bottom`. 

In most cases people must add `mb-0` class to properly vertical align element (for example in card header).

Will not it be better if `margin-bottom` is gone form .h1-.h5 classes?

If `margin-bottom` will gone then you can use these classes to control icon size or font size of any element without adding additional class `mb-0`

**Comment by hokiecoder** [comment]
Don't forget that it is not only the `.h*` classes, but also the `<h*>` elements. And, there is `<h6>`/`.h6`, too!

But to the point of your suggestion, I agree with **afuno** that in most, if not all, situations of using a header element/class, the bottom margin is a good thing. In your example of the card header, you should either be using a `<h*>` element with the `.card-header` class or another element (e.g. `<div>`) with `.h*` and `.card-header` classes...both cases set the bottom margin to 0. Without pouring through all the source code, I'd be willing to bet that most situations where the bottom margin is inappropriate for a header element there is CSS there to remove it.

Aside from the card header, can you think of a different case where the bottom margin exists but probably shouldn't?

**Comment by mdo** [comment]
Bottom margin will stay for consistent, clear spacing in bodies of text.

**Comment by wojtask9** [comment]
@hokiecoder 

Maybe I was not to specific.
If I want margins I use h* tags. If I want only control "size" I use .h* classes.
In general I agree with you.
My concern about .h* classes is about that .h* classes have margin-bottom only and it's hard to vertical align elements.

**Comment by mdo** [comment]
The `<h*>` elements and `.h*` classes share the same exact styles:

```scss
h1, h2, h3, h4, h5, h6,
.h1, .h2, .h3, .h4, .h5, .h6 {
  margin-bottom: $headings-margin-bottom;
  font-family: $headings-font-family;
  font-weight: $headings-font-weight;
  line-height: $headings-line-height;
  color: $headings-color;
}

h1, .h1 { font-size: $h1-font-size; }
h2, .h2 { font-size: $h2-font-size; }
h3, .h3 { font-size: $h3-font-size; }
h4, .h4 { font-size: $h4-font-size; }
h5, .h5 { font-size: $h5-font-size; }
h6, .h6 { font-size: $h6-font-size; }
```
