### ISSUE TITLE
Customize doesn't remove default btn-default border color

### ISSUE THREAD

**Issue by CatStarwind** [twbs/bootstrap#23215]
When using http://getbootstrap.com/customize/ if you change the @btn-default-border the outputted css files still have the original `border-color: #ccc;` line which overrides the selected color.

e.g.
```css
.btn-default {
    background-image: -webkit-linear-gradient(top, #fff9f7 0, #ffcbba 100%);
    background-image: -o-linear-gradient(top, #fff9f7 0, #ffcbba 100%);
    background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0, #fff9f7), to(#ffcbba));
    background-image: linear-gradient(to bottom, #fff9f7 0, #ffcbba 100%);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#fffff9f7', endColorstr='#ffffcbba', GradientType=0);
    filter: progid:DXImageTransform.Microsoft.gradient(enabled = false);
    background-repeat: repeat-x;
    border-color: #ffc3b0;
    text-shadow: 0 1px 0 #fff;
    border-color: #ccc
}
```
