### ISSUE TITLE
V4.beta Dropdown menu focus/hover style constrast too low for accessibility

### ISSUE THREAD

**Issue by tmorehouse** [twbs/bootstrap#23329]
The current `:focus` / `:hover` styling is almost impossible to see (on some screens) as it is a very subtle change.

I would recommend that the  background be darkened slightly to make it better for keyboard-only users to know which `.dropdown-item` they have highlighted.

In this screen shot, I have `Another Item` focused, and at quick glance (without straining my eyes) I can't tell which menu item is focused:
![image](https://user-images.githubusercontent.com/2781561/29220721-6246c54c-7e92-11e7-93a1-19ab486119c9.png)

Doing the same thing, but adjusting the background color from `background-color:#f8f9f8` to `background-color:#e8e9e8` makes a big difference in being able to tell which menu item has focus:

![image](https://user-images.githubusercontent.com/2781561/29221029-8d27e1aa-7e93-11e7-8944-d80b92e3eaac.png)

**Comment by tmorehouse** [comment]
Our current workaround is to darken the background:

```css
.dropdown-item:focus:not(.active),
.dropdown-item:hover:not(.active) {
    /* @See https://github.com/twbs/bootstrap/issues/23329 */
    box-shadow: inset 0px 0px 400px 110px rgba(0, 0, 0, .09);
}

.dropdown-item.active {
    box-shadow: initial;
}
```
