### ISSUE TITLE
v4 form input issues

### ISSUE THREAD

**Issue by josephzidell** [twbs/bootstrap#23347]
Two separate issues noticed on Windows 10, in Chrome 60, Firefox 54.0.1, Edge 38. I noticed these in the docs

1. A `<select class="form-control form-control-lg">` needs more height
![screenshot 2017-08-11 09 58 12](https://user-images.githubusercontent.com/1812443/29237470-c275819c-7eec-11e7-9ce2-cb85992f215b.png)

2. Text color is inconsistent between a disabled input vs. select
![screenshot 2017-08-11 10 01 06](https://user-images.githubusercontent.com/1812443/29237475-d9f16fe8-7eec-11e7-8fd6-5e84f16039ea.png)

**Comment by Yeswanth-JG** [comment]
I came to report this. For `select element` below styles might update as below...

### Base Style for `form-control-lg`
```css
.form-control-lg, .input-group-lg>.form-control,
.input-group-lg>.input-group-addon,
.input-group-lg>.input-group-btn>.btn {
    padding: 0.6rem 1rem; /* updated */
    font-size: 1.15rem; /* updated */
    line-height: 1.4; /* updated */
    border-radius: .3rem;
}
```
### height update for `form-control`
```css
select.form-control:not([size]):not([multiple]) {
    height: calc(2.45rem + 2px);
}
```
### height update for `form-control-lg`
```css
.input-group-lg>.input-group-btn>select.btn:not([size]):not([multiple]),
.input-group-lg>select.form-control:not([size]):not([multiple]),
.input-group-lg>select.input-group-addon:not([size]):not([multiple]), select.form-control-lg:not([size]):not([multiple]) {
    height: calc(3.1rem + 2px);
}
```

#### System Details --
Win 7
Chrome - 59.0.3071.115

Above changes update the controls as below.
![image](https://user-images.githubusercontent.com/5590842/29238011-5b47546c-7f48-11e7-98bd-ab656d87f856.png)
