### ISSUE TITLE
sticky-top rule seems broken in Beta

### ISSUE THREAD

**Issue by tiesont** [twbs/bootstrap#23346]
After upgrading to version 4 Beta, the sticky-top class stopped working for me in Firefox and Chrome. Neither seem to like the webkit check in the `@supports` rule, to wit:

This works:
```css
@supports (position: sticky) {
  .sticky-top {
    position: -webkit-sticky;
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
```
This does not:
```css
@supports ((position: -webkit-sticky) or (position: sticky)) {
  .sticky-top {
    position: -webkit-sticky;
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
```

The same markup worked like a champ in Alpha 6, so I assume this is a Beta change. Swapping the order of the rule checks and/or removing the outermost parentheses did not seem to affect anything. 

I will try to test more later, but for now, this is happening on Windows 10, Firefox 54.0.1 and Chrome 60.0.3112.90.
