### ISSUE TITLE
Duplicated rule in .container-fluid class

### ISSUE THREAD

**Issue by Theremsoe** [twbs/bootstrap#23397]
In branch [v4-dev](https://github.com/twbs/bootstrap/tree/v4-dev/scss), file [_grid.scss](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_grid.scss#L18), the class `.container-fluid` has the rule `width`, but the mixin `make-container()` also contains the `width` rule.

The output is the next:
````css
.container-fluid {
    width: 100%;
    margin-right: auto;
    margin-left: auto;
    padding-right: 15px;
    padding-left: 15px;
    width: 100%; // Duplicated rule
}
````

Tanks
