### ISSUE TITLE
Idea: add an optional prefix namespace to improve compatibility

### ISSUE THREAD

**Issue by andresgalante** [twbs/bootstrap#23455]
While extending bootstrap I always find myself in a position where I wish bootstrap variables and classnames were namespace prefixed.

That namespace prefix can be a variable and empty by default for backward compatibility, for example:

```scss
$bs-namespace: "bs-";

.#{$bs-namespace}btn {
  ...
}
```

This would be a large overhead for contributors, but I think it's worth it.

What do you think?
