### ISSUE TITLE
feature: line-clamp utility

### ISSUE THREAD

**Issue by ruscon** [twbs/bootstrap#23559]
How about line-clamp utility ?
http://caniuse.com/#search=line-clamp

scss/mixins/_line-clamp.scss

```scss
//https://stackoverflow.com/a/26634773
@mixin line-clamp($numLines: 1, $lineHeight: 1.5) {
  overflow: hidden;
  text-overflow: -o-ellipsis-lastline;
  text-overflow: ellipsis;
  display: block;
  /* autoprefixer: off */
  display: -webkit-box;
  -webkit-line-clamp: $numLines;
  -webkit-box-orient: vertical;
  max-height: $numLines * $lineHeight + unquote('rem');
}
```

scss/utilities/_line-clamp.scss

```scss
@each $breakpoint in map-keys($grid-breakpoints) {
  @include media-breakpoint-up($breakpoint) {
    $infix: breakpoint-infix($breakpoint, $grid-breakpoints);

    @each $size, $length in $spacers {
      .line-clamp#{$infix}-#{$size}  {
        @include line-clamp($size);
      }
    }
  }
}

```
