### ISSUE TITLE
Wrong credit for "clearfix"

### ISSUE THREAD

**Issue by thierryk** [twbs/bootstrap#23578]
The [doc about clearfix](https://github.com/twbs/bootstrap/blob/620257456ed0685cae6b6ff51d2ab1e37f02a4fa/docs/4.0/utilities/clearfix.md) says:

> Easily clear floats by adding .clearfix to the parent element. Utilizes [the micro clearfix](http://nicolasgallagher.com/micro-clearfix-hack/) as popularized by Nicolas Gallagher. Can also be used as a mixin.

but the [clearfix rule](https://github.com/twbs/bootstrap/blob/890c6041f3bf70b76244611916bc1286a8150bd5/scss/mixins/_clearfix.scss) in v4 looks like this:

```css
@mixin clearfix() {
  &::after {
    display: block;
    clear: both;
    content: "";
  }
}
```

which resembles more to the "clearfix" rule from [this article](http://cssmojo.com/the-very-latest-clearfix-reloaded/) on [cssmojo.com](http://cssmojo.com):

```css
.clearfix:after {
  content: "";
  display: block;
  clear: both;
}
```
