### ISSUE TITLE
4 beta 1, scss @import generates a different file than the original on getbootstrap.com

### ISSUE THREAD

**Issue by johnunclesam** [twbs/bootstrap#23629]
I'm using `node-sass` for my project.

You can try in a simple *style.scss* file with both version (alpha6 and beta):

`@import "./node_modules/bootstrap/scss/bootstrap";`

then type this:

`node-sass style.scss style.css`

and you'll have a different css for the .btn class:

**- original one on getbootstrap.com (https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.css)**

```css
.btn {
  display: inline-block;
  font-weight: normal;
  text-align: center;
  white-space: nowrap;
  vertical-align: middle;
  -webkit-user-select: none;
     -moz-user-select: none;
      -ms-user-select: none;
          user-select: none;
  border: 1px solid transparent;
  padding: 0.5rem 0.75rem;
  font-size: 1rem;
  line-height: 1.25;
  border-radius: 0.25rem;
  transition: all 0.15s ease-in-out;
}
```

**- generated one**

```css
.btn {
  display: inline-block;
  font-weight: normal;
  text-align: center;
  white-space: nowrap;
  vertical-align: middle;
  user-select: none;
  border: 1px solid transparent;
  padding: 0.5rem 0.75rem;
  font-size: 1rem;
  line-height: 1.25;
  border-radius: 0.25rem;
  transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
}
```

Look at this:

```css
transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
```

Why this differences?

**With this problem "disabled" property on a button has no transition anymore** as you can see here: https://plnkr.co/edit/LSeKKSaB2Lk2JMtoFi9K?p=preview
