### ISSUE TITLE
Sass issue using color function 

### ISSUE THREAD

**Issue by craigpotter** [twbs/bootstrap#23690]
When looking at [Bootstrap Sass Options](https://getbootstrap.com/docs/4.0/getting-started/options/), it gives the example 
``` scss 
// From the Sass map with our `color()` function
.beta { color: color("purple"); }
```
This doesn't work for me.
After debugging and putting lots of @debug statements in my own code and the BS4 _function.scss, I noticed that wrapping the color name in quotes stopped it working for me. It just returns null. 

``` scss 
// From the Sass map with our `color()` function
.beta { color: color(purple); }
```
This version works for me. 
Is any one else having this problem ? 

- Windows 10 
- Sass complied with Gulp-Sass
