### ISSUE TITLE
Minimal CSS for JavaScript components

### ISSUE THREAD

**Issue by DannyJoris** [twbs/bootstrap#23819]
Would you ever consider including CSS or Sass files that contain just the minimum amount of styling for JavaScript components?

Currently you can conditionally include Sass files per component, but often when I'm working off an existing design I need to implement, I would have to override all those styles somehow, which includes borders, shadows, etc. If I could include just the bare minimum, I may save some time.

I went ahead and created minimal versions for each component, just to see what it would look like:

- `alert.js`: https://codepen.io/DannyJoris/pen/NvLGJW/
- `button.js`: https://codepen.io/DannyJoris/pen/mMGeNv
- `carousel.js`: https://codepen.io/DannyJoris/pen/rzZxxz
- `collapse.js`: https://codepen.io/DannyJoris/pen/yoxoag
- `dropdown.js`: https://codepen.io/DannyJoris/pen/jLvbzO
- `modal.js`: https://codepen.io/DannyJoris/pen/YxOYNB
- `popover.js`: https://codepen.io/DannyJoris/pen/JyapdV
- `scrollspy.js`: https://codepen.io/DannyJoris/pen/ZJwdbv (can be stripped down more)
- `tab.js`: https://codepen.io/DannyJoris/pen/brxKPK
- `tooltip.js`: https://codepen.io/DannyJoris/pen/RZYyrv

Let me know what you think.

**Comment by Johann-S** [comment]
Bootstrap allow a lot of customisation with including `_custom.scss` file, so you'll be able to create a custom theme with the minimal css you need

**Comment by DannyJoris** [comment]
That's fair. I guess I was just looking at Bootstrap to "enhance" parts of custom projects. I'll look into it further.

**Comment by IamManchanda** [comment]
@Johann-S ??

```scss
$minimal-styling: false !default;

@mixin alert {
  @if ($minimal-styling) {
    /**
     * Minimal Styling here
     */
  } @else {
    /**
     * Regular Styling here
     */
  }
}
```
