### ISSUE TITLE
Remove borders in the "accordion"

### ISSUE THREAD

**Issue by SamThilmany** [twbs/bootstrap#23836]
At the moment the accordion doesn't look very good. It isn't very difficult to fix this, but I think it could be a nice feature to include in one of the next updates.

Here is how the accordion currently looks ([BS4 Documentation](https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example)):

![Accordion](http://i.imgur.com/uH1JmpP.jpg)

If the card is neither the first, nor the last one in the list, there should be no border radius. Moreover one of the borders (top or bottom) should be set to `0px`.
This was already kind of made for [vertical button groups](https://getbootstrap.com/docs/4.0/components/button-group/#vertical-variation).

This is my proposal for a fix:

```css
.card:not(:first-of-type):not(:last-of-type) {
    border-bottom: none;
    border-radius: none;
}

.card:first-of-type {
    border-bottom-left-radius: none;
    border-bottom-right-radius: none;
}

.card:last-of-type {
    border-top-left-radius: none;
    border-top-right-radius: none;
}

```

This results in a much nicer accordion:

![Accordion fixed](https://i.imgur.com/czfGW3y.jpg)
