### ISSUE TITLE
Responsive Border Utilities

### ISSUE THREAD

**Issue by LarryAzevedo** [twbs/bootstrap#23892]
It would be great to be able to do something like this:
`<div class="border-top border-lg-top-0 border-lg-left">...</div>`
So in this example, you'll have:

1. a 1px top border from xs to md
2. a 1px left border from lg to xl (the top border get's removed)

Here's what the SASS might look like:

`@each $breakpoint in map-keys($grid-breakpoints) {
	@include media-breakpoint-up($breakpoint) {
		$infix: breakpoint-infix($breakpoint, $grid-breakpoints);

		.border#{$infix}-top-0{		border-top: 0 !important;}
		.border#{$infix}-right-0{	border-right: 0 !important;}
		.border#{$infix}-bottom-0{	border-bottom: 0 !important;}
		.border#{$infix}-left-0{	border-left: 0 !important;}
		.border#{$infix}-top{		border-top: 1px solid $gray-200 !important;}
		.border#{$infix}-right{		border-right: 1px solid $gray-200 !important;}
		.border#{$infix}-bottom{	border-bottom: 1px solid $gray-200 !important;}
		.border#{$infix}-left{		border-left: 1px solid $gray-200 !important;}
		.border#{$infix}-x{			border-left: 1px solid $gray-200 !important; border-right: 1px solid $gray-200 !important;}
		.border#{$infix}-y{			border-top: 1px solid $gray-200 !important; border-bottom: 1px solid $gray-200 !important;}
	}
}`

**Comment by mdo** [comment]
No plans to make these responsive.

**Comment by tmorehouse** [comment]
Too bad, as I have a use case for adding/removing borders based on responsive positioning.

**Comment by spaceemotion** [comment]
Since I had the same issue today, here's an updated version of @LarryAzevedo's proposal that uses the proper BS4 variables:

```scss
@each $breakpoint in map-keys($grid-breakpoints) {
  @include media-breakpoint-up($breakpoint) {
    $infix: breakpoint-infix($breakpoint, $grid-breakpoints);

    .border#{$infix}-top-0 {    border-top: 0 !important; }
    .border#{$infix}-right-0 {  border-right: 0 !important; }
    .border#{$infix}-bottom-0 { border-bottom: 0 !important; }
    .border#{$infix}-left-0 {   border-left: 0 !important; }
    .border#{$infix}-top {      border-top: $border-width solid $border-color !important; }
    .border#{$infix}-right {    border-right: $border-width solid $border-color !important; }
    .border#{$infix}-bottom {   border-bottom: $border-width solid $border-color !important; }
    .border#{$infix}-left {     border-left: $border-width solid $border-color !important; }

    .border#{$infix}-x {
      border-left: $border-width solid $border-color !important;
      border-right: $border-width solid $border-color !important;
    }

    .border#{$infix}-y {
      border-top: $border-width solid $border-color !important;
      border-bottom: $border-width solid $border-color !important;
    }
  }
}
```
