### ISSUE TITLE
Dropmenu caret is wrapping in a strange way on the navbar

### ISSUE THREAD

**Issue by andresgalante** [twbs/bootstrap#23932]
It only happens on a very specific width here:
http://getbootstrap.com/docs/4.0/examples/navbars/

Plus it pushes the search bar out. Play with it and you'll see it.

![screen shot 2017-09-12 at 9 59 13 pm](https://user-images.githubusercontent.com/1832037/30354871-d31fbba2-9805-11e7-9b9e-498cd0598109.png)

If nobody wants to take this one, I'll probably work on it this week.

**Comment by andresgalante** [comment]
I noticed that if I remove the dropmenu the search box will resize itself, but when the drop menu is present it falls out of the navbar box.

**Comment by andresgalante** [comment]
After looking for it I found that the problem is here:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_forms.scss#L325

The fact that the input is not a 100% on larger devices, pushes it outside the navbar container because it doesn't wrap here:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L151

![screen shot 2017-09-13 at 7 18 38 am](https://user-images.githubusercontent.com/1832037/30372567-a13f3cb2-9854-11e7-9f9d-fab8ca8c6e17.png)

If anyone wants to take this one please take really good care of not breaking forms while fixing it 😄

**Comment by andresgalante** [comment]
The dropdown words wraps too:

![screen shot 2017-09-14 at 9 02 36 am](https://user-images.githubusercontent.com/1832037/30428854-8b9e6ef0-992b-11e7-89e2-56d664a6ed63.png)

**Comment by mdo** [comment]
Yeah not much we can do about this I think :).

**Comment by andresgalante** [comment]
👍 I agree, I have actually been looking more closely to the navbar since then and the flex behaviour is correct. I'll close it. Thanks for reviewing it.

**Comment by jbeard4** [comment]
Here is how I worked around this:

```css
   .dropdown-toggle::after{
      font-family: 'FontAwesome' !important;
      content: "\00a0\00a0\f0d7" !important;
      margin-left: 0 !important;
      vertical-align: 0 !important;
      border: none !important; 
      display: inline !important;
      width: auto !important;
      height: auto !important;
   } 
```

Or without fontawesome:

.dropdown-toggle::after {
    content: "\00a0\00a0\25BC" !important;
    margin-left: 0 !important;
    vertical-align: 0 !important;
    border: none !important;
    display: inline !important;
    width: auto !important;
    height: auto !important;
}

Hope this helps. Thanks.
