### ISSUE TITLE
Minor display issue with labels inside dropdowns in an inline-form

### ISSUE THREAD

**Issue by mortenn** [twbs/bootstrap#23978]
Placing a dropdown menu inside an inline form, labels within the menu get centered, leading to a jumbled layout.

I added this CSS to fix it on my application:
```css
.form-inline .dropdown-menu .form-check-label {
	justify-content: left !important;
	padding-left: 1rem !important;
}
```
