### ISSUE TITLE
v4: Can't set $font-size-base to a pixel value

### ISSUE THREAD

**Issue by Jakobud** [twbs/bootstrap#23982]
Currently, `$font-size-base` is defined as:

```
$font-size-base: 1rem !default;
```

If you attempt to define your base font size using pixels, for example:

```
$font-size-base: 14px;
```

Then SASS will not compile because of `Incompatible units: 'rem' and 'px'.` in various calculations. It seems like you should be able to define a font size using pixels. If you are working with a designer who is using Sketch or something, you can sure bet that they have their font's defined in pixels. A designer is not going to have any clue what a `rem` is.

**Comment by andresgalante** [comment]
Hi @Jakobud you should always avoid doing fonts in px, it's not good for accessibility.

Let me help you with your designers using sketch issues :)

You can set up a function that transform px to rem like this:

```scss
$font-size-root: 16; // no units, you assume the font size base of most browsers is 16px.

@function strip-unit($num) {
    @return $num / ($num * 0 + 1);
}

// prem stands for  px to rem.
@function prem($pxval, $base: $font-size-root) {
    @return strip-unit($pxval) / $base * 1rem;
}
```

Then if the designers set a 36px font size, you use it like this:

```scss
.class-name {
    font-size: pem(36); // Returns 2em (or 36px)
}
```

This is a flexible solution that will let you use px and your designers px. We are using it at our project with successful results.

hope it helps!
