### ISSUE TITLE
Input success tick has pointy ends.

### ISSUE THREAD

**Issue by t-p-l-k** [twbs/bootstrap#24148]
Svg tick used in successfully validated inputs is incorrect geometrically.
http://v4-alpha.getbootstrap.com/components/forms/#examples
```css
.has-success .form-control-success {
  background-image: url(data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' v… 1.4 3.4-3.8c.6-.63 1.6-.27 1.2.7l-4 4.6c-.43.5-.8.4-1.1.1z'/%3E%3C/svg%3E);
}
```
![image](https://user-images.githubusercontent.com/20531968/30919664-bbc72282-a3aa-11e7-918b-637476b44751.png)

If that's not intended I can create a PR with updated svg.
