### ISSUE TITLE
Too strong selectors

### ISSUE THREAD

**Issue by joneff** [twbs/bootstrap#24140]
The following selector Is a notch too strong (0, 2, 1) and overrides normal class names:

https://github.com/twbs/bootstrap/blob/6dd3d91768227a7ac03a63f8e47eacae99be8892/scss/_reboot.scss#L208-L220

It could be

```scss
a[name]:not([href]):not([tabindex]): {
  color: inherit;
  text-decoration: none;


  @include hover-focus {
    color: inherit;
    text-decoration: none;
  }


  &:focus {
    outline: 0;
  }
}
```

Note: Updated snippet to better reflect the purpose of the styling i.e. named anchors. Original selector was `a:not([href]):not([tabindex]):not([class])`
