### ISSUE TITLE
the same type @media{} one coming immediately after the other

### ISSUE THREAD

**Issue by VeX78rus** [twbs/bootstrap#24269]
it was a mistake or it makes sense:

```css
@media (min-width:768px){.navbar{border-radius:4px}}@media (min-width:768px){.navbar-header{float:left}}
```

v.3.3.7
