### ISSUE TITLE
box-sizing best practice

### ISSUE THREAD

**Issue by Dunexus** [twbs/bootstrap#24357]
Reading [reboot.css](https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap-reboot.css), I saw you set box-sizing using
```css
*,
*::before,
*::after {
    box-sizing: border-box;
}
```
instead of
```css
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
```

Even if in most cases the first version would works fine, the second one allows devs to reset box-sizing for components designed to work in default box-sizing just by setting `box-sizing : conten-box` on the parent element.

Related article: [Inheriting box-sizing Probably Slightly Better Best-Practice](https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/)

**Comment by andresgalante** [comment]
Hi @Dunexus this is smart! (not surprisingly since it's coming from Chris Coyer)

**Comment by yuheiy** [comment]
Is `*` necessary for `::before` and `::after`?

**Comment by bkdotcom** [comment]
@yuheiy,  it's not required.   we could save two bytes and just use

```css
*,
::before,
::after {
    box-sizing: border-box;
}
```
