### ISSUE TITLE
appearence:none (need webkit prefix ?)

### ISSUE THREAD

**Issue by jipexu** [twbs/bootstrap#24372]
Hi
in V4 dev (with safari, chrome)
for the .custom-select in custom-forms.scss file
we have   appearance: none;
with not webkit prefix :  i get 2 set of select indicator (4 arrows instead 2)

with the prefix all is fine ...

Thanks for some light about this

**Comment by gijsbotje** [comment]
i think you are right: https://caniuse.com/#feat=css-appearance

**Comment by XhmikosR** [comment]
We use autoprefixer, so this *should* be handled there. If not please make an issue there.

**Comment by gijsbotje** [comment]
indeed the dist files contain the prefixed webkit version
for firefox though, i'm not sure it it works (according to caniuse it needs the moz prefix for current version)

**Comment by XhmikosR** [comment]
Like I said, we need an issue reported upstream in autoprefixer. If someone does make an issue, comment here with the link.

**Comment by XhmikosR** [comment]
Or actually, caniuse, since autoprefixer is using their data.

**Comment by jipexu** [comment]
@XhmikosR @gijsbotje  sorry  i am on fog ... and dont understand ..probably i must look for what means autoprefixer ... 
to be more precise the behavior explained is after a compilation (no webkit prefix in the final css)

**Comment by XhmikosR** [comment]
Actually, this is invalid.

I see this in the dist css

```css
.custom-select {
  display: inline-block;
  max-width: 100%;
  height: calc(2.25rem + 2px);
  padding: 0.375rem 1.75rem 0.375rem 0.75rem;
  line-height: 1.5;
  color: #495057;
  vertical-align: middle;
  background: #fff url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 4 5'%3E%3Cpath fill='%23333' d='M2 0L0 2h4zm0 5L0 3h4z'/%3E%3C/svg%3E") no-repeat right 0.75rem center;
  background-size: 8px 10px;
  border: 1px solid #ced4da;
  border-radius: 0.25rem;
  -webkit-appearance: none;
     -moz-appearance: none;
          appearance: none;
}
```
