### ISSUE TITLE
Beta.2 @mixin button-variant is missing a variable for $btn-active-box-shadow

### ISSUE THREAD

**Issue by ernestbofill** [twbs/bootstrap#24535]
Version 4.0.0-beta.2

In "scss/mixins/_buttons.scss" line 47:
```sass
box-shadow: $btn-box-shadow, 0 0 0 $input-btn-focus-width rgba($border, .5);
```

The 2nd shadow doesn't use a variable, therefore it's difficult to customize.

I would like an easy way to customize that shadow.

For now I applied the following override:
```sass
@each $color, $value in $theme-colors {
  .btn-#{$color} {
    &:not([disabled]):not(.disabled):active,
    &:not([disabled]):not(.disabled).active,
    .show > &.dropdown-toggle {
      @if $enable-shadows {
        box-shadow: $btn-active-box-shadow;  // that's the only shadow that I want.
      }
    }
  }
}
```

**Comment by mdo** [comment]
Your code snippet is a little out of date with `v4-dev`. We've replaced that line with this:

```scss
    // Avoid using mixin so we can pass custom focus shadow properly
    @if $enable-shadows {
      box-shadow: $btn-active-box-shadow, 0 0 0 $btn-focus-width rgba($border, .5);
    } @else {
      box-shadow: 0 0 0 $btn-focus-width rgba($border, .5);
    }
```

I don't believe it's possible for us to use a variable here as we're pulling in the `$border` from mixin parameters. There's no way to get that `$border` outside the mixin.
