### ISSUE TITLE
Can't compile the SCSS file

### ISSUE THREAD

**Issue by coldpumpkin** [twbs/bootstrap#24549]
I can't export the SCSS file in scss/bootstrap.scss, it says:

> Error: Invalid CSS after "...lor}: #{$value}": expected "{", was ";"
>         on line 4 of C:/bootstrap-4.0.0-beta.2/scss/_root.scss
>         from line 11 of C:\bootstrap-4.0.0-beta.2\scss\bootstrap.scss
>   Use --trace for backtrace.
> [Finished in 1.0s]

Straight from the downloaded folder, didn't even modify anything.

**Comment by andresgalante** [comment]
Hi @coldpumpkin what do you mean by "export"? compile? Can you please describe the steps to get that error?

**Comment by coldpumpkin** [comment]
Hey. Yes, compile, sorry. Basically I'm doing 

> sass --update something.css --stop-on-error --no-cache --sourcemap=none

**Comment by RandyBooth** [comment]
+1 . Same issue with @coldpumpkin

**Comment by Jas-n** [comment]
If you're not worried about loosing some of the CSS variables, comment out line 4 and 8 of _root.scss then recompile.
Otherwise, add `color-` onto the beginning of these lines to give `--color-#{$color}: #{$value};`

By the looks of things SCSS doesn't like using a SCSS variable for the first part of the CSS variable... if that makes sense.

**Comment by mrsfiggons** [comment]
Having the same issue as well

**Comment by RandyBooth** [comment]
Comment out @import "root"; to fix that for now.

**Comment by andresgalante** [comment]
@XhmikosR Can you please take a look, I can't reproduce the issue using `Sass 3.5.2 (Bleeding Edge)`, I can compile bootstrap.scss and get this:

```css
:root {
  --blue: #007bff;
  --indigo: #6610f2;
  --purple: #6f42c1;
  --pink: #e83e8c;
  --red: #dc3545;
  --orange: #fd7e14;
  --yellow: #ffc107;
  --green: #28a745;
  --teal: #20c997;
  --cyan: #17a2b8;
  --white: #fff;
  --gray: #868e96;
  --gray-dark: #343a40;
  --primary: #007bff;
  --secondary: #868e96;
  --success: #28a745;
  --info: #17a2b8;
  --warning: #ffc107;
  --danger: #dc3545;
  --light: #f8f9fa;
  --dark: #343a40;
}
```
