### ISSUE TITLE
Feature: direction RTL support

### ISSUE THREAD

**Issue by dharmeshpipariya-zz** [twbs/bootstrap#24807]

**Comment by mdo** [comment]
We definitely want to do this soon. The approach should be to generate a separate CSS file, built from `bootstrap-rtl.scss` with an ability to generate our other builds using the same approach if folks want it (no need to provide RTL builds for each one).

We'll need to hear from @Johann-S and @bardiharborow though to see if we need to adjust our JS plugins to account for the direction change. I dunno if Popper supports it off the top of my head.

@twbs/team I'd like this for v4.1 or v4.1—thoughts?

**Comment by XhmikosR** [comment]
Sounds good to me. Feel free to ping me if there are new tools we need to add.

**Comment by Superpencil** [comment]
Popper does not support it currently cc @FezVrasta

**Comment by FezVrasta** [comment]
@Superpencil what do you mean? What should Popper.js to to support RTL?

**Comment by kishorsathe** [comment]
Any tentative date , when it will be release ?

**Comment by PerseusTheGreat** [comment]
Hi,
@mdo, please consider these:
- [Unofficial RTL-ized Bootstrap 4.x ](https://github.com/PerseusTheGreat/bootstrap-rtl)
- [RTL-ized Bootstrap 4.x Examples](https://perseusthegreat.github.io/bs4rtl/)

**Comment by prateem** [comment]
Hi, @mdo 
Given that v4.1 is coming out soon and the ship list for it (#25375) doesn't include this issue, is there any update that can be provided about rtl support?
Thanks!

**Comment by mdo** [comment]
No update to give other than this won't be in v4.1 :).

**Comment by DJafari** [comment]
@mdo rtl support is coming for v4.2 ? :-(

**Comment by nabeel-alalmai** [comment]
@mdo we need rtl support, is it coming in 4.2?

**Comment by mohamedragaey** [comment]
Hello @mdo 
I have an approach for rtl-ltr support that i used on Bootstrap3 and now on bootstrap4 
here in this repo you will find that i took only the scss core files for bootstrap 4 and updated for direction and added my direction.scss file 
and in the build you will find 2 files bootstrap.css & bootstrap-rtl.css 
https://mohamedragaey.github.io/bootstrap-scss-multi-dir/
and here is my build tool included in bootstrap-rtl as npm package 
https://mohamedragaey.github.io/bootstrap4-playground/
if you find it interesting please let me know then i will make a pull request and then go for it .

**Comment by MERamadan** [comment]
4.1.2 is out and RTL is not included too. Can you please give this a priority in the next release, either 4.1.3 or 4.2? This is important for all RTL languages to get in bootstrap 4.

**Comment by typistX** [comment]
cast my vote, too.

**Comment by mkamensky** [comment]
Can someone summarise the RTL issues? I use bootstrap on a bidi site without any problems (flex utils solved most of the problems for me)

**Comment by PerseusTheGreat** [comment]
@mkamensky 
In [forked version](https://github.com/PerseusTheGreat/bootstrap-4-rtl) that I am working on it, there are some issues on SCSS modules & mixins, I tagged those by `//rtl` inside `*-rtl.scss` files.

**Changed SCSS module:**
alert, button group, card, carousel, close, custom form, dropdown, input group, list group, modal, nav, navbar, pagination, popover, reboot, type, variables

**Changed SCSS mixins:**
caret, forms, grid, list, pagination, reset text

**Comment by mkamensky** [comment]
Thanks, I'll have a look

**Comment by kishisland** [comment]
Sounds good to me

**Comment by parhamDA** [comment]
I am waiting for RTL version 👍 Thanks ...

**Comment by Kamalifar** [comment]
That's great. Thanks in advanced.

**Comment by IdanCo** [comment]
Just a small tip for those RTL pioneers out there -

when printing a page, the `$print-body-min-width` variable causes weird print issues unless you set `direction: rtl` for your `html` element (or `dir="rtl"` attribute in your tag). Sounds elementary, but until I started printing content, i was fine with setting just the `body` tag.

**Comment by olegsv** [comment]
It would be great to have official RTL for Boostrap 4.

**Comment by tornadofay** [comment]
waiting for rtl version. thanks

**Comment by abuassar** [comment]
I hope RTL-support will make it for 4.3.0

thanks for your hard work, much appreciated!

**Comment by mkamensky** [comment]
As I mentioned somewhere before, the following changes resolve almost all problems I had:
1. Use flexbox wherever possible (already supported by bootstrap)
2. Replace all physical direction specs by logical ones, e.g., `padding-inline-start` in place of `padding-left`, etc. For instance, I have the following for forms (bs 4.2.1):

```css
.custom-control {
  padding-inline-end: inherit;
  padding-inline-start: $custom-control-gutter + $custom-control-indicator-size;
}

.custom-control-inline {
  margin-inline-start: inherit;
  margin-inline-end: $custom-control-spacer-x;
}

.custom-control-label {
  &::before {
    inset-inline-start: -($custom-control-gutter + $custom-control-indicator-size);
    inset-inline-end: inherit;
  }
    
  &::after {
    inset-inline-start: -($custom-control-gutter + $custom-control-indicator-size);
    inset-inline-end: inherit;
  }
}
.custom-switch {
  padding-inline-end: inherit;
  padding-inline-start: $custom-switch-width + $custom-control-gutter;

  .custom-control-label {
    &::before {
      inset-inline-start: -($custom-switch-width + $custom-control-gutter);
      inset-inline-end: inherit;
    }

    &::after {
      inset-inline-start: calc(#{-($custom-switch-width + $custom-control-gutter)} + #{$custom-control-indicator-border-width * 2});
      inset-inline-end: inherit;
    }
  }
}

.custom-select {
  padding-inline-start: $custom-select-padding-x + $custom-select-indicator-padding;
  padding-inline-end: $custom-select-padding-x;

  &[multiple],
  &[size]:not([size="1"]) {
    padding-inline-start: inherit;
    padding-inline-end: $custom-select-padding-x;
  }
}

.custom-select-sm {
  padding-inline-start: $custom-select-padding-x-sm;
  padding-inline-end: inherit;
}

.custom-select-lg {
  padding-inline-start: $custom-select-padding-x-lg;
  padding-inline-end: inherit;
}

.breadcrumb-item {
  + .breadcrumb-item {
    padding-left: inherit;
    padding-inline-start: $breadcrumb-item-padding;

    &::before {
      padding-right: inherit;
      padding-inline-end: $breadcrumb-item-padding;
    }
  }
}
```

This solves almost all my issues, and it should be very easy to implement, basically search and replace.
