### ISSUE TITLE
Use font size array

### ISSUE THREAD

**Issue by academici** [twbs/bootstrap#24856]
```scss
$font-size-base:              1rem !default; // Assumes the browser default, typically `16px`
$font-sizes: () !default;
$font-sizes: map-merge((
    "base":    $font-size-base,
    "sm":  ($font-size-base * 1.25),
    "lg":    ($font-size-base * .875),
), $font-sizes);

div {
    font-size: font-size("sm")
}
```
