### ISSUE TITLE
Responsive container-fluid

### ISSUE THREAD

**Issue by fulldecent** [twbs/bootstrap#24903]
FEATURE REQUEST: `.container-*-fluid`

DESCRIPTION: Switch to fluid layout for viewports larger than a certain size.

Use case: https://codepen.io/anon/pen/WXaoyo?editors=1100#0

Implementation for `.container-xl-fluid`:

```css
@media (min-width: 1200px) {
  .container-xl-fluid {
    width: 100%;
    margin-right: auto;
    margin-left: auto;
    padding-right: 15px;
    padding-left: 15px;
    width: 100%;
    max-width: none;
  }
}
```
