### ISSUE TITLE
Responsive dropdown-menu-right class

### ISSUE THREAD

**Issue by niftylettuce** [twbs/bootstrap#25019]
It'd be great if we could have responsive control over the dropdown menu opening either left or right aligned (as opposed to writing custom CSS).

Here's a quick demo of what the following sass does:

![kapture 2017-12-15 at 18 10 07](https://user-images.githubusercontent.com/523141/34063900-397ed2be-e1c3-11e7-955c-512e900dc4f7.gif)

```scss
// since .dropdown-menu-right is not responsive
// we need to make sure that the language dropdown
// is right aligned on < md screen sizes
// <https://github.com/twbs/bootstrap/blob/34d745540d690086cdfc4ce648963f9acdc56bdb/scss/_navbar.scss#L160-L163>
#navbar-dropdown-language-ul {
  right: 0;
  left: auto; // Reset the default from `.dropdown-menu`
}
@include media-breakpoint-up(md) {
  #navbar-dropdown-language-ul {
    left: 0;
    right: auto; // Reset the default from `.dropdown-menu`
  }
}
```

Not sure if it should be called `dropdown-menu-right-$size-up` or `dropdown-menu-right-$size-down`?

Thoughts @mdo?
