### ISSUE TITLE
Changing $headings-color override text enphasises

### ISSUE THREAD

**Issue by Soullivaneuh** [twbs/bootstrap#25077]
With the following `app.scss`:

```scss
@import "variables";
@import "~bootstrap/scss/bootstrap";
@import "~font-awesome/scss/font-awesome";

body {
  > header {
    background: url('../img/header-background.svg') center top;

    #header {
      a:not(.btn) {
        @extend .text-light;
        text-decoration: underline;
      }
    }
  }
}
```

And the following `variables.scss` override:

```scss
$cyan: #0097a7;
$green: #689f38;
$orange: #ffa000;
$red: #e64a19;

$theme-colors: (
  primary: #455a64,
  secondary: #644f45,
  warning: $orange,
);

$headings-color: map_get($theme-colors, 'primary');
```

Changing the `$heading-color` variable to primary also affect titles under `text-light` (and certainly the other) rules:

```html
<h1>This title should be colored</h1>

<div class="text-light">
    <h2>This one not. But it is.</h2>
</div>
```

This may be not a bug, but in this case the `$heading-color` is not very useful for overriding in my opinion.

Though?
