### ISSUE TITLE
Missing border radius on input group with validation feedback

### ISSUE THREAD

**Issue by MoritzBru** [twbs/bootstrap#25110]
With new beta 3 and using the new input-group stuff, inputs inside input-groups with some validation feedback after them are missing the border-radius.

![formbug](https://user-images.githubusercontent.com/23639869/34426369-e70a858c-ec35-11e7-86f4-f178276e1f6e.png)
red circle: without border-radius
green circle: with border-radius

This is an example from the [bootstrap documentation](https://getbootstrap.com/docs/4.0/components/forms/#custom-styles)

**Comment by mdo** [comment]
Damn, I'm super disappointed in myself for not catching this during Beta 3. I thought I had this all locked up with that rewrite. This is going to be tough.

/cc @ysds in case he has ideas having looked at some of this code recently

**Comment by mdo** [comment]
I spent an hour on this last night and had nothing, but just had an idea to use the validation state.

```scss
  .form-control,
  .custom-select {
    &:not(:last-child) { @include border-right-radius(0); }
    &:not(:first-child) { @include border-left-radius(0); }

    &:not(:last-child):required,
    &:not(:last-child).is-valid,
    &:not(:last-child).is-invalid {
      @include border-right-radius($input-border-radius);
    }
  }
```

This works on the particular docs example, but I need to see if it doesn't work elsewhere.

**Comment by ysds** [comment]
@mdo I am terribly sorry for the lack of confirmation. There is still a issue. e.g. appended addon:

```html
<div class="input-group mb-3">
  <input type="text" class="form-control is-invalid" placeholder="Recipient's username">
  <div class="input-group-append">
    <span class="input-group-text">@example.com</span>
  </div>
  <div class="invalid-feedback">
    Please provide a valid zip.
  </div>
</div>
```

I created various test cases here. https://codepen.io/fellows3/pen/OzmMoz

**Comment by mdo** [comment]
Nice, thanks for the test case. I've forked your pen to:

- Add my latest built CSS from my local changes I included in my last comment
- Remove validation on multiple inputs—there's no way to do this, and we already explicitly do not support this.

See https://codepen.io/emdeoh/pen/OzmNNw?editors=1100. Have to improve some custom select and custom file, as well as dealing with the appended as you noted.

**Comment by ysds** [comment]
We also have to suppose a case that `.is-invalid` or `.is-valid` .class does not exist as the initial. Like https://getbootstrap.com/docs/4.0/components/forms/#custom-styles

**Comment by mdo** [comment]
@ysds That's where I'm hoping `:required` can help, which I've included in that snippet. Might need to sneak `:optional` in there, too.

**Comment by ysds** [comment]
I don't have any solution with only CSS3 selector to this issue. It would be impossible.
 
I think we should move `.invalid-feedback` to outside of input group. And then, extend `.input-group` class (`.has-valid/invalid`) as many times proposed in #23454. That would solve most of the issues (validation feedback of multiple input and combination with custom file input etc.). The `.has-valid/invalid` class will be unnecessary in the future by `:has` selector of CSS4.

**Comment by mdo** [comment]
Hmm, that'd be a breaking change from the final beta. I'm pushing for no breaking changes, but we'll see. I agree there doesn't seem to be a solution. I was trying to use some `:nth-last-child` stuff, but that's a bit messy right now.

**Comment by mdo** [comment]
I have some real funky CSS for y'all in #25352 to address as much of this as I can. 😅

**Comment by altbdoor** [comment]
Just dropping my two cents. I'm using v4.0 at the moment, and I was able to get the rounded corners back on the appended button with:

```html
<div class="input-group">
    <input type="text" class="form-control is-invalid" readonly required>
    
    <div class="input-group-append">
        <button class="btn btn-outline-secondary rounded-right" type="button">
            Hey
        </button>
    </div>
    
    <div class="invalid-feedback">
        Error
    </div>
</div>
```

It needs an extra declaration of `.rounded-right` on the element within the `.input-group-append`. Not the most elegant, but at least it works.

**Comment by cbossi** [comment]
I found a solution to the problem using [bootstrap's `order` classes](http://getbootstrap.com/docs/4.0/layout/grid/#reordering): 
You can place the `.invalid-feedback` element in between the `input` and the `input-group-append` element and then append the `order-1` class to it. This way the `.invalid-feedback` element is NOT the last child inside the `input-group` (which would cause the border radius problem), but nonetheless appears at the end of the `input-group`:
```html
<div class="form-group">
    <label for="name">Name</label>
    <div class="input-group">
    <input type="text" class="form-control" id="name" required>
    <div class="invalid-feedback order-1">
        Please provide a name.
    </div>
    <div class="input-group-append">
        <span class="input-group-text">
        <i class="fas fa-envelope"></i>
        </span>
    </div>
    </div>
</div>
```

**Comment by flachware** [comment]
I ran into the same issue. How about generally using the `:last-of-type` selector instead of `:last-child` in `_input-group.scss` and switching `div.invalid-feedback` to `p.invalid-feedback`?
![appended-button](https://user-images.githubusercontent.com/419747/40775842-5df10f0c-64c9-11e8-9246-00639c52b3ee.png)
![appended-button-ok](https://user-images.githubusercontent.com/419747/40776360-d4a37c10-64ca-11e8-8a98-297cc6d7e127.png)

**Comment by claudioalmeiida** [comment]
I find another problem when it does not use `.dropdown-toggle` class, I do not know if it was a known problem
https://codepen.io/anon/pen/BVZMVj

![image](https://user-images.githubusercontent.com/942899/41376607-ae7bcbe8-6f27-11e8-8acd-954aa4abd1fe.png)

**Comment by rushairer** [comment]
So that????

**Comment by kjjdion** [comment]
March 2019 and issue still exists. Is there no pull request for a fix?

**Comment by mdo** [comment]
@kjjdion If you have a fix, we'd love a PR, but otherwise, the lack of a PR means that there is no fix (or that's rather difficult to do).

**Comment by nibblesnbits** [comment]
Forgive my ignorance, but why would it be more complicated than this?

```css

.input-group > .form-control:not(:first-child), .input-group > .custom-select:not(:first-child) {
  border-radius: 0.25rem;
  transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
}
.input-group > .input-group-prepend > .btn, .input-group > .input-group-prepend > .input-group-text, .input-group > .input-group-append:not(:last-child) > .btn, .input-group > .input-group-append:not(:last-child) > .input-group-text, .input-group > .input-group-append:last-child > .btn:not(:last-child):not(.dropdown-toggle), .input-group > .input-group-append:last-child > .input-group-text:not(:last-child) {
  border-top-right-radius: 0.25rem;
  border-bottom-right-radius: 0.25rem;
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
}
```

Obviously these are likely overly specific, but these rules seem to fix it in my app.

![image](https://user-images.githubusercontent.com/6042917/57586621-46b31980-74c6-11e9-8e00-0925d8744ecc.png)

**Comment by chrisbo** [comment]
Although a sort of hack, adding the class border-right to my form inputs and textarea seems to have fixed my issue.

**Comment by rushairer** [comment]
Thanks all

**Comment by andreanz22** [comment]
style="border-top-right-radius: 4px;border-bottom-right-radius: 4px;"

**Comment by clementAC** [comment]
I have the issue with append group. I have a Dashlane extension that add some impala logo to signify the user the input can be auto-completed (Dashlane is not the only extension to do that). This logo is added to the end of the input so the :not-last selector is not working and apply border radius 0 to the right. 
Not sure how to fix that without avoiding the @andreanz22  solution

**Comment by ysds** [comment]
Sorry, we bootstrap core team don't have any smart way to solve this for v4. Please try the following workaround.

When you are using a medium size input group and doesn't customize the default border radius values, please add `.rounded-right` to the missing border radius elements.

Example:
```html
<div class="input-group">
  <div class="input-group-prepend">
    <span class="input-group-text">@</span>
  </div>
  <input type="text" class="form-control rounded-right" required>
  <div class="invalid-feedback">
    Please choose a username.
  </div>
</div>
```

When you are using a small or large input-group or customizing the default border radius values, please add custom CSS to the missing border radius elements.

```scss
.fix-rounded-right {
  // Change values to match the radius of your form control.
  border-top-right-radius: .2rem !important;
  border-bottom-right-radius: .2rem !important;
}
```

```html
<div class="input-group input-group-sm">
  <div class="input-group-prepend">
    <span class="input-group-text">@</span>
  </div>
  <input type="text" class="form-control fix-rounded-right" required>
  <div class="invalid-feedback">
    Please choose a username.
  </div>
</div>
```
