### ISSUE TITLE
Deprecate .btn-group-toggle class for simpler selectors

### ISSUE THREAD

**Issue by hafezdivandari** [twbs/bootstrap#25281]
Single toggle button used to work with checkbox/radio buttons on `4.0.0-beta.2` like this:

```html
<div data-toggle="buttons">
  <label class="btn btn-outline-primary">
    <input type="checkbox" autocomplete="off"> I don't know
  </label>
</div>
```
Output: 
![image](https://user-images.githubusercontent.com/30104764/34854633-ffca7f3a-f74f-11e7-8cf7-721e765a5745.png)

But it doesn't work anymore on `4.0.0-beta.3`:
![image](https://user-images.githubusercontent.com/30104764/34854707-78094436-f750-11e7-9a83-61b620d2ef64.png)

I searched your change log and found #23728 but It doesn't make sense to add `btn-group-toggle` to a single toggle button to make this work.

**Comment by mdo** [comment]
Yeah, we have to improve the naming there, but we were working with what we had in our betas. For now, use the class. Our motivation for the change was separating style from behavior. In the future, we won't need this separation because we'll rewrite the component to use sibling selectors and leverage all the browser behaviors we have from inputs.

**Comment by hafezdivandari** [comment]
@mdo the current selector for hiding checkbox/radio button in a toggle button is like this:

```css
.btn-group-toggle > .btn input[type="radio"],
.btn-group-toggle > .btn input[type="checkbox"],
.btn-group-toggle > .btn-group > .btn input[type="radio"],
.btn-group-toggle > .btn-group > .btn input[type="checkbox"] {
    position: absolute;
    clip: rect(0, 0, 0, 0);
    pointer-events: none;
}
```

Why not just:

```css
label.btn input[type="radio"],
label.btn input[type="checkbox"] {
    ...
}
```

Hide checkbox if it was in a button, it works for both **single** and group toggle buttons:

```html
<label class="btn btn-outline-primary">
    <input type="checkbox" autocomplete="off"> I don't know
</label>
```
