### ISSUE TITLE
More column breaks

### ISSUE THREAD

**Issue by NoOorZ24** [twbs/bootstrap#25367]
I think it would be useful to add a bit more complex column break options.
Idea is to create container breaks for specific window sizes so that break happens only when needed.
As it was required in my case I created one myself:

```css
@media (max-width: 992px) {
    .w-100-md {
        width: 100% !important;
    }
}
```

I'm not sure if that wouldn't be too many extra lines in css, but mby this helps someone...
