### ISSUE TITLE
Form Validation - Validate File

### ISSUE THREAD

**Issue by prbrazil** [twbs/bootstrap#25399]
https://github.com/twbs/bootstrap/blob/2f4e785a8c623fbe1b011edabecafe99b9f0817b/scss/mixins/_forms.scss#L53

I would like to add a file validation on the following form:

``` scss
.form-control,
.form-control-file,
```

**Comment by ysds** [comment]
@mdo We can not change the style of `<input type="file">`, but how about adding support for validation feedback?

```scss
  .form-control-file {
    .was-validated &:#{$state},
    &.is-#{$state} {
      ~ .#{$state}-feedback,
      ~ .#{$state}-tooltip {
        display: block;
      }
    }
  }
```
