### ISSUE TITLE
http://getbootstrap.com/docs/4.0/content/tables/#contextual-classes

### ISSUE THREAD

**Issue by LarryAzevedo** [twbs/bootstrap#25535]
The background color on the [Contextual clases section on the Tables page](http://getbootstrap.com/docs/4.0/content/tables/#contextual-classes) is incorrect.  It uses `<tr class="table-dark">...</tr>` but it's getting overwritten by:

```css
.table-dark, .table-dark > td, .table-dark > th {
	background-color: #c6c8ca;
}
```
I'm not sure if that CSS block above should even exist.

![screen shot 2018-02-01 at 8 38 44 pm](https://user-images.githubusercontent.com/2222751/35712509-564ce960-0790-11e8-985d-8feac338999b.png)
