### ISSUE TITLE
Contrast issue: Border between two table-{success,danger,…} rows is gray

### ISSUE THREAD

**Issue by blixt** [twbs/bootstrap#25685]
Currently, when several rows of the same `table-<context>` class follow each other, they are separated by a gray border which looks out of place and in some cases also have contrast issues:

<img width="466" alt="screen shot 2018-02-22 at 4 21 23 pm" src="https://user-images.githubusercontent.com/158591/36546745-7e386ef6-17ec-11e8-81e7-f72bbbe6f646.png">

(Note: in this screenshot the leftmost column has `rowspan="3"`)

I propose a rule similar to the following to all classes that affect table row backgrounds:

```css
tr.table-success ~ tr.table-success td, tr.table-success ~ tr.table-success th {
    border-top-color: hsla(133, 42%, 74%, 1);
}
```

It would look like this instead:

<img width="470" alt="screen shot 2018-02-22 at 4 15 36 pm" src="https://user-images.githubusercontent.com/158591/36546763-88479a52-17ec-11e8-9ed8-283faeedf0f6.png">
