### ISSUE TITLE
Bootstrap v4 Dropdown menu with btn-block and align caret to the right workaround/fix

### ISSUE THREAD

**Issue by shenlong** [twbs/bootstrap#25734]
Using dropdown as an input for form. To have consistent input width, use btn-block for the dropdown input:
```javascript
      <div class="form-group row">
        <label class="col-sm-2 col-form-label col-form-label-sm">Normal Dropdown</label>
        <div class="col-sm-10">
          <div class="">
            <div class="dropdown flatmenu">
              <div class="btn btn-outline-secondary btn-sm btn-block dropdown-toggle text-justify" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span>Dropdown button</span>
              </div>
              <div class="dropdown-menu w-100" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </div>
          </div>
        </div>
      </div>
```
Add the following css class to target fix for various browser:

```css
.dropdown-toggle::after {
   
}

.firefox.dropdown-toggle::after {
    text-align: right;
    float: right;
    /*Firefox fix*/
    margin-top: -12px;
}
.chrome.dropdown-toggle::after {
    text-align: right;
    float: right;
    /*Chrome IE fix*/
    margin-top: 8px;
}
```

Demo: https://jsfiddle.net/shenlong/tv2y3n2n/10/

![dropdown_bootstrap_v4_preview](https://user-images.githubusercontent.com/953106/36765981-c7fbf14e-1c6e-11e8-965d-728c25cbe90a.png)

Is there a better implementation? 
I'm using .dropdown-toggle::after which is a native bootstrap 4 dropdown element.
