### ISSUE TITLE
Change padding and margin in GRID to rem - 1px issue

### ISSUE THREAD

**Issue by SkuterPL** [twbs/bootstrap#25790]
I can see that in BS4 you change PX to REM, but PX still is in grid system where is 1px problem, because in grid on left and right side I have 15px, but when I want to add extra margin to the bottom I use `.m-3`, but it is 1rem, so 16px and there is 1px issue.

**Comment by browner12** [comment]
so make your own class.

```scss
.bottom-gutter {
    margin-bottom: $grid-gutter-width;
}
```
