### ISSUE TITLE
Card-text on every element instead of *:lastchild

### ISSUE THREAD

**Issue by stephenbe** [twbs/bootstrap#25849]
I was wondering why use card-text on every element when you could have done  : 

```css
.card-body > *:last-child {
margin-bottom:0;
}
```
I'm guessing it's maybe speed and it's faster for the browser to parse. 

I'm loving bs4 so this doesn't come from a place of hate or negativity ! 

Thanks!
