### ISSUE TITLE
custom-checkbox and is-valid/is-invalid not working due to priority clashs

### ISSUE THREAD

**Issue by waldiTM** [twbs/bootstrap#25867]
## Version
Bootstrap 4.0.0

## Problem
Using a custom checkbox and the server side validation classes `is-valid`/`is-invalid` does not work.

The CSS definitions for this behavior are:
```css
.custom-checkbox .custom-control-input:checked ~ .custom-control-label::before {
￼    background-color: #007bff;
}
￼
.custom-control-input.is-invalid:checked ~ .custom-control-label::before {
    background-color: #e4606d;
}
```
The first definition provides the blue color on the normal checked checkbox.
The second definition is supposed to override the color to the invalid red.
If I count correctly, they have the same priority, so the second definition never applies.

```html
<div class="custom-control custom-checkbox">
  <input checked type="checkbox" class="custom-control-input is-invalid" id="box1">
  <label class="custom-control-label" for="box1"></label>
</div>
```

## Possible solutions
* In the mixin `form-validation-state` specify also `.custom-checkbox` and others to match the full definition and make it more specific.

**Comment by mdo** [comment]
> they have the same priority, so the second definition never applies.

If the second of two definitions has the same specificity, the second would override the first.

More importantly, you haven't provided a live example of the problem. Please comment with one and we can re-open to take another look.

**Comment by acshef** [comment]
Here's an example: http://jsbin.com/buseke/3/edit?html,output
![image](https://user-images.githubusercontent.com/9013284/37623468-6c62acf8-2b8a-11e8-999e-4f32a1fd899d.png)

**Comment by acshef** [comment]
@mdo this problem is still exhibited in v4.1.1: http://jsbin.com/buseke/7/edit?html,output

**Comment by acshef** [comment]
@mdo this problem is still exhibited in v4.1.2: http://jsbin.com/buseke/8/edit?html,output

**Comment by acshef** [comment]
@mdo this problem is still exhibited in v4.1.3: http://jsbin.com/buseke/10/edit?html,output

**Comment by whyleee** [comment]
The issue is clearly reproduced and visible online. Please reopen it and review

**Comment by oprobst-ethz** [comment]
Overriding with the following works (I guess):

```css
.custom-control-input.is-valid:checked ~ .custom-control-label:after {
  border-radius: $custom-checkbox-indicator-border-radius;
  background-color: $form-feedback-valid-color;
}

.custom-control-input.is-invalid:checked ~ .custom-control-label:after {
  border-radius: $custom-checkbox-indicator-border-radius;
  background-color: $form-feedback-invalid-color;
}

.custom-control-input.is-valid ~ .custom-control-label:after {
  border-radius: $custom-checkbox-indicator-border-radius;
  background-color: $form-feedback-valid-color;
}

.custom-control-input.is-invalid ~ .custom-control-label:after {
  border-radius: $custom-checkbox-indicator-border-radius;
  background-color: $form-feedback-invalid-color;
}
```
