### ISSUE TITLE
Consider rem-calc() instead of calc()

### ISSUE THREAD

**Issue by Kopyov** [twbs/bootstrap#26206]
In some cases, calc() thing breaks CSS: if i set $card-border-width to 0, compiled CSS for card header top border radius will look like calc(0.25rem - 0), which is incorrect. Same happens if $input-height-border variable is set to 0.
We either need to document $border-width and other px values used in calc() function properly (value greater than 0 is required) or implement custom rem-calc() function, which will convert all px units to rem and get rid of calc() where possible.

**Comment by mdo** [comment]
I don't see the value in using the `rem-calc()` function, which we don't have, when `calc()` is provided and supported by browsers. What exactly would we document?

**Comment by razh** [comment]
The units need to be specified when using `calc()`.

For example, this is invalid:

```scss
$input-btn-padding-y-sm: .25rem;
$input-border-width: 0;

padding-top: calc(#{$input-padding-y-sm} + #{$input-border-width});

// outputs

padding-top: calc(0.25rem + 0);
```

But this works:

```scss
$input-border-width: 0px;
padding-top: calc(0.25rem + 0px);
```

https://stackoverflow.com/questions/27829919/why-do-i-have-to-specify-a-unit-identifier-e-g-px-when-passing-0-as-the-onl
