### ISSUE TITLE
Incorrect custom tick color on compile

### ISSUE THREAD

**Issue by Quberik** [twbs/bootstrap#26208]
```css
/* dist/css/bootstrap.css */

.custom-radio .custom-control-input:checked ~ .custom-control-label::after {
  background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='-4 -4 8 8'%3E%3Ccircle r='3' fill='%23fff'/%3E%3C/svg%3E");
}
```

`fill='%23fff'`. Is it correct fill color? I don't think so. Seems it is a bug.

Link https://github.com/twbs/bootstrap/blob/v4.0.0/dist/css/bootstrap.css#L3687
