### ISSUE TITLE
replace reboot/normalize monospace hack with monospace system font stack

### ISSUE THREAD

**Issue by client9** [twbs/bootstrap#26228]
There are two stanzas (selectors) for `code, kbd, pre, samp` in the main bootstrap distribution

The first in reboot:

```css
code, kbd, pre, samp {
  font-family: monospace,monospace;
  font-size: 1em;
}
```

And then later in bootstrap:

```css
code, kbd, pre, samp {
  font-family: SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;
}
```

The proposal would be to move the system monospace font stack into reboot and get rid of the monospace, monospace hack (more details of which can be found here: https://github.com/necolas/normalize.css/issues/695 ).  I think this would make reboot more consistent (since sans-serif font uses system stack), be more clear, and make bootstrap smaller.

thoughts?

regards,

n
