### ISSUE TITLE
.btn-link have incomplete reset

### ISSUE THREAD

**Issue by K-Ko** [twbs/bootstrap#26294]
# v4.1.0
For **.btn-link** in continuous text the border and vertical-align is not reset properly.

``` css
.btn-link {
    border: 0;
    vertical-align: initial;
}
```

Tested with
- Google Chrome 65.0.3325.181 (Offizieller Build) (64-Bit)
- Mozilla Firefox 59.0.2 (64-Bit)
