### ISSUE TITLE
radio/checkbox: validation with input inside label

### ISSUE THREAD

**Issue by tkrotoff** [twbs/bootstrap#26404]
Demo: https://codepen.io/tkrotoff/pen/mLOmVN

Validation works in this case (code taken from https://getbootstrap.com/docs/4.1/components/forms/#server-side):
```HTML
<div class="form-check">
  <input class="form-check-input is-invalid" type="checkbox" value="" id="invalidCheck3" required>
  <label class="form-check-label" for="invalidCheck3">
    Agree to terms and conditions
  </label>
  <div class="invalid-feedback">
    You must agree before submitting.
  </div>
</div>
```

But does not with input inside label:
```HTML
<div class="form-check">
  <label class="form-check-label">
    <input class="form-check-input is-invalid" type="checkbox" value="" required>

    Agree to terms and conditions 2

    <div class="invalid-feedback">
      You must agree before submitting.
    </div>
  </label>
</div>
```

The interesting part about input inside label is that you then don't need `for` and `id` (it's implicit => less code)

Screenshot:

![screen shot 2018-04-27 at 14 12 34](https://user-images.githubusercontent.com/643434/39362000-1b3018d4-4a25-11e8-8a46-fae42c3eb088.png)

This is because of [this CSS rule](https://github.com/twbs/bootstrap/blob/v4.1.0/scss/mixins/_forms.scss#L71):
```SCSS
  .form-check-input {
    .was-validated &:#{$state},
    &.is-#{$state} {
      ~ .form-check-label {
        color: $color;
      }

      ~ .#{$state}-feedback,
      ~ .#{$state}-tooltip {
        display: block;
      }
    }
  }
```

The way it was done with Bootstrap 3 allowed input inside label: https://getbootstrap.com/docs/3.3/css/#forms-control-validation
```HTML
<div class="has-success">
  <div class="checkbox">
    <label>
      <input type="checkbox" id="checkboxSuccess" value="option1">
      Checkbox with success
    </label>
  </div>
</div>
<div class="has-warning">
  <div class="checkbox">
    <label>
      <input type="checkbox" id="checkboxWarning" value="option1">
      Checkbox with warning
    </label>
  </div>
</div>
<div class="has-error">
  <div class="checkbox">
    <label>
      <input type="checkbox" id="checkboxError" value="option1">
      Checkbox with error
    </label>
  </div>
</div>
```
