### ISSUE TITLE
Responsive Text Colors

### ISSUE THREAD

**Issue by nk2580** [twbs/bootstrap#26553]
Wondering if anyone has had a crack at making the text color classes work with the breakpoints.

MY USE CASE:
when on a mobile the text content of a column wraps onto a different background. as the text is white, you can no longer see the content

PROPOSED ADDITIONAL CLASSES:
text-sm-white
text-sm-primary
text-sm-secondary
etc..

Anyone have any strong opinions against?

**Comment by Daniel217D** [comment]
If your css code change background by media queries, why you can't change text color? So also it have to add classes `.bg-sm-black`, but this classes are very specific and there is standart bootstrap color palette

**Comment by browner12** [comment]
it seems like a very edge case, and it has the potential to add a considerable amount of generated classes.

I guess my opinion would be unless we can show that this is an issue more people run into, I would vote against.

**Comment by patrickhlauke** [comment]
I'd say no, this is a lot of work/extra classes for very minimal general purpose usefulness. Closing, unless @mdo feels otherwise...

**Comment by nk2580** [comment]
So let me get this straight here? You guys have a feature request... without setting a time limit on assessing the validity of the request (or even entertaining the idea of a PR) you simply close the issue and wait for @mdo to comment otherwise?

**Comment by nk2580** [comment]
@browner12 completely agree with that approach. Is there a way to open a poll on new features so we can determine if this is worth it? 

I can say from the uses I have (multiple projects) this is definitely something I get requests for often (i just compile an extension when the other devs / designers complain)

**Comment by bderblatter** [comment]
@nk2580 if you're extending Bootstrap (I would recommend it if you really need features like this) you can add it yourself without too much trouble.  Here's a [similar solution for responsive borders](https://github.com/twbs/bootstrap/issues/23892#issuecomment-378172751) that you can use to help you out.  I even modified that one in my project to make border gradient direction responsive, so the sky's the limit.

**Comment by nk2580** [comment]
Ended up making my own package

**Comment by leecollings** [comment]
I've landed here after seeing if there was any discussion of using background colours with breakpoints, for example setting bg-primary on any from small and above.

I have to agree with @nk2580 that the whole process of immediately denying any discussion and closing requests without asking for other opinions is a common thing here, and it's one that really gets to me.

Is there any current or future polling process that could be used to ask fellow users / developers about new features (rather than listing them as issues, or PR)?

**Comment by bderblatter** [comment]
@leecollings not that I know of; Bootstrap seems to be pretty top down from what I've seen. It is pretty easy to extend though. You can copy and modify some of the functions to make responsive text colors, background colors, and anything else really. That's what I've done at least.

**Comment by febrez** [comment]
I use this for responsive text/background colors :

```scss
@each $breakpoint in map-keys($grid-breakpoints) {
    @include media-breakpoint-up($breakpoint) {
        $infix: breakpoint-infix($breakpoint, $grid-breakpoints);
        @each $prop, $abbrev in (background: bg, text: text) {
            @each $color,
            $length in $colors {
                .#{$abbrev}#{$infix}-#{$color} {
                    #{$prop}: $length !important;
                }
            }
        }
    }
}
```

**Comment by febrez** [comment]
I use this : 

```scss
@each $breakpoint in map-keys($grid-breakpoints) {
    @include media-breakpoint-up($breakpoint) {
        $infix: breakpoint-infix($breakpoint, $grid-breakpoints);
        @each $prop, $abbrev in (background-color: bg, color: text) {
            @each $theme-color,
            $length in $theme-colors {
                .#{$abbrev}#{$infix}-#{$theme-color} {
                    #{$prop}: $length !important;
                }
            }
        }
    }
}
```
