### ISSUE TITLE
Buttons: Text color on <a> elements

### ISSUE THREAD

**Issue by FabianKoestring** [twbs/bootstrap#26644]
http://jsfiddle.net/x1hphsvb/4594/

The text color differs between `<button>` and `<a>` elements. Is this a bug or default behavior?

I know a workaround by specifying some extra css like:
```css
a.btn-outline-danger {
  color:red !important;
}
a.btn-outline-danger:hover {
  color:white !important;
}
```
