### ISSUE TITLE
Enhance button-variant mixin to accept disable styles

### ISSUE THREAD

**Issue by epignosisx** [twbs/bootstrap#26737]
Our styles require us that all buttons end up with the same disable style:

![image](https://user-images.githubusercontent.com/697377/41721347-9e2a8920-7533-11e8-8aab-ef3a380b8518.png)
![image](https://user-images.githubusercontent.com/697377/41721405-c6882206-7533-11e8-9741-55023b906158.png)

The current implementation of the disable state is based on the button background. Each button has its own disable state that is a lighter version of the regular button background color:

![image](https://user-images.githubusercontent.com/697377/41721532-24dba65c-7534-11e8-9723-ca1455289a9f.png)

Would you consider accepting a PR that enhances the button-variant mixin in a backward compatible way to allow for such extensibility?

This is what I have in mind:

Current:

```scss
@mixin button-variant(
    $background, $border, 
    $hover-background: darken($background, 7.5%), $hover-border: darken($border, 10%), 
    $active-background: darken($background, 10%), $active-border: darken($border, 12.5%)) {

    ...
    &.disabled,
    &:disabled {
      color: color-yiq($background);
      background-color: $background;
      border-color: $border;
    }
    ...
}
```

Proposed:
```scss
@mixin button-variant(
    $background, $border, 
    $hover-background: darken($background, 7.5%), $hover-border: darken($border, 10%), 
    $active-background: darken($background, 10%), $active-border: darken($border, 12.5%),
    $disabled-background: $background,
    $disabled-border: $border,
    $disabled-color: color-yiq($background)) {

    ...
    &.disabled,
    &:disabled {
      color: $disabled-color;
      background-color: $disabled-background;
      border-color: $disabled-border;
    }
    ...

}
```
