### ISSUE TITLE
Unable to scroll modal when bootstrap is namespaced

### ISSUE THREAD

**Issue by jdanil** [twbs/bootstrap#26742]
Our app currently namespaces bootstrap so that our styles don't affect other areas.
Something like this...
```scss
.app {
  @import '~bootstrap/scss/bootstrap';
}
```

The style in `_modal.scss` that displays the scrollbar is this.
```scss
.modal {
  .modal-open & {
    overflow-x: hidden;
    overflow-y: auto;
  }
}
```

In our app, this evaluates to `.modal-open .app .modal`, so the style is not applied.
On top of that, it is unintuitive to read.
@mdo pointed out this could be a potential issue when it was [submitted](https://github.com/twbs/bootstrap/pull/24404/files/6c580bc428746da9b1f718ed342aa4f25b2526e3#r145225612).

Testing in [SassMeister](https://www.sassmeister.com/) with this block of code...
```scss
.app {
  .modal {
    .modal-open & {
      overflow-x: hidden;
      overflow-y: auto;
    }
  }
}
```

...outputs the following compiled css.
```css
.modal-open .app .modal {
  overflow-x: hidden;
  overflow-y: auto;
}
```
