### ISSUE TITLE
scss "#" deprecation

### ISSUE THREAD

**Issue by johnunclesam** [twbs/bootstrap#26787]
I'm using something like that in my index.scss:

```scss
.some-class {
  content: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 50 50'><path d='M15.477 ... 50.836z' fill='#{$text-muted}'/><path d='M45.3 ... 10h6.1z' fill='#{$text-muted}'/></svg>");
}
```

But Chrome says to me:

`[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M68, around July 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.`
