### ISSUE TITLE
btn-sm is too big for table row - please include btn-xs

### ISSUE THREAD

**Issue by piernik** [twbs/bootstrap#26791]
As You see in that example: https://stackblitz.com/edit/js-ddybgj?file=index.html
`btn-sm` makes row higher and it should not.
I think You should bring back `btn-xs` which should be exact height as standard text.

**Comment by newsash** [comment]
Quirk, just in case:
```css
.btn-group-xs > .btn, .btn.btn-xs {
  padding  : .25rem .4rem;
  font-size  : .875rem;
  line-height  : .5;
  border-radius : .2rem;
}
```
