### ISSUE TITLE
Form tooltips don't use $tooltip variables

### ISSUE THREAD

**Issue by bhrutledge** [twbs/bootstrap#26816]
Instead, they use hard-coded values:

https://github.com/twbs/bootstrap/blob/779ad9f174ea5ab7e755f6df0ec9e5912d67dd16/scss/mixins/_forms.scss#L38-L51

Here's what I did in my project to make them look more like the other tooltips:

```scss
@each $state, $bg-color in (valid: $form-feedback-valid-color, invalid: $form-feedback-invalid-color) {
    .#{$state}-tooltip {
        background-color: rgba($bg-color, $tooltip-opacity);
        border-radius: if($enable-rounded, $border-radius, 0);
        color: color-yiq($bg-color);
        line-height: $line-height-base;
        font-size: $tooltip-font-size;
        padding: $tooltip-padding-y $tooltip-padding-x;
        z-index: $zindex-tooltip;
    }
}
```
