### ISSUE TITLE
4.1.2 breaks alignment of inline SVG icons

### ISSUE THREAD

**Issue by nifte** [twbs/bootstrap#26878]
A new change in 4.1.2 causes inline SVG icons to become unaligned.

The code in question, `/scss/_reboot.scss`, line 277:
```
svg:not(:root) {
    overflow: hidden;
    vertical-align: middle; <--- (Line 277)
}
```
The issue can be seen in the following examples:
[Version 4.1.1 (Icons aligned)](https://codepen.io/nifte/pen/YjyRGE)
[Version 4.1.2 (Icons not aligned)](https://codepen.io/nifte/pen/bjVQeQ)

**Comment by mdo** [comment]
Ah, yes, the selector is too strong and overrides classes.

**Comment by ysds** [comment]
Removing `:not(:root)` and `overflow: hidden;` is a solution?

```css
svg {
  vertical-align: middle;
}
```

Because, 

```css
svg:not(:root) {	
  overflow: hidden;	
}
```
is for IE9, so we can remove it.
ref: https://github.com/necolas/normalize.css/commit/004d58b2f2e0ac3d03d075f8de46ce7c8234742f#diff-04c6e90faac2675aa89e2176d2eec7d8L73

And...

```css
svg:not(:root) {
  vertical-align: middle;
}
```

SVG can be the root element, but I'm not sure you need `:not(:root)`. Even if that is the root, I don't think that `vertical-align: middle` will cause something.

**Comment by mdo** [comment]
Yup, I agree with that. Feel free to open a PR @ysds, or I can later this week. Hoping to do a 4.1.3 next week to fix some issues.

**Comment by ysds** [comment]
@mdo sure. Which is preferred?

```scss
img {
  vertical-align: middle;
  border-style: none; // Remove the border on images inside links in IE 10-.
}

svg {
  vertical-align: middle;
}
```

or

```scss
img, svg {
  vertical-align: middle;
}

img {
  border-style: none; // Remove the border on images inside links in IE 10-.
}
