### ISSUE TITLE
No Border Bottom in Accordion First Item

### ISSUE THREAD

**Issue by ismailfarooq** [twbs/bootstrap#27124]
There is no Border Bottom if Accordion has only single Item

https://www.bootply.com/vB8GoWkFz3

**Comment by royklutman** [comment]
I believe it is technically not an accordion when using just a single item, you can fix this by just using the collapse class without the accordion: https://www.bootply.com/wpXTWhpi7V

**Comment by Ruffio** [comment]
@royklutman, your solution/example isn't 100% bulletproof. If you look closely (zoom in), you can easily see a double border at the bottom:

![image](https://user-images.githubusercontent.com/1877612/44625986-cd15d400-a914-11e8-87b3-4accb19c80a1.png)

However I can see this has already been raised as an issue: https://github.com/twbs/bootstrap/issues/27108

Iøm sure that the fix is quite small and it would be cool if it was corrected in 4.2 :-)

**Comment by royklutman** [comment]
@Ruffio You are correct indeed, didn't notice that. I do have a possible fix for this, i'm discussing this in #27108 so it's not scattered all over the place.

**Comment by royklutman** [comment]
@ismailfarooq Ah, that makes sense. If you are using plain CSS, add these lines:
```css
.accordion .card {
  overflow: hidden;
}

.accordion .card-header {
  margin-bottom: -1px;
}
```
If you are using SCSS and build Bootstrap yourself, add this to your custom SCSS:
```scss
.accordion {
  .card {
    overflow: hidden;
  }
  
  .card-header {
    margin-bottom: -1px;
  }
}
```
This will fix your issue, the proposed fix is in PR #27133.
