### ISSUE TITLE
Replace clip with clip-path property

### ISSUE THREAD

**Issue by Rohitkrops** [twbs/bootstrap#27177]
Hi team, 

The .`sr-only` and `.sr-only-focusable` classes need to be updated to use `clip-path` property instead of the old deprecated clip property. 

According to MDN web docs, the CSS property `clip` has been [removed from the Web standards](https://developer.mozilla.org/en-US/docs/Web/CSS/clip
).

The same result is achievable with  
```css
@mixin sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  overflow: hidden;
  clip-path: circle(0% at 50% 50%);
  white-space: nowrap;
  border: 0;
}

@mixin sr-only-focusable {
  &:active,
  &:focus {
    position: static;
    width: auto;
    height: auto;
    overflow: visible;
    clip-path: none;
    white-space: normal;
  }
}
```
View Demo here on [jsfiddle](http://jsfiddle.net/Rohitkrops/xnjut03w/30/)

Reference
https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path
