### ISSUE TITLE
"disabled" class doesn't disable the link

### ISSUE THREAD

**Issue by matthewspace** [twbs/bootstrap#27380]
One feature that I'd like to request is regarding the `.nav-link.disabled` class.

![code](https://user-images.githubusercontent.com/38481138/46644977-8ee51480-cb50-11e8-899e-ca78197cf8c3.PNG)

Adding the `disabled` class to the link only changes the color of the link; however it would be convenient if the class kept the default mouse pointer state and when clicked it wouldn't redirect you to the specified URL. This is what it currently looks like when you hover your mouse over the disabled link:

![screenshot](https://user-images.githubusercontent.com/38481138/46645159-9a850b00-cb51-11e8-955b-88d945337e82.png)

I'd say changing the `.nav-link.disabled` class up a bit would be nice.

```css
.nav-link.disabled {
  color: #6c757d;
  pointer-events: none;
  cursor: default;
}
```
