### ISSUE TITLE
dropdown -> dropup if its child of .fixed-bottom

### ISSUE THREAD

**Issue by YveIce** [twbs/bootstrap#27512]
Need additional css definitions for **.dropdown-menu**, in the case a parent element has the class **fixed-bottom**. For example a navbar on the bottom.

[File: _dropdown.scss]:
```scss
.dropup, .fixed-bottom { //add: ", .fixed-bottom"
  .dropdown-menu {
    top: auto;
    bottom: 100%;
    margin-top: 0;
    margin-bottom: $dropdown-spacer;
  }

  .dropdown-toggle {
    @include caret(up);
  }
}
```
