### ISSUE TITLE
Replace fixed "bolder" value in reboot with available variable "font-weight-bolder"

### ISSUE THREAD

**Issue by gijsroge** [twbs/bootstrap#27774]
In [_reboot.scss#L164](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_reboot.scss#L164)
```scss
b,
strong {
  font-weight: bolder; // Add the correct font weight in Chrome, Edge, and Safari
}
```

we have a fixed value `bolder`. In my opinion this should be replaced with the available variable `$font-weight-bolder` in [_variables.scss#L291](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L291) 

Useful if you want to use a fixed bold value for `<strong>` & `<b>` tags.

Thoughts? I can submit a PR if needed.
