### ISSUE TITLE
* selector removed from minified CSS

### ISSUE THREAD

**Issue by kitchenfoil** [twbs/bootstrap#27835]
Noticed a difference between minified and non-minified CSS files when border boxing everything. 

In the non-min files, e.g. [bootstrap.css](https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css), there is:

```css
*,
*::before,
*::after {
  box-sizing: border-box;
}
```
In the min files, e.g. [bootstrap.min.css](https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.min.css), this appears as:

```css
*,::after,::before{box-sizing:border-box}
```
The * selector is getting removed before the pseudo elements.
