### ISSUE TITLE
.collapse with .d-flex

### ISSUE THREAD

**Issue by Yahasana** [twbs/bootstrap#27971]
collapse panel with d-flex will not hide correctly
```html
<div class="d-flex collapse">...</div>
```
solution:
```css
/* original */
.collapse:not(.show) {
    display: none;
}
/* change to */
.collapse:not(.show) {
    display: none !important;
}
```
