### ISSUE TITLE
Reboot for focused placeholder link

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#28010]
The focus states are taken into consideration, but I have a doubt about the necessity of them.

https://github.com/twbs/bootstrap/blob/39b76861a7afc2ccc90752a61fa5aa998e94761f/scss/_reboot.scss#L199-L211

It can be removed IMO. After:

```scss
a:not([href]) {
  color: inherit;
  text-decoration: none;

  @include hover {
    color: inherit;
    text-decoration: none;
  }
}
```
Related to:  #21633, #21487, #19411

Any thoughts?

P.S: If we have `plain-hover()` mixin like the [plain-hover-focus() mixin](https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_hover.scss), can be more simplified:

```scss
a:not([href]) {
  @include plain-hover {
    color: inherit;
    text-decoration: none;
  }
}
```
