### ISSUE TITLE
make btn-outline in input-group-append sexy

### ISSUE THREAD

**Issue by Yahasana** [twbs/bootstrap#28013]
![rsek1 5e a6 yp 5e w](https://user-images.githubusercontent.com/97450/50910423-b6f25580-1468-11e9-8ec0-f85da79178b7.png)
```css
.input-group-append .btn-outline-secondary { border-color:#ced4da }
```
