### ISSUE TITLE
Add support for forced breaks in .flex.flex-wrap

### ISSUE THREAD

**Issue by SPodjasek** [twbs/bootstrap#28151]
It would be nice if Bootstrap could include support for 'forced' breaks in flex-based containers. This could be achieved by adding class similar to this:
```css
.flex-break {
  flex-basis: 100%;
  width: 0;
  height: 0;
  overflow: hidden;
  display: inline-block;
}
```
Visual demo can be found here: https://codepen.io/spodjasek/pen/ErZREK
