### ISSUE TITLE
Request for font weight 600

### ISSUE THREAD

**Issue by rxbracho** [twbs/bootstrap#28168]
I have a fairly complex application where information in dynamic pages are often shown in tables.  The `<thead>` rows of which look <u>much</u> better using `font-weight: 600`.  I have created a class, arbitrarily named `.font-weight-medium`:

```css
.font-weight-medium {
    font-weight: 600 !important;
}
```

I see an issue (#18433) that wanted it to be called "semi-bold" instead of "medium", that would be fine, too.

I just try to "push" those things out of my CSS file and onto the "platform", which includes Bootstrap.  Thanks.

**Comment by bardiharborow** [comment]
While Bootstrap includes some "utility" classes, these go against the fundamental idea of separating CSS and HTML (i.e. `class="font-weight-medium"` is hardly more semantic than `style="font-weight: 600`). Ideally, you should be using:

```css
.relevant-table-class thead {
    font-weight: 600 !important;
}
```

Bootstrap is a base, and you should expect to extend it with your application classes rather than being overly reliant on our utilities. On the basis that we include too many of these things as it is, and that mdo has already rejected the idea, I suspect we won't be including this.
