### ISSUE TITLE
Carousel slide (fade) flicker at the end of rotation transition

### ISSUE THREAD

**Issue by renejackowski** [twbs/bootstrap#28296]
On Safari (macOS/iOS), the fade transition from the last to the first slide causes an flicker for a moment. Prevent this by set `z-index` property value one step lower:

```
.carousel-fade .active.carousel-item-left,
.carousel-fade .active.carousel-item-right {
  z-index: 0; /* set to -1 and prevent flicker on Safari */
  opacity: 0;
  transition: 0s 0.6s opacity;
}
```

Tested in Safari 11.1.2 and Mobile Safari 12.1.4.

**Comment by mdo** [comment]
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbin.com) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._

**Comment by Tekman03** [comment]
Had same problem on https://whatsmybrowser.org/b/P8WYDY3 (iPhone Safari 12.1)

@renejackowski 's fix solves the problem perfectly. I have found that the problem can also be found on [Bootstrap's website](https://getbootstrap.com/docs/4.3/components/carousel/#crossfade) when viewed on all iPhones that I have tried.

**Comment by XhmikosR** [comment]
@twbs/css-review: can you confirm this?

**Comment by MartijnCuppens** [comment]
I can't reproduce this via browserstack.

**Comment by ysds** [comment]
I can see the flicker behavior on https://getbootstrap.com/docs/4.3/components/carousel/#crossfade.

But it seems to have been fixed for now.
https://twbs-bootstrap.netlify.com/docs/4.3/components/carousel/#crossfade.

**Comment by MartijnCuppens** [comment]
@renejackowski, can you confirm this is fixed now:
twbs-bootstrap.netlify.com/docs/4.3/components/carousel/#crossfade.

**Comment by renejackowski** [comment]
@MartijnCuppens, confirmed. It’s all about the transition:

```
--- getbootstrap.com/docs/4.3/dist/css/bootstrap.min.css
+++ twbs-bootstrap.netlify.com/docs/4.3/dist/css/bootstrap.min.css
@@ -3,5 +3,5 @@ .carousel-item:

-transition: -webkit-transform .6s ease-in-out;
-transition: transform .6s ease-in-out;
-transition: transform .6s ease-in-out,-webkit-transform .6s ease-in-out
+transition: transform .6s ease-in-out
```

**Comment by XhmikosR** [comment]
Isn't that the same thing, minus the prefixes?

**Comment by MartijnCuppens** [comment]
> Isn't that the same thing, minus the prefixes?

Not really, this declaration was placed *after* the unprefixed version:
```diff
-transition: transform .6s ease-in-out,-webkit-transform .6s ease-in-out
```
That might have influenced the behaviour or the transition. Anyway, glad this is fixed now 😉

**Comment by XhmikosR** [comment]
It's "fixed" because we change the targeted browsers in v5. In v4 I doubt it has changed. And this comes from autoprefixer.

**Comment by XhmikosR** [comment]
https://v4-dev-xmr--twbs-bootstrap.netlify.com/docs/4.3/dist/css/bootstrap.css

```css
.carousel-item {
  position: relative;
  display: none;
  float: left;
  width: 100%;
  margin-right: -100%;
  -webkit-backface-visibility: hidden;
  backface-visibility: hidden;
  transition: -webkit-transform 0.6s ease-in-out;
  transition: transform 0.6s ease-in-out;
  transition: transform 0.6s ease-in-out, -webkit-transform 0.6s ease-in-out;
}
```

So, if you still insist it's a bug, this should be reported upstream.
