### ISSUE TITLE
Expand `position-fixed` into responsive, ie `position-fixed-lg-up`

### ISSUE THREAD

**Issue by tidelake** [twbs/bootstrap#28350]
I dug around an hour, sure I'd find this, tho i didn't. It is small, tho it would help responsive layout. In my case, I have a nav sidebar, fixed when 'lg' and 'sm', but i need to make it display as block on tablets and phones.
Thank you. 
```html
<header class="position-fixed[-md-up|-md-lg-xl]">
  <nav>
  </nav>
</header>
```

**Comment by muuvmuuv** [comment]
To get it more into Bootstrap philosophy I would more likely do `p-[breakpoint]-[value]`, see [Display Property](https://getbootstrap.com/docs/4.3/utilities/display/).

_utilities/\_position.scss_:

```scss
$positions: static, relative, absolute, fixed, sticky;

@each $breakpoint in map-keys($grid-breakpoints) {
  @include media-breakpoint-up($breakpoint) {
    $infix: breakpoint-infix($breakpoint, $grid-breakpoints);

    @each $value in $positions {
      .p#{$infix}-#{$value} {
        position: $value !important;
      }
    }
  }
}
```
