### ISSUE TITLE
.text-break doesn't work on block elements on Firefox and Edge

### ISSUE THREAD

**Issue by Cnorp** [twbs/bootstrap#28381]
# Problem
When I added in a ```.row``` two ```.col``` and placed a long string of text without breaks in one (then added ```.text-break```), I noticed the following features in browsers:
* In Chrome it works normally;
* In Firefox it breaks column on new line;
* In Edge it doesn't work at all. 

[Link to the test case](https://www.w3schools.com/code/tryit.asp?filename=G1MSU4Y43TLF)

# Solution
None of the browsers interpret this feature properly: ```word-break: break-word !important;``` because Firefox and Edge considers the parameter like ```break-word``` incorrect.
But if change it to ```word-break: break-all !important;``` it works correctly.

**Comment by bardiharborow** [comment]
The relevant code is [scss/utilities/_text.scss#L65-L68](https://github.com/twbs/bootstrap/blob/v4.3.1/scss/utilities/_text.scss#L65-L68). `overflow-wrap` [only applies to inline elements](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap), which `.col` isn't. If we want to properly support block elements, we'll need to use this:
```scss
.text-break {
  // for inline elements
  word-break: break-word !important; // IE & < Edge 18
  word-break: break-all !important;
  // for block elements
  overflow-wrap: break-word !important;
}
```
