### ISSUE TITLE
is `text-decoration: underline; text-decoration: underline dotted;` still necessary?

### ISSUE THREAD

**Issue by leeoniya** [twbs/bootstrap#28723]
the source of `_reboot.scss` has this:

```scss
// Abbreviations
//
// 1. Duplicate behavior to the data-* attribute for our tooltip plugin
// 2. Add the correct text decoration in Chrome, Edge, IE, Opera, and Safari.
// 3. Add explicit cursor to indicate changed behavior.
// 4. Remove the bottom border in Firefox 39-.
// 5. Prevent the text-decoration to be skipped.

abbr[title],
abbr[data-original-title] { // 1
  text-decoration: underline; // 2
  text-decoration: underline dotted; // 2
  cursor: help; // 3
  border-bottom: 0; // 4
  text-decoration-skip-ink: none; // 5
}
```

is it still necessary to have both `text-decoration: underline;` and `text-decoration: underline dotted;`. it's been quite some time since this "hack" was introduced and maybe it's no longer necessary. here's the relevant discussion from 2016: https://github.com/necolas/normalize.css/pull/468#issuecomment-174107494

thanks!

**Comment by ysds** [comment]
I've not tested those needs, but the latest (8.0.1) normalize.css has both.

https://github.com/necolas/normalize.css/blob/8.0.1/normalize.css#L87-L88

**Comment by mdo** [comment]
Since normalize.css still has it, we'll be leaving it intact. Thanks!

**Comment by gMan1990** [comment]
@mdo 

* Duplicate property 'text-decoration' found.
https://github.com/twbs/bootstrap/blob/8fa0d3010112dca5dd6dd501173415856001ba8b/dist/css/bootstrap-reboot.css#L57
```css
abbr[data-original-title] {
  text-decoration: underline;
  -webkit-text-decoration: underline dotted;
  text-decoration: underline dotted;
  cursor: help;
  border-bottom: 0;
  -webkit-text-decoration-skip-ink: none;
  text-decoration-skip-ink: none;
}
```

* Duplicate property 'outline' found.
https://github.com/twbs/bootstrap/blob/8fa0d3010112dca5dd6dd501173415856001ba8b/dist/css/bootstrap-reboot.css#L203
```css
button:focus {
  outline: 1px dotted;
  outline: 5px auto -webkit-focus-ring-color;
}
```
