### ISSUE TITLE
add -webkit-text-decoration to _reboot.scss

### ISSUE THREAD

**Issue by leeoniya** [twbs/bootstrap#28722]
the source of `_reboot.scss` has this:

```scss
// Abbreviations
//
// 1. Duplicate behavior to the data-* attribute for our tooltip plugin
// 2. Add the correct text decoration in Chrome, Edge, IE, Opera, and Safari.
// 3. Add explicit cursor to indicate changed behavior.
// 4. Remove the bottom border in Firefox 39-.
// 5. Prevent the text-decoration to be skipped.

abbr[title],
abbr[data-original-title] { // 1
  text-decoration: underline; // 2
  text-decoration: underline dotted; // 2
  cursor: help; // 3
  border-bottom: 0; // 4
  text-decoration-skip-ink: none; // 5
}
```

which gets compiled to:

```scss
abbr[title],
abbr[data-original-title] {
  text-decoration: underline;
  -webkit-text-decoration: underline dotted;
  text-decoration: underline dotted;
  cursor: help;
  border-bottom: 0;
  -webkit-text-decoration-skip-ink: none;
  text-decoration-skip-ink: none;
}
```

something in the Bootstrap's SASS chain is adding the `-webkit-text-decoration` variants. this is inconsistent with the rest of the file which does not rely on SASS to add `-webkit` versions of properties. i ran into this issue when compiling `_reboot` with https://github.com/medialize/sass.js/ and discovered that these were missing from a vanilla sass compile.

while we're on the `text-decoration` topic, is it still necessary to have both `text-decoration: underline;` and `text-decoration: underline dotted;`. it's been quite some time since this "hack" was introduced and maybe it's no longer necessary. here's the relevant discussion from 2016: https://github.com/necolas/normalize.css/pull/468#issuecomment-174107494

thanks!
