### ISSUE TITLE
"Card Integrated Tabs" active background should default to $card-bg.

### ISSUE THREAD

**Issue by shaneparsons** [twbs/bootstrap#28820]
### Is your feature request related to a problem? Please describe...

When using [Card Integrated Tabs](https://getbootstrap.com/docs/4.1/components/card/#navigation), the active tab background defaults to `$body-bg`.

### Describe the solution you'd like

The active tab background should default to `$card-bg` rather than `$body-bg`, to match the background of the card.

### Describe alternatives you've considered

It can easily be overridden with scss, e.g.
```scss
.card-header-tabs .nav-link.active {
  background: $card-bg;
  border-color: $card-border-color $card-border-color $card-bg;
}
```
 but I believe it makes sense to not have to go down that road.

### Additional context

![Screen Shot 2019-05-23 at 4 31 17 PM](https://user-images.githubusercontent.com/5495493/58284628-03d02c00-7d79-11e9-898a-e08b857fe964.png)
