### ISSUE TITLE
Outline to modal .close

### ISSUE THREAD

**Issue by danielpaz6** [twbs/bootstrap#29302]
Once you've clicked on the Close button of [Modals,](https://getbootstrap.com/docs/4.0/components/modal/) it seems like outline is being showed.

A way to fix that:
```css
.modal-header .close:focus {
    outline: 0;
}
```

That worked for me.
