### ISSUE TITLE
Layered box-shadows

### ISSUE THREAD

**Issue by midzer** [twbs/bootstrap#29463]
Hi all,

I stumbled upon this article https://tobiasahlin.com/blog/layered-smooth-box-shadows/ and thought this approach might be an idea to improve our `.shadow` utilities.

Whether those additional bytes are worth it, depends on your comments about this topic.

Have a nice day
midzer

**Comment by MartijnCuppens** [comment]
From an aesthetic point of view, I like it. We'll have to see the difference to really decide if it's worth it.

**Comment by azhrhussain** [comment]
I think it's a great suggest by @midzer; I normally use this approach when I building enterprise web apps

**Comment by mdo** [comment]
Awhile back I created a function and mixin after reading Tobias's post. See https://codepen.io/emdeoh/pen/zYYGZGx.

```scss
@function diffuse-shadows($size, $color: rgba(0,0,0,.125), $multiply: false) {
  $val: 0 1px 1px $color;
  @for $i from 1 through $size {
    @if $i % 2 == 0 {
      @if $multiply == true {
        $i: $i * 2;
      }
      $val: #{$val}, 0 #{$i}px #{$i}px #{$color};
    }
  }
  @return $val;
}

@mixin diffuse($size, $color, $multiply) {
  box-shadow: diffuse-shadows($size, $color, $multiply);
}

.mixin-sm { @include diffuse(4, rgba(0,0,0,.1), false); }
.mixin    { @include diffuse(8, rgba(0,0,0,.075), false); }
.mixin-lg { @include diffuse(16, rgba(0,0,0,.05), false); }
.mixin-xl { @include diffuse(16, rgba(0,0,0,.05), true); }
```
