### ISSUE TITLE
Weird SCSS with .text#{infix}-center

### ISSUE THREAD

**Issue by nmaxcom** [twbs/bootstrap#29513]
All of a sudden I'm getting errors in Pinegrow referring to the file `/Users/path/to/node_modules/bootstrap/scss/utilities/_text.scss`. More specifically, this bit of code:

```scss
// Responsive alignment
@each $breakpoint in map-keys($grid-breakpoints) {
    @include media-breakpoint-up($breakpoint) {
        $infix: breakpoint-infix($breakpoint, $grid-breakpoints);

        .text#{$infix}-left {
            text-align: left !important;
        }

        .text#{$infix}-right {
            text-align: right !important;
        }

        @media (max-width:575px) {
            .text# {
            }

            -center {
                text-align: center !important;
                margin-top: 0;
                margin-bottom: 0;
            }
        }
    }
}
```

The complaint it gives me is this (can't copy text):

![image](https://user-images.githubusercontent.com/8936090/66635825-430bf600-ec10-11e9-9714-2d1fc1c411f1.png)

Indeed, this part doesn't make a lot of sense:

```scss
        @media (max-width:575px) {
            .text# {
            }

            -center {
                [...]
```

So I thought it must be a packet/module fart, so I deleted bootstrap from node_modules and did an `npm i`. In the same place then I see this:

```scss
// Responsive alignment

@each $breakpoint in map-keys($grid-breakpoints) {
  @include media-breakpoint-up($breakpoint) {
    $infix: breakpoint-infix($breakpoint, $grid-breakpoints);

    .text#{$infix}-left   { text-align: left !important; }
    .text#{$infix}-right  { text-align: right !important; }
    .text#{$infix}-center { text-align: center !important; }
  }
}
```

Which looks fine. But when I start working again with my stylesheet which has `@import '../../../node_modules/bootstrap/scss/bootstrap';` on top, that _text.scss part breaks again.

I don't know why, because it's not like it's being compiled to CSS, it's still SCSS, just changed to bad syntax.

Versions:
- sass (-g module): 1.23.0 compiled with dart2js 2.5.1
- Bootstrap: ^4.3.1
- WebStorm: 2019.2.2
- Pinegrow: 5.7
- macOS: 10.12.6
