### ISSUE TITLE
.text-decoration-underline .text-decoration-line-through missing from bootstrap-utilities.css

### ISSUE THREAD

**Issue by kopax** [twbs/bootstrap#29790]
This is the generated `bootstrap-utilities.css`: https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap-utilities.css#L1145

This is the one class available for `text-decoration`:

```css
.text-decoration-none {
  text-decoration: none !important;
}
```

This is the `$utilities` for `text-decoration`: https://github.com/twbs/bootstrap/blob/master/scss/_utilities.scss#L427

It as the following configuration:

```js
    "text-decoration": (
      property: text-decoration,
      values: none underline line-through
    ),
```

I expect to have the 3 following generated class (instead of just one):

```css
.text-decoration-none {
  text-decoration: none !important;
}

.text-decoration-underline {
  text-decoration: underline !important;
}

.text-decoration-line-through {
  text-decoration: line-through !important;
}
```

branch: `master`
