### ISSUE TITLE
min and max width classes using -xs, -sm, ... postfixes

### ISSUE THREAD

**Issue by kaan-atakan** [twbs/bootstrap#30092]
I often like to use flexbox and combine it with wrapping to get responsive layouts. I find it to be more flexible and intuitive than the grid. A big part of making this work is specifying min-widths. Max widths can be useful too if you are dealing with large screens. Unfortunately the sizing utilities of bootstrap have been quite limited forcing me to write my own utility classes for this purpose.

It would be nice to have the following classes added to bootstrap and documented:

```css
.min-xs {
    min-width: 180px;
}
.min-sm {
    min-width: 200px;
}

.min-md {
    min-width: 375px;
}

.
.
.

.max-md {
     max-width: 750px;
}

.max-lg {
    max-width: 1060px;
}

.max-xl {
    max-width: 1900px;
}
```

The widths chosen here are slightly smaller than half the  iphone 6/7/8, iphone6/7/8 plus, ipad, vertical hd screen and horizontal hd screen horizontal resolutions for min, and slightly less than the full horizontal resolution on max. The 14-20 pixels subtracted from actual screen sizes are to account for margins paddings and borders.
