### ISSUE TITLE
Screen size indicator for development

### ISSUE THREAD

**Issue by anthony0030** [twbs/bootstrap#30146]
Here is the code I use when testing different breakpoints. It would be perfect to have something like this activatable by a flag.

``` SCSS
body::before{
  color: red;
  position: fixed;
  top: 5px;
  left: 5px;
  padding: 2px;
  background-color: white;
  border-radius: 10%;
  border: 1px solid black;
  z-index: 100000000000;
  opacity: 0.3;
  @each $breakpoint in map-keys($grid-breakpoints){
    @include media-breakpoint-up($breakpoint){
      content: to-upper-case("#{$breakpoint}");
    }
  }
}
```
