### ISSUE TITLE
Table coloring should be applied to TD, not to TR

### ISSUE THREAD

**Issue by lllopo** [twbs/bootstrap#30163]
Currently, the **$table-bg**, **$table-accent-bg** etc are applied to the table TR. This does not allow tables with transparent borders, done with **background-clip: padding-box** and **$table-border-color: transparent**. If the colors get applied to TH/TD instead, this would work nicely.

**Comment by ysds** [comment]
Could you show a live demo via [Stackblitz](https://stackblitz.com/) or any other?

**Comment by lllopo** [comment]
@ysds There you go : [CodeSandbox](https://codesandbox.io/s/bootstrap-transparent-borders-y60zm?fontsize=14&hidenavigation=1&theme=dark)

As you can see, I've set **$table-border-color** to **transparent** and no borders appear visually, although I've set the TD style **background-clip: padding-box;**. The bottom table that has no bootstrap styling, but the background color is applied to the TD's instead of the TR's (as bootstrap does) and there the transparent borders are visible, since there is no background color on the TR to mask them.

**Comment by ysds** [comment]
Due to the complexity of CSS priorities and the support for table hover and table stripes, it would be difficult for Bootstrap to allow such customization unless an intelligent solution is proposed. At least, does the following code solve what you want to do?

```scss
$table-bg: transparent;
$table-border-width: 2px;
$table-border-color: transparent;

.table {
  td {
    background-clip: padding-box;
    background-color: red;
  }
}
```
