### ISSUE TITLE
[disabled] or .disabled

### ISSUE THREAD

**Issue by GeoSot** [twbs/bootstrap#30320]
Hello,

I have done a search but didn't find something on this.

may I propose on _reboot.scss to add something like the following? 
```css
[disabled], .disabled{
pointer-events:none !important;
}
```
