### ISSUE TITLE
Card-group class looses its display:flex; when screen < 576px

### ISSUE THREAD

**Issue by yoannlepetit** [twbs/bootstrap#30366]
Hi,

After upgrading from `4.3.1` to `4.4.1` I've noticed that `.card-group` class was loosing it attribute `display: flex;` when resizing screen under the `576px`.

Here is the CSS class I get from Dev Tools on the documentation's bootstrap page  (https://getbootstrap.com/docs/4.4/components/card/#card-groups):

```css
@media (min-width: 576px) {
    .card-group {
        display:-ms-flexbox;
        display: flex;
        -ms-flex-flow: row wrap;
        flex-flow: row wrap
    }
   ...
}
```

In the documentation, it is said 
> Card groups use display: flex;
This may be confusing.

Operating system: macOs 10.15.3 (19D76)
Browsers: 
- Safari Version 13.0.5 (15608.5.11)
- Firefox 73.0.1 (64 bits)
- Brave Version 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
