### ISSUE TITLE
"dead area" between radio/checkbox and label with form-check-input

### ISSUE THREAD

**Issue by AzzaAzza69** [twbs/bootstrap#30535]
currently this gives an unclickable area between the [x] and label or the (.) and label:
```css
.form-inline .form-check-input {
...
    margin-right: 0.25rem;
...
}
```

I suggest removing the margin-right and applying a padding-left to the label instead:
```css
.form-inline .form-check-input ~ .form-check-label{
	padding-left: 0.25rem;
}
```
