### ISSUE TITLE
[Feature request] resizable table

### ISSUE THREAD

**Issue by jimmywarting** [twbs/bootstrap#30631]
Just wanted to make resizable columns in a table so i built this:
https://jsfiddle.net/xodtjy2v/2/

it's not that advance, it's simple lightweight and don't depend on any javascript at all. doe it's not as good as any javascript solution that can resize a hole column at any y-axis.

doing this css trick on x-axis was really buggy and not even worth implementing without a js solution.

either way. i thought it would be worth implementing this into bootstrap core:

```css
.table.table-resize-y thead th {
  overflow-y: auto;
  resize: horizontal;
}


 /* optional */
.table.table-resize-y ::-webkit-resizer {
    background-color: transparent;
}
```

huge benefit with little css and no extra DOM elements 😉
