### ISSUE TITLE
Make link achor without href styling configurable

### ISSUE THREAD

**Issue by syabro** [twbs/bootstrap#30761]
@mdo something like 
```scss
a:not([href]):not([tabindex]) {
  @if stylePlaceholdersLinks {
    color: inherit;
    text-decoration: none;

    @include hover-focus {
      color: inherit;
      text-decoration: none;
    }

    &:focus {
      outline: 0;
    }
  }
}
```

with `stylePlaceholdersLinks` turned on by default.

Because a lot of projects
- don't use links as placeholders
- use `a` without `href` or `tabIndex`

So the change wouldn't affect anyone by default, but if it does some harm  user will be able to turn it off?
