### ISSUE TITLE
is-invalid style should override pseudo selectors

### ISSUE THREAD

**Issue by xyide** [twbs/bootstrap#30822]
In the case where the `:valid` pseudo-selector is specified on a form-control along with the `is-invalid` class, then the style of the `is-valid` class should take priority.

**Example Scenario:**
A registration form is submitted and client side HTML validation is performed using `form.checkValidity()`.  The required username field is considered valid and internally has the `:valid` pseudo selector set.  An AJAX request is then submitted to the server.  The server responds saying the username is already registered, so we set the 'is-invalid' class in the form control.

At this point the border around the form control remains green instead of changing to red because the `.was-validated .form-control:valid` style is being applied and overriding style specified by `.form-control.is-invalid`.

There is a fiddle at https://jsfiddle.net/r4g06a21/ to demonstrate the issue.

To resolve this issue, I had to create the following styles:

```css
.was-validated .form-control:valid.is-invalid {
    border-color: red;
    background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='%23f83245' viewBox='-2 -2 7 7'%3e%3cpath stroke='%23f83245' d='M0 0l3 3m0-3L0 3'/%3e%3ccircle r='.5'/%3e%3ccircle cx='3' r='.5'/%3e%3ccircle cy='3' r='.5'/%3e%3ccircle cx='3' cy='3' r='.5'/%3e%3c/svg%3E"); 
}

.was-validated .form-control:valid:focus.is-invalid:focus {
      border-color: red; 
}
```

The fiddle at https://jsfiddle.net/bfLzvad3/ demonstrates this solution.  Not sure if it is the best approach for the fix, but it does what I need it to do.
