### ISSUE TITLE
RTL implementation

### ISSUE THREAD

**Issue by ffoodd** [twbs/bootstrap#30918]
There have been quite a few dicussions around this in Bootstrap, and it's probably been asked more often than any other feature.

## Pre-requisites

1. Should work in [all supported browsers](https://twbs-bootstrap.netlify.app/docs/5.0/getting-started/browsers-devices/), meaning Edge Legacy and Safari 10 for the oldest.
2. Should work seamlessly with all our components and utilities.
3. Should be tested, probably with new examples templates.
4. Should be maintainable, thus not lay on hacky things.

Am I missing any pre-requisite, @twbs/team?

FWIW, one of the best resource I ever read about RTL is very recent: [RTL Styling 101 by Ahmad Shadeed](https://www.rtlstyling.com/posts/rtl-styling/).

## Solutions

Let me try to sum up the various ways to tackle this in v5.

### Another `dist` file

This is what we used in [Boosted v4](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap), using [rtlcss](https://rtlcss.com).

#### Pros
- another file, not a single bloated one
- easy to setup

#### Cons
- some values have to be ignored, and rtlcss is not very pleasant to use with clunky CSS comments to flag things: https://rtlcss.com/learn/usage-guide/control-directives/#ignore
- a few overrides were required in Boosted, mostly around `transform`s and inlined SVGs

### Logical properties

They're meant to be **the** standard way to do. [However Edge Legacy doesn't support them](https://caniuse.com/#search=logical%20properties), so we're kinda stuck with this.

[PostCSS-logical](https://github.com/csstools/postcss-logical) is meant to handle this in two ways:
1. each logical property results in two new declarations, suffixed with `:dir()`
2. each logical property only gets a LTR fallback: `text-align: left; text-align: start;`

Both of them will result in a bloated filesize, and the second—despite being the ordinary fallback—won't allow Edge Legacy to handle RTL.

#### Pros
- future-proof
- standardized and CSS-y

#### Cons
- Lack of support
- Filesize (directly due to the lack of support)

#### Resources
- [Adrian Roselli's post about logical properties](https://adrianroselli.com/2019/11/css-logical-properties.html)
- [Can I Use logical properties?](https://caniuse.com/#search=logical%20properties)
- [Chen Hui Jing's "CSS for internationalisation"](https://www.chenhuijing.com/blog/css-for-i18n/)
- [Andy Bell's Piccalilli's post about logical properties](https://piccalil.li/tutorial/css-logical-properties/)

### Sassy way

As suggested in the most recent issue about RTL— #28797— a sassy way is possible.

I'd be in favor of a simpler way to handle things: 
- using a mixin, **like we do for media queries**: `@include rtl()`
- **checking for a boolean** before going ahead, like we do for shadows or rounded: `@if $enable-rtl {}`
- then wrapping mixin content in `:dir(rtl)` using `@content`
- and then, just use CSS.

#### Pros
- Sass only
- Consistent with our current way to do things
- Can be `false` by default

#### Cons
- Requires that we write the RTL styles by ourselves
- Source code bloat
- A single bloated output when enabled

## So…

My CSS geekery would like to go with Logical properties; rtlcss seems simpler to me since I'm already used to it and it's a robust and proven solution; the sassy way looks a bit naive…

**I'd like to hear opinions and suggestions before trying something**.

## Related issues

Thanks @ZaidBarghouthi for listing this!

#28797 #28238 #24807 #27123 #27122 #26879 #26818 #19545 #26299 #25422 #24662 #23703 #24332 #23117 #22708 #22137 #21619 #21180 #20293 #19555 #20075 #19787 #19703 #19668 #19643 #19545 #19379 #18184 #17595 #16455 #16419 #15717 #15700 #15509 #15479 #15433 #14717 #14510 #13564

**Comment by andresgalante** [comment]
Great write up 🎉  

I am with you about going logical properties if we could drop support for some browsers just for this feature. Can't we?

**Comment by ffoodd** [comment]
You're suggesting using logical properties without any fallback, is that right?

If so, let's sum up browsers that we'd stop supporting. Datas are coming from [Browsel.ist](https://browserl.ist/?q=%3E%3D+1%25%2C+last+1+major+version%2C+not+dead%2C+Chrome+%3E%3D+60%2C+Firefox+%3E%3D+60%2C+Edge+%3E%3D+16.16299%2C+iOS+%3E%3D+10%2C+Safari+%3E%3D+10%2C+Android+%3E%3D+6%2C+not+Explorer+%3C%3D+11%2C+not+ExplorerMobile+%3C%3D+11)—using [`master`'s current `.browserlistrc`](https://github.com/twbs/bootstrap/blob/master/.browserslistrc)— and [Can I Use logical properties?](https://caniuse.com/#search=logical%20properties) to cross-check browser support, but also get global usage stats.

**Edge Legacy 16, 17, 18**

Global usage of **2.17%**, passing two checks in BrowserList: `>= 1%` and `Edge >= 16.16299`
**It has no support for logical properties at all**.

**Chrome <= 69**, **Safari / iOS Safari  <=12.1**, **Opera <= 66**, UC Browser, QQ Browser, Baidu Browser, Opera Mobile.
All of them have partial support for logical properties:
- `*-start` and `*-end` values for `margin`, `border` and `padding`, not the inline/block type values as defined in the spec.
- `*-before` and `*-end` for `*-block-start` and `*-block-end` properties 
- `start` and `end` values for `text-align

I don't know (yet) what this partial support implies, but I'll investigate :)

FWIW, ["CSS Logical Properties and Values" on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties) lists all logical properties—and a dedicated compatitibility table for each.
`

**Comment by ffoodd** [comment]
FYI, I started something based on RTLCSS.

This issue is still a place for discussion—so any help, advice and even opinions are welcome :)

**Comment by DJafari** [comment]
@ffoodd i think best way is sassy way
something like this :

```sass
$hasRTL = true;

.text-start {
  text-align: left;
}
@if $hasRTL {
  [dir="rtl"] .text-start {
    text-align: right;
  }
}
```

**Comment by ferhado** [comment]
My solution to support RTL is like in example:

[dir="ltr"] {
   text-start-* {
      text-align: left
   }
   text-end-* {
      text-align: right
   }
   padding-start-* {
      padding-left: *
   }
   padding-end-* {
      padding-right: *
   }
}

[dir="rtl"] {
   text-start-* {
      text-align: right
   }
   text-end-* {
      text-align: left
   }
   padding-start-* {
      padding-right: *
   }
   padding-end-* {
      padding-left: *
   }
}

**Comment by ferhado** [comment]
My solution to support RTL is like in example:
```scss
[dir="ltr"] {
   text-start-* {
      text-align: left
   }
   text-end-* {
      text-align: right
   }
   padding-start-* {
      padding-left: *
   }
   padding-end-* {
      padding-right: *
   }
}

[dir="rtl"] {
   text-start-* {
      text-align: right
   }
   text-end-* {
      text-align: left
   }
   padding-start-* {
      padding-right: *
   }
   padding-end-* {
      padding-left: *
   }
}
```

**Comment by ferhado** [comment]
My solution to support RTL is like in example:
```scss
[dir="ltr"] {
   text-start {
      text-align: left
   }
   text-end {
      text-align: right
   }
   padding-start-* {
      padding-left: *
   }
   padding-end-* {
      padding-right: *
   }
}

[dir="rtl"] {
   text-start {
      text-align: right
   }
   text-end {
      text-align: left
   }
   padding-start-* {
      padding-right: *
   }
   padding-end-* {
      padding-left: *
   }
}
```

**Comment by ferhado** [comment]
My solution to support RTL is like in example:
```scss

For LTR:

[dir="ltr"] {
   .text-start {
      text-align: left
   }
   .text-end {
      text-align: right
   }
   .padding-start-* {
      padding-left: *
   }
  .padding-end-* {
      padding-right: *
   }
}

For RTL:

[dir="rtl"] {
   .text-start {
      text-align: right
   }
   .text-end {
      text-align: left
   }
   .padding-start-* {
      padding-right: *
   }
   .padding-end-* {
      padding-left: *
   }
}
```
