### ISSUE TITLE
use placeholder selector in scss (eg. %btn) to be able to @extend safely

### ISSUE THREAD

**Issue by SergiArias** [twbs/bootstrap#30926]
I am a long time user of bootstrap. And lately, I am used to use my own naming convention in most of the classes to avoid clutter. I prefer it this way as the code gets quite clean and not bootstrap recognizable.

But extending a bootstrap class directly can create a huge mess as it extends everything recursively. So I think a very good and simple improvement would be to use the placeholder selector in all the classes.

For example, a button:

The bootstrap selector would be

```scss
%btn {
  // bootstrap definition of btn
}

.btn {
@extend %btn;
}
```

Then, if I want to create my own button I just would write:
```scss
.my-amazing-bootstrap-based-button {
  @extend %btn;
  @extend %btn-outline-primary;

  color: whatever;
  // more custom definitions over the bootstap button.
}
```

It would be super elegant without adding any extra code, as when compiling the % selectors only get included in the css output if extended.
