### ISSUE TITLE
Unstyled link class utility

### ISSUE THREAD

**Issue by caub** [twbs/bootstrap#31013]
It'd be helpful for example in this scenario:

```html
<a id="foo" href="#foo" class="link-unstyled">
  <h4>Foo</h4>
</a>
```

**Comment by caub** [comment]
I defined that class for now

```css
.link-unstyled, .link-unstyled:hover, .link-unstyled:active, .link-unstyled:focus {
  color: unset;
  text-decoration: unset;
  cursor: default;
}
```
