### ISSUE TITLE
Thumb is difficult to drag using touch input with custom <input type="range"> controls

### ISSUE THREAD

**Issue by polarstoat** [twbs/bootstrap#31241]
When using custom `<input type="range">` controls with `.custom-range`, the thumb is difficult to drag using touch input (mobile and tablet). This occurs on iOS and Android, across browsers.

I recently observed some users interacting with the Bootstrap range sliders in my own project, and almost unanimously they had difficulties with tapping the thumb to drag it. Of course, anywhere in the track can be tapped to 'jump' the thumb to that position, but that doesn't seem to be the primary way users try to interact with it.

Could the hitbox for the thumb be increased in size? Perhaps with the `::before` / `::after` pseudo elements. It looks like material-ui does something like this, and in my own testing their slider thumb is far easier to drag.

The current effective hitbox is a `1.4rem` square (marked in transparent green):
![current](https://user-images.githubusercontent.com/20626621/86532180-b8ff6e00-bebf-11ea-94aa-d61f24564f45.png)

Could this be increased to twice the value of `$custom-range-thumb-width` — so by default a `2rem` diameter circle? (marked in transparent green):
![proposed](https://user-images.githubusercontent.com/20626621/86532207-f5cb6500-bebf-11ea-853c-090b1a097973.png)

**Comment by polarstoat** [comment]
I've done some more research and it seems like `::before` / `::after` can't be used on `<input>` elements (see [this Stack Overflow answer](https://stackoverflow.com/a/4660434) and [this blog post](https://www.scottohara.me/blog/2014/06/24/pseudo-element-input.html)), so that wouldn't work as a solution.

**Comment by patrickhlauke** [comment]
note that material-UI and similar frameworks end up "faking" the sliders with extra spans/divs etc, wihch in the end break them for users of touch+assistive technologies (i've filed issues with some of them about this).

currently, the bootstrap slider simply adds a bit of style/finesse to the native `<input type="range">`, so the problem is fundamentally one of the browsers not making these controls touch-friendly enough. not sure if there's a clean solution to this at this point, i'm afraid.

**Comment by patrickhlauke** [comment]
though potentially there are some more hacky CSS-based approaches that could be gleaned from https://css-tricks.com/sliding-nightmare-understanding-range-input/

**Comment by polarstoat** [comment]
I've found some success with the below code: ([which is also on CodePen here](https://codepen.io/polarstoat/pen/XWXZzyx))

```scss
.custom-range {
  &::-webkit-slider-thumb {
    background-clip: padding-box;
    border: 0.4rem solid rgba(0, 255, 0, 0.5); // translucent green used to aid development, set to 'transparent' in production
    transform: scale(4);
  }
}
```

It seems promising, but the box-shadow on `:focus` will need fixing.

<img width="757" alt="new" src="https://user-images.githubusercontent.com/20626621/86535483-9299fc80-bed8-11ea-9921-86c0fb8625f6.png">

**Comment by patrickhlauke** [comment]
unfortunately doesn't work in Firefox though. that's the problem generally, cross-platform support for some of these form styling hacks is not great.

**Comment by polarstoat** [comment]
Actually I've got it working in Firefox just fine ([see updated CodePen](https://codepen.io/polarstoat/pen/XWXZzyx)):
```scss
.custom-range {
  &::-webkit-slider-thumb {
    background-clip: padding-box;
    border: 0.4rem solid rgba(0, 255, 0, 0.5);
    transform: scale(4);
  }
  &::-moz-range-thumb {
    background-clip: padding-box;
    border: 0.4rem solid rgba(0, 255, 0, 0.5);
    box-sizing: border-box;
    transform: scale(4);
  }
}
```

I'm not sure why it becomes necessary to explicitly set `box-sizing: border-box;` for Firefox, but with it it seems to look/work exactly as Safari/Chrome.

It seems unlikely we'll see better browser support for touch controls like this anytime soon, and currently the usability of them is quite poor. I don't think this solution (once the `:focus` outline if figured out/fixed) is a particularly hacky one.
