### ISSUE TITLE
Flex layout broken with Version 4.5.1

### ISSUE THREAD

**Issue by MBurchard** [twbs/bootstrap#31435]
The reduced Layout is that...

```html
<div class="h-100">
	<div class="container-fluid h-100 d-flex flex-column">
		<div class="row justify-content-between header">
			<div class="col-sm-9">
				<h3>Customer Identity Management Portal</h3>
			</div>
		</div>
		<div class="row flex-grow-1" style="overflow-y: auto;">
			content area
		</div>
	</div>
</div>
```

```css
html, body {
	height: 100%;
}

.header {
	background-color: #0078dc;
	box-shadow: 0 6.4px 14.4px 0 rgba(0, 0, 0, .132), 0 1.2px 3.6px 0 rgba(0, 0, 0, .108);
	color: #fff;
	height: 42px;
}
```
Under Linux Mint with Firefox 79 and Vivaldi 3.1.1929.48 the layout changes between 4.5.0 and 4.5.1. I have not tested it with another OS.

![grafik](https://user-images.githubusercontent.com/4256302/89387283-8fc23f80-d702-11ea-9a55-de591f076131.png)

![grafik](https://user-images.githubusercontent.com/4256302/89387349-a5376980-d702-11ea-8743-28378542f18e.png)

With 4.5.1 the small bar at the top has the height of the full screen and scrollbar appears.
