### ISSUE TITLE
4.5.2: A firefox built-in full page screenshot moves bootstrap fixed navbar (down)

### ISSUE THREAD

**Issue by ophian** [twbs/bootstrap#31705]
Example page to study
https://getbootstrap.com/docs/4.5/getting-started/download/
which navbar behaviour normally relies on:
```css
.fixed-top {
    position: fixed;
    top: 0;
    right: 0;
    left: 0;
    z-index: 1030;
}
```
in this case
```css
.bd-navbar {
    position: -webkit-sticky;
    position: sticky;
    top: 0;
    z-index: 1071;
}
```
Setting this to  ```position: absolute;``` for the screenshot only fixes the issue.

Is there anything we can do for having this fixed by default on (firefox) print/screenshot cases?
