### ISSUE TITLE
Filesize can be reduced by putting SVG images in --css-variables

### ISSUE THREAD

**Issue by TheNewSound** [twbs/bootstrap#31703]
Some SVG's are used multiple times and the build process/minifier doesn't automatically de-duplicate identical `url("data/image ....")` being used inside CSS files.
```css
:root {
  --bs-image-form-select-indicator: escape-svg($form-select-indicator);
}

.form-select {
  background-image: var(--bs-image-form-select-indicator);
}
```

De-duping inline images by creating a css-variable out of it would save some KB's.
