### ISSUE TITLE
Including Apple Color Emoji in font stack prevents coloring unicode

### ISSUE THREAD

**Issue by paulschreiber** [twbs/bootstrap#31860]
Before opening:
Including `Apple Color Emoji` in the font stack prevents coloring unicode, such as the ✖.

### Config
- Operating system and version: macOS 10.15.7
- Browser and version Chrome 85, Firefox 81

### Codepen
https://codepen.io/paulschreiber/pen/NWrPOjg

### Sample CSS
```css
.remove {
  color: yellow;
  background: black;
}
.fonts {
  font-family: sans-serif;
}
```

### Sample HTML
```html
<span class="remove">✖</span> 
<span class="remove fonts">✖</span>
```

### Actual
![image](https://user-images.githubusercontent.com/86784/95616929-9dfd4680-0a38-11eb-8962-8a2e015801eb.png)

### Expected
![image](https://user-images.githubusercontent.com/86784/95616959-ac4b6280-0a38-11eb-8e80-aa3454af1e9f.png)
