### ISSUE TITLE
.navbar-collapse block occupies 100% width. This causes space issue to other elements placed outside the navbar-collapse block.

### ISSUE THREAD

**Issue by DeboBuiz** [twbs/bootstrap#32383]
- OS: Windows 10
- Browser: Chrome latest

The code in bootstrap-4 uses the following, This works fine

```css
.navbar-collapse {
  flex-basis: 100%;
  flex-grow: 1;
  align-items: center;
}
```

The code in bootstrap-5 uses the following. This causes the words in the btn block that is placed outside the nav-collapse block to break.

```css
.navbar-collapse {
    align-items: center;
    width: 100%;
}
```

![bootstrap5-bug](https://user-images.githubusercontent.com/9299145/101508432-aec92a80-399d-11eb-8b7e-fade27de368c.jpg)
