### ISSUE TITLE
Floating label on textarea overlaps content

### ISSUE THREAD

**Issue by rynop** [twbs/bootstrap#32800]
- Operating system and version: macOS 11.1
- Browser and version: Chrome 87.0.4280.141 (Official Build) (x86_64)

Bug:
![image](https://user-images.githubusercontent.com/372730/104614054-7fb57100-564d-11eb-8619-693ff7390f9c.png)

To reproduce:
1. Visit https://getbootstrap.com/docs/5.0/forms/floating-labels/#textareas
2. Type in 4 lines of text

**Comment by alecpl** [comment]
Confirmed with Chromium 87.0.4280.66 on Linux, no issue in Firefox.

**Comment by TechOverflow** [comment]
Confirmed in Safari 14.0.3.

**Comment by mdo** [comment]
No need for further confirmation, it’s a problem in literally every browser :).

**Comment by rynop** [comment]
I will do my best to circle back around and PR if it's not obvious to you what the fix is.  I spent 5mins on what I thought the obv.  fixes might be, and no 🎲 . LMK. Thanks

**Comment by z3r0101** [comment]
While waiting for the official fix...

.form-floating > .form-control:not(:-moz-placeholder-shown) ~ label {
    opacity: 1;
    color: rgba(0, 0, 0, 0.5);
    background-color: #fff;
    height: auto;
    padding: 0px;
    padding: 0px 0px 0px 10px;
    width: 100%;
    transform: scale(0.982) translateY(0.045rem) translateX(0.1rem);
    border-radius: 5px 0 0 0;
}
.form-floating > .form-control:focus ~ label,
.form-floating > .form-control:not(:placeholder-shown) ~ label,
.form-floating > .form-select ~ label {
    opacity: 1;
    color: rgba(0, 0, 0, 0.5);
    background-color: #fff;
    height: auto;
    padding: 0px 0px 0px 10px;
    width: 100%;
    transform: scale(0.982) translateY(0.045rem) translateX(0.1rem);
    border-radius: 5px 0 0 0;
}
.form-floating > .form-control:-webkit-autofill ~ label {
    opacity: 1;
    color: rgba(0, 0, 0, 0.5);
    background-color: #fff;
    height: auto;
    padding: 0px;
    padding: 0px 0px 0px 10px;
    width: 100%;
    transform: scale(0.982) translateY(0.045rem) translateX(0.1rem);
    border-radius: 5px 0 0 0;
}

**Comment by Attila217** [comment]
Place <label> under <input> inside your Bootstrap code

**Comment by mikacalvo** [comment]
Hello team, there's also another problem linked to floating label in textarea. I feel like the rows attribute is no longer taken into account when we use that feature 😬

**Comment by ffoodd** [comment]
Applying an opaque back plate might be a good idea, as suggested by @z3r0101. Using a `background` however forces us to revamp quite a few things, so may I suggest to add a pseudo-element on `.form-floating` instead, and globally?

Something like `.form-floating::before` that'd be there on every floating forms? Any thougts?

**Comment by ctsstc** [comment]
Here's a not so great option, but it does help avoid broken overlapped interfaces. This option is for single lines it will prevent wrapping, and turn over flow into ellipsis. Unfortunately there's no great way to add anything like a title attribute since the input sits over the label to my understanding -- so you'll get feedback from the input instead like "the field is required". 

This also helps the label regain some lost width from the scaling that occurs when the input is focussed and it gets smaller.

It solves one problem, but creates another :(

```javascript
/* Floating label wrap fix */
.form-floating > .form-control:focus ~ label,
.form-floating > .form-control:not(:placeholder-shown) ~ label,
.form-floating > .form-select ~ label {
  width: 150%;
}

.form-floating > label {
  white-space: nowrap;
  text-overflow: ellipsis;
  width: 100%;
  overflow: hidden;
}```

**Comment by Mohsnb** [comment]
First add class like `input_textarea` to parent div which is `textarea` input then add this css:

```
.form-floating.input_textarea label {
    min-width: 90%;
}

    .form-floating.input_textarea label::before {
        content: "";
        position: absolute;
        top: 0.9em;
        z-index: -1;
        width: 100%;
        height: 1.2em;
        background-color: white;
        box-shadow: 0 0 8px 4px #ffffff;
    }


.form-floating.input_textarea > .form-control:focus ~ label, .form-floating.input_textarea > .form-control:not(:placeholder-shown) ~ label, .form-floating.input_textarea > .form-select ~ label {
    opacity: 0.95;
    color: gray;
}
```

**Comment by MrTSCode** [comment]
> First add class like `input_textarea` to parent div which is `textarea` input then add this css:
> 
> ```
> .form-floating.input_textarea label {
>     min-width: 90%;
> }
> 
>     .form-floating.input_textarea label::before {
>         content: "";
>         position: absolute;
>         top: 0.9em;
>         z-index: -1;
>         width: 100%;
>         height: 1.2em;
>         background-color: white;
>         box-shadow: 0 0 8px 4px #ffffff;
>     }
> 
> 
> .form-floating.input_textarea > .form-control:focus ~ label, .form-floating.input_textarea > .form-control:not(:placeholder-shown) ~ label, .form-floating.input_textarea > .form-select ~ label {
>     opacity: 0.95;
>     color: gray;
> }
> ```

Nice answer @Mohsnb , I'm made some improvement from your answer, in the your answer when we scroll, the text label it didn't cover 100% to top and to the right, so will look like this 
![image](https://user-images.githubusercontent.com/88914794/145916831-f8401acc-b270-4e74-8a90-99cdb52a7062.png)

So instead of using min-width: 90%, then i use 100% + 15% to make sure i'ill cover all. The reason add 15% it was because floating text will scale to .85 (reduce 15% of original scale) when textarea befing focus.  And set height label::before to 100% + 1.5rem + 0.5px; As for 1.5rem is we can use label padding-bottom which is 1rem and add .5rem from label translateY(-.5rem) 0.5px to make sure will cover to top. and set postition to bottom = 1 to make sure ::before position equal to label text position because default label padding-bottom = 1rem;

As for text opacity using rgba because what i want for the label there is no opacity at all or opacty = 1;
And the style must trigger only when textarea is focus or there is a text in it
Here the code 

`.form-floating.input_textarea2>.form-control:focus~label,
.form-floating.input_textarea2>.form-control:not(:placeholder-shown)~label {
    display: block;
    height: auto !important;
    opacity: 1;
    color: rgba(33, 37, 41, .5);
    width: calc(100% + 15%);
}

.form-floating.input_textarea2>.form-control:focus~label::before,
.form-floating.input_textarea2>.form-control:not(:placeholder-shown)~label::before {
    content: '';
    position: absolute;
    bottom: 1rem;
    left: 0;
    width: 100%;
    height: calc(100% - 1.5rem + .5px);
    background-color: white;
    z-index: -1;
    box-shadow: 0 5px 8px 0 #fff;
}`

**Comment by RaenonX** [comment]
This is by far the best fix by far I found for now:

https://stackoverflow.com/a/67334114/11571888

**Comment by maftieu** [comment]
> This is the best-looking fix by far I found for now:
> 
> https://stackoverflow.com/a/67334114/11571888

Here is that answer adapted to SCSS with Bootstrap variables for styling & sizes, and a specific class to target only textareas

```scss
$textarea-floating-label-pseudo-element-height: (
    $form-floating-input-padding-t + ($font-size-base * $line-height-base)
  ) * 0.85 - $form-floating-padding-y;
// look at $form-floating-label-transform for "0.85"

.form-floating-textarea {
  position: relative;

  &:before {
    content: "";
    position: absolute;
    top: $input-border-width;
    left: $input-border-width;
    width: calc(100% - $spacer); /* to show scrollbar */
    height: $textarea-floating-label-pseudo-element-height;
    border-radius: $input-border-radius;
    background-color: $input-bg;
  }

  &.form-control:focus,
  &.form-control:not(:placeholder-shown) {
    padding-top: $textarea-floating-label-pseudo-element-height + ($form-floating-padding-y * 0.5); /* leave a little more space below the label */
  }
}
```

This will look like that:
![image](https://user-images.githubusercontent.com/6186483/163962747-80761d31-f027-44ac-8753-220431eef8e2.png)

**Comment by robphillips** [comment]
First off, kudos to @maftieu for the inspiration. Here is another solution that moves the pseudo element inside the label. Main benefit is the pseudo element doesn't cover the textarea. Thus pointer events work as expected. Added benefit is the pseudo element can be modified as needed based on the element state. SCSS designed to work with all control types.

```scss
// These two variables already included with Bootstrap 5.
$form-floating-label-transform: translateY(-.5rem);
$form-floating-transition: opacity .1s ease-in-out, transform .1s ease-in-out, font-size .1s ease-in-out;

.form-floating {
  $form-floating-label-font-size: .75rem;
  $form-floating-label-line-height: $line-height-base;
  $form-floating-label-height: $form-floating-label-font-size * $form-floating-label-line-height + ($form-floating-padding-y * .5);

  label {
    &:before {
      display: none;
      content: '';
      position: absolute;
      z-index: -1;
      top: .5rem;
      left: $input-border-width;
      width: calc(100% - $spacer - 1px);
      height: $form-floating-label-height;
      border-radius: $input-border-radius;
      background-color: $input-bg;
    }
  }

  > .form-control:focus,
  > .form-control:not(:placeholder-shown),
  > .form-control-plaintext,
  > .form-select {
    ~ label {
      font-size: $form-floating-label-font-size;
      line-height: $form-floating-label-line-height;

      &::before {
        display: block;
      }
    }
  }
}

```
