### ISSUE TITLE
Pointer Cursor

### ISSUE THREAD

**Issue by imithu** [twbs/bootstrap#32822]
# Pointer Cursor

in mobile device,  **.navbar-toggler** is showing cursor point as default.
make it pointer.

[link: issue in this line,  .navbar-toggler](https://github.com/twbs/bootstrap/blob/bb19b08fbe41157c5a6e8238ecefda064adda318/dist/css/bootstrap.css#L3919)

Old code,
``` css
.navbar-toggler {
  padding: 0.25rem 0.75rem;
  font-size: 1.25rem;
  line-height: 1;
  background-color: transparent;
  border: 1px solid transparent;
  border-radius: 0.25rem; 
  transition: box-shadow 0.15s ease-in-out;
}
```

New code,
``` css
.navbar-toggler {
  cursor: pointer;   /* this is the new line */
  padding: 0.25rem 0.75rem;
  font-size: 1.25rem;
  line-height: 1;
  background-color: transparent;
  border: 1px solid transparent;
  border-radius: 0.25rem; 
  transition: box-shadow 0.15s ease-in-out;
}
```

Version: Bootstrap v5.0.0-beta1

Thanks in advance.
