### ISSUE TITLE
Bootstrap 5 tab panes not working with flexbox properly

### ISSUE THREAD

**Issue by alexisakov1** [twbs/bootstrap#32992]
- Windows 10
- Chrome, Edge (Chromium), Firefox

I am using barebones Bootstrap 5 tabs(pills) setup straight from [Docs](https://getbootstrap.com/docs/5.0/components/navs-tabs/) page:

```html
<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <a class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Home</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Profile</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false">Contact</a>
  </li>
</ul>
<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">...</div>
  <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">...</div>
  <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">...</div>
</div>
```

I then populate `tab-pane`s with `floating-div`s:

```css
.floating-div {
  float: left;
  display: block;
  height: 100px;
  width: 100px;
  border: 1px solid #dddddd;
  margin: 10px 10px 0 0;
}

.pane-1 {  
  background-color: green;  
}

.pane-2 {  
  background-color: orange;  
}

.pane-3 {  
  background-color: blue;  
}
```

Up to this point everything works as expected - [JsFiddle](https://jsfiddle.net/comparebest/dLpeu230/7/) .

Then I am applying standard bootstrap's flexbox classes to `tab-pane`s to align tab content to my liking `d-flex flex-wrap justify-content-between`.

That's where the whole thing went downhill - [JsFiddle](https://jsfiddle.net/comparebest/dLpeu230/12/) .

The way the content in the first `tab-pane` lays out is what I am after visually, but for some reason content in all the other `tab-pane`s is shifted down. Not only that, but, on the close inspection it appears that each of the `tab-pane`s contain ALL the `floating-div`s that are supposed to be spread out across 3 different divs, some of them are just invisible...
