### ISSUE TITLE
Strange values generated from RFS - Bootstrap 4.6

### ISSUE THREAD

**Issue by danielblazquez** [twbs/bootstrap#33035]
When customizing my title sizes (`h1`, `h2`...) with RFS active, I have found an unwanted effect in the `h5` tag (only in that one).

In this tag a value inside `calc()` is generated **much higher** (`1.1999882569vw`) than the previous tags (for `h4`, it is ` 0.15vw`).

**My custom variables:**

```scss
$enable-responsive-font-sizes:                true;
$font-size-base:              1.125rem;
$h1-font-size:                $font-size-base * 2.22222222223;
$h2-font-size:                $font-size-base * 1.77777777778;
$h3-font-size:                $font-size-base * 1.44444444445;
$h4-font-size:                $font-size-base * 1.22222222223;
$h5-font-size:                $font-size-base * 1.11111111112;
$h6-font-size:                $font-size-base;
```

**CSS generated:**

```css
h1, .h1 {
  font-size: 2.5rem;
}
@media (max-width: 1200px) {
  h1, .h1 {
    font-size: calc(1.375rem + 1.5vw);
  }
}

h2, .h2 {
  font-size: 2rem;
}
@media (max-width: 1200px) {
  h2, .h2 {
    font-size: calc(1.325rem + 0.9vw);
  }
}

h3, .h3 {
  font-size: 1.625rem;
}
@media (max-width: 1200px) {
  h3, .h3 {
    font-size: calc(1.2875rem + 0.45vw);
  }
}

h4, .h4 {
  font-size: 1.375rem;
}
@media (max-width: 1200px) {
  h4, .h4 {
    font-size: calc(1.2625rem + 0.15vw);
  }
}

h5, .h5 {
  font-size: 1.25rem;
}
@media (max-width: 1200px) {
  h5, .h5 {
    font-size: calc(1.25rem + 1.1999882569vw);
  }
}
```

- Sass 1.32.7
- Windows 10.
- Chrome 88.0.4324.146
