### ISSUE TITLE
Helper of notch screen (eg iphoneX)

### ISSUE THREAD

**Issue by ttttttssssss** [twbs/bootstrap#33200]
Will `notch screen` features be adapted in `V5`?

Feature requests must include:

- As much detail as possible for what we should add and why it's important to Bootstrap

    Helps developers a lot

- Relevant links to prior art, screenshots, or live demos whenever possible
![image](https://user-images.githubusercontent.com/58020640/109091782-5c9fd600-7750-11eb-917a-9553bc840fb8.png)

> This is just one abstract example
```css
.iphone_x{
  padding-bottom: constant(safe-area-inset-bottom);
  padding-bottom: env(safe-area-inset-bottom);
}

```
