### ISSUE TITLE
input-group validation wrong right border color

### ISSUE THREAD

**Issue by tkrotoff** [twbs/bootstrap#33204]
Applies to Bootstrap 4.6.0 & 5.0.0-beta2.

Consider this 4.6.0 code:

```HTML
<div class="input-group">
  <input class="form-control is-invalid">
  <div class="input-group-append">
    <button type="button" class="btn btn-outline-secondary">Button</button>
  </div>
</div>
```

https://codepen.io/tkrotoff/pen/rNWYbyJ?editors=1100

We get:
![Screen Shot 2021-02-25 at 20 11 43](https://user-images.githubusercontent.com/643434/109204669-ecbc3a80-77a5-11eb-837e-ce0eca4dec3a.png)

Instead of:
![Screen Shot 2021-02-25 at 20 12 26](https://user-images.githubusercontent.com/643434/109204641-e463ff80-77a5-11eb-9e8e-465d4f91ea77.png)

==> the input right border should be red instead of grey

The same happens with 5.0.0-alpha2: https://codepen.io/tkrotoff/pen/MWbrNpp?editors=1100

```HTML
<div class="input-group">
  <input class="form-control is-invalid">
  <button type="button" class="btn btn-outline-secondary">Button</button>
</div>
```

Quick fix:
```SCSS
// 4.6.0
.input-group {
  .form-control.is-invalid,
  .custom-select.is-invalid {
    z-index: 3;
  }
}

// 5.0.0-beta2
.input-group {
  .form-control.is-invalid,
  .form-select.is-invalid {
    z-index: 3;
  }
}
```

FYI when focusing on the input, the right border is OK:

![Screen Shot 2021-02-25 at 20 14 50](https://user-images.githubusercontent.com/643434/109204909-386ee400-77a6-11eb-9d39-50218e6c469d.png)

because of this code:
```SCSS
// Bring the "active" form control to the top of surrounding elements
> .form-control:focus,
> .form-select:focus {
  z-index: 3;
}
```
https://github.com/twbs/bootstrap/blob/v5.0.0-beta2/scss/forms/_input-group.scss#L20-L24
