### ISSUE TITLE
Different heights when using "form-select" with floating labels on v5 Beta 2

### ISSUE THREAD

**Issue by Shifrin** [twbs/bootstrap#33284]
![image](https://user-images.githubusercontent.com/7717399/110198633-f581d000-7e79-11eb-8711-f6e212b44ef4.png)

I hope the screenshot clearly explains it.

I checked in Firefox V86 (64-bit) and Chrome 89.0.4389.82 (64-bit)

I can fix this maybe temporarly by changing the value of height:

```css
/* Defaults */
.form-floating>.form-control, .form-floating>.form-select {
    height: calc(3.5rem + 2px);
    ...
}

/* Firefox fix */
.form-floating>.form-control, .form-floating>.form-select {
    height: calc(3.5rem + 3px);
    ...
}

/* Chrome fix */
.form-floating>.form-control, .form-floating>.form-select {
    height: calc(3.5rem + 4px);
    ...
}
```

Operating System: Windows 10 (64-bit)

**Comment by Shifrin** [comment]
I think it may be a padding issue. I just play with the padding and it can be fixed by changing the `padding-bottom` value for both browsers easily:

```css
.form-floating > .form-select {
    ...
    padding-bottom: .425rem; 
}
```
