### ISSUE TITLE
Offcanvas inside containers other than viewport

### ISSUE THREAD

**Issue by iainhallam** [twbs/bootstrap#33574]
In some user interfaces, it's possible to make a drawer appear using any element with appropriate classes as the container, rather than the viewport. I'd like to use this to allow properties panes to easily be associated with different parts of the page, rather than needing to go to the window edge all the time.

A codepen for the sort of thing I'm after:

https://codepen.io/iainhallam/pen/vYywVev

If this is already possible, could it be added to the documentation, and if not, could this be a feature request, please?

**Comment by mdo** [comment]
I believe this is already possible, but a quick demo could be helpful for sure. Unsure what kind of potential issues the backdrop could introduce though. Might be something @GeoSot is already thinking about elsewhere.

**Comment by GeoSot** [comment]
@mdo when #33545 is landed, will be possible to have this feature, given a mark-up to constrain `offcanvas & backdrop`  like below or something better



```css

.offcanvas-parent {
  position: relative;

  .offcanvas {
    position: absolute;
  }
  .modal-backdrop {
    position: absolute;
    height: 100%;
    width: 100%;
  }
}


```
