### ISSUE TITLE
Col-0 for Grid System

### ISSUE THREAD

**Issue by lukas13on** [twbs/bootstrap#33611]
We need urgent this feature.

```css
.col-xxl-0{
    display: none !important;
}

/* X-Small devices (portrait phones, less than 576px)*/
@media (max-width: 575.98px) {
    .col-0{
        display: none !important;
    }
}

/* Small devices (landscape phones, less than 768px)*/
@media (max-width: 767.98px) {
    .col-sm-0{
        display: none !important;
    }
}

/* Medium devices (tablets, less than 992px)*/
@media (max-width: 991.98px) {
    .col-md-0{
        display: none !important;
    }
}

/* Large devices (desktops, less than 1200px)*/
@media (max-width: 1199.98px) {  
    .col-lg-0{
        display: none !important;
    }
}

/* X-Large devices (large desktops, less than 1400px)*/
@media (max-width: 1399.98px) {
    .col-xl-0{
        display: none !important;
    }
}
```
