### ISSUE TITLE
$theme-colors not works

### ISSUE THREAD

**Issue by luispastendev** [twbs/bootstrap#33838]
I am following the documentation but it seems that it cannot register the variables that I add ...

the code I am using is the following: 

```scss

@import "../node_modules/bootstrap/scss/functions";

// override rules

@import "../node_modules/bootstrap/scss/variables";
@import "../node_modules/bootstrap/scss/mixins";
@import "../node_modules/bootstrap/scss/utilities";

$custom-colors: (
    "custom-color": #900
);

$theme-colors: map-merge($theme-colors, $custom-colors);

@import "../node_modules/bootstrap/scss/root";
@import "../node_modules/bootstrap/scss/reboot";
@import "../node_modules/bootstrap/scss/type";
@import "../node_modules/bootstrap/scss/images";
@import "../node_modules/bootstrap/scss/containers";
@import "../node_modules/bootstrap/scss/grid";

body {
    background-color: $custom-color;
}
```

throws the following error: 

![imagen](https://user-images.githubusercontent.com/4117596/117238776-1f606000-adf3-11eb-929b-4cfc158ba1b4.png)
