### ISSUE TITLE
Asymmetric gutter to avoid horizontal scrollbar

### ISSUE THREAD

**Issue by donquixote** [twbs/bootstrap#33911]
I made some observations:

- A `.row` where the gutter is bigger than the padding on `.container` will cause horizontal scrollbar, see #33219.
- This overflow behavior is asymmetric, see https://stackoverflow.com/questions/67453548/horizontal-scrollbar-for-div-sticking-out-on-one-side-but-not-the-other

One way to fix this would be to apply the negative margin + padding only on one side, not the other:

```scss
.row {
  margin-left: calc(var(--bs-gutter-x) * -1);
  margin-right: 0;
  > * {
    padding-left: var(--bs-gutter-x);
    padding-right: 0;
  }
}
```

This would need to be reversed in scroll containers with RTL, perhaps using CSS variables.

It should be made optional to avoid BC break on existing code.

Note:
This "problem" does not currently affect me in a real-world scenario, but I encountered it in the past, and in some experiments.
