### ISSUE TITLE
Bottom border of 'popover-header' does not respect value specified for $popover-border-color

### ISSUE THREAD

**Issue by brneor** [twbs/bootstrap#34005]
When customizing Bootstrap, setting a new value for `$popover-border-color` does not affect the value for `border-bottom` of elements with `popover-header` class.

The same does not occur when setting a new value for `$card-border-color`, where `card-header` get the correct color for `border-bottom`.

From `_card.scss`:
```scss
.card-header {
  padding: $card-cap-padding-y $card-cap-padding-x;
  margin-bottom: 0; // Removes the default margin-bottom of <hN>
  color: $card-cap-color;
  background-color: $card-cap-bg;
  border-bottom: $card-border-width solid $card-border-color;

  &:first-child {
    @include border-radius($card-inner-border-radius $card-inner-border-radius 0 0);
  }
}
```
From `_popover.scss`:
```scss
.popover-header {
  padding: $popover-header-padding-y $popover-header-padding-x;
  margin-bottom: 0; // Reset the default from Reboot
  @include font-size($font-size-base);
  color: $popover-header-color;
  background-color: $popover-header-bg;
  border-bottom: $popover-border-width solid shade-color($popover-header-bg, 10%);
  @include border-top-radius($popover-inner-border-radius);

  &:empty {
    display: none;
  }
}
```
