### ISSUE TITLE
Make use of text cursor on date picker

### ISSUE THREAD

**Issue by Yash-Singh1** [twbs/bootstrap#34420]
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

Feature requests must include:

- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to the prior art, screenshots, or live demos whenever possible

```css
::-webkit-datetime-edit-month-field,
::-webkit-datetime-edit-day-field,
::-webkit-datetime-edit-week-field,
::-webkit-datetime-edit-year-field {
  cursor: text;
}
```

Currently, hovering on an editable date, year, week, or month in the HTML5 date picker doesn't show the text cursor, which should be shown on all selectable text. With the above code, the text cursor is shown.

- https://stackoverflow.com/questions/14946091/are-there-any-style-options-for-the-html5-date-picker

Before:

![Selection_011](https://user-images.githubusercontent.com/53054099/124404435-c37d5f00-dcef-11eb-8eec-8e8a37d4fa3f.png)

After:

![Selection_012](https://user-images.githubusercontent.com/53054099/124404471-e7d93b80-dcef-11eb-931f-0013d93812c8.png)

**Comment by Apoorve73** [comment]
I would like to work on this issue.

**Comment by Apoorve73** [comment]
Can I take up this issue?

**Comment by ffoodd** [comment]
@Apoorve73 Sure :+1: FWIW I think this should sit in `_reboot.scss`, but any opinion is welcome.

**Comment by Yash-Singh1** [comment]
Also, don't forget to add in the: `::-webkit-datetime-edit-week-field` for `<input type="week" />`. That will make the new CSS:

```css
::-webkit-datetime-edit-month-field,
::-webkit-datetime-edit-day-field,
::-webkit-datetime-edit-week-field,
::-webkit-datetime-edit-year-field {
  cursor: text;
}
```
