### ISSUE TITLE
.bg-body in 5.1 uses body font color as background color

### ISSUE THREAD

**Issue by MyIgel** [twbs/bootstrap#34724]
After upgrading from `v5.0.2` to `v5.1.0` the definition of `.bg-body` is
```css
.bg-body {
    --bs-bg-opacity: 1;
    background-color: rgba(var(--bs-body-rgb),var(--bs-bg-opacity)) !important;
}
```
-> it uses the body font color as the background which imho should not happen here.

`5.0` uses
```css
.bg-body {
    background-color: #fff !important;
}
```

Which is what I expect.

I hope this is not a duplicate as I haven't found one but I might be (hopefully not) wrong.
