### ISSUE TITLE
Revisit `::file-selector-button` prefixes and duplicate selector

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#35101]
The latest autoprefixer >= 10.3.0 supports prefixing `::file-selector-button`.

Now, we need to eventually sort these issues:

1. we end up with a duplicate selector in reboot due to https://github.com/twbs/bootstrap/blob/ae16dbbb50bf4ffabe19fc71827b8b031d6141f4/scss/_reboot.scss#L576-L586
  We have `font: inherit` in both selectors so we end up with this CSS:
  ```css
  ::-webkit-file-upload-button {
    font: inherit;
  }

  ::file-selector-button {
    font: inherit;
  }

  ::-webkit-file-upload-button {
    font: inherit;
    -webkit-appearance: button;
  }
  ```
2. we need to deprecate the prefixes in Sass and remove them in the next major version
