### ISSUE TITLE
breakage in Firefox due to a bug in Chrome for site using this library

### ISSUE THREAD

**Issue by karlcow** [twbs/bootstrap#35318]
The computation of these two margin (right, left) in a flex container creates a lot of webcompat issues for Firefox.

https://github.com/twbs/bootstrap/blob/a2aa8c5a6e8c37fa605ca31111c6529629d32b3f/scss/mixins/_grid.scss#L8-L13

They rely on a [bug in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=1141209) but has effect on Firefox.

The latest example of [webcompat breakage](https://github.com/webcompat/web-bugs/issues/92024) for Firefox.
where the fix is to replace the margins by a width 

```css
/* styles.447625b19799ac3c3871.css | https://www.puticollege.com/styles.447625b19799ac3c3871.css */

.row {
  /* margin-right: -15px; */
  /* margin-left: -15px; */
  width: calc(100% - 30px);
}
```

There are more webcompat bug examples in the chromium bug.
