### ISSUE TITLE
Option to remove the thick bottom border from `thead` and top border from `tfoot` in table element

### ISSUE THREAD

**Issue by TanvirArjel** [twbs/bootstrap#35342]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

There should be an option to remove the thick glaring dark bottom border from `thead` and top border from `tfoot` in the table element.

![image](https://user-images.githubusercontent.com/14342773/140927002-1681c250-b444-428e-9a95-c80a6f67c264.png)

### Motivation and context

Not everybody will like this. I have updated a big project (which has hundreds of tables) to bootstrap 5.1.3. Now I need to remove the thick glaring dark bottom broder from `thead` and the top border from `tfoot` in the table element.

Right now, how can I remove these borders using custom CSS? Please help me.

**Comment by nkdas91** [comment]
@TanvirArjel 

This is the CSS that adds the borders
```css
.table > :not(:first-child) {
    border-top: 2px solid currentColor;
}
```

You may use the following to remove them
```css
.table > :not(:first-child) {
    border-top: 0;
}
```

**Comment by TanvirArjel** [comment]
@TanvirArjel Thank you so much for your response. It worked. I was searching for the CSS that was applying that borders but could not find those by inspecting them.

**Comment by insideshell** [comment]
I agree with @TanvirArjel. Is that thickness really intended? Because:

1) We can't override it with border color utilities:

![image](https://user-images.githubusercontent.com/4362224/140979914-11e95ecc-73a0-4b54-bdfd-05d839d57ac1.png)

2) It seems to me it was more elegant in Bootstrap 4:

![image](https://user-images.githubusercontent.com/4362224/140979715-662686d4-5f69-4795-9a42-63f0854104bf.png)

Thanks!

**Comment by Petercopter** [comment]
I ended up doing this:
```
thead {
  border-bottom-width: 2px;
}
```
For whatever reason this causes it to use the light grey border color instead

**Comment by insideshell** [comment]
To have both thickness and gray color, I did this (as per @nkdas91 and using a CSS variable):

```css
.table > :not(:first-child) { border-color: var(--bs-gray-300); }
```

**Comment by cjhudson** [comment]
I don't get these thick lines unless the table has a caption.  
![image](https://user-images.githubusercontent.com/4315518/146085759-a87f39b2-14ad-411b-a2ab-7e3269f39b73.png)

With no caption, this CSS

> .table > :not(:first-child) {
>     border-top: 2px solid currentColor;
> }
> 

doesn't get generated.  With a caption it does.

**Comment by unclebay143** [comment]
After a long trial with `react-bootstrap`:

I added the `borderless` prop option to the table component like this `<Table borderless />` and add my custom border style rules

```
  border-bottom: 0.6px solid #555555;

```


And it worked perfectly.

This concept might help someone.

**Comment by MinePlay96** [comment]
I also came across this, my solution was to override the SCSS so that I can edit the border values individually.

```SCSS
$table-group-separator-width: (2 * $table-border-width) !default;\n
$table-group-separator-color: inherit !default;

.table {
    > :not(:first-child) {
        border-top-width: $table-group-separator-width;
        border-top-style: solid;
        border-top-color: $table-group-separator-color;
    }
}
```

**Comment by membersound** [comment]
I used the following to remove borders, but keep the top level border in a light grey for better distinction between header and content:

```
.table thead tr th {
    border-bottom: 2px solid grey;
}
```

**Comment by insideshell** [comment]
Don't forget you can access the original grey color using the CSS variable `var(--bs-gray-300)`.

```css
.table thead tr th {
    border-bottom: 2px solid var(--bs-gray-300);
}
```
