### ISSUE TITLE
Change form-control validation border-color to !important

### ISSUE THREAD

**Issue by LB22** [twbs/bootstrap#35768]
This should have perhaps been posted with the bug label rather than the feature label. Don't know how to change it.

### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Under scss/mixins/_forms.scss

I believe this is where the code change should be.

```scss
@mixin form-validation-state(
  $state,
  $color,
  $icon,
  $tooltip-color: color-contrast($color),
  $tooltip-bg-color: rgba($color, $form-feedback-tooltip-opacity),
  $focus-box-shadow: 0 0 $input-btn-focus-blur $input-focus-width rgba($color, $input-btn-focus-color-opacity)
) {
  .form-control {
    @include form-validation-state-selector($state) {
      // I'm proposing to change this rule to be !important which it currently isn't.
      border-color: $color !important;
    }
  }
}
```

### Motivation and context

See the code comment about making this rule !important

I propose this as this would allow to set your own non-validated default border-color outside of bootstrap. (I'm not sure if this is possible otherwise?) 
Bootstrap having the !important rule would override the default border color set outside of bootstrap when validating (which is what we want)
If it doesn't have !important, the validation border color gets overridden by the non-validated border color set outside bootstrap.

Bad (Currently setting border color outside of bootstrap overrides bootstrap validation)
![bad](https://user-images.githubusercontent.com/55314315/152154866-3966c67d-f18f-4003-9084-2ed92d04aff9.jpg)

Good (Proposed solution, bootstrap overrides default border-color ON VALIDATION only)
![good](https://user-images.githubusercontent.com/55314315/152154851-212351c0-32ab-44ba-bb33-f257b2c50231.jpg)

**Comment by ffoodd** [comment]
That's not something we'll do for at least two reasons:
1. The issue you're experiencing is due to  another styles, not Bootstrap's ones: we won't ship something for everyone to fix something not everyone's using 
2. We have border utilities that shouldn't be overridable, and your suggestion would be able to override them.


A few ideas to help with your situation:
- if you're able to alter `_checkout.scss`, you may try to exclude validation states using `:not(.is-valid)`, or to lower the specifity using `:where()` (but beware of limited browser support).
- if you can't, maybe using [`border-color` utilities](https://getbootstrap.com/docs/5.1/utilities/borders/#border-color) is possible?
- in last resort, add your own additive CSS layer to override `_checkout.scss` styles.

I hope it helps, I'm closing this as it's definetly not an issue with Bootstrap.

**Comment by LB22** [comment]
Thanks for the feedback. I had no idea `:not` existed. Sorry I took up your time.

I was indeed able to achieve what I wanted with this.
```scss
.form-control {
   &:not(.is-valid, .is-invalid) {
      border-color: #2e2e2e;
   }
}
```

Keep up the good work! Bootstrap is awesome and you are awesome!
