### ISSUE TITLE
Document how to make modals print nicely

### ISSUE THREAD

**Issue by folknor** [twbs/bootstrap#35819]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

There's a few issues related to printing Modals at the moment, from a websites end users perspective:

1. The modal is printed as many times as the page content needs to print - so if the website is 15x sheets tall when the modal is closed, and the user opens a modal which coincidentally fits on one sheet, then prints, the modal is apparently printed 15 times (that is the perception of a user)
2. Modal static backdrops can overlay the modal content, depending on modal height and print settings

I've made a - as far as I can tell - satisfactory solution until CSS parent selectors exist, which is this: (the solution obviously depends on all content except modals being inside `main`)
```scss
@media print {
	body.modal-print {
		main {
			visibility: hidden;
			display: none;
		}

		.modal.show {
			position: relative;

			.modal-dialog {
				width: 100vw;
				max-width: none;
				margin: 0;

				.modal-content {
					height: 100%;
					border: 0;
				}

				.modal-body {
					overflow-y: visible;
				}

				.modal-footer {
					visibility: hidden;
					display: none;
				}
			}
		}

		.modal-backdrop {
			visibility: hidden;
			display: none;
		}
	}
}
```

```js
	window.addEventListener("beforeprint", () => {
		let m = document.querySelector(".modal.show")
		if (m != null) {
			document.body.classList.add("modal-print")
		}
	})
	window.addEventListener("afterprint", () => {
		document.body.classList.remove("modal-print")
	})
```

I'm hoping for two things with this ticket request:

1. Help to improve on my solution (though I've tested it in a few browsers and it seems to be fine, it's probably not optimal)
2. That this gets documented somewhere, because surely I can't be the only one with this issue

Thank you!

### Reduced test cases

You can, as of right now;
1. Go to https://gammelbilen.no
2. Click "Styret" in the very top right, or in the dropdown menu
3. Click the link "Klubbens vedtekter kan leses her."
4. Print

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

5.1.3
