### ISSUE TITLE
Pagination are not displayed correctly in the current main branch

### ISSUE THREAD

**Issue by jonnysp** [twbs/bootstrap#36015]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

current release looks good https://getbootstrap.com/docs/5.1/components/pagination/#overview
![grafik](https://user-images.githubusercontent.com/1651241/158133056-9259a9e1-1c7b-4292-926b-ad241ca26eac.png)

current brunch looks bad https://twbs-bootstrap.netlify.app/docs/5.1/components/pagination/#overview
![grafik](https://user-images.githubusercontent.com/1651241/158133143-ded622b9-41a5-4537-8b69-3f85c3c538b2.png)

### Reduced test cases

https://getbootstrap.com/docs/5.1/components/pagination/#overview
https://twbs-bootstrap.netlify.app/docs/5.1/components/pagination/#overview

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

v5.1.3 and current main Brunch

**Comment by jonnysp** [comment]
:wink:

**Comment by tysongach** [comment]
I just upgrade to v5.2 and am seeing what I believe to be the same bug that this issue is filed against:

![Screen Shot 2022-07-20 at 10 02 53](https://user-images.githubusercontent.com/903327/180029575-a9608c42-a8d7-4657-a593-2956e8708e65.png)

Let me know if you’d prefer I open a new issue.

---

As a gut check, I looked at the compiled CSS on the Bootstrap v5.2 doc website, which has…

```css
.page-item:not(:first-child) .page-link {
  margin-left: -1px;
}

.page-item:first-child .page-link {
  border-top-left-radius: var(--bs-pagination-border-radius);
  border-bottom-left-radius: var(--bs-pagination-border-radius);
}

.page-item:last-child .page-link {
  border-top-right-radius: var(--bs-pagination-border-radius);
  border-bottom-right-radius: var(--bs-pagination-border-radius);
}
```

…whereas my compiled CSS is:

```css
.page-item:not(:first-child) .page-link {
  margin-left: -1px;
}

.page-item .page-link {
  border-radius: var(--bs-pagination-border-radius);
}
```

That makes me suspicious of this line, which [was recently changed](https://github.com/twbs/bootstrap/commit/11751c613fdb040f8db5a155d7aafaeabd387499):

https://github.com/twbs/bootstrap/blob/edf9c40956d19e6ab3f9151bfe0dfac6be06fa21/scss/_pagination.scss#L78

This appears to be evaluating to `false` for me. I’ve tried to create a reduced test case here: https://www.sassmeister.com/gist/eeae55c689cbaba226ec9ef0d148f315 (note that this is using Dart Sass v1.32.12)

If that test case is valid, it seems as though the compiled version of Bootstrap 5.2 differs from (at least some…) consumer-compiled versions.

It makes me wonder if this is a variation between Sass compilers or versions. I’m in a Rails app, using the `sass-rails` and `bootstrap` gems. I believe `sass-rails` is a wrapper around LibSass. I’m not sure which Sass was used to build the distributed CSS files for Bootstrap 5.2.

Any help greatly appreciated! Let me know if I can provide anything else. Thanks!
