### ISSUE TITLE
bootstrap doesn't compile my extended color palette

### ISSUE THREAD

**Issue by arcanisgk** [twbs/bootstrap#36012]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

bootstrap doesn't compile my extended color palette

### Reduced test cases

I am trying to compile the following scss file for Bootstrap::

```scss
@import "node_modules/bootstrap/scss/bootstrap";

$custom-colors: (
        "rcred": #DA291C,
        "rcwine": #A50034,
        "rcblue": #002554,
        "rcgold": #FFB200,
        "rcsilver": #808080,
        "rcskyblue": #00B0F0,
        "aliceblue": #F0F8FF,
        "antiquewhite": #FAEBD7,
        "aqua": #00FFFF,
        "aquamarine": #7FFFD4,
        "azure": #F0FFFF,
        "beige": #F5F5DC,
        "bisque": #FFE4C4,
        "blanchedalmond": #FFEBCD,
        "blueviolet": #8A2BE2,
        "brown": #A52A2A,
        "burlywood": #DEB887,
        "cadetblue": #5F9EA0,
        "chartreuse": #7FFF00,
        "chocolate": #D2691E,
        "coral": #FF7F50,
        "cornflowerblue": #6495ED,
        "cornsilk": #FFF8DC,
        "crimson": #DC143C,
        "darkblue": #00008B,
        "darkcyan": #008B8B,
        "darkgoldenrod": #B8860B,
        "darkgray": #A9A9A9,
        "darkgreen": #006400,
        "darkgrey": #A9A9A9,
        "darkkhaki": #BDB76B,
        "darkmagenta": #8B008B,
        "darkolivegreen": #556B2F,
        "darkorange": #FF8C00,
        "darkorchid": #9932CC,
        "darkred": #8B0000,
        "darksalmon": #E9967A,
        "darkseagreen": #8FBC8F,
        "darkslateblue": #483D8B,
        "darkslategray": #2F4F4F,
        "darkslategrey": #2F4F4F,
        "darkturquoise": #00CED1,
        "darkviolet": #9400D3,
        "deeppink": #FF1493,
        "deepskyblue": #00BFFF,
        "dimgray": #696969,
        "dimgrey": #696969,
        "dodgerblue": #1E90FF,
        "firebrick": #B22222,
        "floralwhite": #FFFAF0,
        "forestgreen": #228B22,
        "fuchsia": #FF00FF,
        "gainsboro": #DCDCDC,
        "ghostwhite": #F8F8FF,
        "gold": #FFD700,
        "goldenrod": #DAA520,
        "greenyellow": #ADFF2F,
        "grey": #808080,
        "honeydew": #F0FFF0,
        "hotpink": #FF69B4,
        "indianred": #CD5C5C,
        "ivory": #FFFFF0,
        "khaki": #F0E68C,
        "lavender": #E6E6FA,
        "lavenderblush": #FFF0F5,
        "lawngreen": #7CFC00,
        "lemonchiffon": #FFFACD,
        "lightblue": #ADD8E6,
        "lightcoral": #F08080,
        "lightcyan": #E0FFFF,
        "lightgoldenrodyellow": #FAFAD2,
        "lightgray": #D3D3D3,
        "lightgreen": #90EE90,
        "lightgrey": #D3D3D3,
        "lightpink": #FFB6C1,
        "lightsalmon": #FFA07A,
        "lightseagreen": #20B2AA,
        "lightskyblue": #87CEFA,
        "lightslategray": #778899,
        "lightslategrey": #778899,
        "lightsteelblue": #B0C4DE,
        "lightyellow": #FFFFE0,
        "lime": #00FF00,
        "limegreen": #32CD32,
        "linen": #FAF0E6,
        "magenta": #FF00FF,
        "maroon": #800000,
        "mediumaquamarine": #66CDAA,
        "mediumblue": #0000CD,
        "mediumorchid": #BA55D3,
        "mediumpurple": #9370DB,
        "mediumseagreen": #3CB371,
        "mediumslateblue": #7B68EE,
        "mediumspringgreen": #00FA9A,
        "mediumturquoise": #48D1CC,
        "mediumvioletred": #C71585,
        "midnightblue": #191970,
        "mintcream": #F5FFFA,
        "mistyrose": #FFE4E1,
        "moccasin": #FFE4B5,
        "navajowhite": #FFDEAD,
        "navy": #000080,
        "oldlace": #FDF5E6,
        "olive": #808000,
        "olivedrab": #6B8E23,
        "orangered": #FF4500,
        "orchid": #DA70D6,
        "palegoldenrod": #EEE8AA,
        "palegreen": #98FB98,
        "paleturquoise": #AFEEEE,
        "palevioletred": #DB7093,
        "papayawhip": #FFEFD5,
        "peachpuff": #FFDAB9,
        "peru": #CD853F,
        "plum": #DDA0DD,
        "powderblue": #B0E0E6,
        "rebeccapurple": #663399,
        "rosybrown": #BC8F8F,
        "royalblue": #4169E1,
        "saddlebrown": #8B4513,
        "salmon": #FA8072,
        "sandybrown": #F4A460,
        "seagreen": #2E8B57,
        "seashell": #FFF5EE,
        "sienna": #A0522D,
        "silver": #C0C0C0,
        "skyblue": #87CEEB,
        "slateblue": #6A5ACD,
        "slategray": #708090,
        "slategrey": #708090,
        "snow": #FFFAFA,
        "springgreen": #00FF7F,
        "steelblue": #4682B4,
        "tan": #D2B48C,
        "thistle": #D8BFD8,
        "tomato": #FF6347,
        "transparent": #00000000,
        "turquoise": #40E0D0,
        "violet": #EE82EE,
        "wheat": #F5DEB3,
        "white": #FFFFFF,
        "whitesmoke": #F5F5F5,
        "yellowgreen": #9ACD32
);

@each $name, $value in $custom-colors {
  .bg-#{$name} {
    background-color: $value !important;
  }

  .#{$name}:hover {
    color: white !important;
  }

  .text-#{$name} {
    color: $value !important;
  }

  @error "El color: `#{$name}` que has pasado no está disponible.";

}

$theme-colors: map-merge($theme-colors, $custom-colors);

@import "node_modules/bootstrap/scss/bootstrap";
```

**_custom error catcher that I have placed:_**

```
--------------------
Change Detected...
styles.scss
--------------------
Compilation Error
Error: El color: `rcred` que has pasado no está disponible.
        on line 162 of sass/d:\Desarrollos\Personales\custom BS5\styles.scss
>>   @error "El color: `#{$name}` que has pasado no está disponible.";

   --^

--------------------
Watching...
--------------------
```

**_without the custom error:_**

```
--------------------
Change Detected...
styles.scss
--------------------
Compilation Error
Error: argument `$color` of `red($color)` must be a color
        on line 185 of sass/d:\Desarrollos\Personales\custom BS5\node_modules\bootstrap\scss\_functions.scss, in function `red`
        from line 185 of sass/d:\Desarrollos\Personales\custom BS5\node_modules\bootstrap\scss\_functions.scss, in function `luminance`
        from line 174 of sass/d:\Desarrollos\Personales\custom BS5\node_modules\bootstrap\scss\_functions.scss, in function `contrast-ratio`
        from line 159 of sass/d:\Desarrollos\Personales\custom BS5\node_modules\bootstrap\scss\_functions.scss, in function `color-contrast`
        from line 10 of sass/d:\Desarrollos\Personales\custom BS5\node_modules\bootstrap\scss\mixins\_buttons.scss, in mixin `button-variant`
        from line 61 of sass/d:\Desarrollos\Personales\custom BS5\node_modules\bootstrap\scss\_buttons.scss
        from line 24 of sass/d:\Desarrollos\Personales\custom BS5\node_modules\bootstrap\scss\bootstrap.scss
        from line 166 of sass/d:\Desarrollos\Personales\custom BS5\styles.scss
>>     "r": red($color),

   ---------^

--------------------
Watching...
--------------------
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.3
