### ISSUE TITLE
For some border radius cannot change size

### ISSUE THREAD

**Issue by mjablecnik** [twbs/bootstrap#36536]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I want to create container with rounded corners on top but when I add `rounded-5` class so there are rounded bottom corners instead of top:
![image](https://user-images.githubusercontent.com/2686906/172949871-d0705db3-fa69-41d7-a4ee-969197c354aa.png)
![image](https://user-images.githubusercontent.com/2686906/172949914-c2805c16-927b-4901-b270-79c6335fa5ae.png)

My code is:
```
<div class="container py-3 my-3 border border-primary rounded-top rounded-5"><h1>This is a heading</h1><p>This is a paragraph of text.</p></div>
```

### Reduced test cases

```
 <html>
  <head>
    <meta charset="utf-8">
    <title>bootstrap example</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
	</head>

	<body>
		<hr>
			<div class="container py-3 my-3 border border-primary rounded-top rounded-5">
				<h1>This is a heading</h1>
				<p>This is a paragraph of text.</p>
			</div>
		<hr>
	</body>
</html>
```

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.0-beta1

**Comment by julien-deramond** [comment]
Thanks for opening this issue @mjablecnik.
Indeed `rounded-top` defines `border-top-right-radius: var(--bs-border-radius) !important; border-top-left-radius: var(--bs-border-radius) !important; }` while `rounded-5` defines the rounded for all borders `border-radius: var(--bs-border-radius-2xl) !important;`.

We could maybe create `.rounded-{top|end|bottom|start}-{0-5}` (in your example using `.rounded-top-5` instead of `.rounded-top .rounded-5`) by doing:
```scss
"rounded-top": (
    property: border-top-left-radius border-top-right-radius,
    class: rounded-top,
    values: (
    null: var(--#{$prefix}border-radius),
    0: 0,
    1: var(--#{$prefix}border-radius-sm),
    2: var(--#{$prefix}border-radius),
    3: var(--#{$prefix}border-radius-lg),
    4: var(--#{$prefix}border-radius-xl),
    5: var(--#{$prefix}border-radius-2xl),
    circle: 50%,
    pill: var(--#{$prefix}border-radius-pill)
  )
),
```
What do you think @mdo about adding it?
