### ISSUE TITLE
Don't display dotted underline on `abbr[title]` tags to browsers that don't support hover

### ISSUE THREAD

**Issue by coliff** [twbs/bootstrap#36607]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Currently the [Abbreviation styles](https://getbootstrap.com/docs/5.2/content/typography/#abbreviations) show the dotted underline on all browsers, even mobile devices where it isn't possible to hover over them to show the title.

I'd like to propose that the styles for `abbr` and `.initialism` be limited to only browsers/devices which support the [supports:hover media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/hover) (namely iOS/iPadOS). I think it'd look something like this:

```css
@media (supports: hover) {
  abbr[title] {
    -webkit-text-decoration: underline dotted;
    text-decoration: underline dotted;
    cursor: help;
    -webkit-text-decoration-skip-ink: none;
    text-decoration-skip-ink: none;
  }
  .initialism {
    font-size: 0.875em;
    text-transform: uppercase;
  }
}
```

I've tested this on iPhone, iPad, Edge 102 and it works as expected there  - the text is not underlined on iPadOS/iOS where it isn't possible to see the title - even with a pointing device (mouse) connected.
The text is still underlined on Android 7 with latest Chrome (102) just as it is with the shipping version of Bootstrap (5.2.0-Beta1).

Codepen:
https://codepen.io/coliff/pen/rNJbEoM

I used this to simplified page test:
https://tests.christianoliff.com/title-style-hover/

### Motivation and context

Currently the [Abbreviation styles](https://getbootstrap.com/docs/5.2/content/typography/#abbreviations) show the dotted underline on Safari for iPadOS and iOS and it can be frustrating for users to see the dotted underlines on abbr text but have no way to interact with it. It'd be better if the text just appeared as normal.

**Comment by ffoodd** [comment]
My two cents: using `@media (hover: hover)` to reset those styles would decrease potential side effects. 

Apart from that, why not? I'm almost sure we shop such progressive enhancement here and there.

**Comment by coliff** [comment]
UPDATE: I did some further testing and got it working correctly on Android too! 👍
(basically we want to set `text-decoration: none` on ` @media (hover: none)`
I've updated my original post to reflect the changes.

**Comment by julien-deramond** [comment]
Removing the text decoration when `@media (hover: none)` seems a good idea to avoid having frustrated users. Maybe we could enhance their experience by displaying the full title as well with something like (supposing that doesn't cause any issues with internationalization):
```scss
@media (hover: none) {
  abbr[title]:after
  {
   content: " (" attr(title) ")";
  }
}
```
