### ISSUE TITLE
List-group-item margin-top is offset when importing sass in a nested class

### ISSUE THREAD

**Issue by hadouin** [twbs/bootstrap#36662]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

## Context
When using list-groups nested inside another class for exemple: 
```sass
.darkmode
  @import 'bootstrap/scss/list-group';
```
The list-group-items do not behave correctly especially for borders ([see code pen](https://codepen.io/Hadouin/pen/KKopyrW))
## Cause
This is due to `.list-group-item` using a `& + &` selector. exemple:  
```sass
.darkmode
  .list-group-item
    & + &
      border-top-width: 0px
```
compiles to:
```css
.darkmode .list-group-item + .darkmode .list-group-item {
  border-top-width: 0px;
}
```
## What we want
I propose we change the `&` in `scss/_list-group-item.scss` to `.list-group-item`
```scss
// ...
& + & { // The Issue would be here to change the second "&" to ".list-group-item"
  border-top-width: 0;

  &.active {
    margin-top: calc(var(--#{$prefix}list-group-border-width) * -1); // stylelint-disable-line function-disallowed-list
    border-top-width: var(--#{$prefix}list-group-border-width);
  }
}
```
### compiled   
```css
.darkmode .list-group-item + .list-group-item {
  border-top-width: 0px;
}
```

### Reduced test cases

https://codepen.io/Hadouin/pen/KKopyrW

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.0-beta1
