### ISSUE TITLE
Add Background/Text color on mouse over

### ISSUE THREAD

**Issue by Asmitta-01** [twbs/bootstrap#36869]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

My idea is to add classes like `text-hover-*` and `bg-hover-*` for colors and backgrounds when the mouse fly over an element. 
So we can have a code like this in css:
```css
.text-hover-primary:hover {
  --bs-text-opacity: 1;
  color: rgba(var(--bs-primary-rgb), var(--bs-text-opacity)) !important;
}
```

### Motivation and context

The [color & background helper](https://getbootstrap.com/docs/5.2/helpers/color-background/) is very useful.  And this new this proposition could be heplful also. 

- In navbars we can need the `(text-)bg-hover-*` class to change the background color of a nav-item when the mouse is over.

- In list-group or a custom list of cards by default the "hover" background color is a derivation of the gray, with a thing like `bg-hover-primary bg-opacity-10` this background color will be more attractive and customizable by the developer.

I think there are other applications that i could not see know but these are some of them.
