### ISSUE TITLE
`.dropdown-center` and `.dropup-center` in `.navbar` not working

### ISSUE THREAD

**Issue by Sysix** [twbs/bootstrap#36897]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When a Dropdown with `.dropup-center` or `.dropdown-center` is inside `.navbar` the centering is not working.
Because it checks itself if it's inside `.navbar`  and will disable popper auto positioning:

see:
https://github.com/twbs/bootstrap/blob/v5.2.0/js/src/dropdown.js#L309

### Reduced test cases

https://stackblitz.com/edit/jbtery?file=index.html

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v5.2.0

**Comment by GeoSot** [comment]
Hello @Sysix. 

It is a fair observation. Is happening because most of documented dropdown position-classes are handled by javascript (popper).
In case we have a dropdown inside navbar, we do not use the popper engine

It may be closed by #35901

**Comment by currentcreative** [comment]
Any workarounds? I'm surprised this was overlooked and apparently complicated enough to still not be resolved. Makes me feel better about trying to figure out the problem for the last hour.

**Comment by ZuK94** [comment]
i taught im missing something. 
when will there be a fix?

**Comment by aaron-loa** [comment]
hello, here is a workaround i found for bootstrap 5.2, run this code when the page loads:
``` js
  let dropdowns = document.querySelectorAll('.dropdown-toggle')
  for (let i = 0; i < dropdowns.length; i++) {
    let dropdownToggle = dropdowns[i];
    dropdownToggle = new Dropdown(dropdownToggle, {
      popperConfig(defaultBsPopperConfig) {
        return { ...defaultBsPopperConfig };
      }
    });
    dropdownToggle._inNavbar = false;
  }

```
i am bundling bootstrap with webpack, if you are using bootstrap with a cdn then instead of using `new Dropdown` you might need to use `new bootstrap.Dropdown` or similar, not sure

**Comment by FrancoJavierGadea** [comment]
To center a dropdown in the navbar manually, you can use CSS

```css
@media (min-width: 992px) {

        .dropdown {
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .dropdown-menu[data-bs-popper] {
            top: 100%;
            left: initial;
            margin: 10px;
        }
 }
```
> You need to control the media query when the navbar is hidden

You can also try with

```css
@media (min-width: 992px) {

        .dropdown-menu[data-bs-popper] {
            position: absolute;
            top: 100%;
            left: 50%;
            transform: translateX(-50%);
            margin: 10px;
        }
}
```
