### ISSUE TITLE
Opacity utilities lack "!important" in v5.2.0

### ISSUE THREAD

**Issue by rxbracho** [twbs/bootstrap#36891]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The opacity utlities, e.g., .opacity-50 are defined without !important so they are sometimes ignored (v5.2.0)

### Reduced test cases

No need, they just need to be generated with the !important

### What operating system(s) are you seeing the problem on?

Windows, Android

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.2.0

**Comment by mdo** [comment]
They show for me in the compiled CSS.

```css
.opacity-0 {
  opacity: 0 !important;
}

.opacity-25 {
  opacity: 0.25 !important;
}

.opacity-50 {
  opacity: 0.5 !important;
}

.opacity-75 {
  opacity: 0.75 !important;
}

.opacity-100 {
  opacity: 1 !important;
}
```
