### ISSUE TITLE
Use WCAG 3 luminance algorithm 

### ISSUE THREAD

**Issue by rivajunior** [twbs/bootstrap#37022]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Change threshold value from `.03928` to `.04045` in the `luminance` scss function.

Example:

```scss
@function luminance($color) {
  $rgb: (
    "r": red($color),
    "g": green($color),
    "b": blue($color)
  );

  @each $name, $value in $rgb {
    $value: if(divide($value, 255) < .04045, divide(divide($value, 255), 12.92), nth($_luminance-list, $value + 1));
    $rgb: map-merge($rgb, ($name: $value));
  }

  @return (map-get($rgb, "r") * .2126) + (map-get($rgb, "g") * .7152) + (map-get($rgb, "b") * .0722);
}
```

I don't know if it is the only change required to be updated with WCAG 3.0 compliance, but as I checked in [Calculating Relative Luminance](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_Colors_and_Luminance#calculating_relative_luminance), I believe it is.

### Motivation and context

From IEC standard for sRGB, `0.04045` is the right threshold for calculating relative luminance instead of `0.03928`.

See [Relative luminance](https://www.w3.org/WAI/GL/wiki/Relative_luminance) and [Web Accessibility: Understanding Colors and Luminance](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_Colors_and_Luminance)
