### ISSUE TITLE
[Feature request] Add missing classes for viewport-based sizing

### ISSUE THREAD

**Issue by lonix1** [twbs/bootstrap#37427]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

````css
.max-vw-100 { max-width:  100vw !important; }
.max-vh-100 { max-height: 100vh !important; }
````

### Motivation and context

Bootstrap already [has these](https://getbootstrap.com/docs/5.2/utilities/sizing/#relative-to-the-viewport):
````css
.min-vw-100 { min-width:  100vw !important; }
.min-vh-100 { min-height: 100vh !important; }

.vw-100 { width:  100vw !important; }
.vh-100 { height: 100vh !important; }
````

So the missing classes would complete the viewport-based sizing feature. I found a need for them in layouts.

Similar to #28965 which was closed by OP.
