### ISSUE TITLE
CSS output issue when prefixing scss compilation

### ISSUE THREAD

**Issue by Lausselloic** [twbs/bootstrap#37544]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When building bootstrap scss file with a prefix classname : 
```css
// Import all of Bootstrap's CSS
.custom-theme {
@import "~bootstrap/scss/bootstrap";
}
```

Output something strange for `.is-invalid` class in css file (and only for this class)

it outputs in css :
```css
      .was-validated .custom-theme:invalid ~ .invalid-feedback,
      .was-validated .custom-theme:invalid ~ .invalid-tooltip, .custom-theme.is-invalid ~ .invalid-feedback,
      .custom-theme.is-invalid ~ .invalid-tooltip {
        display: flex;
      }
```
   
The expected result is
```
.custom-theme .is-invalid
```
instead of
```
.custom-theme.is-invalid
```

### Reduced test cases

Sample could be seen : 
https://stackblitz.com/edit/github-2mqn2d-oqc1ps?file=dist/index.html

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

5.2.3
