### ISSUE TITLE
.card class conflicts with application's .card class - perhaps bs-card would be better.

### ISSUE THREAD

**Issue by DaveO-Home** [twbs/bootstrap#37563]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

rename .card to something else, perhaps .bs-card

### Motivation and context

conflicts with existing application. Problem started with 5.2.0.

**Comment by mdo** [comment]
We won't be doing this—it's been that way for years and hasn't started since v5.2.0 as no component class names have changed in that release :).

**Comment by DaveO-Home** [comment]
@mdo - fyi your javascript since 5.2 is injecting `var (--bs-card-height)` into the element(s) using the the `card` class. This was very difficult to figure out, I'm surprised that others haven't had the problem. I had to change my app.

**Comment by julien-deramond** [comment]
@DaveO-Home I'm intrigued by your feedback because there's no JavaScript at all for the cards. 
[This is the main change](https://github.com/twbs/bootstrap/commit/e342142b61aacc187c776052bde93e414eb25db7#diff-be5262d08eefacbcdbfa1f9d100c4d23d2d66fecdd720b1336881e174ce7fe9b) done between v5.1 and v5.2 for the CSS of our cards. `--bs-card-height` is a CSS variable defined in the `.card` scope (see https://github.com/twbs/bootstrap/blob/main/scss/_card.scss). So I'm not sure why you had to change anything (for the cards) while migrating from v5.1 to v5.2.

**Comment by DaveO-Home** [comment]
@julien-deramond I'm not using the bootstrap card scope. I had a `.card` class for my own use. It's only used as  a parent to my cards, `.card1`, `.card2`.... Somehow `var (--bs-card-height)` is getting injected. It really trashed my app. I can't see how it gets injected unless it's javascript or the bundler, `rollup`.

**Comment by julien-deramond** [comment]
In Bootstrap v5.1.3 (generated `dist/css/bootstrap.css`):
```scss
.card {
  position: relative;
  display: flex;
  flex-direction: column;
  min-width: 0;
  word-wrap: break-word;
  background-color: #fff;
  background-clip: border-box;
  border: 1px solid rgba(0, 0, 0, 0.125);
  border-radius: 0.25rem;
}

// There are other rules (e.g. '.card > hr' and so on of course)
```

In Bootstrap v5.2.0 (generated `dist/css/bootstrap.css`):
```scss
.card {
  --bs-card-spacer-y: 1rem;
  --bs-card-spacer-x: 1rem;
  --bs-card-title-spacer-y: 0.5rem;
  --bs-card-border-width: 1px;
  --bs-card-border-color: var(--bs-border-color-translucent);
  --bs-card-border-radius: 0.375rem;
  --bs-card-box-shadow: ;
  --bs-card-inner-border-radius: calc(0.375rem - 1px);
  --bs-card-cap-padding-y: 0.5rem;
  --bs-card-cap-padding-x: 1rem;
  --bs-card-cap-bg: rgba(0, 0, 0, 0.03);
  --bs-card-cap-color: ;
  --bs-card-height: ;
  --bs-card-color: ;
  --bs-card-bg: #fff;
  --bs-card-img-overlay-padding: 1rem;
  --bs-card-group-margin: 0.75rem;
  position: relative;
  display: flex;
  flex-direction: column;
  min-width: 0;
  height: var(--bs-card-height);
  word-wrap: break-word;
  background-color: var(--bs-card-bg);
  background-clip: border-box;
  border: var(--bs-card-border-width) solid var(--bs-card-border-color);
  border-radius: var(--bs-card-border-radius);
}

// There are other rules (e.g. '.card > hr' and so on of course)
```

The only difference in Bootstrap v5.2 for `.card` is that we introduced CSS variables/custom properties. So as you can see there's no JavaScript involved at all.

Maybe you could try to create a [CodePen](https://codepen.io) or a [StackBlitz](https://stackblitz.com/) to show us the issue with a minimal reproducible example and [launch a discussion in our dedicated space](https://github.com/twbs/bootstrap/discussions) so that someone could maybe help you.

But TBH I don't see technically how it could mess with your app considering the fact that you already used the `.card` class before with Bootstrap v5.1.3 in your app.

**Comment by DaveO-Home** [comment]
I just tested rollup with `.card` and that's not he problem.

**Comment by julien-deramond** [comment]
In Bootstrap v5.1.3 (generated `dist/css/bootstrap.css`):
```scss
.card {
  position: relative;
  display: flex;
  flex-direction: column;
  min-width: 0;
  word-wrap: break-word;
  background-color: #fff;
  background-clip: border-box;
  border: 1px solid rgba(0, 0, 0, 0.125);
  border-radius: 0.25rem;
}

// There are other rules (e.g. '.card > hr' and so on of course)
```

In Bootstrap v5.2.0 (generated `dist/css/bootstrap.css`):
```scss
.card {
  --bs-card-spacer-y: 1rem;
  --bs-card-spacer-x: 1rem;
  --bs-card-title-spacer-y: 0.5rem;
  --bs-card-border-width: 1px;
  --bs-card-border-color: var(--bs-border-color-translucent);
  --bs-card-border-radius: 0.375rem;
  --bs-card-box-shadow: ;
  --bs-card-inner-border-radius: calc(0.375rem - 1px);
  --bs-card-cap-padding-y: 0.5rem;
  --bs-card-cap-padding-x: 1rem;
  --bs-card-cap-bg: rgba(0, 0, 0, 0.03);
  --bs-card-cap-color: ;
  --bs-card-height: ;
  --bs-card-color: ;
  --bs-card-bg: #fff;
  --bs-card-img-overlay-padding: 1rem;
  --bs-card-group-margin: 0.75rem;
  position: relative;
  display: flex;
  flex-direction: column;
  min-width: 0;
  height: var(--bs-card-height);
  word-wrap: break-word;
  background-color: var(--bs-card-bg);
  background-clip: border-box;
  border: var(--bs-card-border-width) solid var(--bs-card-border-color);
  border-radius: var(--bs-card-border-radius);
}

// There are other rules (e.g. '.card > hr' and so on of course)
```

The only difference in Bootstrap v5.2 for `.card` is that we introduced CSS variables/custom properties. So as you can see there's no JavaScript involved at all.

Maybe you could try to create a [CodePen](https://codepen.io) or a [StackBlitz](https://stackblitz.com/) to show us the issue with a minimal reproducible example and [launch a discussion in our dedicated space](https://github.com/twbs/bootstrap/discussions) so that someone could maybe help you.

But TBH I don't see technically how it could mess with your app considering the fact that you already used the `.card` class before with Bootstrap v5.1.3 in your app.
