### ISSUE TITLE
Using Font-Awesome Icon in $breadcrumb-divider variable

### ISSUE THREAD

**Issue by alexander-rebello** [twbs/bootstrap#37666]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I am trying to use a font awsome icon (chevron-right) for the $breadcrumb-divider in my sass. My sass rule for that looks like this:

`$breadcrumb-divider: url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 384 512'><path d='M342.6 233.4c12.5 12.5 12.5 32.8 0 45.3l-192 192c-12.5 12.5-32.8 12.5-45.3 0s-12.5-32.8 0-45.3L274.7 256 105.4 86.6c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0l192 192z' fill='#{$breadcrumb-divider-color}'/></svg>") !default;`

When using the example from the docs

(`$breadcrumb-divider: url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' width='8' height='8'><path d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='#{$breadcrumb-divider-color}'/></svg>");`)

it works perfectly fine and also when I use the svg in html it works. The overwriting of the variable works also, because I can see the svg as value for the content rule for the ::before pseudo element of the breadcrumb item.

### Reduced test cases

https://codepen.io/alexander_r/pen/ZEjzorQ

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.2.0

**Comment by julien-deramond** [comment]
In the `#one` example, there's no width/height for the SVG so you can try adding `width='10' height='10'` in the CSS.

```css
#one {
  --bs-breadcrumb-divider: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='10' height='10' viewBox='0 0 384 512'%3E%3Cpath d='M342.6 233.4c12.5 12.5 12.5 32.8 0 45.3l-192 192c-12.5 12.5-32.8 12.5-45.3 0s-12.5-32.8 0-45.3L274.7 256 105.4 86.6c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0l192 192z' fill='%23666'/%3E%3C/svg%3E");
}
```

Seems to be displayed correctly on Firefox macOS.
