### ISSUE TITLE
Grid System should support CSS Container Queries for responsive column sizing

### ISSUE THREAD

**Issue by NateRadebaugh** [twbs/bootstrap#37807]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

CSS Container Queries are becoming widely supported.
* https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries
* https://caniuse.com/css-container-queries

Proposal: `_breakpoints.scss` should be extended to be configurable to use container queries, perhaps defaulting to the body or falling back to media queries where appropriate for backwards compatibility.

### Motivation and context

I have pages that can be displayed in either modal or full-page and currently there isn't a good way to wire up this sort of functionality.

Layouts with collapsible side navigation or modal dialogs would benefit from Container Queries instead of using normal Media Queries for responsive widths.

**Comment by goulvench** [comment]
I'm having the same issue, with grid layouts that get squished when rendered inside modals.
Here's a quick hack that just stacks grid columns inside modals:
```scss
// Stack grid columns when displayed in a modal
@each $breakpoint in map-keys($grid-breakpoints) {
  $infix: breakpoint-infix($breakpoint, $grid-breakpoints);
  @for $i from 1 through $grid-columns {
    .modal .col#{$infix}-#{$i} {
      width: 100%;
    }
  }
}
```

Adding this, any `.col-BP-I` class inside a modal will just stretch to full-width. It's a bit brutal but it works well. And it doesn't even need container queries, making it compatible with older browsers 😉

**Comment by NateRadebaugh** [comment]
Thanks @goulvench this is a nice workaround, but doesn't fully solve the need. For instance, if we have a shared component inside one of bootstrap's various modal sizes: https://getbootstrap.com/docs/5.3/components/modal/#optional-sizes

An additional scenario I'm trying to support is a layout with a side nav menu that can be expanded or collapsed. I'd like the grid system to be based on the width of the "main" component rather than the whole page width.

**Comment by Joniras** [comment]
I solved my problem (which was that i wanted to be responsive against the size of my content-container) with [patch-package](https://www.npmjs.com/package/patch-package) with the following patch (named patches/bootstrap+5.2.3.patch) : 

> The following Code does not set breakpoints relative to @media but relative to the element you add a specific class to.

```scss
diff --git a/node_modules/bootstrap/scss/mixins/_breakpoints.scss b/node_modules/bootstrap/scss/mixins/_breakpoints.scss
index 286be89..f80a7ea 100644
--- a/node_modules/bootstrap/scss/mixins/_breakpoints.scss
+++ b/node_modules/bootstrap/scss/mixins/_breakpoints.scss
@@ -61,7 +61,7 @@
 @mixin media-breakpoint-up($name, $breakpoints: $grid-breakpoints) {
   $min: breakpoint-min($name, $breakpoints);
   @if $min {
-    @media (min-width: $min) {
+    @container #{$containerName} (min-width: #{$min}) {
       @content;
     }
   } @else {
@@ -74,7 +74,7 @@
 @mixin media-breakpoint-down($name, $breakpoints: $grid-breakpoints) {
   $max: breakpoint-max($name, $breakpoints);
   @if $max {
-    @media (max-width: $max) {
+    @container #{$containerName} (max-width: #{$max}) {
       @content;
     }
   } @else {
@@ -89,7 +89,7 @@
   $max: breakpoint-max($upper, $breakpoints);
 
   @if $min != null and $max != null {
-    @media (min-width: $min) and (max-width: $max) {
+    @container #{$containerName} (min-width: #{$min}) and (max-width: #{$max}) {
       @content;
     }
   } @else if $max == null {
@@ -112,7 +112,7 @@
   $max:  breakpoint-max($next, $breakpoints);
 
   @if $min != null and $max != null {
-    @media (min-width: $min) and (max-width: $max) {
+    @container #{$containerName} (min-width: #{$min}) and (max-width: #{$max}) {
       @content;
     }
   } @else if $max == null {


```

and an additional styling: 
```scss

$containerName: mainSection;

.breakpoint-container {
  container-type: inline-size;
  container-name: $containerName;
}

```

and used like this: 

```html
...
<app-sidebar ></app-sidebar>
  <div>
    <app-header></app-header>
    <section class="breakpoint-container">
      ...
    </section>
    <app-footer ></app-footer>
  </div>
...
```

But i hope it gets built in in some form!

**Comment by Schwarcelo** [comment]
@Joniras where did you add the additional styling?
Could you create a Repository or something like that for your fix?

Thank you!

**Comment by Joniras** [comment]
The additional styling has to be applied on a global level. It has to be included before the bootstrap scss because the scss variable is defined in the additional styling and used in the (changed) bootstrap mixins.

**Comment by Moongazer** [comment]
+1 for that feature. E.g. creating cards or square-tiles holding lots of content (e.g. header, sub-header, text, buttons, ...) where the font-size should be scaled beside being rendered in 1-4 responsive columns depending on the parents width, is a huge mess just using breakpoints.

**Comment by lana-white** [comment]
Bootstrap are in dire need of adding this, it is such a basic necessity, that columns should be based on the container that they're in and not the device width. iFrames, modals, even just adding in an aside to a page stuffs up all of your bootstrap responsive classes.

**### PLEASE ADD THIS IN ASAP!!!!!!!!!!!!!!!!!!!!!!**

**Comment by manstie** [comment]
I have added this to my scss for the time being:
```scss
.cq {
    display: flex;
    flex-wrap: wrap;
    container-type: inline-size;
}

@each $infix, $breakpoint in $grid-breakpoints {
    @container (min-width: #{$breakpoint}) {
        .cq-#{$infix}-1 {
            flex: 0 0 auto;
            width: 8.33333333cqw;
        }

        .cq-#{$infix}-2 {
            flex: 0 0 auto;
            width: 16.66666667cqw;
        }

        .cq-#{$infix}-3 {
            flex: 0 0 auto;
            width: 25cqw;
        }

        .cq-#{$infix}-4 {
            flex: 0 0 auto;
            width: 33.33333333cqw;
        }

        .cq-#{$infix}-5 {
            flex: 0 0 auto;
            width: 41.66666667cqw;
        }

        .cq-#{$infix}-6 {
            flex: 0 0 auto;
            width: 50cqw;
        }

        .cq-#{$infix}-7 {
            flex: 0 0 auto;
            width: 58.33333333cqw;
        }

        .cq-#{$infix}-8 {
            flex: 0 0 auto;
            width: 66.66666667cqw;
        }

        .cq-#{$infix}-9 {
            flex: 0 0 auto;
            width: 75cqw;
        }

        .cq-#{$infix}-10 {
            flex: 0 0 auto;
            width: 83.33333333cqw;
        }

        .cq-#{$infix}-11 {
            flex: 0 0 auto;
            width: 91.66666667cqw;
        }

        .cq-#{$infix}-12 {
            flex: 0 0 auto;
            width: 100cqw;
        }
    }
}
```
so you can use it like row/col:
```html
<div class="cq">
        <div class="cq-xs-12 cq-sm-6 cq-lg-4">Hello</div>
        <div class="cq-xs-12 cq-sm-6 cq-lg-4">Hello</div>
        <div class="cq-xs-12 cq-sm-6 cq-lg-4">Hello</div>
</div>
```

**Comment by bastienmoulia** [comment]
I have started a repo to try implementing container queries in the bootstrap way, but it's still work in progress:
https://github.com/bastienmoulia/bootstrap-container-queries
PR welcomed 😉

**Comment by mdo** [comment]
Container queries are coming to v6. Unsure about adding to v5.4 at this point, but leaving open. This would be a breaking change in v5 to automatically update things to use container vs viewport media query though.

**Comment by hybridwebdev** [comment]
> I have started a repo to try implementing container queries in the bootstrap way, but it's still work in progress: https://github.com/bastienmoulia/bootstrap-container-queries PR welcomed 😉

Anyone who comes across this from google or whatever search engine brought you here. Skip it. It's total rubbish.

**Comment by nextgenthemes** [comment]
I hope the general grid system gets container queried by default. I think It's pretty much universally better. The site layout where you name your grid areas people will do manually anyway but any kind of grid system you quickly want to put together by slapping some classes on elements its always something that is better with CQ. Even without sidebars or anything if you just simply change padding on a container/body the grid system would auto adjust.

I see some components on v6 already use CQ, that is great. v6 now has both Flexbox and Grid based grid classes enabled by default. I am still unsure about when to use what. I remember reading on CSS Tricks that Flex is better if you prioritize content and Grid is better if you prioritize layout. To me, I always felt like Grid is just simpler and more modern and I use it manually enabled in v5 already for everything.

For simple things you actually do not even need any breakpoints with CSS Grid. The WordPress Grid Block takes two values, the `Min. column width` and `Max columns`

Then it creates this out of it, but that's it, no breakpoints needed. That is pretty cool (13rem, max 3 cols)

```css
grid-template-columns: repeat(auto-fill, minmax(max(min(13rem, 100%), (100% - (24px * (3 - 1))) / 3), 1fr));
```

https://v6-dev--twbs-bootstrap.netlify.app/docs/6.0/forms/layout/

Here you can see the forms would benefit from container queries, when the sidebars kick in ...

@hybridwebdev 

> > I have started a repo to try implementing container queries in the bootstrap way, but it's still work in progress: https://github.com/bastienmoulia/bootstrap-container-queries PR welcomed 😉
> 
> Anyone who comes across this from google or whatever search engine brought you here. Skip it. It's total rubbish.

Explain to us WHY this is "rubbish" instead of just trashing somebody work without any argument.

**Comment by hybridwebdev** [comment]
> Explain to us WHY this is "rubbish" instead of just trashing somebody work without any argument.

Several MAJOR issues:

- Does NOT work out of the box. Took a LOT of effort to get it to even work without errors. Clearly it was not tested. 
- Breakpoints are not created correctly. They do not work the same way bootstraps native responsive breakpoints are implemented. They're completely backwards.
- Repeats a LOT of bootstraps native code. Not DRY at all. 

Like I said, it's a total waste of time.

**Comment by adasnow1231-afk** [comment]
Thank you for providing more specific feedback regarding the implementation
issues you encountered.

Could you please clarify which specific errors you ran into while setting
it up? Additionally, any examples of how the breakpoints are behaving
incorrectly compared to Bootstrap's native responsive implementation would
be very helpful.

Regarding the code repetition, I'm open to suggestions on how to make the
repository more DRY while still maintaining the core functionality. If you
have any specific ideas or want to open a PR to address these points,
please let me know.

**Comment by nextgenthemes** [comment]
@hybridwebdev Yeah, thanks. I found it out myself after that it's not working, maybe next time include a tiny bit of reasoning. I am very skeptical, I do not know if you do not like the coding style, the class names used or whatever, so there I went and wasted my time, not as much as you but still the thing you were trying to prevent.

Even he abandoned it, if you spend a lot of time getting it to work you could send a PR so at least people could see/use your working version.

Anyway I hope mdo or someone will do it better.

**Comment by mdo** [comment]
Yeah this is definitely something worth evaluating now. We're super super close on v6 going to an alpha. I'm trying my best to get issues and PRs closed, major issues addressed or started at least. Could even be a situation where one grid is container-ed and another isn't? I dunno yet.

**Comment by hybridwebdev** [comment]
> [@hybridwebdev](https://github.com/hybridwebdev) Yeah, thanks. I found it out myself after that it's not working, maybe next time include a tiny bit of reasoning. I am very skeptical, I do not know if you do not like the coding style, the class names used or whatever, so there I went and wasted my time, not as much as you but still the thing you were trying to prevent.
> 
> Even he abandoned it, if you spend a lot of time getting it to work you could send a PR so at least people could see/use your working version.
> 
> Anyway I hope mdo or someone will do it better.

Yeah I didn't end up keeping the code because it was just bad. I ended up rolling my own that builds off bootstrap natively. I'll post it here for anyone that may come across this and wants an alternative:

```scss


@mixin cq-breakpoint-up( $name, $breakpoints ) {
  
  $min: map-get( $breakpoints, $name );

  @if $min != 0 {
    @container (min-width: #{$min}) {
      @content;
    }
  } @else {
    @content;
  }

} 
  
@mixin apply-container-queries-to-utilities( $prefix, $breakpoints, $utilities ){
  
  @each $breakpoint in map-keys( $breakpoints ) {

    @include cq-breakpoint-up( $breakpoint, $breakpoints ) {

      @each $key, $utility in $utilities {

        $bp: if( $breakpoint == none, "", "-#{$breakpoint}" );

        $_prefix: if( $key == 'cq-container-type', "", $prefix );

        @if map-get( $utility, responsive ) {

          @include generate-utility( $utility, "#{$_prefix}#{$bp}");
        
        }
         
      }

    }

  }

}

@mixin apply-container-queries-to-grid( $prefix, $breakpoints ){

  @each $breakpoint in map-keys( $breakpoints ) {

    @include cq-breakpoint-up( $breakpoint, $breakpoints ) {

      $bp: if( $breakpoint == none, "", "-#{$breakpoint}" );

      @for $i from 1 through $grid-columns {
        
        .g-col#{$prefix}#{$bp}-#{$i} {
          grid-column: auto / span $i;
        }

        .col#{$prefix}#{$bp}-#{$i} {
          flex: 0 0 auto;
          width: percentage($i / $grid-columns);
        }

      }
      
      .g-col#{$prefix}#{$bp}-auto {
        grid-column: auto
      }

      .col#{$prefix}#{$bp} {
        flex: 1 0 0%;
      }

      .col#{$prefix}#{$bp}-auto {
        flex: 0 0 auto;
        width: auto;
      }

    }

  }

}

// This adds a .cq class that is added to an element to have it support container query. 

$utilities: map-merge(
  $utilities,
  (
    "cq-container-type": (  
      responsive: true,
      property: container-type,
      class: cq,
      values: (
        null: inline-size
      )
    ),
  )
);

@include apply-container-queries-to-utilities( "-cq", $grid-breakpoints, $utilities );
@include apply-container-queries-to-grid( "-cq", $grid-breakpoints );

```

Just drop it in a scss file and load it after you've loaded the relevant bootstrap stuff (maps, utilities etc). It just replicates everything bootstrap does. Eg it will iterate all utilities etc. No hacks, just does container queries the same way BS does its normal media queries.  

You can do something like
```html
<div class='cq'>
    <div class='d-cq-md-flex p-cq-md-2'>
```
