### ISSUE TITLE
margins with RTL support

### ISSUE THREAD

**Issue by BSarmady** [twbs/bootstrap#37854]
Since there is no `margin-start` and `margin-end` exist in CSS, I assumed 
`me-auto` and `ms-auto` will handle this by adding  `:ltr` and `:rtl` for directional support.

Note that if I wanted to explicitly use margin-left and margin-right there could be `mr-auto` and `ml-auto`

Is this a bug or over expectation from me?

On an unrelated note, when working with 5.2.3 I noticed a few of values are not defined. since this is not the latest version (an alpha is in works) I thought it is not necessary to open a separate issue for it, as they might have fixed.
I assume the do not cause a serious issue in rendering of the website, however they cause havoc in phpstorm and webstorm show 27 errors on each of bootstrap css files.

Following variables are missing a definition
`--bs-body-text-align` 
`--bs-nav-link-font-size` 
`--bs-scroll-height` 
`--bs-breadcrumb-font-size` 
`--bs-breadcrumb-divider` 

Following variables do not have a value (I assume `none` or `inherit` could be used?)
`--bs-btn-font-family` 
`--bs-dropdown-box-shadow` 
`--bs-nav-link-font-weight` 
`--bs-card-box-shadow` 
`--bs-card-cap-color` 
`--bs-card-height` 
`--bs-card-color` 
`--bs-breadcrumb-bg`
`--bs-breadcrumb-border-radius`
`--bs-toast-color`
`--bs-modal-color` 
`--bs-modal-footer-bg` 
`--bs-tooltip-margin`
`--bs-popover-header-color`
`--bs-offcanvas-color`

**Comment by Sarvesh-Ghildiyal** [comment]
@BSarmady **ms-auto** will shift your content to right, it woks same as **ml-auto**.. Or in other words you can say, ms=margin left(ml) and me=margin right(me).. So, both of these things are equivalent, the only change is ms stands for margin start and me stands for margin end. Hope! this helps/.

**Comment by BSarmady** [comment]
@Sarvesh-Ghildiyal,
`m (start)-auto` should shift content to start and `m(end)-auto` should shift content to end. 
`m(lleft)-auto`  on the other hand, should shift content to left as expected and same concept for `m(right)-auto`

In case of `Right To Left` direction (languages) start doesn't mean left (means right) and end doesn't mean right (means left)

Same concept goes to padding-start, align-start, text-start, .... if they existed.

Hope this clarifies.

**Comment by ffoodd** [comment]
Start and end exist in CSS, known as logical properties (in opposition to physical properties, using right and left keywords). 

V5 spacing utilities use this naming to ensure the same markup can be used for both LTR and RTL pages, although they're still applying left and right physical properties (and to shift from one to the other, you'd used a dedicated file, respectively `bootstrap.css` or `bootstrap.rtl.css`).

V6 should use logical properties and keep the current class names, which would allow to use a single CSS file, whatever the direction is.

I hope this clarifies things, but you can take a look at our docs and previous issues, pull requests and discussions to better understand our choices.

**Comment by julien-deramond** [comment]
> On an unrelated note, when working with 5.2.3 I noticed a few of values are not defined. since this is not the latest version (an alpha is in works) I thought it is not necessary to open a separate issue for it, as they might have fixed.

Regarding this part, it's probably a duplicate of https://github.com/twbs/bootstrap/issues/36595.

**Comment by BSarmady** [comment]
@ffoodd , You are correct. 

Even though using separate css file for RTL and LTR makes my job harder specially on a multi-language website when user can instantly change from one language to another, I'm doing that. but having only ms-auto and missing ms-left causes bugs.

What I'm trying to say, is we don't always want to `ms-auto`, `text-start`,  `float-start` ... 
Sometimes we need to `ms-left`, `text-left` e.g. putting a text or picture on top of another picture, and that text or picture, showing a phone number or coordinate on map, a number field, ... , it need to stay there, regardless of direction of page.

For example a field with number entry in LTR is aligned to right, it is also aligned to right in RTL but I cannot use text-end since it would push the numbers to the wrong side of field. this is more problematic on phone number (fields with `- + ( )` ) or codes that start with English alphabets (e.g. A3000412 will show as 3000412A)


Not having `-left`, `-right`, because we have `-end`, `-start` is an inconvenience at best (have to define it myself for whole team)
May be it is over expectation from my side, but having those would be nice, so I don't have to add one extra css file to project.

BTW, since most RTL styles are same as LTR styles. I remove duplicates and add :dir(RTL)  to styles different between LTR and RTL and merge them to same file. My users would always be able to see both language instantly anyway. so it is less bandwidth for me to have a single file instead of two almost identical.


@julien-deramond, I wasn't trying to make a bug report (since I'm on 5.2.3 and not latest), it was kind of a reminder that some might not been fixed yet,

**Comment by ffoodd** [comment]
We already handle [a few edge cases like number input by setting the `direction` CSS property in RTL build](https://github.com/twbs/bootstrap/blob/main/scss/_reboot.scss#L538) based on user feedbacks while we were implementing RTL and on [Ahmad Shadeed's RTL styling 101](https://rtlstyling.com/)—but indeed, applying our spacing utilities on those elements won't match your expectations.

While obviously there always edge cases we're not aware of, we tried to handle as much as we can.

The current state of Bootstrap RTL build relies on RTLCSS to convert horizontal directional styles to their counterparts (eg. left becomes right, etc.), which currently prevent using both versions at the same time—even if there's a workaround suggested in our docs. This is known limitation and have been tolerated for v5 since a different RTL build was better than no RTL handling at all. V6 and logical properties would match your expectations since setting `direction` in CSS would make `start` and `end` corresponding to the right side.

Using `:dir()` and deduping styles is (at the time of writing) fighting against the framework, but if you find yourself more comfortable doing so, I encourage you to share your how-to in this discussion, as it might help others.

Now, as your explanations are quite technical and you seem to know what you're doing, the current best way to get `left` and `right` properties is to use our Sass Utilities API to add them—which we recommended already multiple times to people preferring `left` and `right` to `start` and `end` (while most of them being users not needing RTL at all).

**Comment by mdo** [comment]
Comments here are correct, so closing out as a won't fix given utility API.

**Comment by BSarmady** [comment]
@ffoodd , @mdo,

As this issue is closed. I just put my suggestion here.

Again this might be edge case for most people, but for my software, people can switch between RTL and LTR languages instantly. or in other words they are both available at the same time (most of the time element level)

With this, I cannot link both RTL and LTR css files at the same time, since they conflict.

Instead, I combine `bootstrap.css` and `bootstrap.rtl.css` to one single file, ignoring classes that are similar between RTL and LTR
next I add `[dir="rtl"]` infront of classes that are meant for RTL overriding those properties that are different.

```css
.me-auto{ margin-right:auto !important; }
[dir="rtl"] .me-auto{ margin-left:auto !important; margin-right:unset !important; }

.ms-auto{ margin-left:auto !important; }
[dir="rtl"] .ms-auto{ margin-left:unset !important; margin-right:auto !important; }

.text-start { text-align: left !important; }
[dir="rtl"] .text-start { text-align: right !important; }

.text-end { text-align: right !important; }
[dir="rtl"] .text-end { text-align: left !important; }

...

/*These classes are needed for hard left and right ( number, date and code container elements) */
.ml-auto{ margin-left:auto !important; }
.mr-auto{ margin-right:auto !important; }

.text-left { text-align: left !important; }
.text-right { text-align: right !important; }

...
```

This is until chrome, edge and opera too start supporting `:dir(LTR)` and `:dir(RTL)` at that time, those classes will be simpler and I don't need to unset the opposite property

```css
.me-auto:dir(ltr){ margin-right:auto !important; }
.me-auto:dir(rtl){ margin-left:auto !important; }
.ms-auto:dir(ltr){ margin-left:auto !important; }
.ms-auto:dir(rtl){{ margin-right:auto !important; }
...
```

Since changing from LTR to RTL just need adding an attribute to HTML tag in most cases (it immediately changes direction)
in some other cases (e.g. posting to forum) it is applied to root element of form using a button and everything works fine in both direction. User can switch between two modes by clicking that button and continue preparing their post in their desired language. and when retrieving a text content from server, I just need to set the direction on root of element and I'm good to go, without worrying if it will show codes, numbers and dates in wrong direction (I fix them using `text-left` and `text-right` instead of `text-end` and `text-start`)
