### ISSUE TITLE
Dark mode's derived variables should reference the variables they are based on, not the defaults

### ISSUE THREAD

**Issue by yugabe** [twbs/bootstrap#37949]
### Discussed in https://github.com/orgs/twbs/discussions/37911

<div type='discussions-op-text'>

<sup>Originally posted by **Nysosis** January 18, 2023</sup>
I'm just looking through the https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss and wondering why the variables at https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss#L325 aren't based off the actual, and primarily I'm concerned on `$primary` variable, instead they use the appropriate shade of what the default colour is.

If I change the $primary, I would have thought it would feed through into all derived colours, instead of also needing to override those (and potentially others down the line)</div>

----

This seems to be mainly true for colors defined in _variables-dark.scss and _variables.scss. It became mostly impossible to migrate to 5.3.0 from 5.2.x, because overriding the base colors don't work at all.

For reference, I think the correct way to define the dark mode variables would be similar to as follows:

    _variables-dark.scss:

``` scss

/* ... */

// scss-docs-start sass-dark-mode-vars
$primary-text-dark: tint-color($primary, 40%) !default; // was $blue-300 !default;
$secondary-text-dark: $gray-300 !default; // Kept as is. As secondary is used as "disabled" colors, it doesn't really make sense to override them at all anyways. Grays are defined manually, so tinting isn't straighforward either.
$success-text-dark: tint-color($success, 40%) !default; // was $green-300 !default;
$info-text-dark: tint-color($info, 40%) !default; // was $cyan-300 !default;
$warning-text-dark: tint-color($warning, 40%) !default; // was $yellow-300 !default;
$danger-text-dark: tint-color($danger, 40%) !default; // was $red-300 !default;
$light-text-dark: $gray-100 !default;
$dark-text-dark: $gray-300 !default;

$primary-bg-subtle-dark: shade-color($primary, 80%) !default; // was $blue-900 !default;
$secondary-bg-subtle-dark: $gray-900 !default;
$success-bg-subtle-dark: shade-color($success, 80%) !default; // was $green-900 !default;
$info-bg-subtle-dark: shade-color($info, 80%) !default; // was $cyan-900 !default;
$warning-bg-subtle-dark: shade-color($warning, 80%) !default; // was $yellow-900 !default;
$danger-bg-subtle-dark: shade-color($danger, 80%) !default; // was $red-900 !default;
$light-bg-subtle-dark: $gray-800 !default;
$dark-bg-subtle-dark: mix($gray-800, $black) !default;

$primary-border-subtle-dark: shade-color($primary, 40%) !default; // was $blue-700 !default;
$secondary-border-subtle-dark: $gray-700 !default;
$success-border-subtle-dark: shade-color($success, 40%) !default; // was $green-700 !default;
$info-border-subtle-dark: shade-color($info, 60%) !default; // was $cyan-800 !default;
$warning-border-subtle-dark: shade-color($warning, 60%) !default; // was $yellow-800 !default;
$danger-border-subtle-dark: shade-color($red, 40%) !default; // was $red-700 !default;
$light-border-subtle-dark: $gray-700 !default;
$dark-border-subtle-dark: $gray-800 !default;

$body-color-dark: $gray-500 !default;
$body-bg-dark: $gray-900 !default;
$body-emphasis-color-dark: $gray-100 !default;
$body-secondary-color-dark: rgba($body-color-dark, .75) !default; // Wierd to see how this correctly references its base color...
$body-secondary-bg-dark: $gray-800 !default;
$body-tertiary-color-dark: rgba($body-color-dark, .5) !default; // This too.
$body-tertiary-bg-dark: mix($gray-800, $gray-900, 50%) !default;
$emphasis-color-dark: $white !default;
$border-color-dark: $gray-700 !default;
$border-color-translucent-dark: rgba($white, .15) !default;
$headings-color-dark: #fff !default; // This is just plain bad, I would certainly do a blame on this. Why use $white one line above, and #fff here?
$link-color-dark: tint-color($primary, 40%) !default; // was $blue-300 !default;
$link-hover-color-dark: shift-color($link-color-dark, -$link-shade-percentage) !default; // was $blue-200 !default; - I'm taking a guess shading with a negative value will work correctly.
$code-color-dark: tint-color($code-color, 40%) !default; // was $pink-300 !default;

/* ... */
```

     _variables.scss

```scss
/* ... */

$primary-text: shade-color($primary, 20%) !default; // was $blue-600 !default;
$secondary-text: $gray-600 !default;
$success-text: shade-color($green, 20%) !default; // was $green-600 !default;
$info-text: shade-color($info, 40%) !default; // was $cyan-700 !default;
$warning-text: shade-color($warning, 40%) !default; // was $yellow-700 !default;
$danger-text: shade-color($danger, 20%) !default; // was $red-600 !default;
$light-text: $gray-600 !default;
$dark-text: $gray-700 !default;

$primary-bg-subtle: tint-color($primary, 80%) !default; // was $blue-100 !default;
$secondary-bg-subtle: $gray-100 !default;
$success-bg-subtle: tint-color($success, 80%) !default; // was $green-100 !default;
$info-bg-subtle: tint-color($info, 80%) !default; // was $cyan-100 !default;
$warning-bg-subtle: tint-color($warning, 80%) !default; // was $yellow-100 !default;
$danger-bg-subtle: tint-color($danger, 80%) !default; // was $red-100 !default;
$light-bg-subtle: mix($gray-100, $white) !default;
$dark-bg-subtle: $gray-400 !default;

$primary-border-subtle: tint-color($primary, 60%) !default; // was $blue-200 !default;
$secondary-border-subtle: $gray-200 !default;
$success-border-subtle: tint-color($success, 60%) !default; // $green-200 !default;
$info-border-subtle: tint-color($info, 60%) !default; // $cyan-200 !default;
$warning-border-subtle: tint-color($warning, 60%) !default; // $yellow-200 !default;
$danger-border-subtle: tint-color($danger, 60%) !default; // $red-200 !default;
$light-border-subtle: $gray-200 !default;
$dark-border-subtle: $gray-500 !default;

/* ... */
```

It would be even better if the default was calculated based on the default light value, so that it would be lightened/darkened sufficiently enough that the target contrast ratio could be achieved. This is mostly because like `$primary-border-subtle-dark` uses `$blue-700`, but `$info-border-subtle-dark` uses `$cyan-800`, so they cannot use the same percentage for shading (unless we accept 50% as a correct middle ground).

A problem is with light, dark and "secondary", which are whites, blacks and shades of gray. See comments in the code above. Secondary shouldn't have been repurposed as the color that you use for "disabled" states and whatnot - or I might have missed it previously, but overriding it makes a bit less sense in this case.

It's very obvious no reference should be made to discrete colors (like `$red`) in the body of the "_variables*.scss" files instead where they are defined and assigned to the default theme - so, usually once.

Making multiple different variables in 5.3.0 doesn't help at all if someone wants do define more theme colors then the ones currently built in. The docs don't reflect how adding one more color to the theme map might affect all related aspects either.

**Comment by mdo** [comment]
The `$secondary` color hasn't been repurposed entirely yet, but the aim is to do that in v6 (and then add to it with `$tertiary`). Just the names have been re-used for "body secondary/tertiary" as I wanted a new way to reference shades of foreground and background colors without just adding a new number scale like `body-bg2` or `body-bg3`. Was thinking we could drop `secondary` in v6, add an `accent`, and maybe replace the light/dark options with `emphasis` and `reverse` (to hit that request for a light in dark and dark in light button). Would make the color mode adaptive colors more sensible.

I'll experiment with normalizing some of those percentages as well...might be that we use a middle value with new colors instead, but I'm trying to avoid generating new hex values in our compiled code.

**Comment by yugabe** [comment]
Regarding `$secondary`, it's a shame, because migration will be very hard for those who already configured it. 

Regarding generating new hex values, you might consider dropping the color variants and generate variants for the theme colors instead? I'm not sure the color variants ($blue-700) add anything useful, and the framework itself shouldn't depend on colors other than the theme colors themselves anyway. That could potentially solve this too. So `$primary-text-dark` could become `$primary-300`, and so on.

Having `$primary-lighter` and `$primary-darker` in many places (including the other theme colors) would be great, but I assume it would generate quite a large output in the end. It would be nice if CSS itself would support parametrization in its selectors, but I'm not even aware of any proposals to the spec regarding this.

My solution for a 5.2.3 dark mode was... quite simple, really. It didn't work everywhere, and it was hacky, but you could also consider setting the dark values to light in dark mode and vice-versa. The naming would be confusing though, because a "bg-dark" in dark mode would become light. It might be better to use only a normal `body` color (maybe with shades), and an "inverse" one - dropping the light variant?

Just for reference, my poor man's dark mode for Bootstrap <5.3.0:
```scss
@import "_variables.scss";

$dark-mode-colors: ();

$dark-mode-theme-colors: (
    "primary": tint-color($primary, 20%),
    "secondary": tint-color($secondary, 20%),
    "success": tint-color($success, 20%),
    "info": tint-color($info, 20%),
    "warning": tint-color($warning, 20%),
    "danger": tint-color($danger, 20%),
    "light": $dark,
    "dark": $light
);

$dark-mode-to-rgb: map-merge($dark-mode-theme-colors, (
    "body-color": tint-color($body-bg, 10%),
    "body-bg": shade-color($body-color, 25%),
    "black": $white,
    "white": $black
));

$dark-mode: map-merge(map-merge($dark-mode-to-rgb, $dark-mode-theme-colors), $dark-mode-colors);

.prefers-dark:not(.reset-dark) {
    @each $variable, $value in $dark-mode {
        --pnx-#{$variable}: #{$value};
    }

    @each $variable, $value in $dark-mode-to-rgb {
        --pnx-#{$variable}-rgb: #{to-rgb($value)};
    }

    --pnx-link-color: #{tint-color($link-color, 30%)};
    --pnx-link-hover-color: #{tint-color($link-hover-color, 30%)};
    --pnx-code-color: #{$code-color};
    --pnx-highlight-bg: #{$mark-bg};
}

.reset-dark {
    @extend :root;
}

```
