### ISSUE TITLE
[enhancement] light and dark mode easy way

### ISSUE THREAD

**Issue by BSarmady** [twbs/bootstrap#37961]
Most of the websites these days allow users to switch between dark and light mode with just one click.

With current bootstrap coloring model to implement dark mode classes such as `dropdown-menu-dark` `navbar-dark`, `.text-bg-light` ... have to be added separately to each component. Implementing dark mode this way is not an easy task since you will need to add classes to entire elements manually or add them by default and then remove them by JavaScript  when light mode requested. 
With this some components are still not behaving correctly (hard-coded colors in component).

However an easier way would be adding a single `dark` class to body and that is it. 

To implement it, I define all light mode (default) color variables in `:root` and then define same variables for dark mode in another `,dark` group class.

for example
```css
.dark{
    --body-bg:rgba(var(--bs-dark-rgb), 0.9);
    --bs-border-color:#343a40;
    --bs-link-color:#3d8bfd;
    --bs-link-hover-color:#9ec5fe;
}
```

With this configuration I can also add theme variants to group classes and then add them to body tag to instantly change entire theme of the website in one go. again default theme will be defined in `:root`

```css
.theme-red{
    --header-bg:#d50000;
    --drawer-bg-0:#b71c1c;
    --drawer-bg-1:#c62828;
    --drawer-bg-2:#d32f2f;
    --drawer-bg-active:#a70c0c;
}
```
Obviously pre-defined colors (primary secondary, danger, success, ...) stay same but dark and light will reverse.

Since I just started to use bootstrap, I'm not sure if this is a good idea or is it even feasible, but I had to change a lot of bootstrap css to make this happen and still a lot more places are not working correctly. for example I had to change .btn-close svg like this

```css
:root
    --btn-close-icon: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23000'%3e%3cpath d='M.293.293a1 1 0 0 1 1.414 0L8 6.586 14.293.293a1 1 0 1 1 1.414 1.414L9.414 8l6.293 6.293a1 1 0 0 1-1.414 1.414L8 9.414l-6.293 6.293a1 1 0 0 1-1.414-1.414L6.586 8 .293 1.707a1 1 0 0 1 0-1.414z'/%3e%3c/svg%3e");
    --btn-close-hover: var(--bs-dark)
}

.dark{
    --btn-close-icon: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23fff'%3e%3cpath d='M.293.293a1 1 0 0 1 1.414 0L8 6.586 14.293.293a1 1 0 1 1 1.414 1.414L9.414 8l6.293 6.293a1 1 0 0 1-1.414 1.414L8 9.414l-6.293 6.293a1 1 0 0 1-1.414-1.414L6.586 8 .293 1.707a1 1 0 0 1 0-1.414z'/%3e%3c/svg%3e");
    --btn-close-hover: var(--bs-light)
}

.btn-close{ background:transparent var(--btn-close-icon) center/1em auto no-repeat; }
.btn-close:hover{ color:var(--btn-close-hover); }
```

Would be nice to have this implemented by default.

**Comment by BSarmady** [comment]
Implementing this will require changing for example 

```css
.form-control-dark {
    background-color: rgba(255, 255, 255, .05);
    border-color: rgba(255, 255, 255, .15);
}
```
to

```css
.dark .form-control {
    background-color: rgba(255, 255, 255, .05);
    border-color: rgba(255, 255, 255, .15);
}
```
