### ISSUE TITLE
Default to using the `prefers-color-scheme` in @media for automatically rendering the client's preferred colour scheme

### ISSUE THREAD

**Issue by dan-giddins** [twbs/bootstrap#37973]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I'm very happy that dark mode has been added to bootstrap, I think its been in desperate need of it for a long time now. However I am a bit disappointed in the way it has been implemented. I do not like how the 'default' way of using it is to hard code elements to be a particular colour scheme. I believe it would be better to, by default, look to `prefers-color-scheme` to automatically decide how every element on the page should be rendered, and to view all bootstrap components as being 'colour scheme agnostic', i.e. the same semantic design is present, regardless of the client's specific colour scheme preference.

I appreciate that it is possible through the use of JavaScript to create a toggler, but there is no guarantee that developers will do this.

Before v5.3 was released, I added my own rules to my site, using the following CSS, which hijacks some of Bootstrap's internal variables:
``` css
@media (prefers-color-scheme: dark) {
	:root {
		--bs-body-color: white;
		--bs-white-rgb: 32, 32, 32;
		--bs-light-rgb: 40, 40, 40;
		--bs-dark-rgb: 255, 255, 255;
		--bs-border-color: grey;
	}
}
```
This mostly worked well, causing my site to automatically render in the light mode when user is in light mode, and dark mode. However due to the way Bootstrap was (is still?) designed, I had to intervene in a few other areas as well (for the sake of `@media (prefers-color-scheme: dark)`):
``` css
	.form-control {
		background-color: rgb(var(--bs-white-rgb));
		border-color: var(--bs-border-color);
		color: var(--bs-body-color);
	}

		.form-control:focus {
			background-color: rgb(var(--bs-light-rgb));
			color: var(--bs-body-color);
		}

	.alert {
		background-color: var(--bs-alert-color);
		color: var(--bs-alert-bg);
	}

	.btn-close {
		filter: invert(1) grayscale(100%) brightness(200%);
	}
```

### Motivation and context

I personally prefer dark theme. I find it much easier on the eyes to read, and I think a lot of people, especially developers agree with me and also have this preference. However, I also know someone who really struggles with dark mode, to the point that they cannot read the contents of any page with white text on a black background due to their [astigmatism](https://en.wikipedia.org/wiki/Astigmatism), and will simply cease to use that site, as the site is completely unusable to them. There are also many people who prefer light theme, either because they find it more comfortable to read, or it is just their personal preference.

I really despise having to use a site that is fixed to be light theme, in the same way that people who require/prefer a light theme despise having to or simply won't use a dark theme site. I see this as an accessibility issue that stretches all the way from a minor preference to absolutely critical for a sites usability.

If, by default, the easiest way that dark theme is available to a developer is through the use of `data-bs-theme="dark"`, then we know full well that many developers will simply drop `data-bs-theme="dark"` at the `html` tag level, rendering the site fully dark theme, creating an uncomfortable or even unusable experience for those who prefer light theme. Conversely, if a developer is ignorant of the `data-bs-theme` system, or prefers light theme, then they will, by default, create a site that will be light theme, causing a problem for those of us who prefer dark theme.

My interpretation of the Bootstrap library philosophy is that usage of it should allow a site to be as usable and as accessible as possible to the highest number of users, with the least amount of developer input. Surely, the default theme of the page should be whatever the client prefers through the use of `prefers-color-scheme`? If the site is well made with a correct application of Bootstrap, then this would cause this site to automatically present a dark theme to a user, simply with the upgrading of the version of Bootstrap. Then if the client does have a reason to force a certain colour scheme, they then could explicitly override this.

Bootstrap already automatically looks at properties of the client for `prefers-reduced-motion` for the sake of accessibility. Why is `prefers-color-scheme` any less deserving of this status? While we are at it, `prefers-contrast` could also be given the same treatment. Image all the sites that would automatically become more accessible to more people.

**Comment by mdo** [comment]
For v5, it'll stay as-is with the data attributes being the first class method for adding new color modes. Right now, `prefers-color-scheme` only supports `light` and `dark` values. We wanted to implement color modes that extend beyond light and dark, allowing you to build and ship more complex and custom series of "themes", color schemes, or color modes. For example, you could have light, dark, dimmed dark, high contrast, and high contrast dark.

Beyond that, shipping a whole new behavior to anyone who updates in a minor release feels like an overreach. The vast majority of websites built on Bootstrap likely don't have dark mode, and surprising them with it doesn't feel right.

Lastly, it bears mentioning that while the data attributes are static by default, our JS color mode picker that we use in our own docs defaults to automatically changing the color mode to match the OS color mode. This gives developers and users flexibility. Developers can pick what modes to include, while users can use their OS defaults or select an override as their new default. This is the case in Bootstrap's docs, and the solution we recommend others take as well.

Hope that helps explain things more.

**Comment by dan-giddins** [comment]
@mdo 
> our JS color mode picker that we use in our own docs defaults to automatically changing the color mode to match the OS color mode.

I use .NET Blazor, so my projects are free of JS, but I could do the same thing in C#. However, I feel that its better to use inbuilt CSS styling functionality instead of using something dynamic, where possible.

I also wonder how popular the ability for a user to be able to change the theme of a site manually on the fly actually is. I wouldn't be surprised if most users don't just stick with/select the same theme that their OS/Browser is currently running anyway.

The ability to have different colour themes is an interesting one, and it will be interesting to see how you progress with that, and what the uptake of this is like.

For now though, I think for the sites I build, I will continue to just use my custom `(prefers-color-scheme: dark)` rules for simplicity. It would be nice though to only need to override root variables, not have to manually override rules like:
``` css
.form-control {
	background-color: rgb(var(--bs-white-rgb));
	border-color: var(--bs-border-color);
	color: var(--bs-body-color);
}
```
I think when I looked at these properties, they are getting their colours from hard coded values. Is there any reason why they aren't instead drawing from variables? I think I may raise a PR to improve this, unless you can think of reason why I shouldn't...

**Comment by mdo** [comment]
> I think when I looked at these properties, they are getting their colours from hard coded values. Is there any reason why they aren't instead drawing from variables? I think I may raise a PR to improve this, unless you can think of reason why I shouldn't...

Not sure I follow you there, please open that PR if possible if you see an opportunity for impromement :).

**Comment by EccentricVamp** [comment]
@mdo

> Shipping a whole new behavior to anyone who updates in a minor release feels like an overreach.

I agree. Maybe this entire feature should wait until version 6?

> The vast majority of websites built on Bootstrap likely don't have dark mode

This statement seems to conflate the lack of a feature with the lack of desire or preparedness.

> Our JS color mode picker that we use in our own docs defaults to automatically changing the color mode to match the OS color mode. This gives developers and users flexibility. Developers can pick what modes to include, while users can use their OS defaults or select an override as their new default

`prefers-color-scheme` and `prefers-contrast` also offers flexibility to developers and users. Developers can choose which scheme's their site supports via meta attributes or CSS. And users can choose via their browser (or OS) defaults.

My company wants to use offer dark mode on our websites, but the current implementation only seems to give us two options.

* Write a custom "color mode" picker from scratch in JavaScript and maintain it for the foreseeable future
* Recompile Bootstrap's Sass from scratch, and then recompile it again everytime an update comes out.

My coworkers (who are software developers) have very little experience with JavaScript and zero experience with Sass. So, we effectively can't use dark mode.

**Comment by dan-giddins** [comment]
@EccentricVamp for now, try adding this on to the end of your custom site.css file for now to go with my 'auto dark theme' approach:
``` css
@media (prefers-color-scheme: dark) {
	:root {
		/*custom dark theme rgb values*/
		--dark-1: 32, 32, 32;
		--dark-2: 48, 48, 48;
		--dark-3: 64, 64, 64;
		--light-1: 240, 240, 240;
		/*bs overrides*/
		--bs-body-color: rgb(var(--light-1));
		--bs-white-rgb: var(--dark-1);
		--bs-light-rgb: var(--dark-2);
		--bs-dark-rgb: var(--light-1);
		--bs-border-color: rgb(var(--dark-3));
		--bs-body-bg: rgb(var(--dark-1));
	}

	/*swap colours*/
	.alert {
		background-color: var(--bs-alert-color);
		color: var(--bs-alert-bg);
	}

	/*invert*/
	.btn-close {
		filter: invert(1) grayscale(100%) brightness(200%);
	}
}
```
Basically, you code the whole site for light mode, and then just add in this media query for dark mode users. The advantage of doing things this way is that you are using native CSS media queries to set the site theme, so that the site is the 'right' theme for the user before it is even rendered to the page. But the disadvantage of this is that it may be tricky to give the user the ability to manually toggle the site theme.

This code is working for me however, and it looks great imo (although you may need to add more bootstrap variable overrides and custom class rules as you add in more components to your project).

Maybe it might be worth setting up a new repo just for maintaining this 'auto dark mode' code for everyone to contribute to...

@mdo
> Not sure I follow you there

I had another look, and I realise now that the way bootstrap is currently built is actually fine for me as is for this; I just wasn't making proper use of all of the variables. I have also done a little refactor to pull out the RGA values, as these seem to be fundamental in the bootstrap rules for allowing for transparency, and this also allows me to define my dark mode 'override' colours in one place. I did have to keep the 'swap' rules for the alert component, but this feels reasonable to me. The `.btn-close` element is a funny one, as it is constructed from an SVG as a background, so I have had to use a filter on it. I could replace this with an icon for my site, but I think I will stick with the recommended approach, now that I have figured out how to modify it for dark mode.
