### ISSUE TITLE
Add Vertical Breakpoints

### ISSUE THREAD

**Issue by glenfletcher** [twbs/bootstrap#38203]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

As with the existing horizontal breakpoints, define three default vertical breakpoints.

| Breakpoint | Class Infix | Dimensions |
|-------------|------------|---------------|
|  Small        | *None*     | &lt;416px     |
|  Medium   |   `vm`        | &ge;416px   |
|  Large       |    `vl`          | &ge;720px   |

Then update the actual breakpoint naming to be `-{Horoziontal Breakpoint}-{Vertical Breakpoint}`

i.e. for Sticky Top, you would end up with the following examples

- `sticky-top` (No Break Points)
- `sticky-vm-top` (Only Vertical Break Point)
- `sticky-vl-top` (Only Vertical Break Point)
- `sticky-sm-top` (Only Horizontal Break Point)
- `sticky-sm-vm-top` (Both Breakpoints)
- `sticky-sm-vl-top` (Both Breakpoints)
- etc.

Further, either `{media-}breakpoint-*` mixins and functions should accept vertical breakpoints or an equivalent set of mixins and functions should be provided. ,

### Motivation and context

I came up with this idea while working on a website and examining how it would appear on a smartphone orientated in the landscape. I found that the 64px sticky navbar caused problems in this layout, and my solution, in this case, was to use the following custom CSS:

```css
@media (min-height: 416px) {
  .stick-vm-top {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
```
This works fine for this single-use case, but my first solution was to check the breakpoints in bootstrap, which is when I realised that bootstrap doesn't currently have any vertical breakpoints. So, I needed to make the sticky top breakpoint class manually.

Having realised this lack, I can think of several other used cases, such as the display classes, to hide redented or unnecessary content when vertical space is limited or only show it when there is a lot of vertical space.

Also, imposing image height restrictions when viewport height is limited.

**Comment by glenfletcher** [comment]
Ok, I've worked out how to implement some of the breakpoint functions and mixins in a backwards-compatible way.

- The max function can be done similarly to the min functions.
- The down and between mixins can be done similarly to the up mixin.
- The `breakpoint-next` function needs further thought.

Once the functions are all working, this would need to be integrated into the rest of the code base, i.e. pull breakpoint keys from
`$combine-breakpoints` instead of `$grid-breakpoints`. **Question**: Are there any parts of the code base that don't depend on the breakpoint functions and would need to be separately updated?

```scss
$grid-breakpoints: (
        xs: 0,
        sm: 576px,
        md: 768px,
        lg: 992px,
        xl: 1200px,
        xxl: 1400px
) !default;

$vertical-breakpoints: (
        vs: 0,
        vm: 416px,
        vl: 720px,
) !default;

$combine-breakpoints: ();

@each $vname, $vsize in $vertical-breakpoints {
  @if map-has-key($grid-breakpoints, $vname) {
    // This is important; to support singular breakpoints, vertical names must be distinct from the horizontal names
    @error "Invalid Vertical Breakpoint #{$vname} is already used as a Horizontal Breakpoint, Vertical and Horizontal Breakpoint names must be Uniues.";
  }
  @each $hname, $hsize in $grid-breakpoints {
    // Use $hname if both $vsize and $hsize are 0 so all the horizontal names are defined for backwards compatibility
    $name: if($vsize == 0, $hname, if($hsize == 0, $vname, #{$hname}-#{$vname}));
    $combine-breakpoints: map-merge($combine-breakpoints, ($name: [$hsize, $vsize]));
  }
}

@function breakpoint-min-width($name, $breakpoints: $combine-breakpoints) {
  $min: nth(map-get($breakpoints, $name), 1);
  @return if($min != 0, $min, null);
}

@function breakpoint-min-height($name, $breakpoints: $combine-breakpoints) {
  $min: nth(map-get($breakpoints, $name), 2);
  @return if($min != 0, $min, null);
}

@function breakpoint-min($name, $breakpoints: $combine-breakpoints) {
  @return breakpoint-min-width($name, $breakpoints); // Backwards compatibility
}

@function breakpoint-infix($name, $breakpoints: $combine-breakpoints) {
  @return if((breakpoint-min-width($name, $breakpoints) == null) and
             (breakpoint-min-height($name, $breakpoints) == null), "", "-#{$name}");
}

@mixin add_query($query, $value) {
  @if ($value) {
    @media (#{$query}: $value) {
      @content;
    }
  } @else {
    @content;
  }
}

@mixin media-breakpoint-up($name, $breakpoints: $combine-breakpoints) {
  $min-width: breakpoint-min-width($name, $breakpoints);
  $min-height: breakpoint-min-height($name, $breakpoints);
  @include add_query(min-width, $min-width) {
    @include add_query(min-height, $min-height) {
      @content;
    }
  }
}

@each $name in map-keys($combine-breakpoints) {
  @include media-breakpoint-up($name) {
    .sticky#{breakpoint-infix($name)}-top {
      position: sticky;
      top: 0;
      z-index: 1020;
    }
  }
}
```
This will generate 
```css
.sticky-top {
  position: sticky;
  top: 0;
  z-index: 1020;
}

@media (min-width: 576px) {
  .sticky-sm-top {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
@media (min-width: 768px) {
  .sticky-md-top {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
@media (min-width: 992px) {
  .sticky-lg-top {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
@media (min-width: 1200px) {
  .sticky-xl-top {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
@media (min-width: 1400px) {
  .sticky-xxl-top {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
@media (min-height: 416px) {
  .sticky-vm-top {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
@media (min-width: 576px) and (min-height: 416px) {
  .sticky-sm-vm-top {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
@media (min-width: 768px) and (min-height: 416px) {
  .sticky-md-vm-top {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
@media (min-width: 992px) and (min-height: 416px) {
  .sticky-lg-vm-top {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
@media (min-width: 1200px) and (min-height: 416px) {
  .sticky-xl-vm-top {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
@media (min-width: 1400px) and (min-height: 416px) {
  .sticky-xxl-vm-top {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
@media (min-height: 720px) {
  .sticky-vl-top {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
@media (min-width: 576px) and (min-height: 720px) {
  .sticky-sm-vl-top {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
@media (min-width: 768px) and (min-height: 720px) {
  .sticky-md-vl-top {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
@media (min-width: 992px) and (min-height: 720px) {
  .sticky-lg-vl-top {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
@media (min-width: 1200px) and (min-height: 720px) {
  .sticky-xl-vl-top {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
@media (min-width: 1400px) and (min-height: 720px) {
  .sticky-xxl-vl-top {
    position: sticky;
    top: 0;
    z-index: 1020;
  }
}
```
