### ISSUE TITLE
New style `table-striped-inverse`

### ISSUE THREAD

**Issue by IvanPizhenko** [twbs/bootstrap#38617]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Provide style `table-striped-inverse` which make uses striped color in the even rows instead of odd.

### Motivation and context

At the moment the same it is easily achievable with additional empty `<tr>` (as recommended [here](https://stackoverflow.com/a/62108314/1540501)).  But it is more natural to have this a built-in style.

**Comment by IvanPizhenko** [comment]
Suggested implementation:

```css
.table-striped-inverse > tbody > tr:nth-of-type(even) > * {
  --bs-table-accent-bg: var(--bs-table-striped-bg);
  color: var(--bs-table-striped-color);
}
```
