### ISSUE TITLE
When modifying CSS variables of a table, all variants are affected

### ISSUE THREAD

**Issue by marcoarib** [twbs/bootstrap#38703]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When modifying a CSS variable in the .table class, all variants are affected.
Example:

`.table {
  --bs-table-striped-bg: lightblue;
}`

Wouldn't it be appropriate for it to only affect the default variant?

Thanks.

### Reduced test cases

https://codepen.io/marcoarib/pen/VwVZPwa

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.0

**Comment by julien-deramond** [comment]
If it affects only the default variant, you won't be able to customize easily the striped colors for `.table-primary` for example, except if we provide other CSS variables. But it won't work for classes created by users (e.g. `table-whatever-primary`).

In your example, you still have a fine-grained approach with the following:

```css
.table:not(.table-primary):not(.table-danger) {
  --bs-table-striped-bg: red;
  --bs-table-striped-color: yellow;
}

.table-primary {
  --bs-table-striped-bg: black;
  --bs-table-striped-color: white;
}
```

**Comment by marcoarib** [comment]
> If it affects only the default variant, you won't be able to customize easily the striped colors for `.table-primary` for example, except if we provide other CSS variables. But it won't work for classes created by users (e.g. `table-whatever-primary`).
> 
> In your example, you still have a fine-grained approach with the following:
> 
> ```css
> .table:not(.table-primary):not(.table-danger) {
>   --bs-table-striped-bg: red;
>   --bs-table-striped-color: yellow;
> }
> 
> .table-primary {
>   --bs-table-striped-bg: black;
>   --bs-table-striped-color: white;
> }
> ```

I believe there should be a ".table-light" variant as the main variant, so it doesn't affect the rest of the variants:

```CSS
.table.light { 
   --bs-table-striped-bg: lightblue; 
}
```
