### ISSUE TITLE
Outline buttons have the same active and hover color

### ISSUE THREAD

**Issue by xeron** [twbs/bootstrap#39085]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Outline buttons have the same active and hover color, making them barely usable on mobile where hover stays after the tap, making an impression that active state didn't change.

Sort of workaround applying 15% shading to the button:

```scss
.btn-outline-calculator {
  @include button-outline-variant($gray-100);
}
.btn-outline-calculator:hover {
  background-color: shade-color($gray-100, 15%);
}
```

But I think such shading should be enabled by default?

### Reduced test cases

With dark themed HTML:

```
<button aria-pressed="true" class="btn btn-outline-light active" data-bs-toggle="button">Text</button>
```

Testing on iOS, pressing the button doesn't change the color at all which is very confusing.

### What operating system(s) are you seeing the problem on?

iOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.1
