### ISSUE TITLE
v5.3 alert custom theme doesn't work 

### ISSUE THREAD

**Issue by NeutronSelector** [twbs/bootstrap#39155]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In v5.1, alert-{variant} works with this code, in v5.3 doesn't work properly

in _variable.scss I've

```scss
$theme-colors: (
    "primary": $ac-red,
    "secondary": $ac-gray,
    "success": $green,
    "info": $cyan,
    "warning": $yellow,
    "danger": $red,
    "light": $gray-100,
    "dark": $gray-900,
);

$custom-colors: (
    "critical": $purple,
);

$theme-colors: map-merge($theme-colors, $custom-colors);
```

bg-critical css class generated and works

alert-critical not generate or doesn't works

### Reduced test cases

I tried to add this

The documentation v5.3 says this
"Loop that generates the modifier classes with the alert-variant() mixin."

in _alert.scss I've

```scss
$prefix: 'bs-';

@each $state in map-keys($theme-colors) {
    .alert-#{$state} {
        --#{$prefix}alert-color: var(--#{$prefix}#{$state}-text-emphasis);
        --#{$prefix}alert-bg: var(--#{$prefix}#{$state}-bg-subtle);
        --#{$prefix}alert-border-color: var(--#{$prefix}#{$state}-border-subtle);
        --#{$prefix}alert-link-color: var(--#{$prefix}#{$state}-text-emphasis);
    }
}
```

in app.scss I've

```scss
@import 'variables';
@import 'alert';
@import '~bootstrap/scss/bootstrap';
```

But, alert-critical css class doesn't exist or work
I missed something ?

thank's

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3
