### ISSUE TITLE
Object position for images

### ISSUE THREAD

**Issue by naider** [twbs/bootstrap#39196]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

```css
.object-position-center{
    object-position: center;
}

.object-position-top-left{
    object-position: top left;
}
.object-position-top-right{
    object-position: top right;
}
.object-position-top-center{
    object-position: top center;
}

.object-position-bottom-left{
    object-position: bottom left;
}
.object-position-bottom-right{
    object-position: bottom right;
}
.object-position-bottom-center{
    object-position: bottom center;
}
```

### Motivation and context

I don't found "object-position" for images. 
Has only "object-fit" in utilities.
