### ISSUE TITLE
Striped colors with exact colors (and not mixed with gray).

### ISSUE THREAD

**Issue by PGTBoos** [twbs/bootstrap#39247]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I'm trying to set table striped by exact colors as defined 
In bootstrap 4 i used below css for an anular component.

```css
.table-green tbody tr:nth-child(odd) {
  background-color: #f8faf9;
}
.table-green tbody tr:nth-child(even) {
  background-color: #e6ece7;
}
```

Bootstrap 5, doesnt seam to have a way to set body rows striped colors exactly to a specific color.
I tried various ways to set it, though as none of them gave the exact colors i put in place the code that worked in bootstrap 4
I noticed that with other terms background : #405060, --bs-table-bg-type: #405060, colors can be overriden, though bootstrap 5 

If I used a wrong syntax to do it please let me know,

### Reduced test cases

https://codepen.io/Peter-Boos/pen/jOXKbgO

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.2

**Comment by julien-deramond** [comment]
Thanks for reporting an issue @PGTBoos 
[Your CodePen link](https://codepen.io/team/bootstrap/pen/qBamdLj) seems to be incorrect as it points out to the default one we provide

**Comment by PGTBoos** [comment]
I updated the codepen link sorry, didnt knew i had to subscribe, i normally used postbin
I forked the default made a table, and provided code, in this case as how it works in bootstrap 4
As dont know a syntax that allows to set those collors wihtout they get added or becomme gray-ish

**Comment by julien-deramond** [comment]
Considering a `<table class="table table-striped">`, you could play with the CSS variables in place:

```css
.table.table-striped {
  --bs-table-striped-bg: green;
  --bs-table-accent-bg: pink;
}
```

The "issue" here is that the table header background is also modified and becomes pink. It's a bit hacky but I suppose that you could do the following:

```css
.table.table-striped {
  --bs-table-striped-bg: green;
}

.table.table-striped tbody tr:nth-child(even) td {
  background-color: pink;
}
```

Note: your selector doesn't work anymore because the background color is now set to the `<td>` instead of `<tr>` in v4. I don't have the history here in mind, but I suppose that it's done to handle also the striped columns.
