### ISSUE TITLE
CSS variables not adopting default overrides 

### ISSUE THREAD

**Issue by v3nt** [twbs/bootstrap#39379]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

With 5.3 the CSS variable defaults are no longer overwritten. Its seems that any CSS variables functions do not absorb the changes. 

My variables file
```scss
$enable-dark-mode: false;

@import "../../node_modules/bootstrap/scss/functions";
@import "../../node_modules/bootstrap/scss/variables";

$primary: $gray-800;
$link-color: $primary;
$link-color-rgb: $primary;
$link-hover-color: $green;

/* works, $primary: is $gray-800; */
a {
  outline: $primary 1px solid;
}

/* does not work. CSS var still start with bs- */
$variable-prefix: "rdbs-";

@import "../../node_modules/bootstrap/scss/bootstrap";
```

<img width="379" alt="Screenshot 2023-11-08 at 17 04 55" src="https://github.com/twbs/bootstrap/assets/6348562/a9b8849f-81ed-4672-9d5f-88ab05fef352">

<img width="701" alt="Screenshot 2023-11-08 at 17 05 22" src="https://github.com/twbs/bootstrap/assets/6348562/60f3d04c-a88c-4f43-b9bb-1fb9bba82057">

<img width="278" alt="Screenshot 2023-11-08 at 17 05 34" src="https://github.com/twbs/bootstrap/assets/6348562/df0fc9b9-211c-4876-a704-8f9d0bc443b6">

<img width="348" alt="Screenshot 2023-11-08 at 17 05 44" src="https://github.com/twbs/bootstrap/assets/6348562/7b99e3a2-d177-42e6-b8d5-90e0a3389763">

### Reduced test cases

```scss
$primary: $gray-800;
$link-color: $primary;
$link-color-rgb: $primary;
$link-hover-color: $green;

/* works, $primary: is $gray-800; */
a {
  outline: $primary 1px solid;
}

/* does not work. CSS var still start with bs- */
$variable-prefix: "rdbs-";
```

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

5.3.2
