### ISSUE TITLE
Utilities: Introduce an option to generate more display utility

### ISSUE THREAD

**Issue by aboutjquery** [twbs/bootstrap#39561]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

For example, I want to display a div as flex only when it is sm or less than sm and not change its name at other times (that is, it is defaulted to block). The current method is to add `d-flex` and `d-md-block` to it.

I hope that the above effect can be achieved by adding only one class, that is, adding `d-sm-max-flex`

Similarly, there are also people who want to add classes such as `d-sm-lg-between` as helpers.

I believe I only need to modify `mixins/_utilities.scss` to achieve it, but I don't know where to start. The code inside is a bit complicated for me. Please give me some guidance. Thank you.

### Motivation and context

I think some users have also encountered this problem. Although this will increase the size of scss, I think it can be an option for users to decide for themselves.

**Comment by louismaximepiton** [comment]
Hey there,

First of all, we don't recommand to introduce classes that could be mimic in another way and as you said, it's quite easy to mimic this behavior atm. Furthermore, we try as much as possible to have a mobile first approach.
Since we don't remove unused CSS, we try to limit the number of classes we introduce.

In a second time, I'd consider to introduce those classes manually.

That said, you don't need to change anything in our mixin. Here is a two step process to get what you need.

I just tried this (naming might be reworked and code might be optimized):

Inside `scss/utilities/_api.scss`
```scss
@each $breakpoint1 in map-keys($grid-breakpoints) {
  @each $breakpoint2 in map-keys($grid-breakpoints) {
    $i1: index(map-keys($grid-breakpoints), $breakpoint1);
    $i2: index(map-keys($grid-breakpoints), $breakpoint2);

    @if $i1 < $i2 {
      @include media-breakpoint-between($breakpoint1, $breakpoint2) {
        $infix: #{breakpoint-infix($breakpoint1, $grid-breakpoints) + breakpoint-infix($breakpoint2, $grid-breakpoints) + "-between"};

        // Loop over each utility property
        @each $key, $utility in $utilities {
          @if type-of($utility) == "map" and (map-get($utility, between-responsive) or $infix == "") {
            @include generate-utility($utility, $infix);
          }
        }
      }
    }
  }
}
```

Inside `scss/_utilities.scss`
```scss
    "display": (
      responsive: true,
      between-responsive: true, // Only new line
      print: true,
      property: display,
      class: d,
      values: inline inline-block block grid inline-grid table table-row table-cell flex inline-flex none
    ),
```

<details>
<summary>And here are the results (only few)</summary>

```css
@media (max-width: 479.98px) {
  .d-sm-between-inline {
    display: inline !important;
  }
  .d-sm-between-inline-block {
    display: inline-block !important;
  }
  ...
}
@media (max-width: 767.98px) {
  .d-md-between-inline {
    display: inline !important;
  }
  .d-md-between-inline-block {
    display: inline-block !important;
  }
  ...
}
...
@media (max-width: 1439.98px) {
  .d-xxl-between-inline {
    display: inline !important;
  }
  .d-xxl-between-inline-block {
    display: inline-block !important;
  }
  ...
}
@media (min-width: 480px) and (max-width: 767.98px) {
  .d-sm-md-between-inline {
    display: inline !important;
  }
  .d-sm-md-between-inline-block {
    display: inline-block !important;
  }
  ...
}
...
@media (min-width: 1280px) and (max-width: 1439.98px) {
  .d-xl-xxl-between-inline {
    display: inline !important;
  }
  .d-xl-xxl-between-inline-block {
    display: inline-block !important;
  }
  ...
}
```

</details>

This code generates `.75kB` of CSS. 
Once more, prefer using another approach and if you use this, please make sure to clean all unused CSS with any tool like [PurgeCSS](https://purgecss.com/).
