### ISSUE TITLE
Floating Labels for File Input

### ISSUE THREAD

**Issue by lionfood** [twbs/bootstrap#39867]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

It would be a nice feature to have floating labels also for file inputs. At the moment, the label is placed over the button of the input field and overlaps parts of the button.
![Screenshot_20240404_175422](https://github.com/twbs/bootstrap/assets/108174379/8aa1ec30-3ba0-422f-b9ad-0769e2164643)

### Motivation and context

With having floating labels also for file inputs, (nearly) all input fields of a web form could be labeled with this, which enables a consistent layout.

**Comment by thedanbob** [comment]
I got it looking pretty decent with the following SCSS:

```scss
.form-floating > input[type="file"].form-control {
  padding-top: 2.25rem;
  height: calc(3.875rem + calc(var(--bs-border-width) * 3));

  &::file-selector-button {
    border-top: var(--bs-border-width) solid var(--bs-border-color);
    border-right: var(--bs-border-width) solid var(--bs-border-color);
    border-top-right-radius: var(--bs-border-radius); // optional
  }
}
```
