### ISSUE TITLE
Form control placeholder colour has incorrect opacity

### ISSUE THREAD

**Issue by lonix1** [twbs/bootstrap#40499]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

A form control's placeholder colour is defined like this:
```css
--bs-secondary-color: rgba(33, 37, 41, 0.75);

.form-control::placeholder {
  color: var(--bs-secondary-color);
  opacity: 1;
}
```
Note how it resets opacity to `1`.

Surely that's a mistake? The placeholder text is expected to be lighter than normal text.

### Reduced test cases

```html
<input type="text" class="form-control" placeholder="hello world!">
```

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

5.3.3
