### ISSUE TITLE
New button class:  btn-neutral

### ISSUE THREAD

**Issue by webJose** [twbs/bootstrap#40490]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Create a new `btn-neutral` CSS class:

```css
.btn-neutral {
    &:hover, &.hover {
        background-color: rgba(var(--bs-dont-remember, var(--bs-black-rgb)), var(--bs-also-dont-remember, 0.05));
        /* maybe add color too */

        [data-bs-theme="dark"] & {
            /* Same thing but with black white BG color */
        }
    }
```

Something like that.  I'm no expert.

If you would like to see, you may see the neutral button in the first column of the data view of [this Svelte demo component](https://WJSoftware.github.io/wjfe-dataview).

Sample:

```html
<button type="button" class="btn btn-sm btn-neutral"><i class="bi bi-chevron-bar-expand"></i></button>
```

### Motivation and context

I commonly find myself with the need to add a button that has the same background as the parent container.  The most common example I can give is data view components (tables with lots of data).  In my project, all the data view tables have a "controls" column (usually the first column) where buttons to perform various tasks are added.  Most often than not, having the buttons with just icons in it and no theme (primary, secondary, etc.) is the best look.

So what do I do?  I do:

```html
<button type="button" class="btn btn-sm"><i class="bi bi-chevron-bar-expand"></i></button>
```

This works.  Looks good.  But there is something missing:  Active state and hover state.
