### ISSUE TITLE
Floating labels: Artificial label background clashing with autofill / per-field styling

### ISSUE THREAD

**Issue by Bouke** [twbs/bootstrap#40551]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I have a sign-in form with a floating label, like this:

![image](https://github.com/twbs/bootstrap/assets/235882/a919c43e-0f03-4497-aa16-586562da63a7)

When I use Safari Autofill (password manager), Safari applies a custom background to let the user know the field was filled in by the browser:

![image](https://github.com/twbs/bootstrap/assets/235882/3155f4da-622b-4ae9-9744-f213223862b9)

The CSS that is applied on the input is the following:

```css
input:autofill, input:-webkit-autofill-strong-password, input:-webkit-autofill-strong-password-viewable, input:-webkit-autofill-and-obscured {
  background-color: rgb(250, 255, 189);
  background-image: none;
  color: rgb(0, 0, 0);
}
```

Disabling the artificial background fixes the field's rendering:

![image](https://github.com/twbs/bootstrap/assets/235882/e70ddade-e91f-4d06-a4a2-dbbb006306ed)

The artificial was introduced in #37125. It seems the fix was applied rather broadly on all input elements, rather than the element for which the issue was reported (`textarea`). Is an `input` even susceptible to the reported bug?

### Reduced test cases

```html
<div class="form-floating mb-3">
  <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" style="background:rgb(250, 255, 189)">
  <label for="floatingInput">Email address</label>
</div>
```

This is the outcome on v5.3.3 is different from 5.2.2 that I've shown above, but I think is still not looking great:

![image](https://github.com/twbs/bootstrap/assets/235882/6e25b23d-e223-41aa-897b-f74005b0e9d2)

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari

### What version of Bootstrap are you using?

v5.3.3
