### ISSUE TITLE
Adding backdrop-filter blur on navbar breaks offcanvas element

### ISSUE THREAD

**Issue by firesightstudios** [twbs/bootstrap#40575]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

**Create a Navbar With offCanvas element & add custom class**

`<nav class="navbar fixed-top customNavbar-mobile">`

**Add css to custom class**

`.customNavbar-mobile {
        background-color: #282d43cc !important;
        backdrop-filter: blur(5px);
    }`
    
 Offcanvas breaks.

### Reduced test cases

https://codepen.io/Justin-Zimmerman/pen/WNBzLBB

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.3.3

**Comment by LadonAl** [comment]
This does not seem to be a bug actually. Refer to [this]( https://stackoverflow.com/questions/52937708/why-does-applying-a-css-filter-on-the-parent-break-the-child-positioning)

I believe that something like this should solve your problem:

```css
.customNavbar-mobile {
  background-color: #282d43cc !important;
}

.customNavbar-mobile .offcanvas-backdrop {
  backdrop-filter: blur(5px);
}
```
