### ISSUE TITLE
bootstrap docs: Windows high contrast: navbar has transparent background

### ISSUE THREAD

**Issue by rr-it** [twbs/bootstrap#40757]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In Windows high contrast mode the navbar in bootstrap docs https://getbootstrap.com/docs/5.3/getting-started/introduction/ becomes transparent.

Also see: https://github.com/twbs/bootstrap/issues/35941

Maybe just change https://github.com/twbs/bootstrap/blob/048f56f51460df75e92a2f7b472e1c56baeb68f7/site/assets/scss/_navbar.scss#L1-L13

```css
.bd-navbar {
  background-color: transparent;

  &::after {
    background-image: linear-gradient(rgba(var(--bd-violet-rgb), 1), rgba(var(--bd-violet-rgb), .95));
  }
``` 

to something like

```css
.bd-navbar {
  background-color: rgba(var(--bd-violet-rgb), .00001);

  &::after {
    background-image: linear-gradient(rgba(var(--bd-violet-rgb), 1), rgba(var(--bd-violet-rgb), .95));
  }
``` 

or 

```css
.bd-navbar {
  background-color: transparent;
  @media (forced-colors) {
    background-color: var(--bd-violet);
  }

  &::after {
    background-image: linear-gradient(rgba(var(--bd-violet-rgb), 1), rgba(var(--bd-violet-rgb), .95));
  }
``` 

### Reduced test cases

https://codepen.io/rr-it/pen/MWMVXKQ

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3
