### ISSUE TITLE
Breakpoint indicator label

### ISSUE THREAD

**Issue by tugrul** [twbs/bootstrap#40927]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Actually I use following snipped in my projects to figure out which breakpoint is active on viewport. It would be nice opt-in feature like Sass mixin or utility class.
```scss
body.breakpoints-label {
  &:before {
    @include border-radius();
    content: "no";
    position: fixed;
    left:2px;
    top:2px;
    padding: 2px 4px;
    font-size:12px;
    line-height: 1em;
    color: var(--bs-danger-text-emphasis);
    background-color: var(--bs-danger-bg-subtle);
    border: 1px solid var(--bs-danger-border-subtle);
    z-index: 100;
    opacity:0.4;

    @each $name, $size in $grid-breakpoints {
      @media (min-width: $size) {
        content: "#{$name}";
      }
    }
  }
}
```

### Motivation and context

It is hard to understand which breakpoint is active on development phase and it increase development speed when we see active breakpoint's name in the label.
