### ISSUE TITLE
Popover arrow doesn't match the header background if placement is bottom

### ISSUE THREAD

**Issue by xvaara** [twbs/bootstrap#40993]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Popover arrow doesn't match the header background if placement is bottom.

There is a potential fix using variables:

```css
.bs-popover-auto[data-popper-placement^='bottom'] .popover-arrow:has(+ .popover-header)::after,
.bs-popover-bottom .popover-arrow:has(+ .popover-header)::after {
  --bs-popover-bg: var(--bs-popover-header-bg);
}
```

### Reduced test cases

https://stackblitz.com/edit/wb5ais?file=index.html

### What operating system(s) are you seeing the problem on?

macOS

### What version of Bootstrap are you using?

5.4
