### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by thiagogaia** [twbs/bootstrap#41182]
### Prerequisites

- [x] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [x] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

#### Tested Browsers:
- Google Chrome  
- Mozilla Firefox  

#### Steps to Reproduce:
1. Create a form that supports autocomplete (e.g., "state").  
2. Add a `select` field for autocomplete functionality.  
3. Observe that the dropdown arrow for the `select` field disappears.  

#### Example:
A live example of the issue can be seen here:  
[[CodePen Example](https://codepen.io/designer-professional/pen/ZYzVrLR)](https://codepen.io/designer-professional/pen/ZYzVrLR)  

#### Screenshot:  
![Image](https://github.com/user-attachments/assets/58f1053b-5017-4457-aeab-bf7e31ec1fca)  

As shown in the screenshot, the dropdown arrow for the `select` field vanishes when autocomplete is enabled, making it unclear to users that additional options are available in the field.  

### Reduced test cases

https://codepen.io/designer-professional/pen/ZYzVrLR

### What operating system(s) are you seeing the problem on?

Linux, Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

5.3.3

**Comment by thiagogaia** [comment]
Segue a sugestão de correção para o bug, explicando a abordagem com a pseudo-classe:  

---

### Suggested Fix: Use a Pseudo-Class for the Select Dropdown Arrow  

#### Problem:
The issue arises because the dropdown arrow for the `select` element in Bootstrap is implemented as a `background`, which gets overridden when the browser's native autocomplete interacts with the field.  

#### Solution:
Instead of relying on the `background` property for the dropdown arrow, implement it using a pseudo-element, such as `::after` or `::before`. This ensures the arrow remains visible, as pseudo-elements are not affected by the browser's autocomplete behavior.  

#### Example Fix:  
```css
select {
  appearance: none; /* Hide default browser styling */
  position: relative;
  padding-right: 2rem; /* Add space for the arrow */
}

select::after {
  content: var(--bs-form-select-bg-img); /* Customize the dropdown arrow */
  position: absolute;
  right: 1rem; /* Adjust spacing */
  pointer-events: none; /* Prevent interaction */
  font-size: 0.8rem; /* Scale the arrow */
  color: #6c757d; /* Match Bootstrap's styling */
}
```

#### Notes:  
1. Ensure `appearance: none` is used to remove the browser's default arrow.  
2. Position the pseudo-element carefully to align it with the field, considering padding and margins.  
3. Maintain compatibility with different themes and colors in Bootstrap by using appropriate variables or classes.  

This approach provides a consistent experience across browsers and ensures the arrow remains visible even when autocomplete is active.

**Comment by mdo** [comment]
Just for future folks, the pseudo-element solution isn't possible—you can't generate them on form controls.

**Comment by mdo** [comment]
The select's arrow is a background image, and the browser's autofill styling replaces the control's background, overwriting the arrow. That's a browser limitation we can't override from CSS on a form control. Closing as won't-fix — please open a new issue if you find a workable approach in v6-dev.

**Comment by foobear** [comment]
FYI: You _can_ work around this by styling `.form-select` to use `appearance: base-select`, and hide Bootstrap's icon image. The native `::picker-icon` is not hidden through autofill styles. Works only in Chrome/Edge; other browsers will just behave as before.

Example:
```css
@supports (appearance: base-select) {
  .form-select {
    --bs-form-select-bg-img: none;
  }
  .form-select,
  .form-select::picker(select) {
    appearance: base-select;
  }
  .form-select::picker-icon {
    /* styles to render an icon, e.g. from Bootstrap icons */
  }
}
```

See https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Forms/Customizable_select for details.
