### ISSUE TITLE
Class text balanced

### ISSUE THREAD

**Issue by julien-deramond** [twbs/bootstrap#41389]
### Discussed in https://github.com/orgs/twbs/discussions/41368

<div type='discussions-op-text'>

<sup>Originally posted by **abielmagudev** April 12, 2025</sup>
Hi friends, can you add a class for balanced text?

```css
.text-balanced {
  text-wrap: balance;
}
```

```html
<p class="text-balanced">This is a text balanced by a class of CSS.</p>
```
