### ISSUE TITLE
Vertical nav-tabs

### ISSUE THREAD

**Issue by AndreasArvidsson** [twbs/bootstrap#41472]
### Prerequisites

- [x] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [x] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Bootstrap supports vertical nav using `flex-column`, but combining `flex-column` with `nav-tabs` gives a weird result.

Today:
![Image](https://github.com/user-attachments/assets/da54cdd2-7bfd-43b9-a3b4-e1dc7b99a661)

Desired:
![Image](https://github.com/user-attachments/assets/b465b6e2-d5d2-4b0f-a9d9-3c91bb63458b)

I can get the desired result by applying the bellow css. I could make a pull request if this kind of solution is acceptable. 

```css
.nav-tabs.flex-column {
    border-bottom: 0;
    border-right: var(--bs-nav-tabs-border-width) solid var(--bs-nav-tabs-border-color);
}

.nav-tabs.flex-column .nav-link {
    border-radius: var(--bs-nav-tabs-border-radius) 0 0 var(--bs-nav-tabs-border-radius);
    margin-bottom: 0;
    margin-right: calc(-1 * var(--bs-nav-tabs-border-width));
}

.nav-tabs.flex-column .nav-link.active {
    border-color: var(--bs-nav-tabs-border-color);
    border-right-color: var(--bs-body-bg);
}
```

### Motivation and context

If you have to many menu items horizontal tabs isn't optimal
