### ISSUE TITLE
--bs-dropdown-box-shadow is set, but never used.

### ISSUE THREAD

**Issue by jcoyne** [twbs/bootstrap#41569]
Should this rule exist?

```css
.dropdown_menu { 
  box-shadow: var(--bs-dropdown-box-shadow);
}
```
